NVIDIA/Fuser

- .github/workflows/blossom-ci.yml
just an initial setup, will add remaining authors later
> add workflow file

- .gitignore
- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- python_tests/test_python_frontend.py
Note that currently this op will fail if concatenating a tensor with 0 size in the specified concatenation dimension.
> Add cat op to frontend

- csrc/codegen.cpp
- csrc/dispatch.cpp
- csrc/fusion.cpp
- csrc/ir_interface_nodes.h
- csrc/type.cpp
- csrc/type.h
- test/test_gpu3.cpp
> Add support for reduced precision scalars

- csrc/lower_double_buffer.cpp
- test/test_loop_rotation.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/39
> Fix bug in `kir::CpAsyncWait` insertion

- python_tests/test_torchscript.py
A change to make python `lintrunner` pass.
> Fix `TestCudaFuser.test_view`

- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul.h
Adds https://github.com/NVIDIA/Fuser/pull/42 to main.
> Parameter to change rasterization order

- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/python_frontend/python_bindings.cpp
- csrc/type.cpp
- csrc/type.h
- test/test_gpu2.cpp
This reverts commit c7c4911d80aaf4a9d879199e3f555b5cc8d0cf4e.
running into errror when importing nvfuser in python `ImportError: /opt/pytorch/pytorch/nvfuser/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN7nvfuser7complexEPNS_3ValEPNS_10TensorViewE`
Will investigate and patch later
> Revert "Llu/welford complex (#75)"

- .github/workflows/nvfuser-ci-trigger.yml
Added all contributor to the list
> added all contributor to blossom authorization list

- csrc/executor_utils.cpp
I am getting an unknown symbol error on this line on TOT: https://github.com/NVIDIA/Fuser/pull/113/files#diff-7a4f65bea86e65f941636f4355972029ce48141c38d5ae2db39c10ad7a291207R1226. The fix is pretty simple I believe.
> Fix non-debug compile

- csrc/ir_iostream.cpp
When reading Jacob's slides this morning, I feel it would be more convenient to read the transformations if leaf domains are also printed. Besides, `IrTransformPrinter::printTransforms` needs cleanup.
New print
```C++
T5_l[ iblockIdx.x23{( ceilDiv(i0, 128) )}, iblockIdx.y25{( ceilDiv(i3, 128) )}, rS27{( ceilDiv(i2, 32) )}, rS77{( ceilDiv(32, 16) )}, ithreadIdx.z69{( ceilDiv(128, 64) )}, ithreadIdx.y71{( ceilDiv(128, 64) )}, iS73{( ceilDiv(64, 16) )}, iS75{( ceilDiv(64, 8) )}, iMMA153{( ceilDiv(16, 8) )}, ithreadIdx.x157{( 8 * ( ceilDiv(8, 2) ) )}, iMMA156{2}, rMMA78{16} ] ca_pos( 2 ) produce_pos( 6 )
root domain : (iS10{i0}, iS11{i3}, rS12{i2})
contiguity: t t t
Split: iS10{i0} by factor 128 -> iblockIdx.x23{( ceilDiv(i0, 128) )}, iS24{128}, start offset: 0, stop offset: 0
Split: iS11{i3} …
```
> Cleanup fusion transformations printting

- setup.py
This is to allow us customize wheel pkg version for nightly posting
> Adding an option to put a `-version-tag=[TAG]` option

- csrc/utils.cpp
- csrc/utils.h
- test/test_gpu2.cpp
1. added util struct `ThreadLocalFmaDisableOverwrite` to disable fma for local thread;
2. disable fma on `FusionBiasGeluBwd`
> Patch fma biasgelubwd cpp test

- test/test_gpu2.cpp
fixing failing CI `NVFuserTest.FusionBiasGeluBwd_CUDA`
> patching test by bumping tolerance

- setup.py
- tools/gen_nvfuser_version.py
...this lets nvfuser build with non-default python.
I have not yet figured out how to get a wheel...
> use python used for running setup.py

- setup.py
Update to setup.py
default build type to release. with `--debug` to switch to debug build
> add debug option for setup.py

- csrc/lower_predicate_elimination.cpp
`predicateSharedMemAccess` is being called two times from the same function when handling gmem to smem load exps.
Store result in var to avoid duplicate calls. #235 
======== T7_s[ iblockIdx.y57{( ceilDiv(T1.size[1], 32) )}, iS59{( ceilDiv(T0.size[0], 32) )}, iS149{( ceilDiv(( ( ( ( ceilDiv(32, 8) ) * ( ceilDiv(8, 2) ) ) * 2 ) * ( ( ( ceilDiv(( ceilDiv(32, 8) ), 4) ) * 4 ) * 8 ) ), 1024) )}, ithreadIdx.z155{( ceilDiv(( ceilDiv(( ceilDiv(1024, 8) ), 32) ), 1) )}, ithreadIdx.y156{1}, ithreadIdx.x154{32}, iV152{8} ] ca_pos( 2 )
= CpAsyncCg( T1_g[ iS61{( ceilDiv(T1.size[1], 32) )}, iS63{( ceilDiv(T0.size[0], 32) )}, iS62{32}, iS64{32} ] )
calling predicateSharedMemAccess
calling predicateSharedMemAccess
> remove duplicate calls to predicateSharedMemAccess

- csrc/scheduler/registry.cpp
#265 
enable reduction pattern check no matter combined reduction or inner or outer reduction.
> enable reduction pattern check

- CMakeLists.txt
- setup.py
To the best of my knowledge, we have to put an extension's `an_extension.*.so` into `build_ext.build_lib` directory so that setuptools can see it and copy it into an appropriate path which is site-packages/package or /path/to/package for normal install and editable install, respectively.
Rel:
- #153 
- #101 
```
$ python setup.py install
...
running build_ext
old_inplace = 1, self.inplace = 0
copying ./nvfuser/lib/libnvfuser.so -> build/lib.linux-x86_64-cpython-310/nvfuser/_C.cpython-310-x86_64-linux-gnu.so
```
after the install command, in `_C.*.so` in `nvfuser.__path__` and local one seem to have the same size as in the following:
```
mkozuki@mkozuki-desktop ~/ghq/github.com/NVIDIA/fuser put_C_to_build
torchdev-2 ❯ ls -g "$(cd; python -c 'import nvfuser; print(nvfuser.__path__[0])')" …
```
> Copy `libnvfuser.so` to `build_lib` as `_C.*.so`

- csrc/serde/fusion_cache_generated.h
Fixes https://github.com/NVIDIA/Fuser/issues/281
> Update Flatbuffers to v2.0.7 to support cpp17

- csrc/scheduler/matmul_utils.cpp
- replace in-house index type calculation in favor of runtime info index data,
- replace c10::optional with std::optional in matmul utils,
> Matmul scheduler - update kernel index handling

- csrc/fusion.h
```C++
/home/gaoxiang/Fuser/csrc/fusion.h(394): warning #186-D: pointless comparison of unsigned integer with zero
```
> Fix compiler warning in fusion.h

- test/test_gather.cpp
> Adjust problem sizes to avoid test errors

- csrc/ir_internal_nodes.h
I don't like C++ move semantics.
> Fix use after move

- .lintrunner.toml
- csrc/serde/fusion_cache_generated.h
Fixes https://github.com/NVIDIA/Fuser/issues/281
Related: https://github.com/pytorch/pytorch/pull/100716
> Bump flatbuffers to match upstream version (v23.3.3)

- csrc/foo.cpp
- csrc/ir/base_nodes.h
- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/internal_nodes.h
- csrc/utils.h
updating comments per recent file movement;
removing empty cpp files;
> trivial code cleaning

- test/test_dynamic_transform.cpp
- test/test_gather.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_gpu_compute_with.cpp
- test/test_gpu_fused_reduction.cpp
- test/test_gpu_indexing.cpp
- test/test_gpu_indexing_ops.cpp
- test/test_gpu_outer_reduction.cpp
- test/test_gpu_shift.cpp
- test/test_gpu_tensorcore.cpp
- test/test_gpu_view.cpp
- test/test_matmul_sass.cpp
- test/test_resize.cpp
- test/utils.h
~~Fix the validation issue of #374~~
The validation error still persists.
> Avoid validation error

- csrc/scheduler/normalization.cpp
Only do multi reductions per block if we need at least 2 waves.
> one full wave

- csrc/expr_simplifier.cpp
- test/test_expr_simplifier.cpp
A small incremental step for https://github.com/NVIDIA/Fuser/issues/421
> Simplify trivial abs

- csrc/expr_simplifier.cpp
- test/test_expr_simplifier.cpp
An incremental step for https://github.com/NVIDIA/Fuser/issues/421
> Simplify trivial gcd

- csrc/executor_utils.cpp
> Replace initializeCudaContext() with cudaFree(nullptr)

- csrc/expr_simplifier.cpp
- test/test_expr_simplifier.cpp
```c++
gcd(a * x, b * x) -> gcd(a, b) * abs(x)
```
especially if `x >= 0`:
```
gcd(a * x, x) -> x
```
> Factorize gcd

- csrc/executor_utils.cpp
Fixes #429 
This fix still calls `at::cuda::jit::initializeCudaContext()`, as removing it causes some breakage (see #431). Instead, we now check after that call that a context has actually been created. If not, we manually create one with `cudaFree(nullptr)`.
> Manually create context if initializeCudaContext() fails

- setup.py
> patching packaging for contrib in wheel

- csrc/options.h
https://github.com/NVIDIA/Fuser/pull/498#discussion_r1238400240
> Fix missing option loads from env

- python_tests/test_torchscript.py
> Initialize env before load

- test/test_gpu_tensorcore.cpp
These tests are failing on RTX4090.
> Use larger tol for matmul beta tests

- csrc/device_lower/analysis/bank_conflict.cpp
- csrc/device_lower/analysis/bank_conflict.h
- csrc/evaluator_common.cpp
- csrc/evaluator_common.h
- csrc/expr_evaluator.cpp
- csrc/expr_evaluator.h
- csrc/expr_simplifier.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/polymorphic_value.h
- test/test_dynamic_type.cpp
- test/test_evaluator.cpp
Thanks @naoyam for suggesting a better name!
> Name change: `ScalarValue` -> `PolymorphicValue`

- csrc/kernel_db/kernel_db.cpp
> Fix incorrect regex pattern in `KernelDB`

- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
Per review comment: https://github.com/NVIDIA/Fuser/pull/690/files/e253a3c152a3fbee346a80cc545b4e1273da4862#r1300745154
> adding `TensorDomain::TensorDomain(IrBuilderPasskey passkey, const TensorDomain* src)`

- csrc/device_lower/pass/replace_size.cpp
> Fix non-determinism in getSimplificationMap

- tools/compare_codegen.sh
Follow up of #787
Update tools/compare_codegen.sh to make it more CI compatible
> Update tools/compare_codegen.sh to make it more CI compatible

- tools/compare_codegen.sh
> Fixed a minor error in tools/compare_codegen.sh

- .github/workflows/nvfuser-ci-trigger.yml
Adding new members for bot access.
> adding authorized user

- test/test_rng.cpp
Adding a new test to make sure that we are not generating the same RNG numbers, and we do move forward ATen's "current offset". I just realized that we never tested this, and feels worried. Fortunately, nothing is failing.
> Add new test `RNGTest.DifferentRandomNumbers`

- test/test_matmul_sass.cpp
- test/utils.cpp
- test/utils.h
Examining PTX using the approach in the old code triggers an error when the driver version is older than the PTX version nvrtc generates.
> Constify some methods of sass::Instruction. 

- csrc/executor.cpp
- csrc/executor.h
- csrc/executor_utils.cpp
- csrc/executor_utils.h
This is a refactoring PR needed to fix #775 . A separate PR will change FusionExecutor to return both PTX and SASS.
> Wrap getCompiledKernel's return value into a struct. 

- .github/workflows/nvfuser-ci-trigger.yml
> adding a comma

- .github/workflows/nvfuser-ci-trigger.yml
> Refactor CI trigger events

- csrc/codegen.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/validation.cpp
- csrc/ir/interface_nodes.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/scheduler/matmul.cpp
- csrc/tensor_view.cpp
- csrc/type.cpp
- csrc/type.h
- test/test_gpu3.cpp
- test/test_gpu_tensorcore.cpp
- test/test_loop_rotation.cpp
Use cacheOp to distinguish them.
> Consolidate CpAsyncCa and CpAsyncCg to one op type. 

- CMakeLists.txt
- test/test_tutorial.cpp
@Priya2698, @wujingyue, @tfogal Here's annotated fusion examples that I used today. Please let me know if you have any question.
The tests can be run as:
```
NVFUSER_TUTORIAL_VERBOSE=1 ./bin/nvfuser_tests --gtest_filter=Tutorial.Reduction
NVFUSER_TUTORIAL_VERBOSE=1 ./bin/nvfuser_tests --gtest_filter=Tutorial.ReductionRFactor
```
> Example fusions for reduction

- csrc/scheduler/normalization_inner.h
remove TORCH_CUDA_CU_API in csrc/scheduler/normalization_inner.h
> remove TORCH_CUDA_CU_API in csrc/scheduler/normalization_inner.h

- csrc/kernel_ir.h
- csrc/type.h
> remove TORCH_CUDA_CU_API

- CMakeLists.txt
- csrc/cuda_utils.h
- csrc/driver_api.cpp
- csrc/driver_api.h
- csrc/tma.cpp
Suggest starting review from `csrc/driver_api.h`
> Lazily load and invoke driver API

- csrc/fusion_segmenter.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/transpose.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
Step-2 for #946, Introduce a templated hasXops function,to directly check for the existence of specific operations without gathering all of them.
> add hasOpsOfType

- tools/compare_codegen.sh
> patching ci script

- CMakeLists.txt
> Link `libnvfuser_codegen.so` with `-ldl`

- CMakeLists.txt
Another recommendation from @tfogal
> Add `--no-allow-shlib-undefined`

- nvfuser_python_utils/patch_nvfuser.py
It will help for the eventual debugging of this process.
> make `patch-nvfuser` verbose for debugging

- csrc/tensor_metadata.cpp
- test/test_allocation_domain.cpp
patches failing cases in #1031
> fixing trailing contiguity flag for fully broadcast tensors

- csrc/type.cpp
- runtime/bf16_support.cu
- runtime/fp16_support.cu
- test/test_gpu3.cpp
Split-out from https://github.com/NVIDIA/Fuser/pull/990
> Add castings for unsigned integers

- csrc/transform_view.cpp
Use kMixedCase only for constants.
> Minor naming change.

- csrc/id_model/id_graphs.cpp
No idea why this is necessary. I don't think it should hit, so leaving an assertion
> Remove unnecessary code

- test/utils.h
> patch signed compare

- test/utils.h
Fixes the GCC build error I encountered after #1101
> Also cast left-hand side in maybeClearAllocator check

- csrc/ops/alias.cpp
- csrc/python_frontend/fusion_record.h
- test/test_gpu_view.cpp
> Fix tryStaticReshape to look at expanded extents. 

- python_benchmarks/global_params.py
> Fix type errors

- csrc/optimization/alias_analysis.cpp
#1124 left it there accidentally.
> Remove debug output.

- csrc/optimization/alias_analysis.cpp
As @naoyam said in https://github.com/NVIDIA/Fuser/pull/1124#discussion_r1369288588.
> Fix a comment.

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/optimization/alias_analysis.cpp
A follow-up to https://github.com/NVIDIA/Fuser/pull/1124#discussion_r1369092431
> Enforce ViewOp to take and produce a TensorView.

- csrc/id_model/id_graphs.cpp
Don't remember but some of the C++ tests failed.
> Fix use of replayed input IDs

- tools/codediff/compare_codegen.sh
> Fix syntax in tools/codediff/compare_codegen.sh

- csrc/id_model/id_graph.cpp
- csrc/id_model/id_graph.h
- csrc/id_model/id_graphs.cpp
> Finalize loop promotion map

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
> Follow-up to #1161

- csrc/kernel_cache.cpp
> Print the missing key.

- CMakeLists.txt
- test/test_scalar_hoisting.cpp
I'm not sure why it wasn't added or was removed from CMakeLists.txt.
> Recover test_scalar_hoisting.

- test/test_allocation_domain.cpp
Adding an example showing that why the order of allocation domain does not always match with the order of stride. Please let me know if it makes sense to you @wujingyue @jjsjann123 
Generated code:
```CUDA
__global__ void kernel1(Tensor<float, 3, 3> T0, Tensor<float, 3, 3> T2) {
NVFUSER_DEFINE_MAGIC_ZERO;
nvfuser_index_t i0;
i0 = 4LL * ((nvfuser_index_t)threadIdx.x);
nvfuser_index_t i1;
i1 = i0 / T0.logical_size[2LL];
nvfuser_index_t i2;
i2 = T0.logical_size[2LL] * T0.logical_size[1LL];
bool b3;
b3 = (3LL + i0) < ((T0.logical_size[1LL] * T0.logical_size[0LL]) * T0.logical_size[2LL]);
Array<float, 4LL, 4> T1;
if (b3) {
loadGlobalToLocal<float, /*vec_size=*/4, /*is_volatile=*/false, CacheOp::Streaming>(&T1[0LL],  &T0[(((T0.alloc_stride[0LL] * (i1 / T0.logical_size[0LL])) + …
```
> Add test `AllocationDomainTest.VectorizeOverlappingTensor`

- tools/codediff/diff_report.py
- tools/codediff/templates/codediff.html
- tools/codediff/templates/command_env_info.html
- tools/codediff/templates/gitinfo.j2
- tools/codediff/templates/header.html
- tools/codediff/templates/inline_javascript.js
- tools/codediff/templates/test_diff_section.html
This change implements a few minor improvements to the diff reports, especially for non-CI use cases where the same git rev is compared with different envs.
See this example output: [diff.html.gz](https://github.com/NVIDIA/Fuser/files/13239350/diff.html.gz)
> Minor improvements to diff report

- csrc/executor.cpp
- csrc/python_frontend/fusion_record.h
- python_tests/test_python_frontend.py
Fixing a bug in computing `expanded` through `TensorRecord`;
Adding a python test to verify the failure/fix.
> Alloc domain python bug fix

- CMakeLists.txt
> CMAKE print NVFUSER_CPP_STANDARD information

- CMakeLists.txt
`libcupti.so` does not exist in `${CUDA_TOOLKIT_ROOT_DIR}/lib64/`
> Fix cupti build

- CMakeLists.txt
per title
This is needed after https://github.com/NVIDIA/Fuser/pull/1135
> Add pypi cupti library path to nvfuser_codegen RPATH

- csrc/codegen.cpp
- csrc/mma_type.cpp
- runtime/tensorcore.cu
No behavior change, just trying to make the mma helpers more trivial so that it is easy to lower it as `kir::Asm`.
> More mma cleanups

- csrc/ir/nodes.cpp
- test/test_gather.cpp
- test/test_gpu_indexing.cpp
1. Add `take_along_axis` evaluate in `TorchGatherOp`.
2. Clean unit tests in `test_gather.cpp`.
> Evaluate method for `take_along_axis`

- .github/workflows/build.yml
- setup.py
Targeting merging next Monday.
> Update setup.py to use C++20 by default

- csrc/optimization/mark_alias.cpp
> Partially revert 3d25ac345fe904d47260d7edf0fc95a2e348bc4d.

- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/optimization/alias_analysis.cpp
- csrc/optimization/mark_alias.cpp
- test/test_alias.cpp
This reverts commit eef9db87c22fa0bd8721bec89e42323a618c20b8.
Fixes #1353.
> Revert "AliasAnalysis handles slices. (#1281)"

- test/test_gpu1.cpp
> Remove `computeAt` in some unit tests.

- test/test_gpu_compute_with.cpp
- test/test_loop_rotation.cpp
- test/test_optimization_pass.cpp
Clean `test_loop_rotation.cpp`, `test_optimization_pass.cpp`, and `test_gpu_compute_with.cpp`.
> Clean unit tests [3]

- csrc/dynamic_transform.cpp
- python_tests/test_python_frontend.py
DynamicTransformConcretizer should preserve allocation domain
> Alloc domain patch concretization

- python_tests/test_python_frontend.py
> fixing CI with bf16 on pre-ampere

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/polymorphic_value.h
- test/test_gpu_view.cpp
1. Add `rsrt`, `cos`, `bit_cast` to `UnaryOp::evaluate`.
2. PolymorphicValue `abs` for `at::Tensor` type.
> Clean `test_gpu_view.cpp`.

- csrc/dynamic_transform.cpp
- python_tests/test_python_frontend.py
> follow up on code review requests

- tools/codediff/diff_report.py
- tools/codediff/templates/command_env_info.html
I think this should fix the false positives like those in https://nv/e2E/75523191
> Fix PTX false positives in codediff

- CMakeLists.txt
- csrc/compute_at_map.h
- csrc/device_lower/lower2device.cpp
- csrc/disjoint_set.h
- csrc/expr_evaluator.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/validation_utils.cpp
- csrc/id_model/validation_utils.h
- csrc/id_model/visitor.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/options.cpp
- csrc/options.h
- csrc/val_graph.cpp
Merging the current main, which includes #1168
> Updating IterDomainGraphs branch with main

- csrc/type.cpp
> Cast `DataType::SMemAddress`

- csrc/index_compute.cpp
- csrc/ir/builder.cpp
- csrc/ir/builder.h
So that it can be used in other files
> Move `getTensorBaseAddress` to `IrBuilder`

- test/test_mma.cpp
> Cleanup `test_mma.cpp`

- csrc/compute_at_map.cpp
> Stop printing Innermost map in ca_map debug dump

- CMakeLists.txt
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- test/test_id_model.cpp
Mostly just copied from ComputeAtMap
> IdModel: Check self mappings

- csrc/device_lower/pass/expr_sort.cpp
- test/test_alias.cpp
> Revert "Don't generate code that's only for aliased outputs."

- csrc/scheduler/utils.cpp
- test/test_gpu3.cpp
> Place broadcasts outside iteration in 3D reduction

- test/test_gpu1.cpp
> Clean `test_gpu1.cpp`

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_gpu_fused_reduction.cpp
> `evaluate` method for `GroupedReductionOp`

- csrc/val_graph.cpp
Didn't see anything with the main branch but encountered a segfault due to this in the #32 branch
> Fix memory error

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_dynamic_transform.cpp
- test/test_gpu2.cpp
- test/test_gpu_compute_with.cpp
- test/test_gpu_outer_reduction.cpp
- test/test_optimization_pass.cpp
> `evaluate` method for `WelfordOp`

- csrc/ir/nodes.cpp
- test/test_gpu3.cpp
> Clean `test_gpu3`

- csrc/multidevice/device_mesh.h
Remove an old assert that created a bug after merging PR https://github.com/NVIDIA/Fuser/pull/1449
> Remove old assert

- CMakeLists.txt
- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/optimization/optimize_layout.cpp
- csrc/scheduler/mark_aliases.cpp
- csrc/scheduler/no_op.cpp
- test/test_alias.cpp
Because it's used by schedulers as well.
> Move AliasAnalysis out of `csrc/optimization`.

- csrc/id_model/id_model.cpp
- csrc/id_model/validation_utils.cpp
- csrc/val_graph.cpp
- csrc/val_graph.h
> [IdModel] Propagation fix for permissive graphs

- CMakeLists.txt
- csrc/alias_analysis.h
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/id_model/validation_utils.cpp
- csrc/optimization/mark_aliases_prepare.cpp
- csrc/optimization/mark_aliases_prepare.h
- csrc/optimization/pre_segmenter.cpp
- csrc/val_graph.h
- python_tests/test_python_frontend.py
- test/test_gpu_transpose.cpp
Merging 101530ec09a7eab9937f277715be0e3ecc1478b6
> [IdModel] merge main 20231227

- csrc/scheduler/mma_utils.cpp
This is legacy code that is not currently in use. Instead, we now assert that `warp_tile.k == cta_tile.k`.
(Diff best viewed with `Hide whitespace`)
> Remove num_warp_k != 1 branch in matmul scheduler

- python_benchmarks/test_reduction.py
Benchmark inner and outer `sum` reduction.
> Single reduction benchmark

- csrc/scheduler/registry_utils.cpp
- test/test_segmentation.cpp
Needed for #1579. Fixes #1568.
> Allow intermediate tensors to have a non-contiguous allocation domain.

- python_benchmarks/test_silu_mul_bwd.py
- python_benchmarks/test_silu_mul_fwd.py
`F.silu(x) * y` benchmark from Llama2.
> `silu + mul` benchmark

- python_benchmarks/test_gelu_bwd_reduction.py
> `gelu_bwd_reduction` benchmark

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
See the design doc for more details
> IdModel: enable compliment mapping

- benchmark/matmul.cpp
An incomplete fix was provided in #1546. That fix only applied to the split-K benchmark itself, but we still saw errors in partitioned-K on H100. This PR extends the fix to the partitioned-k and splitk-reduction benchmarks.
Fixes #1605
> Use proper index type in matmul benchmarks

- csrc/expr_simplifier.cpp
> Check for obvious contradicting assumptions. 

- csrc/fusion_segmenter.cpp
See https://github.com/NVIDIA/Fuser/issues/1607
> only forward inputs with one use to avoid introducing additional persistent buffer

- test/test_tutorial.cpp
See the added test, which demonstrates how IdModel can be used to analyze reshape ops
Tagging @wujingyue, @Priya2698, @csarofeen
> Add an tutorial case for demonstrating IdModel for analyzing reshape

- csrc/multidevice/communicator.cpp
print utility for the backend type.
Useful for debugging/testing
> Multidevice tests: Print backend

- csrc/alias_analysis.cpp
- csrc/tensor_metadata.cpp
- test/test_alias.cpp
Unfortunately, but I didn't manage to find a better way to unblock myself. This makes alias analysis less effective but is at least safe for expanded broadcasts.
> More bandaids for #1126. 

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
- csrc/val_graph.cpp
- csrc/val_graph.h
There's a bug I found in the main IdModel branch (#32). See #1627 and #1636. This PR is just cherry-picking #1627.
> [IdModel] Cherry pick #1627

- csrc/multidevice/utils.cpp
Adresses issue https://github.com/NVIDIA/Fuser/issues/1656
> Add asserts in haveDifferentSharding

- csrc/executor.cpp
simple change, will print bandwidth when `perf_debug_verbose` is true.
> print bandwidth when perf_debug_verbose is true

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
While I was working on #32, I sometimes saw non-deterministic results. Hope this is the only source of non-determinism.
> Make sure ValGraphs are created deterministically

- python_benchmarks/conftest.py
> Fix Issue #1734

- csrc/multidevice/communication.cpp
API change coming from https://github.com/pytorch/pytorch/pull/119421
> fixing multidevice build

- csrc/multidevice/communication.cpp
- csrc/utils.h
- test/utils.h
patching API version guard so we'll still be able to build against older pytorch version.
> patching API GUARD

- csrc/tensor_view.cpp
as suggested by @jjsjann123, thanks!
https://github.com/jjsjann123/Fuser/pull/1#discussion_r1481044204
> add mesh_ in TensorView copy operator

- test/test_matmul_scheduler.cpp
a temporary patch. for details see #1810
> Disable propagation rule matmul test

- test/utils.h
update API macro guard for torch 2.2.1 patch release.
> patching macro again

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
Add utils functions that remove the multi-device scheduling annotations
> add multidevice utils::unshard

- benchmark/matmul.cpp
- csrc/index_compute.cpp
- csrc/mma_type.h
- test/test_combine_mul_sum.cpp
- test/test_gpu_tensorcore.cpp
- test/test_matmul_sass.cpp
- test/test_matmul_scheduler.cpp
- test/test_memory.cpp
- test/utils.cpp
- test/utils.h
Stacked on https://github.com/NVIDIA/Fuser/pull/1817, adding tests for prologue broadcast and pointwise fusion.
> Add tests for matmul prologue pointwise fusion

- csrc/multidevice/communicator.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- csrc/multidevice/lower_communication.cpp
- csrc/multidevice/utils.cpp
add/fixes some print utilities, notably `MultiDeviceExecutor::print()`
> multidevice print utils

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- test/test_id_model.cpp
> Make hasSelfMapping per tensor.

- csrc/preseg_passes/move_split_cat.cpp
I missed this API and wrote a bunch of unnecessary code.
> Use concatenatedDim to get the cat axis.

- csrc/preseg_passes/move_split_cat.cpp
> Revert "Use concatenatedDim to get the cat axis."

- csrc/fusion.cpp
- csrc/fusion.h
As per review comments from Xiang (thanks!).
> Drop the non-const exprs.

- python_benchmarks/test_transpose.py
> `eager` and `torch.compile` benchmarks for `transpose`

- csrc/tensor_metadata.cpp
- test/test_resize.cpp
> disable size/stride/contiguity validation on size-0 tensor

- csrc/codegen.cpp
- csrc/device_lower/analysis/bank_conflict.cpp
- csrc/kernel.cpp
- csrc/kernel.h
Just making the coding style more consistent
> Rename `parallel_dimension_map_` -> `parallel_dimension_map`

- doc/reading/merge-split-vs-split-merge.md
Just adding a reading material. This question comes to my mind when I was thinking through the design of TMA schedule. I don't think it is difficult for people to reach the same conclusion by themselves if they think into it, but still, I believe explicitly speaking this out could help someone understand our system better.
> Add note about "Merge then split vs split then merge"

- csrc/device_lower/analysis/thread_predicate.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/unroll.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/predicate_compute.cpp
- tests/cpp/test_memory.cpp
TMA is no longer required to be on a `<<<N, 1>>>` kernel
> TMA thread parallelization

- benchmarks/python/test_silu_mul_bwd.py
- benchmarks/python/test_silu_mul_fwd.py
> Torch baselines for `silu-mul` benchmarks

- benchmarks/python/test_scale_bias_relu_bwd.py
- benchmarks/python/test_scale_bias_relu_fwd.py
> Torch baselines for `scale-bias-relu`

- benchmarks/python/test_reduction.py
> Torch baselines for inner/outer reduction

- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_matmul_aten_evaluation.cpp
1. Adds alpha, beta parameters in matmul pattern matching
2. Unifies matching for matmul and matmul + bias.
Issue #1669.
> Unify matmul pattern matching

- CMakeLists.txt
> Drop ATEN_CUDA_ROOT variable.

- benchmarks/python/test_rmsnorm_bwd.py
- benchmarks/python/test_rmsnorm_fwd.py
> Torch baselines for RMSNorm

- csrc/multidevice/c10d_mock.h
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
This is the first step towards limiting the scope of NVFUSER_DISTRIBUTED to just communicator. If you think it's the right thing to do, more PRs will come your way!
> Add c10d mocks and localize NVFUSER_DISTRIBUTED in communicator. 

- csrc/index_compute.cpp
- tests/cpp/test_memory.cpp
Get a new name according to https://github.com/NVIDIA/Fuser/pull/2041
> TMA indexing rename "TMA-global" -> "partitioned"

- csrc/multidevice/communication.cpp
- csrc/multidevice/communicator.cpp
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/cpp/test_multidevice_communications.cpp
> Remove NVFUSER_DISTRIBUTED from fusion_definition and test_multidevice_communications. 

- benchmarks/python/normalization.py
- benchmarks/python/test_batchnorm_bwd.py
- benchmarks/python/test_batchnorm_fwd.py
- benchmarks/python/test_instancenorm_bwd.py
- benchmarks/python/test_instancenorm_fwd.py
> Torch baselines for `batchnorm` and `instance_norm`

- csrc/scheduler/mma_utils.cpp
- tests/python/test_python_frontend.py
Extending the linear API to support a 0-dim bias.
> Add support for 0-dim bias argument in Linear

- doc/dev/tma.md
- doc/dev/tma/arbitrary-view.svg
- tests/cpp/test_memory.cpp
The size in (b) and (e) changed
> Add examples in Figure 10 of `tma.md` as unit tests

- csrc/preseg_passes/move_split_cat.cpp
- tests/cpp/test_move_split_cat.cpp
> Bail out when the catted dimension is an outer-split factor.

- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_pipeline.cpp
https://google.github.io/googletest/faq.html#CtorVsSetUp
> Move code from SetUp to constructor.

- CMakeLists.txt
As per @jjsjann123's review comments on #2129.
> PUBLIC fsanitize=address on objects

- csrc/multidevice/communication.h
- csrc/multidevice/communicator.h
Tested as following. 
```
$ _bn && python -c "import nvfuser"
$ echo $?
0
```
> Remove unnecessary NVF_API.

- nvfuser/__init__.py
patch-nvfuser is no longer installed
> removing obsolete error message

- csrc/ops/alias.cpp
- tests/python/test_python_frontend.py
> Return unpadded cat inputs instead of creating CatOp

- csrc/device_lower/lower2device.cpp
> Disable idmodel

- setup.py
Thanks @jjsjann123 for the pointer!
> Update setup.py to include missing host_ir headers

- csrc/dynamic_transform.cpp
- csrc/dynamic_transform.h
- csrc/ops/alias.cpp
- csrc/transform_view.cpp
- tests/cpp/test_dynamic_transform.cpp
- tests/cpp/test_gpu_view.cpp
- tests/python/test_python_frontend.py
> Allow reshaping of empty tensors

- csrc/device_lower/lower2device.cpp
- csrc/device_lower/lower2device.h
- csrc/index_compute.cpp
Will rebase this PR after https://github.com/NVIDIA/Fuser/pull/2389 is merged.
> Enable IdModel conditionally

- csrc/scheduler/mma_utils.cpp
> Remove reduction axis when translating MatmulOp/LinearOp

- csrc/multidevice/communication.cpp
- tests/cpp/test_multidevice_communications.cpp
Also updates the test to use the subteam backend to expose the bug.
> Fix postSendRecv to use relative indices.

- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
- tests/cpp/test_multidevice_matmul.cpp
- tests/cpp/test_multidevice_pipeline.cpp
- tests/cpp/test_multidevice_sharding.cpp
As a follow-up to https://github.com/NVIDIA/Fuser/pull/2255
> Fix styles.

- csrc/dynamic_transform.cpp
- csrc/dynamic_transform.h
> Add utility to concretize a fusion given inputs

- csrc/multidevice/c10d_mock.h
This should fix the failing non-distributed build: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/99034140#L896
> Add the missing mocks.

- tests/cpp/test_matmul_scheduler.cpp
As of #2472, we perform a more accurate computation in this case by avoiding a downcast round-trip. This actually causes an error as ATen performs that round-trip, losing accuracy. This PR manually computes a reference output in each case.
Specifically, the generated epilogue for the first segment before #2472 looked like this:
```c++
asm volatile("cp.async.wait_all;\n");
#pragma unroll
for(nvfuser_index_t i146 = 0; i146 < 4; ++i146) {
nvfuser_index_t i147;
i147 = 16 * i146;
nvfuser_index_t i148;
i148 = i52 + (512LL * i146);
#pragma unroll
for(nvfuser_index_t i149 = 0; i149 < 4; ++i149) {
nvfuser_index_t i150;
i150 = i147 + (4 * i149);
nvfuser_index_t i151;
i151 = i12 + i149;
nvfuser_index_t i152;
i152 = (i148 + (32LL * (i151 / 4))) + (8LL * (i53 ^ (i151 % 4)));
#pragma unroll …
```
> Use more accurate reference in Llama2FFN test

- csrc/multidevice/c10d_mock.h
- tests/cpp/multidevice.cpp
- tests/cpp/utils.h
See code comments for the motivation.
> Enable logging. 

- runtime/memory.cu
Remove `std` namespace specifier
> Fix `elect_sync`

- CMakeLists.txt
- csrc/executor.cpp
- csrc/executor.h
- tests/cpp/test_multidevice_lower_communication.cpp
This implements Step 1 of [this doc](https://docs.google.com/document/d/1Wvh_vJYmA_LETfVNovb8mXPK95zmPOTUccauF-DX2h8/edit#heading=h.lg68cxhmn0y7). 
I'll add more tests before merging the PR, but wanted to collect early feedback.
> Enable FusionExecutor to run communication. 

- tests/cpp/test_gpu2.cpp
> change welfordShmoo test to TEST_P

- csrc/transform_rfactor.cpp
- tests/cpp/test_gpu3.cpp
> ReplayRFactor, merge of two bcast IDs should generate a bcast ID

- csrc/mma_type.h
- csrc/ops/utils.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- tests/cpp/test_translate_mma.cpp
- tests/cpp/utils.cpp
Just sed + lintrunner to change the names of these types to be more descriptive.
> Rename MatmulRole->MatmulTensorRole, MatmulDomain->MatmulDimRole

- csrc/preseg_passes/mark_aliases_prepare.cpp
For readability, and for future changes planned for #2395.
> Separate the computation of `aliased_outs` to a different loop.

- csrc/fusion.cpp
- tests/cpp/test_preseg_passes.cpp
> Fix a bug in replaceOutput.

- CMakeLists.txt
- csrc/multidevice/executor.cpp
- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/propagate_shardings.cpp
- csrc/preseg_passes/propagate_shardings.h
- tests/cpp/test_sharding.cpp
This PR prepares for Step 4 of [this plan](https://docs.google.com/document/d/1Wvh_vJYmA_LETfVNovb8mXPK95zmPOTUccauF-DX2h8/edit#heading=h.j8ae9cdb7l0y).
> Make propagateShardings a preseg pass.

- .lintrunner.toml
- benchmarks/cpp/matmul.cpp
- benchmarks/cpp/transpose.cpp
- csrc/device_lower/pass/alias_memory.cpp
- csrc/host_ir/host_ir.cpp
- csrc/scheduler/heuristic.h
- csrc/scheduler/transpose.cpp
- csrc/serde/factory.h
- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- runtime/basic_type_traits.cu
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_gpu_transpose.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/test_resize.cpp
The latest clang-format you get if you do `pip install clang-format` is this version:
https://pypi.org/project/clang-format/
> Upgrade clang-format to 18.1.8

- CMakeLists.txt
- csrc/multidevice/executor.cpp
- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/insert_reshardings.cpp
- csrc/preseg_passes/insert_reshardings.h
- tests/cpp/test_resharding.cpp
- tests/cpp/test_sharding.cpp
Similar to https://github.com/NVIDIA/Fuser/pull/2597.
> Make InsertReshardings a preseg pass.

- csrc/multidevice/communicator.cpp
> Detect double cleanup.

- csrc/ops/arith.cpp
This improves the error message for CUDA compile errors like the one in #2642.
> Check inputs to bitwise ops are integer or bool

- tests/cpp/test_alias.cpp
- tests/cpp/test_gpu_view.cpp
- tests/cpp/utils.h
- tests/cpp/validator.h
It's used in multiple test files.
I chose validator.h instead of utils.h, because nvfuser_bench uses utils.h but doesn't depend on gmock.
> Move HeuristicIs to tests/cpp/validator.h. 

- csrc/preseg_passes/propagate_shardings.cpp
Short comment clarifying when sharding propagation is applied
> Sharding propagation comment

- csrc/fusion_segmenter.cpp
> Print group IDs when printing a SegmentedFusion.

- csrc/contiguity.cpp
- csrc/contiguity.h
- csrc/index_compute.cpp
- csrc/options.cpp
- csrc/options.h
Also added a disable option to disable contiguous indexing for testing
> Mostly mechanical cleanup

- tools/codediff/compare_codegen.sh
Currently if you are on a detached HEAD (i.e. if you have run `git checkout <SHA>` then `compare_codegen.sh` will fail with `fatal: ref HEAD is not a symbolic ref`. This PR makes it safe to run in such a scenario.
NOTE: I am sometimes seeing new git branches introduced at cleanup named like the SHA of the commit and the compare commit. This has happened previously and I think it is unrelated to this change. Since it only affects cleanup, I would like to merge this PR so that we can improve `!build --diff` in the CI and look into the branch issue later.
> [codediff] Gracefully handle starting from detached HEAD

- tests/cpp/test_multidevice_transformer.cpp
Only use at::manual_seed(getATenRandomSeed()) to control random seed in reference and nvFuser programs.
> Fix random seed in multidevice mlp test

- csrc/ops/arith.cpp
- tests/cpp/test_multidevice_lower_communication.cpp
- tests/cpp/test_multidevice_sharding.cpp
- tests/cpp/test_resharding.cpp
Similar to #2734 and fixes an issue similar to #2721
> Propagate the input mesh and DIDs via reduction. 

- csrc/scheduler/vectorize_helper.cpp
- tests/python/test_python_frontend.py
This is similar to test_issue1277 but much simplified.
> Add a regression test for #2755.

- csrc/multidevice/utils.cpp
Early exit to simplify conditions and rename.
> Cleanup isSharded.

- csrc/compute_at_map.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_sdpa_node.cpp
> Allow multiple outputs with different root domains for `SDPAOp` in `ComputeAtMap`

- csrc/logical_domain_map.h
- csrc/multidevice/utils.cpp
- tests/cpp/test_multidevice_lower_communication.cpp
- tests/cpp/test_multidevice_sharding.cpp
> Fix some multidevice tests that failed with one GPU.

- csrc/preseg_passes/insert_reshardings.cpp
- csrc/preseg_passes/pre_segmenter.cpp
- csrc/preseg_passes/propagate_shardings.cpp
Separated from #2635. This implements step 4 of [this plan](https://docs.google.com/document/d/1Wvh_vJYmA_LETfVNovb8mXPK95zmPOTUccauF-DX2h8/edit).
> FusionExecutorCache runs sharding-related preseg passes. 

- tests/cpp/test_multidevice_sharding.cpp
This partially implements Step 5 of [this plan](https://docs.google.com/document/d/1Wvh_vJYmA_LETfVNovb8mXPK95zmPOTUccauF-DX2h8/edit#heading=h.lg68cxhmn0y7).
> Use FusionExecutorCache in test_multidevice_sharding.cpp.

- csrc/preseg_passes/mark_aliases_prepare.cpp
- tests/cpp/test_alias.cpp
> Preserve allocation domain when inserting segment_set.

- csrc/device_lower/pass/index.cpp
Found this issue while reading https://github.com/NVIDIA/Fuser/issues/2795
> Hoist pad predicate

- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/logical_domain_map.cpp
Remove isProducerOf/isConsumerOf, replace the one instance. Original definitions were backwards.
> Remove isProducerOf/isConsumerOf

- tests/cpp/test_combined_inner_outer_reduction.cpp
The main change is to use testValidate to compute reference outputs.
> Clean a test.

- csrc/device_lower/validation.cpp
So it's easier to figure out which condition failed.
> Split an NVF_CHECK into two.

- csrc/id_model/indexing.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/2763
> Prioritize using zero index

- csrc/evaluator_common.cpp
- csrc/expr_evaluator.cpp
- csrc/ops/utils.cpp
- tests/cpp/test_multidevice_sharding.cpp
According to what we [discussed](https://docs.google.com/document/d/1Lrx_lt09O-POJfIvzTrq-OnfREkYVIbk0ihJzw8amu0/edit#heading=h.366wkzawvgie) on Thursday.
> Fix the handling of `b(DID)`.

- csrc/scheduler/compile_time_info.h
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/registry.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
Cache the vectorization break point as it's a compile time value.
> Cache the vectorization break point in schedulers

- tests/cpp/test_multidevice_transformer.cpp
This will make the reference implementation and the actual close enough to pass under testValidate, when `-np 1`. I'm looking into `-np 2` or more as part of #2890. I suspect for that we'll have to in addition simulate the behavior of sharding. However, this change is a strict improvement and seems to be standalone enough to get merged first.
> Fix MLP's reference implementation.

- tests/python/opinfo_input_generators.py
This was broken in #2872 but this should fix CI.
> Update expected error message in cat error tests

- tests/cpp/test_multidevice_sharding.cpp
1. Improved naming.
2. Added more tests for broadcast.
> Clean test_multidevice_sharding.cpp.

- csrc/device_lower/pass/index.cpp
- tests/cpp/test_mma.cpp
The SS version of https://github.com/NVIDIA/Fuser/pull/2710
> HopperSS.FullSwizzle

- CMakeLists.txt
- csrc/id_model/indexing_traversal.cpp
- csrc/id_model/indexing_traversal.h
- tests/cpp/test_resize.cpp
Design doc: https://docs.google.com/document/d/1IJK1WdS3Lgq9mrXRJauBfICfoPXzeUN9Peu0axvZnAs/edit
This is a workaround necessary for #2851. There's more promising idea discussed in the above design doc, but for the problem at hand right now, this WAR is good enough.
> Further WAR for indexing resize

- csrc/index_compute.cpp
Fixes false warning from https://github.com/NVIDIA/Fuser/issues/2888
> Ignore DID loop ids in unroll

- tests/cpp/test_multidevice_transformer.cpp
This made validation stricter and indeed captured some precision mismatches. Fixing those has probably made reference implementations closer to actual.
> `validate` checks dtypes. 

- examples/sinh_extension/main.cpp
- examples/sinh_libtorch/main.cpp
This should fix CI errors such as https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/110545210 related to #2756.
> Fix include in C++ extension examples

- tests/cpp/test_multidevice_transformer.cpp
Fix https://github.com/NVIDIA/Fuser/issues/2899
> Update multidevice transformer test skip conditions

- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- nvfuser/__init__.py
- tests/python/test_multidevice.py
and use that to specify DID schedules.
Fixes #2929.
> Add FusionDefinition.multidevice_schedule

- csrc/ir/internal_base_nodes.h
- csrc/logical_domain_map.cpp
Encountered while working on #2936
> Minor cleanup & fix

- tests/python/test_transformer_engine.py
See code comments for details.
> Allow profiling a benchmark iteration.

- tests/cpp/test_mma.cpp
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002
> Add new test `HopperSS.SingleTileTransposed`

- tests/cpp/test_mma.cpp
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002
> Add new test `HopperRS.SingleTileTransposed`

- csrc/ops/alias.cpp
- csrc/scheduler/transpose.cpp
- tests/cpp/multidevice.cpp
- tests/cpp/test_multidevice_sharding.cpp
- tests/python/test_multidevice.py
This is required to land #3045.
> Fix a bug in the transpose scheduler.

- csrc/device_lower/pass/index.cpp
- csrc/val_graph_visitor.cpp
- csrc/val_graph_visitor.h
- tests/cpp/test_mma.cpp
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002
> Add new test `HopperRS.MultipleTile`

- tests/cpp/test_mma.cpp
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002
> Add new test `HopperSS.MultipleTile`

- csrc/multidevice/communicator.cpp
Fixes #3055. Thanks @nWEIdia for recognizing it as a duplicate of an existing bug. 
The github CI has been downgraded to use NCCL 2.22, so I tested this manually using the repro in #3055.
> Destroy ProcessGroupNCCLs in the same order between ranks.

- csrc/preseg_passes/propagate_shardings.cpp
No functionality changes; only for readability.
> Move validation to a separate function.

- tests/cpp/test_gpu3.cpp
It was moved to test_indexing_advanced.cpp in PR #3028. Looks like it got recovered likely when other PRs got merged.
> Delete a moved test again

- tests/cpp/test_mma.cpp
- tests/cpp/utils.h
So that other test files can use it.
> Move a few utilities to a common area

- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_multidevice_sharding.cpp
See code comments for details.
> Backprop meshes in addition to forward. 

- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_multidevice_sharding.cpp
According to what we [discussed](https://docs.google.com/document/d/1Lrx_lt09O-POJfIvzTrq-OnfREkYVIbk0ihJzw8amu0/edit#heading=h.366wkzawvgie).
This is required to land #3045.
> Reset r(DID) at the end of propagation.

- csrc/device_lower/validation.cpp
> A little code refactoring and fix

- tests/cpp/test_multidevice_communications.cpp
> Skip CommunicationTest.SendRecv/UCC.

- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_communicator.cpp
- tests/cpp/test_multidevice_overlap.cpp
- tests/cpp/test_multidevice_pipeline.cpp
- tests/cpp/test_multidevice_tutorial.cpp
https://google.github.io/styleguide/cppguide.html#Constant_Names
> Make naming more consistent with the rest of the code base.

- tests/cpp/test_multidevice_overlap.cpp
From the document with some tasks Sam prepared for me: https://docs.google.com/document/d/1Oj-EgUyhgfpxDFkfF43Q4pIe_4gtJzXOSUIgjYEI7wU/edit#heading=h.t098gw7m1xok
This PR implements Allgather-based pipelining
> Allgather-based pipelining ATen Implementation

- csrc/python_frontend/python_bindings.cpp
- tests/python/test_define.py
- tests/python/test_multidevice.py
As a follow-up to https://github.com/NVIDIA/Fuser/pull/3116#discussion_r1789980138.
> ops.define_tensor can take contiguity as single boolean.

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ops/alias.cpp
- csrc/python_frontend/translation.cpp
- tests/python/test_python_frontend.py
This PR adds support for `Slice` operations to `FusionTranslation`.
> Add Slice to FusionTranslation

- nvfuser/__init__.py
- tests/python/test_python_frontend.py
> Make contiguous tensors with torch.testing.make_tensor.

- csrc/python_frontend/python_bindings.cpp
- tests/python/test_alias.py
Could have been caught if #3117 were fixed.
> Fix a bug in fd.ops.squeeze.

- csrc/python_frontend/fusion_state.cpp
This PR adds which `RecordFunctor` is causing the nvfuser failure to the exception message.
Fixes #3190
> Fix Issue 3190

- tests/python/test_multidevice.py
More tensors are saved, i.e., are returned as an output. This new version is also consistent with #3177, which tries to add the backprop. 
The previous version came from benchmarks/python/test_transformer.py, which has been outdated. Down the road, I plan to remove benchmarks/python/test_transformer.py and maintain only one version.
> Update the forward pass based on a more recent Thunder version. 

- csrc/device_lower/pass/circular_buffer.cpp
Pulled out from https://github.com/NVIDIA/Fuser/pull/3202
> Cleanup of circular buffering pass: add `currentComputeStage`

- csrc/device_lower/pass/circular_buffer.cpp
Pulled out from https://github.com/NVIDIA/Fuser/pull/3202
> Cleanup of circular buffering pass: add `onlyOneSerialForLoopOnStack`

- csrc/ops/composite.cpp
- csrc/utils.h
- tests/python/test_multidevice.py
Similar to https://github.com/NVIDIA/Fuser/pull/3116.
> Fix sdpfa_bwd to not assume the presence of DIDs

- tests/python/test_multidevice.py
Example: 
```
$ mpirun -np 1 pytest tests/python/test_multidevice.py -k 'forward or backward' --only-mpi -s
--------------------------------------------------------------------------------------- benchmark: 2 tests ---------------------------------------------------------------------------------------
Name (time in ms)                  Min                 Max                Mean             StdDev              Median               IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_transformer_forward       45.9815 (1.0)       71.0699 (1.0)       65.1025 (1.0)      10.7965 (4.47) …
```
> Add code to benchmark and profile test_transformer_backward.

- tests/cpp/test_preseg_passes.cpp
> fix test FusionCyclicGraph

- tests/python/utils.py
- tools/codediff/compare_codegen.sh
This is another attempt to fix the codediff CI job
Fixes #3265. Fixes #3283.
> Disable nvfusertest_serde_check if DEBUG_SERDE=disable

- csrc/expr_evaluator.cpp
- csrc/expr_evaluator.h
> Factorize ExpressionEvaluator::bind_.

- .github/workflows/nvfuser-ci-trigger.yml
- .github/workflows/pull.yml
- .github/workflows/push.yml
per title;
wiki and backend trigger will be updated later
> Update !build and !test triggers for CI pipelines; add a CI hello message for pull requests

- csrc/runtime/fusion_executor_cache.cpp
Seems to be legacy code that nobody cares about.
> Remove use of RECORD_FUNCTION.

- CMakeLists.txt
I accidentally replaced this line in #3028
> Accidentally lost in #3028

- csrc/device_lower/id_model_options.h
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/lower2device.h
- csrc/device_lower/utils.cpp
- csrc/id_model/id_model.cpp
- csrc/index_compute.cpp
- csrc/predicate_compute.cpp
This is also a preparation for enabling IdModel
> Clean up IdModel options

- tests/python/test_multidevice.py
> Test multiple memory formats

- csrc/ir/internal_nodes.h
- csrc/ir/utils.h
- csrc/preseg_passes/allocation_order_inference.cpp
- tests/cpp/test_allocation_order_inference.cpp
> AllocationDomainPass sets correct allocation orders for SdpaFwdOp/SdpaBwdOp. 

- tests/cpp/test_multidevice_transformer.cpp
Removes the casts in multihead attention tests that were uncessary following fix from @wujingyue 
that resolved https://github.com/NVIDIA/Fuser/issues/3194
> Remove unnecessary cast

- csrc/device_lower/pass/allocation.cpp
A minor variable renaming and add comment
> Variable renaming in AllocationInserter

- csrc/python_frontend/python_bindings.cpp
* Adds `__repr__` method that maps to `LaunchParams::toString`
> Fix gdimz in LaunchParams

- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
A utility that will be used in my big PR https://github.com/NVIDIA/Fuser/pull/3446. Splitting this out as a separate PR so that my big PR is slightly easier to review.
> Add `ParallelDimensionMap::getNumThreadsEachBlock`

- csrc/preseg_passes/reorder_sharded_axis.cpp
> Remove unnecessary propagation that's already done by the ops API.

- csrc/multidevice/utils.cpp
- csrc/preseg_passes/optimization_pass.h
This is to help track down the host latency regression found in #3421.
> Add a few FUSER_PERF_SCOPEs for isResharding.

- csrc/id_model/circular_buffer_indexing.cpp
A minor refactoring that has no behavioral change but improves code readability and naturally generalizes to warp specialization.
> Minor refactor on circular buffer indexing

- tests/python/test_multidevice.py
> Increase threshold

- benchmarks/python/test_transpose.py
Fixes an import error in PR #3453.
> Fix import error

- csrc/compute_at_map.cpp
Just patching ComputeAtMap to exclude dead expressions and vals.
> Fix ComputeAtMap for non-linear ID dependencies

- csrc/id_model/utils.h
> Don't disable ExprSimplify in shouldUseZero

- csrc/scheduler/hopper_multi_matmul.cpp
- tests/cpp/test_matmul_scheduler.cpp
When we do not have an epilogue (not even a cast), it might be the case that the original `MmaOp` has output which is a Fusion output. In this case the cached output which we often call `dc` is actually an `mma_result`. Currently this causes us to schedule that tensor once in `scheduleMmaResults` then again in `scheduleEpilogue`, leading to an esoteric error (see included test). This PR simply skips scheduling those tensors directly if they are already known to be mma results.
> Fix double-scheduling of dc in HSS hopper matmuls

- tests/python/test_python_frontend.py
The issue #1279 was resolved, so this PR adds a unit tests for the issue.
> Add unit test for issue 1279

- csrc/preseg_passes/move_pad.cpp
- tests/cpp/test_move_pad.cpp
Fixes #3597 
Also used more descriptive variable names to help read the code.
> Fix move pad

- tests/cpp/test_mma.cpp
Fixing types: int -> int64_t
This is based on top of: 
https://github.com/NVIDIA/Fuser/pull/3613
> Fix types in the stmatrix test in test_mma.cpp

- tests/cpp/test_matmul.cpp
> Add warp specialization to HSH_NT_128BSwizzle

- tests/cpp/test_matmul_scheduler.cpp
I happen to have an Ada GPU (8.9) and these tests run just fine there.
> More matmul test coverage

- csrc/ir/nodes.cpp
> BroadcastOp::toString() show broadcast flags as well

- csrc/scheduler/pointwise.cpp
- csrc/scheduler/pointwise_utils.cpp
- csrc/scheduler/pointwise_utils.h
- csrc/scheduler/tools/domain_map.cpp
- csrc/scheduler/tools/domain_map.h
- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.h
so that it can be used by the resize scheduler. Also moved PointwiseDomainMap to domain_map.h.
No logic change. Just code motion.
> Move TransposeDomainMap out of transpose.cpp

- CMakeLists.txt
- csrc/python_frontend/multidevice_bindings.cpp
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/python_bindings.h
and therefore rename it to multidevice_bindings.cpp for more multi-GPU python bindings coming up.
> Move _C.DeviceMesh to communicator_bindings.cpp

- nvfuser/__init__.py
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
> Fix type annotation

- .github/workflows/pull.yml
The system prompt is generated by LLM from https://github.com/NVIDIA/Fuser/wiki/PR-Guidelines
> Update PR review system prompt

- csrc/host_ir/container.cpp
- csrc/host_ir/container.h
Define the destructor in its implementation file to fix the build error of issue #3761
> Fix the build issue of #3761

- csrc/ir/nodes.cpp
- csrc/tensor_view.cpp
- tests/cpp/test_tutorial.cpp
- tests/python/test_multidevice.py
This PR:
1. Adds rfactor support for `MatmulOp`.
2. Under loop split, matmul + allreduce is represented as an rfactored reduction.
> DID loop split for `matmul + allreduce`

- tests/cpp/test_tutorial.cpp
I keep referring to this example when trying to recall rFactor. I think it's helpful to spell out the root domain as well as logical.
> Clarify root domain

- .github/workflows/nvfuser-ci-trigger.yml
The real change is one line, but I also did a `set ff=unix`. Is there a good reason to keep the file in dos format?
> Add syed-ahmed to nvFuser CI

- .lintrunner.toml
- csrc/polymorphic_value.h
- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- lib/dynamic_type/test/member.cpp
- lib/dynamic_type/test/opcheck.cpp
- runtime/fused_welford_helper.cu
Get new version at: https://pypi.org/project/clang-format/
The new version seems to format better, see diff.
> Update clang-format version to the latest (19.1.7)

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/tensor_view.cpp
- tests/cpp/test_multidevice_matmul.cpp
> DID loop split for linear => allreduce

- tests/cpp/test_rope.cpp
> Adding Phi3 RoPE as C++ tests

- csrc/scheduler/pointwise.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- csrc/tensor_view.cpp
- tests/cpp/test_multidevice_sharding.cpp
> Allow pointwise to take a DID-loop-split fusion. 

- csrc/index_compute.cpp
- tests/cpp/test_indexing.cpp
Fixes #3740 
The underlying issue is the same as #817 and #3299, which were fixed in #3387 by using the new indexer. However, we just forgot to extend `Index::getLinearLogicalIndex` to use the new indexer, so that was still using the old indexer, which still has the same issue.
> Add a missing TensorIndexer-based implementation of getLinearLogicalIndex

- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/scheduler/vectorize_helper.cpp
Found them when working on #2563
> A few minor fixes

- csrc/multidevice/utils.cpp
- tests/cpp/test_multidevice_sharding.cpp
`TensorView::reorder` expects a map from old to new position.
> Fix `reorderDIDtoFront`

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
> [Typo] Replace rank to local_rank

- .github/workflows/pull.yml
- .github/workflows/upload-ci-logs-v2.yml
per title
Also adds a new workflow dispatch for upload-ci-logs-v2, which we will use later.
> Update CI prompt messages for expected checks

- csrc/index_compute.cpp
- runtime/memory.cu
- tests/cpp/test_memory.cpp
- UBLK store is added
- Revised the test to use UBLK store
> add ublk store

- csrc/runtime/compiled_kernel.cpp
Important functions like `FusionExecutorCache::getCode`, and `CompiledKernel::recompileKernel` are ignoring the `NVFUSER_EXTERNAL_SRC`, as a result, we are not executing the specified external source.
> fix NVFUSER_EXTERNAL_SRC

- csrc/ir/container.cpp
> Clean the use of unique_ptr

- .github/workflows/pull.yml
> [CI] Remove placeholder pending status for build_image_17

- csrc/kernel_ir.cpp
Before:
```
IF Manual ( threadIdx.y == ( 2 - 1 ) ):
setmaxnreg.dec.sync.aligned.u32    FOR i113 in iS10{( ceilDiv(( (( (( getMetaData(T0) )).logical_size ))[1] ), 32) )}:
IF ElectSync:
return  ELSE:
```
After:
```
IF Manual ( threadIdx.y == ( 2 - 1 ) ):
setmaxnreg.dec.sync.aligned.u32
FOR i113 in iS10{( ceilDiv(( (( (( getMetaData(T0) )).logical_size ))[1] ), 32) )}:
IF ElectSync:
return 
ELSE:
```
> format toString for SetMaxNReg and Return

- setup.py
Update the explanation of `--cpp=STANDARD` to C++20 from C++17.
> update the default to 20

- nvfuser/__init__.py
Fixes #4024
Should have been fixed in #3969
> Don't redefine schedules

- csrc/fusion_segmenter.cpp
- csrc/serde/fusion_cache.fbs
This implementation of toposort is shorter and is guaranteed to be O(V+E).
> Simplify resetLevels

- tests/python/test_python_frontend.py
https://github.com/NVIDIA/Fuser/issues/3856
> Mark is_clonable=False to work around a memory corruption

- csrc/runtime/fusion_kernel_runtime.cpp
and call ExecutorAbstract::supported less often. This is a leftover from https://github.com/NVIDIA/Fuser/pull/3885.
> Create fewer subfusions

- csrc/ir/nodes.cpp
- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/type.cpp
- csrc/type.h
- runtime/bit.cu
- tests/cpp/test_gpu1.cpp
https://en.cppreference.com/w/cpp/numeric/bit_ceil
This function computes the next power of two, which is very useful for things like computing TMem allocation size.
> Add unary op bit_ceil

- csrc/id_model/id_model_index_compute.h
- csrc/id_model/indexing.cpp
Just some random changes I accumulated in my draft branch but have not yet merged in.
> IdModel minor misc updates 

- csrc/utils.h
- tests/cpp/test_utils.cpp
> Write yield in C++ like Python

- benchmarks/python/rope_ops.py
- benchmarks/python/test_rope.py
> Expand rope benchmark to sweep across sequence length

- csrc/host_ir/lower.cpp
See https://github.com/NVIDIA/Fuser/blob/82b9a582119c8eda73c278533079ff13d27ea687/csrc/utils.h#L125
> Fix a nullptr access

- CMakeLists.txt
- csrc/driver_api.h
- tests/cpp/test_driver_api.cpp
- tests/cpp/test_gpu3.cpp
> Enable lazy loading for cuStreamWriteValue32

- csrc/runtime/fusion_kernel_runtime.cpp
- tests/cpp/test_multidevice_lower_communication.cpp
Follow-up PR to https://github.com/NVIDIA/Fuser/pull/4136. Adds HostIR lowering to FusionKernelRuntime.
> Add HostIR lowering to FusionKernelRuntime

- benchmarks/cpp/main.cpp
- csrc/kernel.cpp
- csrc/scheduler/utils.cpp
use cudaDeviceGetAttribute for clock & memory rate
> change to cudaDeviceGetAttribute for clock & memory rate

- csrc/codegen.cpp
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/ir/interface_nodes.h
- csrc/kernel_ir.h
- csrc/parallel_dimension_map.h
- csrc/predicate_compute.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/type.cpp
- csrc/type.h
* Blackwell UTCMMA is an mbarrier async operation that is not a TMA load operation.
* It will be included in the separate warp group and run in parallel with TMA loads for the operands.
* This new name is more consistent with what the warp group does.
> Rename LoadWarp to AsyncWarp

- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/index.cpp
We will use this to track the mbarrier for Blackwell MmaOp
> Rename `ldstMBarrierMap` -> `mbarrierMap`

- csrc/device_lower/pass/circular_buffer.cpp
This PR is a step to separating `CircularBufferInserter` into two separate variants that handle warp specialized and pipeline circular buffering separately.
* Change `CircularBufferLoopNestInspector::run` to return pipeline and warp-specialized in two separate `InsertionInfo`.
* Process `pipeline` before `warp-specialized` because the circular buffer for-loops must be handled from inner to outer-most and we can only nest pipeline circular buffers inside of warp-specialized `IfThenElse`.
* Enforce that only four warp-specialized for-loops occur in the fusion. They will be handled by separate warps inside of a single `AsyncWarp` warp group.
> Split insertion_info into Pipeline and WarpSpecialized parts

- csrc/options.cpp
https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
> Prefer static local to static global

- csrc/host_ir/container.h
- csrc/runtime/compiled_kernel.h
https://google.github.io/styleguide/cppguide.html#Include_What_You_Use
https://google.github.io/styleguide/cppguide.html#Forward_Declarations
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
> Fix includes

- csrc/device_lower/pass/circular_buffer.cpp
Currently, the predicate for the `AsyncWarp` is `threadIdx.y == (blockDim.y - 1)`. This PR generalizes the predicate to be `threadIdx.y >= (blockDim.y - padded_value)` where `padded_value` is the extra value added so the `AsyncWarp` has 128 threads.
- For consistency, we should always pad the `AsyncWarp` to add `128` threads to the original CTA size.
- At the moment, this support is limited to the register sharing case. 
- We have to fix predicate logic to enable it for all `WarpSpecialization`.
- The `padded_value` is 1 if the remaining `ParallelTypes` are of size `128`.
Current:
```python
if threadIdx.y == (blockDim.y - 1):
else:
```
New:
```python
if threadIdx.y >= (blockDim.y - padded_value):
else:
```
> Generalize the AsyncWarp selection predicate.

- csrc/scheduler/resize.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
Just added an assertion. Also changed the interface of a util function.
> Minor change of the resize scheduler

- python/setup.py
Change comment from `NVFUSER_BUILD_TYPE` to `NVFUSER_BUILD_BUILD_TYPE` to match actual code.
> Update environment variable comment in python/setup.py

- doc/dev/debug.md
> Remove setup.py from doc

- tests/cpp/utils.cpp
See code comments and let me know if there's a better fix
> Replace an enum with a hardcoded value

- csrc/disjoint_set.h
> fixing a typo in macro usage

- csrc/device_lower/analysis/divisible_split.cpp
- csrc/device_lower/utils.cpp
No particular case this would help, but generally should promote generating better code.
There are a few diffs found. They seem to be legitimate changes and the code is slightly simplified.
> Expand the divisible split set if Exact graph is available

- python/utils.py
This PR fixes merge conflicts with [Fix using custom install dir in build](https://github.com/NVIDIA/Fuser/pull/4388#top).
> Fix hardcoded path in copy_library

- python/python_frontend/python_bindings.cpp
It should match the beginEvent in _setup_definition.
> Fix a bug in tracing

- csrc/multidevice/ipc_handle.cpp
c10d::TCPstore::get is blocking until a timeout, so there isn't a need to barrier and check for the store to have a key.
> Remove extra assert in ipc handle exchange

- csrc/host_ir/container.cpp
- csrc/host_ir/container.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
> Naming changes

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/ir/nodes.cpp
- csrc/preseg_passes/make_resharding_contiguous.cpp
- csrc/preseg_passes/mark_aliases_prepare.cpp
- tests/cpp/test_alias_analysis.cpp
- tests/cpp/test_dynamic_transform.cpp
- tests/cpp/test_multidevice_sharding.cpp
> Alias analysis tries to recognize meta ops with DID loop splits.

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/propagate_shardings.cpp
- csrc/scheduler/utils.h
> Move `propagateDIDTransform` to utils

- csrc/host_ir/executor.cpp
> Instrument several key methods of HostIrEvaluator

- csrc/dynamic_transform.cpp
- tests/python/multidevice/test_dtensor.py
> Simplify test_dtensor.py::test_linear to use DID loop split

- csrc/scheduler/matmul_hopper+.cpp
- csrc/scheduler/matmul_hopper+.h
Create `scheduleEpilogueWithSmemEpilogue` and `scheduleEpilogueWithoutSmemEpilogue` and split `scheduleEpilogue` into these functions.
> Refactor `HopperPlus::scheduleEpilogue`

- tests/python/multidevice/test_deepseek_v3.py
Downloading occasionally fails in CI. I hope this PR will make the test more reliable.
> Download once and broadcast via cache

- csrc/driver_api.cpp
std::call_once is a library feature. Static variable initializers are instead defined by the language, so it is more reliable and portable.
> Replace std::call_once with a static variable initializer.

- csrc/multidevice/communicator.cpp
> Improve error messages

- csrc/linked_hash_map.h
- csrc/preseg_passes/finalize_multidevice_domains.cpp
This approach is more efficient.
> Use `LinkedHashMap` to compute transfomed allocation domain and contiguity

- csrc/linked_hash_map.h
https://google.github.io/styleguide/cppguide.html#Integer_Types => on unsigned integers
> Let LinkedHashMap::size() return int64_t

- tests/python/multidevice/linear.py
- tests/python/multidevice/test_deepseek_v3.py
> Replace linears in DeepSeek V3 with nvFuser's TP linears. 

- tests/python/multidevice/test_matmul.py
This just works out of the box! Will try row parallel next...
> Test column parallel grouped gemm

- tests/python/opinfo_input_generators.py
Fixes test failure due to error message changed by #4671
> Update error message for define_tensor test

- tests/python/test_pointwise.py
> Missing changes to disable FusionProfiler

- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_multidevice_sharding.cpp
> Backpropagation of shardings should not override user annotations

- tests/python/multidevice/test_transformer.py
> Test tensor-parallel grouped MLP

- CMakeLists.txt
- csrc/runtime/compiled_kernel.cpp
- runtime/argsort.cu
- runtime/cub_utils.cu
- runtime/scan.cu
- runtime/topk.cu
- tests/cpp/argsort_test_kernels.cu
- tests/cpp/scan_test_kernels.cu
- tests/cpp/topk_test_kernels.cu
https://github.com/NVIDIA/Fuser/pull/4775#discussion_r2205558448
> Cleanup to remove duplicated CUB-related code

- CMakeLists.txt
- csrc/host_ir/lower.cpp
- csrc/multidevice/executor.h
- csrc/preseg_passes/decompose_reshardings.cpp
- csrc/preseg_passes/decompose_reshardings.h
- csrc/preseg_passes/pre_segmenter.cpp
- csrc/preseg_passes/remove_bcast_squeeze.cpp
- tests/cpp/test_resharding.cpp
- tests/cpp/test_sharding.cpp
The latter more accurately describes what the pass tries to do.
> Rename insert_reshardings to decompose_reshardings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
* #4824 
* #4825 **<< This PR**
* #4826
* #4827
* #4828
> Add expand op to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
* #4824 
* #4825 
* #4826 
* #4827 **<< This PR**
* #4828
> Add index_select and select ops to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
* Enable unary, binary, ternary, matmul, and linear opinfo tests
* #4824 
* #4825 
* #4826 
* #4827 
* #4828 **<< This PR**
> Add ternary ops to direct bindings

- tests/python/test_moe.py
This makes it easier to use the real grouped_mm when it's ready.
cc @kshitij12345
> Add a fake grouped_mm implementation and use it from the benchmark

- python/python_direct/ops.cpp
- tests/python/direct/test_python_frontend.py
- #4876   
- #4877   **<< This PR.**
- #4878
- #4879 
- #4880 
- #4881
- #4882
- #4883
- #4884
> Add addcmul operation to direct_bindings

- python/python_direct/ir.cpp
- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/opinfo/opinfos.py
- #4876   
- #4877
- #4878
- #4879 
- #4880 
- #4881   **<< This PR.**
- #4882
- #4883
- #4884
> Add topk operation to direct bindings

- python/python_direct/python_translate.cpp
- python/python_direct/runtime.cpp
- tests/python/direct/test_python_frontend.py
- #4876   
- #4877
- #4878
- #4879 
- #4880 
- #4881 
- #4882  **<< This PR.**
- #4883
- #4884
> Support alias outputs in direct bindings.

- csrc/exceptions.h
Fixes https://github.com/NVIDIA/Fuser/issues/1169
> Add more NVF_ERROR/CHECK_* for convenience

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
- #4907
- #4908 **<< This PR.**
- #4909 
- #4910
- #4911 
- #4912
- #4913
- #4914
- #4915
> Add pad operation to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/opinfo/opinfos.py
- #4907
- #4908
- #4909 
- #4910  **<< This PR.**
- #4911 
- #4912
- #4913
- #4914
- #4915
> Add argsort operation to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_sdpa.py
- #4907
- #4908
- #4909 
- #4910 
- #4911 
- #4912  **<< This PR.**
- #4913
- #4914
- #4915
> Add sdpfa_fwd operation to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- #4907
- #4908
- #4909 
- #4910 
- #4911 
- #4912 
- #4913 
- #4914   **<< This PR.**
- #4915
> Add uniform and random operations to direct bindings

- python/nvfuser_direct/__init__.py
- python/python_direct/multidevice.cpp
- tests/python/multidevice/test_dtensor.py
https://github.com/NVIDIA/Fuser/issues/4728#issuecomment-3052751448
Fixes #4728 
cc @kshitij12345
> Propagate mesh_dim_names

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
* Match pytorch name scheme like `torch.sum(input, dim, keepdim=False, *, dtype=None)`
> Rename `keep_dim` keyword name to `keepdim`

- tests/python/multidevice/test_dtensor.py
- tests/python/multidevice/test_expert_parallel.py
> Reference implementation for expert parallelism dispatch

- python/python_direct/ir.cpp
- tests/python/multidevice/test_matmul.py
* Add rfactor support to TensorView
> Convert `test_matmul.py` to direct bindings

- csrc/scheduler/tools/domain_map.cpp
- tests/python/test_repro.py
> Skip indexed ID traversal when multimap contains cycles

- csrc/scheduler/normalization_inner_outer.cpp
> Revert "temp disable warp specialized norm"

- tests/python/direct/test_python_frontend.py
- tests/python/test_python_frontend.py
> reducing test permutation to avoid exploding test time

- csrc/fusion.cpp
- csrc/fusion.h
- csrc/ir/iostream.cpp
- csrc/ir/iostream.h
- csrc/ir/printer.h
- tests/cpp/test_iostream.cpp
Previous code triggers a segfault.
> Properly print (Fusion*)nullptr

- csrc/codegen.cpp
- csrc/device_lower/analysis/sync_information.cpp
- csrc/device_lower/analysis/sync_information.h
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- tests/cpp/test_gpu2.cpp
Just refactoring with no logic change. Added more explicit API like `SyncMap::needsBlockRawSync`.
> Minor refactoring of SyncMap

- CMakeLists.txt
- csrc/device_lower/pass/alias_memory.cpp
- csrc/fusion.cpp
- csrc/fusion_segmenter.cpp
- csrc/host_ir/container.cpp
- csrc/ir/iostream.cpp
- csrc/ir/iostream.h
- csrc/ir/printer.cpp
- csrc/ir/printer.h
- csrc/kernel.cpp
- csrc/utils.h
> Remove IrMathPrinter

- csrc/preseg_passes/propagate_shardings.cpp
`getOutputsWithMesh` can be removed now that we cache `user_sharded_tvs`.
> Remove `getOutputsWithMesh`

- csrc/transform_rfactor.cpp
This approach should be faster and simplifies the update logic.
For PR #5090
> Use linked hash map to update logical domain in rfactor

- doc/reading/multigpu.md
We haven't fully implemented pipeline parallelism but it may be useful to write this down as the North Star.
> Documentation for pipeline parallelism

- csrc/device_lower/analysis/sync_information.cpp
- csrc/device_lower/analysis/trivial_broadcast.cpp
- csrc/device_lower/analysis/trivial_broadcast.h
- csrc/scheduler/greedy.cpp
- tests/cpp/test_greedy.cpp
Minor fixes for misc bugs that were encountered with test_moe.py
> Fix TopK when K=1

- csrc/device_lower/pass/index.cpp
- csrc/ir/internal_base_nodes.h
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/utils.cpp
> Add filter TensorDomain::kNoDevices

- benchmarks/python/benchmark_inference.py
- benchmarks/python/layers_for_inference_benchmark.py
Copying over the inference benchmark from https://github.com/Lightning-AI/lightning-thunder/pull/2487. 
Run with `python benchmarks/python/benchmark_inference.py --mode thunder`:
> Pull Llama-4-Maverick inference benchmark from lightning

- csrc/scheduler/utils.cpp
- tests/cpp/test_utils.cpp
They only run in debug mode so didn't get caught by CI.
> Fix several UtilsTests

- python/log
> Remove a file accidentally checked

- python/python_direct/schedule.cpp
- tests/python/direct/test_tutorial.py
* Add `parallelize_like` and `inline_most` to schedule API
PR stack
* #5247
* #5248  **<< This PR**
* #5249
> Migrate `Tutorial.VectorizeStorePointwiseTMA` and `Tutorial.PointwiseBroadcastTMA` to direct bindings
