NVIDIA/Fuser

- test/test_gpu_multidevice.cpp
- test/test_multicluster_fusion.cpp
Cherry-picking from: https://github.com/csarofeen/pytorch/pull/2574
Author: samnordmann <snordmann@nvidia.com>
Date:   Mon Mar 13 17:44:39 2023 +0100
Fix multidevice tests (#2574)
* fix tests for multicluster fusion
> Fix multidevice tests

- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- test/test_gpu2.cpp
- test/test_gpu_gather_ops.cpp
- test/test_gpu_outer_reduction.cpp
Patched build failure against upstream pytorch where no-sign-compare is enforced now.
> Sign compare patch

- benchmark/layer_norm.cpp
- benchmark/layer_norm_backward.cpp
- csrc/scheduler/normalization.cpp
Fixes https://github.com/csarofeen/pytorch/issues/2331
set pad_bimx to true if bdimx is a multiple of warp size.
I tested shapes of {8K, 16K} x {768, 1024, 1280, 1600} which are used in GPT-2. Bandwidth is improved by 6% to 10% for hidden size of 768 and 1024 since codegen will use warp reduction instead of block reduciton. No influence for 1280 and 1600 as they were using warp reduciton in the devel branch.
> set pad bdimx to ttrue if bdimx is a multiple of warp size

- csrc/ops/alias.cpp
- csrc/ops/arith.cpp
We currently allow `castOp` to convert complex values to real, using `std::real`. In PyTorch, when this is done a warning is presented indicating that this operation discards the imaginary part. This PR adds such a warning to `castOp`.
> Warn when casting from complex to real

- csrc/expr_simplifier.cpp
- csrc/ir_builder.cpp
- csrc/ir_interface_nodes.h
- csrc/kernel_ir.cpp
- csrc/lower_scalar_hoist.cpp
- csrc/ops/arith.cpp
- csrc/type.cpp
- csrc/type.h
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_loop_rotation.cpp
When working on https://github.com/csarofeen/pytorch/pull/1900, I find that sometimes expr simplifier will assign the dtype of a value wrongly. This is because expr simplifier is written loosely assuming the dtypes of all `Val`s are the same. However, because we are putting pointer types into the expression, we need to be more careful, otherwise we will get wrong kernel code like:
```
__half* ptr1 = threadIdx.x * 128;
__half* ptr2 = ptr1 + 256 + T1.data;
```
This PR changes all passes in the expr simplifier to let it infer dtype from its inputs.
> Fix dtype calculation in expr simplifier

- csrc/scheduler/normalization.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- test/test_resize.cpp
C++ test copied from #27 
If the producer of a resized tensor is an input cache and we need to promote it to global memory, just do not cache the input but directly read from the global memory input. It doesn't make any sense to cache a global memory input in global memory. 
This fixes the issue of #27, which is due to the grid sync inserted for an input to pad, where the input is a copy of a fusion input.
> Avoid input cache when resized

- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- test/test_resize.cpp
When a single tensor is sliced multiple times, the insertion of a copy was done just once, which is a bug. Previously I used `cacheAfter`, so that was the right thing to do.
Changed a test to exhibit the problem.
> Bug fix: Resize memory promotion

- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- python_tests/test_python_frontend.py
- Enabled eager mode checking of `test_nanogpt_split_mha_linears` after Naoya fixed the previous errors in PR #51.
- Moved `slice` attribute checking from the `SliceOpRecord` to the python bindings so a terminal cache node was not created prior to the checks.
- Added more testing and checks for matching the input tensor dimensions with the attribute dimensions given in the `slice` operation.
> `slice` python attribute checking and testing update

- CMakeLists.txt
PyTorch changes NVTX dependency and is no longer exposed that as public for `torch_cuda`. https://github.com/pytorch/pytorch/pull/90689
> patch nvtx in cmake lookup

- csrc/scheduler/registry.cpp
- test/test_resize.cpp
Resize ops are not replayed, so they don't need to be exactly mapped
Previously, `FusionSliceForNanoGPT3_CUDA` was segmented as the `resize` ops are not exactly mapped since they have the different expansion arguments. Since those `resize` ops are part of rfactor transformations, they were detected as conflicting rfactor transformations. However, unlike the `split` and `merge` used by `reshape`, `resize` ops are not replayed, so they don't need to be uniform.
This is also part of the fix for #58. Looks like the Python example is not segmented anymore, although I suspect there's still something need to do for `permute`.
> Ignore Resize ops when validating all ID uses are exactly mapped.

- test/test_gpu3.cpp
This fixes a runtime error on Volta machines where we tried to use BFloat16. We now skip that test when we don't detect an Ampere or later device, and we don't compile the test at all for CUDA < 11.
> Split out BFloat16Scalar test and guard for >=Ampere

- csrc/codegen.cpp
- csrc/compute_at.cpp
- csrc/compute_at_map.cpp
- csrc/contiguity.cpp
- csrc/contiguity.h
Minor Errors:
1.  Error (CLANGTIDY) [performance-for-range-copy,-warnings-as-errors] loop variable is copied but only used as const reference; consider making it a const reference
2.  Error (CLANGTIDY) [modernize-use-emplace,-warnings-as-errors] unnecessary temporary object created while calling emplace
3. Error (CLANGTIDY) [readability-container-size-empty,-warnings-as-errors] the 'empty' method should be used to check for emptiness instead of 'size'
4. Error (CLANGTIDY) [bugprone-narrowing-conversions,cppcoreguidelines-narrowing-conversions,-warnings-as-errors] narrowing conversion from 'unsigned int' to signed type 'int' is implementation-defined
> clang-tidy fixes Pt.1

- test/test_multicluster_fusion.cpp
The test MultiClusterFusion gives non-deterministic results.
In this test, we check that the MultiClusterFusion gives the expected results when running on a single process, even though this object is intended for distributed settings.
To do so, we compare the strings printed from the MultiClusterFusion, but in this string the lines can be reordered (maybe because exprs and vals are stored in unordered sets, but tbh I am not sure about the cause) which does not harm anything but makes the test fail.
This PR implements a cheap and easy fix that consists in reordering the compared strings alphabetically
> fix text MultiClusterFusion

- csrc/predicate_compute.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul.h
- test/test_gpu_tensorcore.cpp
Adds a CTA swizzle to change the order in which the tiles of the output matrix are processed. 
This swizzle increases data reuse from A and B, when iterating over gridDim.x. Turns out that CTAs are launched in practice by iterating over gridDim.x first (order is unspecified though, it just happens to behave the same). As a result, the current wave will contain CTAs that compute square sub-matrices of C, and so, increase L2 hit rate. 
Best factor seems to be 4. This will be part of the heuristics. Setting the factor to 1 disables this swizzle.
On a 8192x8192x8192 matmul with default config, the speedup is about 20%. 
An extreme example is following case: `MNK = 6144 6144 6144,  layout=NT stages=0, cta_tile = 32 32 128, warp_tile = 16 16 128, instruction_tile = 16 16 16` where the runtime …
> CTA Swizzles

- .gitignore
- csrc/expr_simplifier.cpp
- test/test_expr_simplifier.cpp
- test/test_gpu2.cpp
- test/test_loop_rotation.cpp
I shall use this to prove `ceilDiv(T0.size[0], 128) <= ceilDiv(T0.size[0], 128) * 4`, so that I can simplify
```C++
max(ceilDiv(T0.size[0], 128), ceilDiv(T0.size[0], 128) * 4)
```
as
```C++
ceilDiv(T0.size[0], 128) * 4
```
which will help remove the trivial predicate
```C++
blockIdx.x < ceilDiv(T0.size[0], 128) * 4
```
where `gridDim.x` is known to be
```C++
max(ceilDiv(T0.size[0], 128), ceilDiv(T0.size[0], 128) * 4, 4)
```
Note that I also need to prove
```C++
4 <= ceilDiv(T0.size[0], 128) * 4
```
which is indeed not true for empty tensor. So, unfortunately, I have to introduce an assumption `T0.size[0] > 0` when simplifying exprs in `parallel_dimension_map.cpp`. I don't think in practice this will cause any issue, but if it does, then we should more systematically special handling empty …
> Prove `i1 * i2 >= i1` if `i2 >= 1 && i1 >= 0`

- benchmark/bert.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/96
> Fix benchmark

- csrc/disjoint_set.h
- `|` is a bitwise op. `||` is used instead
- Unsure `pushBack` is guaranteed to execute within an expression like `already_added || pushBack()`, so moved it out.
Also some other misc changes
> Fix pushBack

- .lintrunner.toml
- csrc/lower_utils.cpp
- runtime/warp.cu
solve https://github.com/csarofeen/pytorch/issues/2526
we need to do shfl two times, one for real part and the other for imag part. The speed is still faster than block reduction. 
In a tested case, warp: achieved: 1324.28 GB/s,  block: achieved: 1248.61 GB/s
> shfl for complex number

- benchmark/gelu_backward.cpp
same as https://github.com/NVIDIA/Fuser/issues/96 and https://github.com/NVIDIA/Fuser/pull/100
> fix benchmark GeluBackward

- CMakeLists.txt
- benchmark/matmul.cpp
- csrc/ir_nodes.cpp
- csrc/ir_utils.cpp
- csrc/ir_utils.h
- csrc/iter_visitor.h
- csrc/mma_type.cpp
- csrc/mma_type.h
- csrc/scheduler/all_schedulers.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul.h
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/matmul_utils.h
- csrc/scheduler/registry.cpp
- csrc/scheduler/registry.h
- csrc/utils.cpp
- csrc/utils.h
- test/test_gpu_matmul_sass.cpp
- test/test_gpu_tensorcore.cpp
- test/test_utils.cpp
- test/test_utils.h
This is PR is a continuation of previous PR ([link](https://github.com/csarofeen/pytorch/pull/2461))
* update registry so segmenter can schedule matmul kernels,
* add an initial implementation of simple heuristics for kernel schedule details, but with reasonable partition to make it easier to extend functionality in future,
* add basic set of tests that will check new execution path,
* organize matmul-related compile/runtime checks to avoid long build (avoiding extending `resgitry.cpp`)
* start with simple checks to reject fusions that are obviously not supported
* when minimal requirements for matmul are met by fusion (number of fusion's input/outputs, type of these inputs) we proceed to more complex check that check dependencies in graph:
* MmaOp inputs and relationship with fusion …
> Enable matmul scheduler in segmenter

- csrc/ir_nodes.cpp
- csrc/type.cpp
- csrc/type.h
`cp.async` uses inline predicate, that is, the predicate is passed as an argument to the function call instead of protecting the expr inside an `if` block. As a result, we can not see the predicate information in the printed kernel ir. This makes the debugging not convenient because we don't know when the predicate is created, when the predicated is indexed, and what the indexed predicate is. With the change in this PR, we can clearly see how the predicate is generated during lowering:
Using
```
PYTORCH_NVFUSER_DUMP="lower_verbose" ./build/bin/nvfuser_tests --gtest_filter=*FusionAmpereMatmul_CUDA*
```
We can see before `UnrollPass`, the `cp.async` is printed as:
(tensors are not indexed, and there is no predicated)
```C++
T6_s[ iblockIdx.x45{( ceilDiv(T0.size[0], 128) )}, iS47{( …
```
> Print `cp.async` predicate

- csrc/executor.cpp
- csrc/executor_utils.cpp
- csrc/executor_utils.h
Did some cleanups around `nvrtcCompileProgram`. The interface of nvrtc and cuModuleLoadDataEx is quite ugly as it expects options passed as `char**` or `void**`. Managing option values needs careful memory management as we can't just pass `std::string`.
This PR adds two helper classes for them:
- `NvrtcCompileDriver`
- `CuModuleLoadDataDriver`
Both are meant to encapsulate the management of option values, so now adding a new option is just calling the `setOption` method of the helper class. Invoking `nvrtcCompileProgram` through the helper class ensures the options are correctly configured and passed to `nvrtcCompileProgram`.
I also refactored `executor_utils::nvrtcCompile`. Previously there's a lot more done than just invoking nvrtcCompileProgram, including option configurations, kernel …
> Clean up nvrtcCompileProgram

- csrc/ir_internal_nodes.h
- csrc/ir_utils.h
- csrc/lower_bank_conflict.cpp
- csrc/lower_bank_conflict.h
Currently, the bank conflict check does not work for matmul, because its address contain tensor's base address (something like `BaseAddress(T7) + 16 * threadIdx.x + 8192 * i487 + 2048 * i481`). This PR fixes this issue, and in addition, this PR also does some cleanup.
> Bank conflict checker fix

- csrc/evaluator_common.h
- csrc/executor_utils.h
- csrc/ir_container.h
- csrc/lower_thread_predicate.h
- csrc/lower_utils.cpp
- csrc/lower_utils.h
- csrc/parallel_dimension_map.h
- csrc/predicate_compute.cpp
- csrc/predicate_compute.h
- csrc/type.h
This is a minor PR removing `TypeHash` from the codebase. This was a workaround (introduced in https://github.com/pytorch/pytorch/pull/35917/commits/c5f805590d69a83729a524be5c39db319209e7e5) for the lack of support for using `enum class`es like `ValType` as keys in STL hash-tables like `std::unordered_map`. See https://stackoverflow.com/questions/18837857/cant-use-enum-class-as-unordered-map-key for more discussion on the general issue. As noted in that issue, this was resolved in C++14 (see https://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2148) so I think it should no longer be necessary as NVFuser has even moved on to C++17 by now.
> Remove TypeHash

- csrc/executor_kernel_arg.cpp
- csrc/type.h
- csrc/utils.h
As part of overall refactoring of the executor, I wanted to clean up the type switch pattern like: `switch (aten_scalar_type) { case at::ScalarType::Float: ....`.
I added two utility template functions: `atenTypeDispatch` and `atenTypeDispatchWithC10Complex`. Here's what `atenTypeDispatch` looks like:
```
template <typename Functor, typename... Args>
auto atenTypeDispatch(at::ScalarType type, Functor func, Args&&... args);
```
`Functor` should be a struct with `operator()(Args...)` templated with the native C++ type of `at::ScalarType type`. `atenTypeDispatch` then calls the functor with the native type.
A variant of this dispatch is `atenTypeDispatchWithC10Complex`. This may not be necessary, but currently we are using both `c10::complex` and `std::complex`, and so sometimes we may want …
> Refactoring type switch

- csrc/expr_evaluator.cpp
- csrc/expr_evaluator.h
- csrc/lower_bank_conflict.cpp
- csrc/lower_bank_conflict.h
- Use `kernel->summary().parallel_dimension_map_` to replace `InferLaunchParams`
- Use `LaunchParams()` (all `LaunchParams::UNINITIALIZED_VAL`) to replace `c10::optional<LaunchParams>`
> Cleanup bank conflict checker to better infer launch param

- csrc/ir_internal_nodes.h
- csrc/ir_nodes.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- test/test_gpu_tensorcore.cpp
- when MmaOp is constructed there are no checks to validate if provided parameters (inputs/outputs) are valid,
- this resulted in implementing consistency checks as rules in compile time checks in matmul scheduler,
- this PR covers part of follow-up tasks mentioned [this comment](https://github.com/NVIDIA/Fuser/pull/23#discussion_r1156366522) in #23 
- move some checks from compile time checks in matmul scheduler to `MmaOp` constructor,
- gather M / N / K / Batch axes from MmaOp inputs/outputs,
- move input layout check from matmul scheduler compile time checks to MmaOp constructor,
- M / N / K / Batch axes and inputs' layout are stored as attributes in MmaOp object,
Tests will be re-enabled with follow up PR that will add in MmaOp handling of scenarios covered by these tests.
- c++ tests …
> MmaOp - consistency checks for basic matmul

- csrc/executor_utils.cpp
- csrc/lower_validation.cpp
- csrc/utils.cpp
- csrc/utils.h
I don't think these checks make sense. I don't see any reason for disallow lowering of an Ampere kernel on Volta, or on a machine without GPU. Cross compilation support is common for compilers, for example, nvcc has `-arch` to specify the target architecture, even if your machine has no GPU at all.
This is blocking https://github.com/NVIDIA/Fuser/pull/155, because the bank conflict checking test fails on Volta. I don't think these failure makes sense.
> Remove `validateMinimumArch`

- csrc/ops/normalization.cpp
- test/test_gpu2.cpp
The op to construct a tensor of complex number from two tensors representing real and imag parts was added in #168.
That feature also enables var_mean on tensor of complex numbers.
> allow var_mean on complex number

- csrc/ir_nodes.cpp
- csrc/lower_validation.cpp
- csrc/scheduler/matmul.cpp
- test/test_gpu_matmul_sass.cpp
This PR has a few changes cherry-picked from https://github.com/NVIDIA/Fuser/pull/38, the most important change is to vectorize global memory write. The perf improvement is actually not small:
On my RTX 3090:
```C++
$CUDA_VISIBLE_DEVICES=1 ./build/nvfuser_bench --benchmark_filter=.*Matmul.*Legacy/2048/3456/4096.*
```
Before:
```C++
---------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                       Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------------------------------
Nvfuser_Matmul_4warp3stage/no_quant_nvfuser_4warp_TT_Legacy/2048/3456/4096/m …
```
> Vectorize global memory write in matmul schedule

- benchmark/matmul.cpp
- csrc/codegen.cpp
- csrc/executor_utils.cpp
- csrc/ir_internal_nodes.h
- csrc/ir_nodes.cpp
- csrc/lower_index.cpp
- csrc/lower_utils.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_utils.cpp
- csrc/tensor_view.cpp
- test/test_gpu_matmul_sass.cpp
- test/test_gpu_tensorcore.cpp
The scope of changes in this PR:
--
- single source of truth for matmul inputs' layouts
- MmaOp input layout dedicated attribute is the single source of truth,
- removed redundant input layout information from struct with mma options,
- removed redundant input layout information from matmul heuristic options,
- updated `MmaOp` constructor to make sure that any and all instances of this class have layout attribute initialized,
- updated code for deciding input's layout, previously there were issues with layout for fusions that simulated inter/intra CTA split-k reduction; more details below
- misc: rename `mma_op` to `mma_macro` in matmul heuristics to avoid confusion with `MmaOp` class,
- misc: replace `c10::optional` with `std::optional`,
- misc: fixed typos
Details about layout inferring …
> MmaOp definition - cleaning

- csrc/ir_utils.cpp
- csrc/ir_utils.h
- csrc/lower_alias_memory.cpp
Set was replaced with LoadStoreOp, which was not recognized as UnaryOp, and thus the alias analysis failed to detect safe aliasing
Fixes #163
> Fix alias analysis

- python_tests/test_torchscript.py
add flag to skip test. This should be used by internal nightly CI
set env variable `NVFUSER_TEST_ONLY_RUN_WHEEL_BUILD_SUBSET` to 1 to skip torchscript test.
> quick flag to skip torchscript test

- test/test_gpu_tensorcore.cpp
Lower once, not twice!
```
./build/nvfuser_tests --gtest_filter=*AmpereMatmul_CUDA*
```
Before
```C++
[       OK ] NVFuserTest.FusionAmpereMatmul_CUDA (20261 ms)
```
After
```C++
[       OK ] NVFuserTest.FusionAmpereMatmul_CUDA (11829 ms)
```
> Reduce matmul test time spent on bank conflict check

- csrc/index_compute.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/lower_double_buffer.cpp
- csrc/lower_index.cpp
- csrc/lower_index_compute.cpp
- csrc/lower_misaligned_vectorization.cpp
- csrc/lower_vectorize_welford.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_loop_rotation.cpp
`ForLoop::isTrivial` should use `simplifiedStop` instead of `stop` for detecting trivial loop. And after switching, I actually see a few bugs in our codebase, I fixed those bugs.
Diff in a matmul kernel: https://www.diffchecker.com/zDtT4IWL/, note that the trivial loop `for(nvfuser_index_t i523 = 0; i523 < 1; ++i523)` is gone.
> Fix trivial loop handling

- csrc/executor.cpp
- csrc/utils.cpp
- csrc/utils.h
Forgot to add this to the recent index-type PR (#108)
> PYTORCH_NVFUSER_DUMP=index_type to print index type of launched kernel

- csrc/lower_index_compute.h
- csrc/lower_shift.cpp
- csrc/lower_shift.h
@jacobhinkle found `HaloInfo::buildConcreteHaloExtentMap` is a major overhead in fusion lowering. This PR should fix it.
`HaloInfo` previously kept a permissive map, which shouldn't be necessary as it's only used in lowering. Also, analysis for LoopIndexing can be skipped when no root ID is extended with halo.
Note that overall rewrite of halo handling is needed, but it's not high priority at this moment.
> Minor cleanup of HaloInfo

- csrc/scheduler/matmul.cpp
The scope of the changes:
--
- matmul heuristic instance is the main source of mma macro,
- scheduleMarmul and all its helpers uses matmul heuristic for accessing mma macro data
- mma builder uses mma macro from matmul heur to initialize attribute in MmaOp instance in matmul,
Local verification:
--
- c++ tests on a100, all passed
cc @mmigdal-nv
> Simplification of mma macro usage in matmul scheduling

- csrc/ir_nodes.cpp
- csrc/ir_utils.cpp
- csrc/ir_utils.h
- csrc/utils.h
- test/test_gpu3.cpp
This is for #225 
A `TensorDomain` is created with a list of IterDomains representing a root domain, and optionally another list of IterDomains for an rfactor domain and also one more list for the leaf domain.
Currently, we do some error check using `IterVisitor::getInputsTo`, but that's not always sufficient. We need to make sure that the root domain and the other domains represent the same logical space without any overlap. 
For example:
```
IterDomain* id0 = IterDomainBuilder()....build();
IterDomain* id1, id2 = IterDomain::split(id0, 4);
```
Here, it'd be valid to have a root and leaf domain as follows:
```
Root: id0
Leaf: id1, id2
```
Suppose `id2` is further split as:
```
IterDomain* id3, id4 = IterDomain::split(id2, 5);
```
Then, this is invalid:
```
Root: id0
Leaf: id1, id2, id3, …
```
> Better validation of domains when creating TensorDomain

- csrc/ir_utils.cpp
- csrc/ir_utils.h
- csrc/root_domain_map.cpp
- test/test_gather.cpp
- test/utils.h
There remain some more issues for torch_gather, but the disabled test for take_along_axis is now working.
Haven't tried yet, but hopefully this should also fixes issue #93
> Fixes for torch_gather and take_along_axis with broadcast input tensors

- csrc/scheduler/matmul_heuristic.h
after fix:
```
===== Matmul Parameters ========
MMA macro: Ampere_16_16_16
DoubleBufferOptions:
double_buffer_smem_write: true
double_buffer_smem_read: true
smem_double_buffer_stage: 3
MatMulTileOptions: instruction tile [16, 16, 16], warp tile [64, 64, 32], CTA tile [128, 128, 32]
Rotate ldmatrix out of main loop: true
Async global mem load: true
Indexing mode: int32_t
Tile rastrization order: row-major
Grid swizzle factor: 1
====================================
```
> fix output format of matmul heuristic

- csrc/kernel_cache.h
In my dirty local environment with clang-14, I needed this attribute.
```
[4/103] Building CXX object CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o
FAILED: CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o
/usr/bin/c++ -DTORCH_CUDA_BUILD_MAIN_LIB -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -Dnvfuser_codegen_EXPORTS -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/benchmark/include -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/third_party/gloo -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/csrc -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/build/include -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/../third_party/flatbuffers/include -isystem /home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/googletest/googlemock/include …
```
> remove unused `hash_scalars_`

- csrc/index_compute.cpp
I believe this is no longer necessary as the index map is propagated from the loop indexing, which is built using the consumer parallel types.
Originally done in #242
> Do not bother propagating vectorize parallel types to transformed producers

- csrc/index_compute.cpp
- csrc/ir_nodes.cpp
- test/test_gpu3.cpp
Added assert check that we only parallelize a leaf domain. #127 
Ideally, leaf domains are domains that are not used by any other domains.
However, this is not true if reduandant split/merge operations are added by the user manually. e.g. case FusionAdvancedComputeAt8_CUDA.
so the check is relaxed to include intermediate domains between root and leaf.
```
tv7->split(1, 2);
tv7->merge(0);
tv7->split(0, 128, false);
tv7->split(0, 4, false);
tv7->axis(0)->parallelize(ParallelType::BIDx);
tv7->axis(1)->parallelize(ParallelType::TIDx);
tv0->computeAt(tv4, -1);
tv2->computeAt(tv4, -1);
tv0->computeAt(tv7, -1);
```
we did one merge and three splits on tv7, but why the printed transform history is different?
```
T7_g[ iS9{i0}, iS12{2}, iS11{( ceilDiv(i13, 2) )} ] produce_pos( 1 )
root domain : …
```
> parallelize on leaf

- csrc/expr_simplifier.cpp
- csrc/ir_container.cpp
- csrc/ir_container.h
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_loop_rotation.cpp
@jacobhinkle discovered that currently, a significant portion of our lowering time is spent at `getAxioms`, this PR removes this time by moving axioms to IR containers just like one value/zero value, etc.
cc: @naoyam
> Move axioms to IR container

- nvfuser/__init__.py
Example:
```py
Error executing nvFuser FusionDefinition:
def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
T0 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguous=[True, True], dtype=DataType.Float, is_cpu=False)
T1 = fd.ops.max(T0, axes=[1], keepdim=False, dtype=DataType.Null)
T2 = fd.ops.broadcast_in_dim(T1, output_shape=[3, 1], broadcast_dims=[0])
T3 = fd.ops.broadcast_in_dim(T2, output_shape=[3, 3], broadcast_dims=[0, 1])
T4 = fd.ops.sub(T0, T3)
T5 = fd.ops.exp(T4)
T6 = fd.ops.sum(T5, axes=[1], keepdim=False, dtype=DataType.Null)
T7 = fd.ops.broadcast_in_dim(T6, output_shape=[3, 1], broadcast_dims=[0])
T8 = fd.ops.broadcast_in_dim(T7, output_shape=[3, 3], broadcast_dims=[0, 1])
T9 = fd.ops.div(T5, T8)
fd.add_output(T9)
inputs = [
torch.randn((3, 3), dtype=torch.float32, …
```
> Python: on error print the way to generate inputs alongside the printed FusionDefinition

- CMakeLists.txt
Optimistically remove `EXPORT` from `install` command.
rel: https://github.com/NVIDIA/Fuser/issues/153#issuecomment-1533519956
- https://gist.github.com/crcrpar/485582e25e551ac36f24a2170a690723
```cmake
foreach(_cmake_expected_target IN ITEMS nvfuser_codegen nvfuser)
list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
if(TARGET "${_cmake_expected_target}")
list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
else()
list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
endif()
endforeach()
```
- https://gist.github.com/crcrpar/3c020c7a5a88d6972f3ad32261984cc7
```cmake
foreach(_cmake_expected_target IN ITEMS nvfuser_codegen)
list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
if(TARGET "${_cmake_expected_target}")
list(APPEND …
```
> not exporting `libnvfuser.so`

- csrc/serde/fusion_cache_generated.h
Reverts NVIDIA/Fuser#283 because upstream PyTorch uses v2.0.5.
Workaround for issue #281 is to comment out https://github.com/google/flatbuffers/blob/v2.0.5/CMakeLists.txt#L254-L321 in third_party/flatbuffers
> Revert "Update Flatbuffers to v2.0.7 to support cpp17"

- CMakeLists.txt
I noticed that cmake is running flatc for every build lately. I think this PR fixes it by explicitly stating that `fusion_cache_generated.h` depends on `fusion_cache.fbs`. I got this pattern from https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/.
> Run flatc only when fusion_cache.fbs is modified

- .github/workflows/lint.yml
- csrc/contiguity.cpp
- csrc/index_compute.cpp
- csrc/ir_internal_nodes.h
- csrc/ir_nodes.cpp
- csrc/kernel_cache.cpp
- csrc/kernel_cache.h
- csrc/lower_misaligned_vectorization.cpp
- csrc/lower_validation.cpp
- Checks only `csrc` folder
- Excludes `benchmark` and `test` folders
- Only modified files between given branch and the `main` branch are checked.
- The clang-tidy CI runtime is proportional to the number of modified files. About 20 minutes on average. 1 hour for all files in `csrc`.
> Enable clang-tidy check in CI

- csrc/contiguity.cpp
- csrc/contiguity.h
- csrc/index_compute.cpp
- csrc/index_compute.h
- csrc/lower_validation.cpp
Split out from https://github.com/NVIDIA/Fuser/pull/276, mostly `root` -> `allocation`
> Renamings in `contiguity.{cpp,h}`

- .github/workflows/lint.yml
- csrc/lower_misaligned_vectorization.cpp
- setup.py
Reduce clang-tidy CI setup time.
e.g., from ~13 minutes to ~6 minutes
> Use top-level build with clang-tidy CI

- test/test_matmul_sass.cpp
```
unknown file: Failure
C++ exception with description "Modifiers for LDGSTS has changed. Please manually check if the new modifiers makes sense and update this test. Expect: E BYPASS LTC128B 128 Get: E BYPASS 128
Exception raised from operator() at /opt/pytorch/nvfuser/test/test_matmul_sass.cpp:170 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7f197086499e in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f197081d6bd in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + …
```
> skip MatmulSASSTest on Hopper

- csrc/executor_utils.cpp
- csrc/lower_index_compute.cpp
- csrc/lower_validation.cpp
- csrc/lower_validation.h
- csrc/vectorization_info.h
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_gpu_fused_reduction.cpp
- test/test_gpu_tensorcore.cpp
- test/test_gpu_transpose.cpp
Split out from https://github.com/NVIDIA/Fuser/pull/276. I suggest reviewing this PR hiding whitespaces.
Currently, we are not validating vectorization correctly, especially, we are not checking the contiguity of producer. Also `fillProducerVectorizedContigRootDomains` does not support the case where the allocation domain is different from rFactor domain.
> Better validate producer vectorization

- setup.py
The `RelwithDebInfo` build mode can be thought of as a mixture of release and debug build: it enable optimizations like in release build, it also keep debugging info such as line info. This is my favorite build mode, and my default build mode for PyTorch. With this build mode, tests are running as fast as in release build, while keeping the debugability close to debug build. Strongly recommend to use :)
> `RelwithDebInfo` build mode support

- csrc/contiguity.cpp
- csrc/expr_simplifier.cpp
- csrc/expr_simplifier.h
- csrc/ir_nodes.cpp
- test/test_expr_simplifier.cpp
- test/test_gpu3.cpp
Reduction IDs does not exist, so it makes no sense to mark them as true or false.
Also:
- Add prove for `i1 % size < size`
- Add simplification `i1 / d < D` -> `i1 < d * D`
The above two items is important to make the predicate of reduction unrelated to contiguity.
> Mark contiguity of reduction ID as nullopt

- csrc/fusion.h
- python_tests/test_python_frontend.py
- setup.py
1. Added `-wheel-name` option on setuptools to allow custom package name
2. changed version separator `+` to `.` to be pypi compatible
> Pip wheel build patch

- runtime/helpers.cu
- test/test_gpu3.cpp
Fixes #319. This implements a minimal fix, in that it does not modify the reduction as stated in the issue, but it removes one nan-check for each call to fmin/fmax. We may further want to disable nan-checking completely, but that will be implemented in another PR.
> Remove unneeded branches in fmin/fmax helpers

- csrc/foo.cpp
- csrc/fusion_segmenter.cpp
- csrc/fusion_segmenter.h
- test/test_gather.cpp
For #278, our schedulers currently can't fuse them into a single kernel, so a segmentation needs to happen. Currently, it's segmented between softmax and take_along_axis, just because of the ordering of the segmenter. However, we want the take_along_axis op to be fused together with the preceding softmax since then the temporary output from the first segment would be much smaller, reducing gmem access overhead. In the case of `[8192, 32768]`, the (logical) I/O cost would be `1 / 32768`.
This PR introduces a simple mechanism to allow preferred fusions in the segmentation steps. Currently, there's only preference of select-like ops with producers. "Select-like" here also includes index_select and torch_gather to size-one domains. In those ops, it's guaranteed that the size of the consumer …
> Promote fusing select-like ops with producers

- test/test_gpu_tensorcore.cpp
- test/test_matmul_sass.cpp
`NVFUSER_TEST_CUDA_ARCH_RANGE_GUARD` check if the current arch satisfy `left <= current < right`, so we should not put `8, 9` on the second arch, but should put `9, 0`.
> Don't skip Ada for some matmul tests

- csrc/executor_kernel_arg.cpp
Avoid pytorch debug build assertion at https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/EmptyTensor.cpp#L280.
> Use `empty_strided_meta` to create meta tensor

- test/test_gpu_view.cpp
trivial fix for [ FAILED ] NVFuserTest.FusionReshapeMagicSchedule6_CUDA at #301 
Afther this PR, all the remaining failures on H100 are validation errors and should be fixed by syncthreads.
> fix FusionReshapeMagicSchedule6_CUDA on H100

- csrc/python_frontend/python_bindings.cpp
- csrc/serde/fusion_record_serde.cpp
- python_tests/test_python_frontend.py
Currently, we're calling the cpp `bitwise_left_shift` from the frontend.
> Use `bitwise_right_shift` in python frontend

- .gitignore
- csrc/dynamic_type.h
- csrc/evaluator_common.cpp
- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ir/nodes.cpp
- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/python_frontend/python_bindings.cpp
- csrc/serde/fusion_record_serde.cpp
- csrc/type.cpp
- csrc/type.h
- python_tests/test_python_frontend.py
- runtime/helpers.cu
- test/test_gpu1.cpp
The main purpose for adding this op is to use it to fix https://github.com/NVIDIA/Fuser/issues/413, but since this op is supported by PyTorch, so why not expose it to the user?
> Add binary op gcd

- csrc/dynamic_transform.h
Declaring a copy constructor should come with a copy constructor as well. Compilation with clang resulted in:
```
error: definition of implicit copy assignment operator for
'DynamicTransformInitialInfo' is deprecated because it has a
user-declared copy constructor [-Werror,-Wdeprecated-copy]
DynamicTransformInitialInfo(const DynamicTransformInitialInfo& other)
=
^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/optional:789:21:
note: in implicit copy assignment operator for
'nvfuser::DynamicTransformInitialInfo' first required here
this->_M_get() = std::forward<_Up>(__u);
```
> Delete an unnecessary copy constructor

- csrc/executor_utils.cpp
This reverts commit 0d55f6c20f81ad03cfd98bff4fd307199ca55d82.
I merged #430 too hastily. There are many failing tests now due to invalid context.
> Revert "Replace initializeCudaContext() with cudaFree(nullptr) (#430)"

- csrc/mma_type.h
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- test/test_gpu_tensorcore.cpp
The scope of the PR:
- replace hand-written topology checks with tools that rely on computeAt map data, this includes:
- tool for accessing problem shapes for heuristics,
- tool for inferring the layout of matmul,
- update existing matmul schedule tests to verify:
- `MmaOp` layout, for Ampere should TN
- inferred from input data layout, should match layout defined as test parameter,
> Matmul scheduler - utils refactoring

- csrc/mma_type.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- test/test_gpu_tensorcore.cpp
The scope of this PR:
- relax requirements for fusion inputs / outputs ordering
- currently: fusion 1st and 2nd input are mapped to MMA 1st and 2nd input, first fusion output is handled as MMA output consumer
- new: fusion inputs'/outputs' definitions are checked and mapped to predefined roles
These changes will enable simplified implementation of compile-time checks when new types of epilogues are introduced.
> Matmul scheduler - relax fusion inputs/outputs order

- csrc/codegen.cpp
- runtime/memory.cu
- test/test_loop_rotation.cpp
There should be no behavioral change, just make `codegen.cpp` more readable.
> Use `ArgumentBuilder` and `genCall` to cleanup codegen of `cp.async` and `ldmatrix`

- csrc/mma_type.cpp
- csrc/mma_type.h
- csrc/scheduler/matmul_utils.cpp
- test/test_gpu_tensorcore.cpp
The scope of this PR:
----
- disable by default magic zero for fusions handled by matmul scheduler,
- remove mma builder API that accepted TV,
This PR is a follow up of https://github.com/NVIDIA/Fuser/pull/253
> Matmul scheduler - magic zero disabled

- csrc/dynamic_transform.cpp
- csrc/dynamic_transform.h
- csrc/kernel_cache.cpp
- csrc/kernel_cache.h
- csrc/utils.h
- test/test_dynamic_transform.cpp
This PR makes a few changes to the dynamic Fusion machinery. Mainly, this is to make ownership of `DynamicTransformInitialInfo`, `DynamicTransformConcretizationInfo`, and `ExpressionEvaluator` more clear. It avoids cloning (and using fusion-managed data for) `DynamicTransformConcretizationInfo` and does not store `Statement` pointers in that object. Instead we refer to lists of dynamic ops that are held in `initial_info`, which _can_ be cloned and is managed by the `Fusion`. This makes it easier to compare concretization infos that apply to different `Fusion`s, and to reuse it for the actual concretization without needing to clone again.
Minor changes:
- Move iteration through root dynamic vals to `finalizeDynamicVals()`.
- Use `executor_utils::bindInputs()` instead of manually binding …
> Cleanups to FusionExecutorCache and DynamicFusionConcretizationInfo

- csrc/scheduler/normalization.cpp
- csrc/scheduler/registry.cpp
- test/test_combined_inner_outer_reduction.cpp
Fix #465 
The vectorization factor was not correctly calculated in `checkCombinedReductionShape`
> avoid 0 batch in layer norm backward

- CMakeLists.txt
- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/utils.cpp
- csrc/dispatch.cpp
- csrc/dispatch.h
- csrc/ir/base_nodes.h
- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/kernel_ir_dispatch.h
- csrc/mutator.cpp
- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/type.cpp
- csrc/type.h
- csrc/utils.h
- runtime/array.cu
- test/test_tensor_factories.cpp
[`torch.tensor`](https://pytorch.org/docs/stable/generated/torch.tensor.html?highlight=tensor#torch.tensor) is a tensor factory that constructs a tensor from given scalar values. This PR adds support for this tensor factory to our C++ API. Python frontend is not supported yet, because of the following reason:
This tensor factory is not something we prioritize to have. However, building this out requires improving our array support in codegen. The main purpose of this PR is to build out array infrastructure and a great portion of this work will be reused for TMA support (which takes an argument of N dimensional coordinates as index). The prototype for TMA is at https://github.com/NVIDIA/Fuser/pull/455
In the future, if this tensor factory turns out to be useful, we can add python frontend …
> Add tensor factory `torch.tensor`

- benchmark/bert.cpp
- benchmark/utils.cpp
- benchmark/utils.h
- Follow the naming convention (`NvFuserScheduler_...`)
- Use `NVFUSER_BENCHMARK_DEFINE` and `NVFUSER_BENCHMARK_RUN` macros
Did a quick check of running the same benchmarks before and after this PR.
There may be other benchmarks that we should update.
> Clean up the Bert benchmarks

- python_tests/pytest_framework.py
- python_tests/pytest_input_generators.py
- python_tests/pytest_opinfos.py
- python_tests/pytest_ops.py
Adds correctness and error checks for `broadcast_in_dim`
We are missing a check for this assumption `tensor.shape[idx] == 1 or tensor.shape[idx] == output_shape[new_idx]` in `broadcast_in_dim`
> Add `broadcast_in_dim` opinfo test

- runtime/warp.cu
Add sync to warp reduction runtime avoid smem data race. It solves #271
> add sync to warp reduction runtime avoid smem data race

- csrc/device_lower/pass/replace_size.cpp
- csrc/kernel_cache.cpp
- python_tests/test_python_frontend.py
Previously some of the lowering and launching code implicitly assumed inputs were not expanded broadcasts. This PR addresses those.
Fixes #469 and fixes #470.
> Use getMaybeExpandedExtent() for lowering and launching segments

- CMakeLists.txt
- test/rng_kernels.cu
- test/test_gpu_rng.cpp
- test/test_rng.cpp
Pulling the kernel in `test_gpu_rng.cu` out as `rng_kernels.cu`, this file should not include any header from nvFuser. Rename `test_gpu_rng.cu` as `test_rng.cpp`. I also rename the tests into `RNGTest.XXXXX`.
This should be just code movement and renaming, no behavioral change.
> Don't compile nvFuser with nvcc

- csrc/codegen.cpp
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/executor.cpp
- csrc/executor_utils.cpp
- csrc/expr_simplifier.cpp
- csrc/instrumentation.cpp
- csrc/instrumentation.h
- csrc/kernel_cache.cpp
- csrc/manager.cpp
- csrc/options.cpp
- csrc/options.h
- csrc/utils.cpp
- csrc/utils.h
- nvfuser/README.md
- python_tests/test_torchscript.py
- runtime/grid_reduction.cu
- test/test_dynamic_type.cpp
- test/test_external_src.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_gpu_outer_reduction.cpp
Renamed `PYTORCH_NVFUSER_` to just `NVFUSER_`, e.g., `PYTORCH_NVFUSER_DUMP` is now `NVFUSER_DUMP`.
PYTORCH_NVFUSER is still available but a warning is issued if used.
> Rename the prefix of environment variables to NVFUSER.

- csrc/C++20/type_traits
- csrc/dynamic_type.h
- csrc/type_traits.h
- test/test_dynamic_type.cpp
In `ForAllTypes`, we were using pointers to pass type information. However, this is not the standard way. The standard way is to use `std::type_identity`
> `ForAllTypes` cleanup

- csrc/executor.cpp
Some of the shift tests use global memory tensors just for testing the functionality. In those cases, there are intermediate global tensors that are extended with halo. Their allocation sizes are not the same as the logical size represented by their allocation domains, but slightly larger to account for the halo regions.
With the current main, the intermediate tensors for `FusionShift2` are:
```
Intermediate global buffers:
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
Float [9, 11] is_zero_initialized: 0
```
This PR effectively reverts the …
> Allocate intermediate tensors using the shape provided by Allocate node

- .github/workflows/lint.yml
- csrc/device_lower/analysis/bank_conflict.cpp
- csrc/evaluator_common.cpp
- test/test_dynamic_transform.cpp
- test/test_dynamic_type.cpp
- test/test_gpu1.cpp
- test/test_gpu_shift.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/538. GCC9's ctor of `std::variant` is buggy and can not handle the case like:
```C++
std::variant<float, long, double> z = 0; // OK, holds long
// float and double are not candidates
```
(example taken from https://en.cppreference.com/w/cpp/utility/variant/variant), so when using `DynamicType` and `EvaluatorValue`, we should use exactly the same type as in the type list. GCC9 is not smart enough to automatically convert `int` into `long` when needed.
> Try workaround gcc9 bug

- csrc/type_promotion.h
I'm getting a new compiler error. The default constructor defined prevents aggregate initialization.
```
[ 32%] Building CXX object CMakeFiles/nvFuserGemm.dir/src/nvFuserGemm/nvFuserGemm.cpp.o
In file included from /home/mmigdal/nvFuser/pytorch/torch/include/nvfuser/ops/arith.h:15,
from /home/mmigdal/nvFuser/nvfuser-perf-evaluation/src/nvFuserGemm/nvFuserHelpers.hpp:17,
from /home/mmigdal/nvFuser/nvfuser-perf-evaluation/src/nvFuserGemm/nvFuserGemm.cpp:9:
/home/mmigdal/nvFuser/pytorch/torch/include/nvfuser/type_promotion.h:42:48: error: no matching function for call to ‘nvfuser::TypePromotionConfig::TypePromotionConfig(<brace-enclosed initializer list>)’
42 |     /* require_full_precision_promoted */ false};
|                                                ^ …
```
> Removing unused TypePromotionConfig constructor.

- csrc/dynamic_type.h
- test/test_dynamic_type.cpp
I suggest reading this PR hiding white spaces.
What this PR does is effectively just use
```C++
std::is_constructible_v<DT::VariantType, decltype(op_result)>
```
to replace
```C++
std::is_same_v<decltype(op_result), SomeMemberTypeInDT>
```
The former makes more sense because it allows implicit type conversion of C++ to participate. An example why this is important is the following (copy-pasted from unit test):
```C++
using Int = DynamicType<NoContainers, int>;
static_assert((Int(2) && Int(0)) == 0);
static_assert((Int(2) && Int(3)) == 1);
```
where we were emulation old C (where there was no `bool` in that language, so people just use `int` for the role of boolean value). In this example, we were unable to do so without this PR because we were requiring the result type to be a member type …
> Use `std::is_constructible` instead of `std::is_same` for filtering return types

- csrc/ops/arith.cpp
- python_tests/pytest_core.py
- python_tests/pytest_input_generators.py
- python_tests/pytest_opinfos.py
- python_tests/pytest_ops.py
- python_tests/pytest_utils.py
* Expand const scalar checks for `iota`
> Add `full`, `iota`, and `where` Opinfo error tests

- csrc/type_traits.h
Fix an error for unused variable, present in gcc94 builds:
```
Fuser/csrc/type_traits.h: In instantiation of ‘constexpr auto nvfuser::remove_void_from_tuple(std::tuple<_Tps ...>) [with Ts = {}]’:
Fuser/csrc/type_traits.h:455:52:   recursively required from ‘constexpr auto nvfuser::remove_void_from_tuple(std::tuple<_Tps ...>) [with Ts = {int, nvfuser::Void, bool, nvfuser::Void, double, nvfuser::Void}]’
Fuser/csrc/type_traits.h:455:52:   required from ‘constexpr auto nvfuser::remove_void_from_tuple(std::tuple<_Tps ...>) [with Ts = {nvfuser::Void, int, nvfuser::Void, bool, nvfuser::Void, double, nvfuser::Void}]’
Fuser/csrc/type_traits.h:469:70:   required from here
Fuser/csrc/type_traits.h:445:57: error: parameter ‘t’ set but not used [-Werror=unused-but-set-parameter]
445 | constexpr auto …
```
> Build system fix

- CMakeLists.txt
Also, format the cmake file. I suggest reading this PR skipping whitespace changes.
I am working on a big PR https://github.com/NVIDIA/Fuser/pull/529 that requires changes in python frontend, serde, and backend. As an incremental development step, I want to begin with skipping frontend and serde first to only build backend and tests. After backend work are done, I will start working on frontend and serde.
This requires us to be able to only build the backend, and this PR fixes `--no-python` to do so.
> Skip entire python frontend when build with --no-python

- csrc/dynamic_type.h
- test/test_dynamic_type.cpp
This PR adds
- `const` overload for `operator[]` of `DynamicType`
- indexing a `DynamicType` with a `DynamicType`, that is, `DynamicType[DynamicType]`
> Improve `operator[]` for `DynamicType`

- csrc/scheduler/matmul.cpp
- test/test_gpu_tensorcore.cpp
The main goal of this PR is to update documentation and variables' names to match inputs/outputs names from the following matmul formula: `D = alpha * (A x B) + beta * C`
The prepared changes replace currently used `c` name with `d` for fusion output.
----
Additional change:
The functional tests that uses matmul scheduler through segmenter will have new prefix, `FusionMatmulScheduler` replaces `FusionMatmulSegmenter`
----
This is a follow up for #550 and @zasdfgbnm comment ([link](https://github.com/NVIDIA/Fuser/pull/550#discussion_r1254716583))
> Adjust names to meet target matmul formula

- csrc/scheduler/matmul.cpp
The goal of this PR is to improve the way how data from fusion input TensorView objects, with assigned `INPUT_C role`, is loaded. The current implementation is inefficient as it is not vectorized, the proposed changes fix this.
Below are examples of epilogue from functional tests where `INPUT_C` tensors are present (literally, beta tests).
---
test case: `FusionMatmulSchedulerEpilogueBeta_CUDA`
- `main`:
```
#pragma unroll
for(nvfuser_index_t i117 = 0; i117 < 4; ++i117) {
int i118 = i49 + (i50 * i117);
int i119 = 16 * i117;
int i120 = -i119;
#pragma unroll
for(nvfuser_index_t i121 = 0; i121 < 4; ++i121) {
int i122 = 8 * i121;
int i123 = i118 + i122;
int i124 = i119 + (2 * i121);
bool b125 = i61 < (-i122);
#pragma unroll
for(nvfuser_index_t i126 = 0; i126 < 2; ++i126) {
int i127 = i123 + …
```
> Matmul INPUT_C role load vectorization

- csrc/scheduler/matmul.cpp
In https://github.com/NVIDIA/Fuser/pull/387, we have to do a
```C++
int64_t swizzle_period =
std::gcd(n_rows / repeated_pattern_size, tile_size_y / n_cols);
```
in order to make our swizzling algorithm work for epilogue. This looks more like an empirical hack whose only goal is to creates a square block. Although it empirically worked, I struggled to find a first-principle explanation for this approach. So I read through my original PR https://github.com/NVIDIA/Fuser/pull/155 multiple times and think through things carefully. But the more I read and think, the more I feel that the original implementation in https://github.com/NVIDIA/Fuser/pull/155 does not make sense. The problem is, https://github.com/NVIDIA/Fuser/pull/155 tries to interleave the entire `ldmatrix_rows / …
> Fix smem swizzle for matmul

- csrc/fusion_segmenter.cpp
- test/test_gpu3.cpp
> Avoid segfault in segmentation with dangling unary ops

- csrc/dynamic_transform.cpp
- csrc/ops/alias.cpp
- test/test_dynamic_transform.cpp
This replaces scalar new sizes that evaluate to `-1` at definition time in the `reshape()` op with a simplified expression for the new output extent. Previous to this change, the output shape would be set to the `Val*` that was provided, which evaluates to `-1`; after which it is difficult to reliably change even at concretization, since that scalar might have legitimate other uses.
Before this change:
```c++
auto tv0 = makeSymbolicTensor(4); // [ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ]
auto tv1 = reshape({tv0->axis(0)->extent(), tv0->axis(2)->extent(), IrBuilder::create<Scalar>(-1)});
// [ ?S4{i0}, ?S5{i3}, ?S6{-1} ]
```
After this change:
```c++
auto tv0 = makeSymbolicTensor(4); // [ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ]
auto tv1 = reshape({tv0->axis(0)->extent(), tv0->axis(2)->extent(), …
```
> Handle constant -1 values in dynamic reshape at definition

- csrc/dynamic_type.h
- test/test_dynamic_type.cpp
In the past, we were not overloading ops for `std::monostate`. This is a mistake and should be fixed.
> `DynamicType`: null == null

- csrc/ir/base_nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
It is used to check if all the dependencies to compute a `Val` is known (either a const or in the specified `known_vals` set)
> Add `ir_utils::dependenciesSatisfied`

- csrc/iter_visitor.cpp
- test/test_gpu3.cpp
Today, `getInputsTo` is not doing as documented:
```C++
//! Optional list of input vals. While traversing to inputs if a value in the
//! all_inputs list is found, that value will be added to the inputs_ and
//! traversal will not go into its definition. Otherwise traversal follows
//! definition paths until hitting a definition that is a nullptr (i.e. a
//! terminating input).
const std::vector<Val*>& all_inputs_;
```
This PR fixes it. See the new test.
> Fix getInputsTo

- csrc/polymorphic_value.h
- csrc/type.cpp
- csrc/type.h
- test/test_loop_rotation.cpp
- test/test_tensor_factories.cpp
If a struct is already defined in the `runtime/`, we do not have to generate its definition during lowering. For that case, we just generate the name as defined in `runtime`. For example, we do not have to generate tensor metadata as `struct {....}`, instead, we can just do things like `Tensor<float, 4, 4>`.
> Allow struct dtype to be named

- csrc/scheduler/vectorize_helper.cpp
The only relevant check is the address alignment. The check of vectorizable extents is done using tv_to_inner_size_map.
No change in resulting code in both the C++ tests and benchmarks
> Use of getMaxVectorizableWidth is not necessary

- csrc/ir/builder.cpp
- csrc/ir/cloner.h
- csrc/ir/container.cpp
- csrc/ir/container.h
`GetMetaData` expr is so widely used. We should avoid creating many instances of it. Also, this would be helpful for kernel parameters support.  For example, if we set `Kernel::parameters` as `v1 = GetMetaData(tv1)` instead of `tv1`, then without this PR, the generated kernel might not work because in the tensor index, we might have `v2 = GetMetaData(tv1)`, although `v2` and `v1` are the same, if scalar hoisting does not work for some reason and `v2` is not replaced with `v1`, the lowered expr might fail, because `tv1` is not a kernel parameter, therefore unknown to the kernel, therefore `v2` can not be evaluated in the kernel.
> Cache metadata access expr inside IR container

- csrc/expr_evaluator.cpp
- csrc/expr_simplifier.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
Some expressions might need context information to evaluate, for example `GetMetaData` might need the split size for symbolic splits in order to compute the sizes and strides of the allocation domain. So I added a const reference of the expr evaluator to `Expr::evaluate`. I think it makes sense to have access to such context information. This change will also allow expr evaluator to evaluate tensor factories like `FullOp` on the non-zero device, because the expr evaluator can just store the desired device and the `FullOp::evaluate` can pull that information out. However, `ExpressionEvaluator` must be passed as a const reference to ensure that the `evaluate` function does not modify it. For example, I don't want someone to do a `ee.bind(...)` inside the `evaluate` function, because this …
> Allow `Expr::evaluate` to have full access to the evaluator

- csrc/executor.cpp
- csrc/executor_kernel_arg.cpp
- csrc/executor_kernel_arg.h
- csrc/polymorphic_value.h
Because it is deprecated in https://github.com/NVIDIA/Fuser/pull/644
> `FusionExecutor::runRtc` don't use `getBuffer`

- csrc/scheduler/normalization.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/vectorize_helper.cpp
- csrc/scheduler/vectorize_helper.h
- test/test_gpu2.cpp
- test/test_gpu3.cpp
Issue #658 is because we are using the number of consumer domains to compute a position in its producer tensor. Since a producer may have reduction IDs that the consumer do not have, the computed position can result in larger than intended, making fewer number of vectorized innermost domains. This issue happens only with the reduction and normalization schedulers.
Fixes #658
> Fix vectorization with reduction domains in fusion inputs

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/device_lower/validation.cpp
- csrc/expr_simplifier.cpp
- csrc/index_compute.cpp
- csrc/predicate_compute.cpp
- csrc/tensor_metadata.cpp
- test/test_gpu2.cpp
The core change introduced by this PR is loosing requirements for predicate elimination,
a result of adding support for bias epilogue in matmul scheduler.
Previous behaviour:
One of conditions required for predicate elimination was that for parallel type of
the domain the stored in parallel dimension map extend was exact, that is, all
domains with the parallel type have same extent,
New behaviour:
Instead of checking if extent for given parallel type in parallel dimension map is exact,
we check if this domain's extent is same/equal to stored extent in parallel dimension
map for given parallel type.
> Simplification of predicate elimination conditions

- python_tests/Pytest.md
- python_tests/pytest_opinfos.py
This PR adds tests for the following operations:
- abs, acosh, asin, asinh, atan, atanh, cos, cosh, erf, erfc, erfcinv, erfinv, exp, exp2, expm1, lgamma, log, log10, log1p, log2, reciprocal, rsqrt, sign, sin, sinh, sqrt, tan, tanh
The `elementwise_unary_torch` input generator creates random values for a function's input domain. It does not test specific small, large, or extremal ('-inf', 'inf', 'nan') input values.
> Add correctness tests for remaining unary-float operations

- csrc/executor.cpp
- csrc/executor_kernel_arg.cpp
- csrc/executor_kernel_arg.h
- csrc/type.cpp
- csrc/type.h
1. `getTensorArgBuffer` is renamed as `polymorphicValueToBytes`. In the past, it was specifically to convert tensor metadata to byte buffer. Now it is used to convert all polymorphic values to byte buffers. This will allow us to support using arbitrary `PolymorphicValue` as kernel parameter.
2. `getKernelArgument` is refactored to use `polymorphicValueToBytes`
> refactor `getKernelArgument` and `getTensorArgBuffer`

- csrc/codegen.cpp
- csrc/device_lower/pass/alias_memory.cpp
- csrc/options.cpp
- csrc/options.h
Currently the `reuseMemoryAllocations` lowering pass reuses `TensorView`s if they have compatible shapes and vectorization, and the same dtype. This PR replaces the dtype condition with a check that the size of each element is the same.
It is somewhat rare in our test suite that we find opportunities to re-use one buffer with another of a different type, but it does happen. For example, one case in `FusionWelfordShmoo_CUDA` corresponding to `testWelford(DataType::ComplexFloat, 1, 320, 256);` currently shows:
```
ptxas info    : Used 61 registers, 16 bytes smem, 464 bytes cmem[0]
```
With the current PR, this becomes
```
ptxas info    : Used 59 registers, 16 bytes smem, 464 bytes cmem[0]
```
since we re-use two register `TensorView`s that change from `int64_t` to `std::complex<float>`. …
> Alias allocations with same size elements despite different dtypes

- csrc/mma_type.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- test/test_gpu_tensorcore.cpp
- test/utils.cpp
- test/utils.h
The core functionality introduced with this change:
- update matmul scheduler to recognize bias epilogue pattern, if detected then handled as TensorView with `INPUT_C` role,
- simplify the handling of non-core roles in matmul scheduler,
- add unit test for bias epilogue,
- add functional tests,
> Matmul, bias epilogue support

- csrc/device_lower/pass/magic_zero.cpp
- csrc/device_lower/pass/vectorize_welford.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
Rename `replaceValInIndexVal` into `replaceValInDef`, make it support all expr types.
> cleanup `replaceValInIndexVal`

- csrc/device_lower/lower2device.cpp
- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/validation.cpp
- csrc/evaluator_common.cpp
- csrc/executor.cpp
- csrc/executor.h
- csrc/expr_evaluator.cpp
- csrc/kernel.cpp
- csrc/tensor_metadata.cpp
Instead, make our system capable of handling `DataType::Index`. `resolveIndexDtype` is a workaround for us for not having a well handling of different integer types. I am fixing this issue right now in https://github.com/NVIDIA/Fuser/pull/696, therefore, this workaround should be removed as well.
> Do not `resolveIndexDtype` in lowering

- python_tests/pytest_core.py
I am getting this error:
```python
❯ python python_tests/pytest_ops.py
Traceback (most recent call last):
File "/home/gaoxiang/Fuser3/python_tests/pytest_ops.py", line 11, in <module>
from pytest_fusion_definitions import default_fd_fn, parse_inputs_fusion_definition
File "/home/gaoxiang/Fuser3/python_tests/pytest_fusion_definitions.py", line 8, in <module>
from pytest_core import OpInfo
File "/home/gaoxiang/Fuser3/python_tests/pytest_core.py", line 79, in <module>
@dataclass
^^^^^^^^^
File "/usr/lib/python3.11/dataclasses.py", line 1223, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix `pytest_core.py`

- csrc/executor.cpp
- test/test_combined_inner_outer_reduction.cpp
When layer norm backward is segmented, the intermediate tensors between different fusion segments are saved as fp16. In a case with a hidden size of 27K, it leads to inf values. see https://github.com/NVIDIA/Fuser/issues/704
If the test case is using a dtype of fp16 and segmented, this PR scales down the inputs by a factor of 0.01.
It allows us to validate the fp16 segmented cases.
> add a test to track inf due to fp16 overflow

- csrc/scheduler/registry.cpp
Not sure why we have this check.
> Remove a requirement that inputs cannot be used multiple times

- csrc/scheduler/normalization.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/registry.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- test/test_resize.cpp
Stacked on top of #706. Part of work to enable slice vectorization.
This is a small bug fix for fusions with both reshape and resize. `propagateViewTransforms` (renamed to `propagateReshapeTransforms`) was attempting to propagate reshape as it's also an rfactor op, which is obviously not necessary. The added tests fail with this fix.
> Fix scheduling with reshape and resize

- test/test_expr_simplifier.cpp
Currently, in expr simplifier tests, we always create a new `Val*` for each variable that appears in the expression. For example, in `"i + i + i"_`, we will create three `NamedScalar`s, all with name `i`. This behavior does not have good coverage on the case where there are the same `Val*` as different inputs of the same expr. And there can be bugs related to this, for example, if I want to simplify `FlattenedAdd(i, i, i, -i)`, if not implemented carefully, I might be removing all the `i`s in the `FlattenedAdd`, instead of just removing one, if all the `i`s has the same `Val*`. In this PR, I changed the "stupid_simple_compiler" to randomly decide whether to reuse an existing `Val*` or to create a new one. This will increase our test coverage, although determinism might get hurt.
> Randomize `Val*` for expr simplifier test

- csrc/scheduler/vectorize_helper.cpp
- csrc/scheduler/vectorize_helper.h
- test/test_combined_inner_outer_reduction.cpp
- test/test_gpu_utils.cpp
It seems odd to me that `ContiguousInnerDimensionMapper::getProjectedExtent` automatically returns 1 for any domain that is not projected. It seems that was necessary for it to work under the non-recording mode, but there's no reason to use the function if no recording projected extents. 
This PR makes `getProjectedExtent` with non-projected domains result in an error. Also changed `distributePE` and `combinePE` to do nothing while not recording as they use `getProjectedExtent`.
Also added an error check to `addProjectedExtent`.
> Do not allow non-projected extents

- csrc/codegen.cpp
- csrc/ir/container.cpp
Currently they are not generating `Val` with the correct dtype....
> Fix `zeroVal(dtype)` and `oneVal(dtype)`

- csrc/tensor_view.cpp
- test/test_gpu3.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/718. Currently, we use `isOneInt` to detect if a dimension is size 1. This is not robust, because not all size one dims are constant one. A dim's extent might be something like `(nvfuser_index_t)1L`, which is still one. For that case, we should be able to detect it correctly.
> More robustly detect size one dim

- csrc/ir/builder.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/mma_utils.cpp
- test/test_gpu_tensorcore.cpp
Address issue reported for Ada device:
https://github.com/NVIDIA/Fuser/issues/682
The core problem:
On Ada devices heuristics enable smem epilogue and in case of
fusion with bias, the propagation of parallelization mode lead
to risk of unaligned reads of bias vector
Solution:
Prevent propagation of vectorization parallel type to epilogue
inputs (bias) if smem feature is enabled.
Note:
Sources of kernels generated for Ada device can be in comments
in PR.
PR contains also fixes that enable builds on GCC 9.4.
> Matmul, avoid vectorization causing misaligned reads

- csrc/device_lower/utils.cpp
Grid sync performs a block sync, so this should be treated as a block-synchronizing expression.
> Return true in hasBlockSync(kir::GridSync)

- csrc/python_frontend/fusion_definition.cpp
This is a single-character typo that fixes printing of repros in the error messages we see when python frontend crashes.
> Fix printing of BFloat16 in python error repros

- csrc/expr_evaluator.cpp
- csrc/polymorphic_value.h
Currently, `ExpressionEvaluator::print` print all types of values using the default `operator<<` of `std::ostream`. This makes sense for most types, but not really for tensors. Because the print of a tensor can be super long. For example, the following code
```C++
TEST_F(ExprEvalTest, AAA) {
Fusion fusion;
FusionGuard fg(&fusion);
TensorView* tv = makeSymbolicTensor(2);
auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
at::Tensor input = at::randn({256, 1024}, options);
ExpressionEvaluator ee;
ee.bind(tv, input);
ee.print();
}
```
prints something like
```
Evaluation context
--------------------
T0_l[ iS0{i0}, iS1{i2} ] = Columns 1 to 6-9.2466e-01 -4.2534e-01 -2.6438e+00  1.4518e-01 -1.2087e-01 -5.7973e-01
-1.0323e+00 -8.8939e-01 -1.9145e-01  8.2447e-01 …
```
> Let `ExpressionEvaluator::print` better print tensors

- test/test_gpu1.cpp
The addition of two scalars should always be a scalar. If we want a tensor filled with a scalar, we should use `FullOp`.
> Disallow `tv = scalar + scalar`

- csrc/device_lower/pass/scalar_hoist.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/kernel_ir.cpp
I changed `resolveIndexDtype` into:
```C++
void Val::resolveIndexDtype() {
TORCH_INTERNAL_ASSERT(dtype_ == DataType::Index);
}
```
And run all C++ tests and benchmarks. The only failure is `TensorFactoryTest.StandaloneARange`. I think it is fine, because the "index" of `arange` by definition can be an arbitrary dtype including double and complex, etc., so having an explicit int64 or int32 will not be a problem.
> Remove `resolveIndexDtype`

- csrc/codegen.cpp
- csrc/device_lower/pass/scalar_hoist.cpp
- test/test_loop_rotation.cpp
By intentionally not allocating some identified common subexpr, we can make the generated code less verbose and more readable
> Tunning index hoisting

- CMakeLists.txt
- setup.py
rpath should be a concatenated string, previous patch ended up overwriting it
> patch .so attempt 2

- setup.py
- tools/memory.py
The default `MAX_JOBS` should make the build as fast as possible, while still run out of memory. I tested locally with gcc 13.1, with 64 jobs in parallel, the highest memory usage is 181GB, so roughly 2.8GB/task. To be safer, we should consider capping the max jobs to `available mem / 3`.
> More smartly determine `MAX_JOBS`

- csrc/mma_type.h
- csrc/scheduler/matmul_utils.cpp
- test/test_gpu1.cpp
- test/test_gpu_tensorcore.cpp
- test/utils.cpp
- test/utils.h
The PRs story:
expose through matmul scheduler access to splitK-like strided batch transformations.
The key changes in the PR:
- update of compile time checks to recognize and correctly process strided batch gemm problems,
- add unit and multiple functional tests with key epilogues (point wise, beta scaling and bias),
- update testing infrastructure
- unification of how at::Tensor objects are initialized for reference calculations,
- extend functionality supported by bias helper functions (matmul and batch matmul support),
- add new debug logging entries in matmul scheduler and its utils,
Note: generated kernels for prepared test cases are posted as comments to each test case.
> Matmul, strided batch gemm support

- csrc/options.cpp
- csrc/options.h
- csrc/scheduler/matmul_utils.cpp
Issue: `NVFUSER_DUMP=scheduler_params` dumps params for all schedulers except matmul. 
This one line change makes matmul heuristic params can be checked with `NVFUSER_DUMP=scheduler_params`, keep consisent with other schedulers.
> enable SchedulerDebug for matmul params

- csrc/dispatch.cpp
- csrc/dispatch.h
- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
Add `ReverseArray` which does the same as `std::reverse`. Currently, this expr can only be eagerly evaluated. The lowering of this expr is not supported yet, but not needed today either.
> Add new expr `ReverseArray`

- csrc/codegen.cpp
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/executor_kernel_arg.cpp
- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ir/nodes.cpp
- csrc/ops/arith.cpp
- csrc/ops/composite.cpp
- csrc/rng.cpp
- csrc/type.cpp
- csrc/type.h
- test/test_evaluator.cpp
- test/test_gpu3.cpp
- test/test_tensor_factories.cpp
I think the previous names are confusing
- `ArrayOf` -> `ArrayType`
- `PointerOf` -> `PointerType`
- `StructOf` -> `StructType`
> Rename non-primitive types

- csrc/tensor_metadata.cpp
Partially take back regressions from shape inference due to recent refactor: https://github.com/NVIDIA/Fuser/issues/749
Shape inference benchmark:
```C++
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
LayerNormBackward_ShapeInference                        128 us          128 us         5428
LayerNormForward_ShapeInference                        44.9 us         44.8 us        15608
LayerNormBackward_NoShapeInferenceCachedBaseline       78.2 us         78.1 us         8917
LayerNormForward_NoShapeInferenceCachedBaseline        37.4 us         37.4 us        18735 …
```
> Fast path for trivial allocation domain

- csrc/executor.cpp
- csrc/executor_kernel_arg.cpp
Shape inference benchmark:
main:
```C++
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
LayerNormBackward_ShapeInference                        129 us          129 us         5434
LayerNormForward_ShapeInference                        46.1 us         46.0 us        15050
LayerNormBackward_NoShapeInferenceCachedBaseline       79.8 us         79.6 us         8682
LayerNormForward_NoShapeInferenceCachedBaseline        37.7 us         37.7 us        18564
```
this:
```C++
------------------------------------------------------------------------------------------- …
```
> Reduce CPU overhead on `allocOutputs` when there is no allocation domain

- test/test_smem_reuse.cpp
This fixes up the condition and avoids the issue in #772 by introducing more space between outer live intervals. When that bug is fixed we should set this test back to using adjacent lifetimes again.
> Silence error in PromoteReuseMultipleDownstream

- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- test/test_gpu_utils.cpp
fixes: #675 (Although the problem only shows up after a few other PR that refactors transpose vectorization computation)
Transpose scheduler should merge dimensions in the expected order (from inner to outer on each group).
Otherwise generated kernel would violate alignment requirement for vectorization.
> fixing transpose scheduler merge dimension issue

- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ops/arith.cpp
- csrc/type.cpp
Due to historical reason (when we do not have pointer dtype), `UnaryOpType::Address` was returning `int64_t` instead of pointers. This is changed now.
> `UnaryOpType::Address` returns pointers instead of `int64_t`

- csrc/device_lower/pass/alias_memory.cpp
- test/test_smem_reuse.cpp
Currently, `ScopeMap` increments the position when recording the end of either a `ForLoop` or the top-level scope. This means we cannot interpret the end position as an actual last read, breaking the guarantee that `BufferLiveInterval` is a closed interval. Since we do not have separate expressions for the end of loops, we cannot point to a specific location for the loop ending, but interpreting the interval as half-open depending on the loop nest structure is confusing, as seen in #772.
This PR introduces positions for the ends of for loops, although they do not have corresponding `Expr`s in the kernel IR. As a result, two adjacent for loops will have non-intersecting intervals, and allocations with uses confined to each will thus have non-intersecting outer live intervals. Since the …
> Stop extending lifetimes past end of for loops in aliasing pass

- csrc/C++20/type_traits
- csrc/dynamic_type.h
- csrc/type_traits.h
- test/test_dynamic_type.cpp
I am about to rewrite struct type in `PolymorphicValue` for better performance, but before doing so, I'd like to have `->*` which will provide a good interface. See `namespace member_pointer_test` to get an idea about how it will be used.
> Overload `->*` for `DynamicType`

- CMakeLists.txt
- csrc/executor.cpp
- csrc/executor_kernel_arg.cpp
- csrc/ir/nodes.cpp
- csrc/polymorphic_value.h
- csrc/serde/polymorphic_value_serde.cpp
- csrc/tensor_metadata.cpp
- csrc/type.h
- test/test_evaluator.cpp
- test/test_polymorphic_value.cpp
Rename `Struct` -> `LegacyStruct`, this class template will be deprecated soon. Also, created a `test/test_polymorphic_value.cpp` for polymorphic value tests. Currently, there is only one test `OpaqueEquality` moved from `test/test_evaluator.cpp`, in the future, more will be added.
> Rename `Struct` -> `LegacyStruct` and misc cleanup

- csrc/dynamic_type.h
- test/test_dynamic_type.cpp
Just noticed that the casting operator from a custom class to `DynamicType` is broken, the failing case is shown in `DynamicTypeTest.CastToDynamicType`. The failure is because of the lack of SFINAE in the ctor of `DynamicType`, when a conversion is needed, the compiler always tries to use the ctor of `DynamicType` instead of the casting operator. This PR adds the required SFINAE.
> Add SFINAE for the ctor of `DynamicType`

- csrc/dynamic_type.h
- test/test_dynamic_type.cpp
The previous implementation does not work for member functions, this PR fixes it.
> Fix `->*` for member functions

- CMakeLists.txt
- cmake/Dependencies.cmake
- csrc/polymorphic_value.h
- lib/dynamic_type/CMakeLists.txt
- lib/dynamic_type/src/C++20/type_traits
- lib/dynamic_type/src/dynamic_type.h
- lib/dynamic_type/src/error.h
- lib/dynamic_type/src/type_traits.h
- lib/dynamic_type/test/test_dynamic_type.cpp
- manual_ci.sh
This PR split out `DynamicType` from nvFuser to maintain it as a separate C++ template library. The codebase of this library is located in `Fuser/lib/dynamic_type`. The main reason for doing so is because I want to be able to build the test for `DynamicType` separately without building the entire nvFuser. This is important for the productivity of the development of `DynamicType`, because I need to do a lot of try-and-errors in development, and each change of the `dynamic_type.h` requires rebuilding almost the entire nvFuser, which today is very slow (due to `DynamicType`). I want to be able to ignore the rest of nvFuser and just try and error in the test of `test_dynamic_type.cpp`. In the future, `test_dynamic_type.cpp` will be split into multiple separate files for better parallelizing …
> Make `DynamicType` a standalone library

- csrc/dynamic_transform.cpp
- csrc/ir/nodes.cpp
- test/test_resize.cpp
This updates the root to rfactor propagation in IterType concretization of dynamic fusions.
Previously, although we only overwrote Symbolic IterDomains in this step, we still asserted that we could infer an IterType for each I moved that check so that it is only applied when we need to make a change.
Additionally, we previously propagated Broadcast-only IterDomains as Symbolic, since we combine with our previous estimate using promoteIterType. As mentioned in a comment, this means Broadcast gets propagated as Symbolic. Instead we now only fall back to promoteIterType when there are multiple input IterTypes to the IterDomain expression.
Fixes #798
> Skip trivial Resize, handle resize of Broadcast at concretization.

- python_tests/pytest_framework.py
Early terminate test suite if there are CUDA errors
Ref: https://github.com/pytorch/pytorch/blob/aa8ea1d787a9d21b064b664c5344376265feea6c/torch/testing/_internal/common_utils.py#L2251-L2263
> CUDA device side error will cause subsequence test cases to fail.
> stop entire test suite if catches RuntimeError during torch.cuda.synchronize().
This can be verified locally with 
```
pytest python_tests/pytest_ops.py -v -k 'test_correctness_atan2 or test_correctness_div'
```
using today's build 20230829
Side note: most of our test_X.py tests inherit TestCase from pytorch, which already has this early termination feature.
> Early terminate test suite if there are CUDA errors

- csrc/exceptions.h
Fixes gcc 13.2.1 error for PR #811 .
> Add `cstdint` header

- CMakeLists.txt
- csrc/serde/fusion_cache_generated.h
The PR enables the FlatBuffers object-based API. It allows for using FlatBuffers objects directly in the NvFuser codebase and then serializing those objects without any extra translation steps.
> --gen-object-api : Generate an additional object-based API. This API is more convenient for object construction and mutation than the base API, at the cost of efficiency (object allocation). Recommended only to be used if other options are insufficient.
https://flatbuffers.dev/flatbuffers_guide_use_cpp.html
This option complements the existing API, so you can use it as-needed. Normally, after deserialization, the FlatBuffer is deleted from memory, so you lose access to the data. This option defines a cpp struct for each table. You can then unpack data into a struct for persistent storage.
> Enable object-based API option when compiling FlatBuffers schema

- csrc/scheduler/matmul_utils.cpp
Issue: When I ran normalization cases with `schedulerDebug`, there are redundant output from matmul scheduler telling me why matmul scheduler is not used. This info should be printed with `{"segmenter_logging", DebugDumpOption::FusionSegmenterLog},` and  schedulerDebug is used to print the parameters of the heuristics.
Fix: remove cout in `getMatmulCompileTimeRejectReason`
Result: MatmulCompileTimeRejectReason will only be printed out if `NVFUSER_DUMP=segmenter_logging`
> schedulerDebug shouldn't print why matmul scheduler is not used.

- csrc/codegen.cpp
Generate type name for brace initializer
Change in `TensorFactoryTest.TensorConstruct`:
Before:
```C++
__global__ void kernel1(int64_t i0, int64_t i1, int64_t i2, int64_t i3, Tensor<int64_t, 2, 2> T0) {
NVFUSER_DEFINE_MAGIC_ZERO;
Array<int64_t, 2, 1> a4;
a4 = {i2, i3};
Array<int64_t, 2, 1> a5;
a5 = {i0, i1};
Array<Array<int64_t, 2, 1>, 2, 1> a6;
a6 = {a5, a4};
#pragma unroll
for(nvfuser_index_t i7 = 0; i7 < 2; ++i7) {
nvfuser_index_t i8;
i8 = 2 * i7;
#pragma unroll
for(nvfuser_index_t i9 = 0; i9 < 2; ++i9) {
nvfuser_index_t i10;
i10 = i9 + nvfuser_zero;
T0[(i8 + i10)] = a6[i7][i10];
}
}
NVFUSER_UPDATE_MAGIC_ZERO;
}
```
After:
```C++
__global__ void kernel1(int64_t i0, int64_t i1, int64_t i2, int64_t i3, Tensor<int64_t, 2, 2> T0) {
NVFUSER_DEFINE_MAGIC_ZERO;
Array<int64_t, 2, 1> a4;
a4 = …
```
> Emit type name in generated C++ for `TensorConstruct` and `ArrayConstruct`

- nvfuser/__init__.py
This originally sized tensor does not work for `as_strided` usage because the first tensor is only sized for 3 elements when, `as_strided` is attempting to access up to a 7th element.  `as_strided`, therefore, would hit an error.
```python
torch.randn((3, 1), dtype=torch.float32, device='cuda:0').as_strided((3, 1), (3, 1)),                                                                            
torch.randn((3, 2), dtype=torch.float32, device='cuda:0').as_strided((3, 2), (3, 1)),
```
we will now print
```python
torch.randn((7,), dtype=torch.float32, device='cuda:0').as_strided((3, 1), (3, 1)),                                                                            
torch.randn((8,), dtype=torch.float32, device='cuda:0').as_strided((3, 2), (3, 1)),
```
Fixes #844
> Python error printing: compute strided size properly

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_resize.cpp
Implements the `Expr::evaluate` method for `PadOp`. This is a part of resolving issue #670.
> `Expr::evaluate` method for `PadOp`

- csrc/scheduler/matmul.cpp
remove unneccessary special inline of output tensor. (This was found while working on the smem epilogue PR and I promised to fix it in a future PR)
No change in generated code checked with
` tools/compare_codegen.sh -- build/nvfuser_tests --gtest_filter='*Matmul*'`
a full check is done by the CI.
> remove unneccessary special inline of output tensor

- CMakeLists.txt
- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/utils.cpp
- csrc/executor.cpp
- csrc/executor.h
- csrc/executor_utils.cpp
- csrc/executor_utils.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/kernel_cache.cpp
- csrc/type.cpp
- csrc/type.h
- runtime/array.cu
- test/test_memory.cpp
- test/test_pipeline.cpp
This reverts commit b3edc818037a48624caa94d096ef3ed903bbe5bc and modifies `compileSource` to decouple `compile_to_sass` and `DebugDumpOption::Ptx`. With this PR, `compileSource` performs a regular compilation according to `compile_to_sass` and if PTX is requested runs another `nvrtcGetProgram` just to get PTX. Other parts of the PR is identical to #843 except that `test_memory.cpp` now requests PTX by enabling `DebugDumpOption::Ptx`.
> LoadStoreOp takes a CacheOp. Second try.

- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- lib/dynamic_type/src/dynamic_type/type_traits.h
- lib/dynamic_type/test/binary_ops.cpp
- lib/dynamic_type/test/opcheck.cpp
- lib/dynamic_type/test/utils.h
- test/test_polymorphic_value.cpp
`PolymorphicValue->*something` returns an accessor of `PolymorphicValue`, instead of returning just `PolymorphicValue`:
https://github.com/NVIDIA/Fuser/blob/0b85a578d968285f3e430c32de90708cc164bfda/csrc/polymorphic_value.h#L202
The accessor has defined automatic conversion operator to `PolymorphicValue`, however, that automatic conversion does not work for operators. For example:
```C++
PolymorphicValue x = ...;
PolymorphicValue y = ...;
x + (y->*"field");  // does not compile
```
This behavior does not make sense.
The root cause for this behavior is because, when we have
```C++
template<typename T>
T f(T x, T y) {
...
}
```
Then `f(2, 2L)` does not work, because `2` and `2L` are different type, so there is no way for C++ to know whether it should choose `f<int>` or `f<int64_t>`. For this …
> [DynamicType] Fix automatic conversion to `DynamicType`

- csrc/scheduler/normalization.cpp
**Issue:** The function `ir_utils::getViewOps(fusion).empty() ` is evaluated twice: once in `getPersistentHeuristics` and then in `schedulePersistentKernel`. The initial evaluation determines the `max_persistent_size`, while the subsequent one is for `project_persistent_buffers`.
**Fix:** In this PR, the value of the first evaluation is also used to set `project_persistent_buffers`, then the second evaluation is unnecessary and can be omitted.
> avoid redundant checking of viewOps

- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul.h
- csrc/scheduler/registry.cpp
This PR did step-7 described in https://github.com/NVIDIA/Fuser/issues/864.
It moved matmul scheduler from registry.cpp to matmul.cpp
> move matmul scheduler from registry.cpp to matmul.cpp

- csrc/type.cpp
- csrc/type.h
- runtime/array.cu
- test/test_memory.cpp
As a follow up to #865, add `CacheOp::Global` so we can emit `ld.global.cg` as well. This provides more ammunition to investigate #775.
> Add CacheOp::Global.

- csrc/scheduler/heuristic_types.h
- csrc/scheduler/registry.cpp
This PR cleans up registry.cpp after schedulers are moved to their own files as described in #864.
It did: 
(1) move comments and list of schedulers to heuristic_types.cpp
(2) clean up header inclusions in registry.cpp.
(3) rename to `all_heuristics_in_priority_order` to convey the intent that order matters.
> clean up registry.cpp after schedulers are moved

- CMakeLists.txt
Even when BUILD_PYTHON doesn't get set, we still need to be able to serialize things. Without this change we have undefined references when BUILD_PYTHON is false or unset.
The second issue is that we couldn't actually set custom flags at cmake invocation time, unless those flags happened to end in a separator.
> Tiny build changes

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_gpu_indexing_ops.cpp
This is a part of resolving issue #670.
> `Expr::evaluate` method for `SelectOp` and `IndexSelectOp`

- csrc/scheduler/pointwise.cpp
Part of #891 to remove redundant nontrivial checks in getHeuristics and scheduleKernel.
In this PR, the check of reduction ops is removed from `schedulePointwise` because:
(1) the same check is already done in `canScheduleCompileTime`
and 
(2) the check is nontrivial as it requires iterating through all the expressions in the fusion.
> remove reductionOps checks from schedulePointwise

- lib/dynamic_type/src/dynamic_type/dynamic_type.h
It is supported, see:
https://github.com/NVIDIA/Fuser/blob/ace12da951cdcf9b806e93387bc905752b165ab0/lib/dynamic_type/test/binary_ops.cpp#L135-L138
> Remove obselete note in `dynamic_type.h`

- CMakeLists.txt
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_inner_outer.h
Split #862 into multiple PRs.
In this PR:
(1) normalization.cpp is duplicated and renamed to normalization_inner_outer.cpp
(2) The duplicated class `PersistentKernelScheduler` is renamed to `InnerOuterPersistentKernelScheduler`
(3) The duplicated APIs `getPersistentHeuristics` and `schedulePersistentKernel` are renamed to `getInnerOuterPersistentHeuristics` and `scheduleInnerOuterPersistentKernel`
(4) Internal functions in normalization_inner_outer.cpp are moved to an anonymous namespace to avoid name collisions with those originally defined in normalization.cpp
> add inner_outer scheduler

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_gather.cpp
This is a part of resolving #670
> `Expr::evaluate` method for `ScatterOp` and `TorchGatherOp`

- CMakeLists.txt
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner.h
Split https://github.com/NVIDIA/Fuser/pull/862 into multiple PRs.
In this PR:
(1) normalization.cpp is duplicated and renamed to` normalization_inner.cpp`
(2) The duplicated class PersistentKernelScheduler is renamed to `InnerPersistentKernelScheduler`
(3) The duplicated APIs getPersistentHeuristics and schedulePersistentKernel are renamed to `getInnerPersistentHeuristics` and `scheduleInnerPersistentKernel`
(4) Internal functions in normalization_inner.cpp are moved to an anonymous namespace to avoid name collisions with those originally defined in normalization.cpp
This scheduler is not being used yet.
> add inner persistent scheduler

- CMakeLists.txt
- csrc/fusion_segmenter.cpp
- csrc/scheduler/all_schedulers.h
- csrc/scheduler/heuristic_types.cpp
- csrc/scheduler/heuristic_types.h
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner.h
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/normalization_utils.h
- csrc/scheduler/reduction_utils.cpp
- csrc/scheduler/reduction_utils.h
- csrc/scheduler/registry.cpp
- test/test_gather.cpp
- test/test_gpu1.cpp
- test/test_gpu3.cpp
Enable the newly added `InnerPersistent` scheduler. It requires inner reduction tvs without outer reduction tvs.
Its priority is higher than the original Persistent scheduler which can process inner, outer, and inner_outer.
> Enable the newly added InnerPersistent scheduler.

- CMakeLists.txt
- csrc/kernel_ir.h
- csrc/scheduler/normalization_inner.h
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/normalization_outer.h
- csrc/type.h
Split https://github.com/NVIDIA/Fuser/pull/862 into multiple PRs.
In this PR:
(1) normalization.cpp is duplicated and renamed to normalization_outer.cpp
(2) The duplicated class PersistentKernelScheduler is renamed to OuterPersistentKernelScheduler
(3) The duplicated APIs getPersistentHeuristics and schedulePersistentKernel are renamed to getOuterPersistentHeuristics and scheduleOuterPersistentKernel
(4) Internal functions in normalization_outer.cpp are moved to an anonymous namespace to avoid name collisions with those originally defined in normalization.cpp
This scheduler is not being used yet.
> add outer persistent scheduler

- test/test_matmul_scheduler.cpp
There is a negative false for case `MatmulSchedulerTest.EpilogueBias_CUDA` in a CI process. 
Change to calculate the reference value using float to avoid negative false and also keep consistent with other cases.
> calculate matmul ref using float

- CMakeLists.txt
- benchmark/softmax.cpp
- csrc/scheduler/all_schedulers.h
- csrc/scheduler/heuristic_types.cpp
- csrc/scheduler/heuristic_types.h
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/normalization_outer.h
- csrc/scheduler/registry.cpp
- test/test_gpu2.cpp
- test/test_gpu_outer_reduction.cpp
Enable the newly added OuterPersistent scheduler. It requires outer reduction tvs without inner reduction tvs.
Its priority is higher than the original Persistent scheduler which can process inner, outer, and inner_outer.
> Enable the newly added OuterPersistent scheduler

- csrc/tma.cpp
- Changed the `padding` and `globalStrides` check. The new one mismatch with the official doc, but I think it is correct.
- Requires `bounding_box_inner_dim >= swizzle` per offline discussion with @drzejan2
> Fix checks in `EncodeTensorMapTiled::evaluate`

- benchmark/transpose.cpp
- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- test/test_allocation_domain.cpp
Fixes #902 
1. for inner most dimension query, we should be using allocation domain instead of rfactor domain.
2. renamed transpose benchmark from `NF_Transpose_XXX` to `NvFuserScheduler_Transpose_XXX`
> use getMaybeAllocationDomain instead of getMaybeRFactorDomain 

- CMakeLists.txt
- setup.py
Tested:
```
$ pip install -e .
$ nm -an bin/nvfuser_tests | grep asan
<empty>
$ python setup.py develop --build-with-asan
$ nm -an bin/nvfuser_tests | grep asan
...
00000000024f3840 B __odr_asan._ZN7nvfuser38NVFuserTest_FusionDefinition_CUDA_Test10test_info_E
00000000024f38e0 B __odr_asan._ZN7nvfuser35NVFuserTest_PyFusionCache_CUDA_Test10test_info_E
00000000024f3980 B __odr_asan._ZN7nvfuser43NVFuserTest_RecordFunctorEquality_CUDA_Test10test_info_E
0000000002528fa0 B __odr_asan._ZN5torch8autograd47_GLOBAL__N__551c3bf8_14_rng_kernels_cu_8fdfe6fb13graph_task_idE
```
> Add an option to build with asan.

- benchmark/gelu_backward.cpp
- benchmark/heuristic_cache.cpp
- benchmark/heuristic_lookup.cpp
- benchmark/indexselect.cpp
- benchmark/lstm_cell.cpp
- benchmark/many_pointwise_ops.cpp
- benchmark/matmul.cpp
- benchmark/shape_inference.cpp
- benchmark/softmax.cpp
The CI is filtering nvfuser benchmark cases with `NvFuserScheduler_*`, however the names of some nvfuser cases are not started with `NvFuserScheduler_`. This PR adds `NvFuserScheduler_` to these cases.
> rename all nvfuser benchmarks start with NvFuserScheduler_

- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/normalization_outer.h
similar to #923
(1) Transformed private static functions in the OuterPersistentKernelScheduler class into utility functions within an anonymous namespace.
(2) Removed checks/calculations that are unrelated to outer persistent scheduler.
> clean normalization_outer

- CMakeLists.txt
- csrc/driver_api.cpp
- csrc/driver_api.h
Added `cuFuncSetAttribute`. Also, we are not linking with `libcuda.so` anymore.
```C++
❯ ldd build/libnvfuser_codegen.so
linux-vdso.so.1 (0x00007ffe4699d000)
libnvrtc.so.12 => /opt/cuda/lib/libnvrtc.so.12 (0x00007f61b7600000)
libnvToolsExt.so.1 => /opt/cuda/lib/libnvToolsExt.so.1 (0x00007f61b7200000)
libtorch.so => /home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/lib/libtorch.so (0x00007f61bbc02000)
libc10.so => /home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/lib/libc10.so (0x00007f61bb124000)
libcudart.so.12 => /opt/cuda/lib/libcudart.so.12 (0x00007f61b6e00000)
libc10_cuda.so => /home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/lib/libc10_cuda.so (0x00007f61b74e2000)
libtorch_cpu.so => …
```
> Don't link `libcuda.so`

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
- test/test_resize.cpp
Implements the `Expr::evaluate` method for `CatOp` and `SliceOp`. This is a part of resolving issue #670.
> `Expr::evaluate` method for `CatOp` and `SliceOp`

- csrc/scheduler/mma_utils.cpp
This sorts the output of `mma_utils::getTensorsRoles` so that the matmul scheduler is repeatable. This should fix the false positives in codegen diff CI jobs. :crossed_fingers: 
Fixes #799.
> Fix non-determinism in `mma_utils::getTensorsRoles`

- examples/sinh_extension/main.cpp
- examples/sinh_extension/setup.py
Example still has `#include <arith.h>`. Changed to `#include <ops/arith.h>`. Also we still used `using namespace torch::jit::fuser::cuda` and we were missing include dirs for flatbuffers and dynamic_type.
> Fix sinh_extension example compile error

- csrc/fusion_segmenter.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/no_op.cpp
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/transpose.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_gpu_tensorcore.cpp
- test/test_matmul_scheduler.cpp
This is the first step to solve #946 : Refactor the existing getXops functions into a single templated function to centralize the operation retrieval logic.
> add template function getOpsOfType

- CMakeLists.txt
- csrc/ir/internal_nodes.h
- csrc/scheduler/cache_policy_refiner.cpp
- csrc/scheduler/cache_policy_refiner.h
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/pointwise.cpp
- test/test_memory.cpp
This change improves #775. I observed >20% speed up for some layer normalization and broadcasting benchmarks. I manually verified the top five regressions and found they are noise. 
```
Top 5 improvements:
Benchmark NvFuserScheduler_LayerNorm_fp16___GRAPH/NvFuserScheduler_LayerNorm_fp16/16/2097152/manual_time changed from 235.70649740466797 seconds 173.04190461790853 (0.73x)
Benchmark NvFuserScheduler_LayerNorm_fp16___GRAPH/NvFuserScheduler_LayerNorm_fp16/8/2097152/manual_time changed from 138.39395947220675 seconds 102.51789488799382 (0.74x)
Benchmark NvFuserScheduler_Broadcast_Outer_fp16___GRAPH/NvFuserScheduler_Broadcast_Outer_fp16/8/2097152/manual_time changed from 66.96629544563652 seconds 50.55804438076262 (0.75x)
Benchmark …
```
> Refine cache policy of global-to-local vector loads. 

- tools/diff_codegen_nvfuser_tests.py
This is just a small utility that will diff codegen output for `nvfuser_tests` in a way that lines up output from the same tests, even if new tests have been introduced.
This addresses a limitation of the default script where new tests lead to more cuda kernels being output at some intermediate point in the run. After that, all the kernels are misnumbered so we wind up with a huge number of false positives.
This script parses the stdout log of each command to find which kernels were produced by each test, and diffs those corresponding files directly. The exit code is the number of tests with mismatches.
A typical usage would be something like the following:
```
> tools/compare_codegen.sh  # create codegen_comparison with subdirs for this commit and merge-base
> python …
```
> Add diff_codegen_nvfuser_tests.py

- .gitignore
This configures pre-commit hooks downloaded from https://pre-commit.com.
> Ignore .pre-commit-config.yaml

- csrc/ir/nodes.cpp
- csrc/ops/alias.cpp
We currently use `isOneVal()` to test that a squeezed broadcast dimension has extent == 1. This change takes a deeper look to verify that it is a constant 1, but does not require it to be an immediate constant.
Fixes #963. Test omitted since it's included in #973 already.
> Evaluate extent for 1 check in squeeze and SqueezeOp

- csrc/driver_api.h
- csrc/executor.cpp
- csrc/executor.h
- csrc/executor_utils.cpp
- csrc/executor_utils.h
This fixes potential memory leaks where `CUmodule`s are never destroyed. It doesn't matter at this point because we never (?) evict `FusionKernelRuntime` from `FusionExecutorCache` (according to https://github.com/search?q=repo%3ANVIDIA%2FFuser%20evictcache%20&type=code).
> Wrap CompiledKernel in unique_ptr and add a proper destructor.

- .github/workflows/lint.yml
- lib/dynamic_type/benchmark/knn.cpp
- lib/dynamic_type/meson.build
We may or may not want to eventually decide to be committed to meson, but for now, since I already have a working `meson.build` for `dynamic-type`, let me just add it. Using OSS CI because this test is fast enough.
> Meson build for dynamic-type library

- .github/workflows/lint.yml
See https://github.com/NVIDIA/Fuser/issues/965#issuecomment-1740862192
> Generate fusion_cache_generated.h in clang-tidy CI job

- csrc/codegen.cpp
- test/test_gpu1.cpp
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_loop_rotation.cpp
In https://github.com/NVIDIA/Fuser/issues/973#issuecomment-1741343225, it was mentioned that expressions on `DataType::Int` constants are not necessarily safe from overflow. For example, an `exp` expression on `Int` constants currently prints like the example `2 ** 30`. Integer literals that are not very large will be compiled as 32-bit ints, so this arithmetic will be taking place at too low precision. This PR addresses this issue by adding a suffix of `LL` for `Int` constants so that these will translate to long long, which is 64-bit (see comment in code and second reference below on why we don't use `L` instead).
References:
- https://en.cppreference.com/w/cpp/language/integer_literal
- https://en.cppreference.com/w/cpp/language/types
> Add LL suffix to Int literals

- csrc/codegen.cpp
So readers know what they refer to. Example output: 
```
[ RUN      ] CacheGlobalLoads/MemoryTest.LoadCache/Streaming
======= Codegen output for kernel: kernel4 =======
__global__ void kernel4(Tensor<float, 1, 1> T0, Tensor<float, 1, 1> T3) {
nvfuser_index_t i0;
i0 = 4 * ((nvfuser_index_t)threadIdx.x);
nvfuser_index_t i1;
i1 = 128 * ((nvfuser_index_t)blockIdx.x);
nvfuser_index_t i2;
i2 = i0 + i1;
bool b3;
b3 = ((3 + i0) + i1) < T0.logical_size[0];
Array<float, 4, 4> T1;
T1.set(float(0));
if (b3) {
loadGlobalToLocal<float, /*vec_size=*/4, /*is_volatile=*/false, CacheOp::Streaming>(&T1[0],  &T0[i2]);
}
Array<float, 4, 4> T2;
#pragma unroll
for(nvfuser_index_t i4 = 0; i4 < 4; ++i4) {
T2[i4]
= T1[i4]
+ (float) 1.00000000000000000e+00;
}
if (b3) {
loadLocalToGlobal<float, /*vec_size=*/4, …
```
> In generated CUDA code, put comments before constants.

- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
This PR fixes the following issue:
The `canScheduleCompileTime` function in normalization schedulers should call `checkReductionPattern` after checking the reduction axis, not before. It avoids building root domain map in easier cases, aligns with the reduction scheduler's order, and follows the principle of performing simpler checks first. This mistake has been present since the repository's first commit.
> fix order of compile time checks in normalization scheduler

- test/test_gpu_outer_reduction.cpp
I believe these tests were moved from test_gpu*.cpp so they inherited the name NVFuserTest. In general, we should use more specific names so it's easier to `--gtest_filter`.
This PR also removes the legacy `Fusion` prefix and `_CUDA` suffix as recommend by @naoyam .
> Rename the tests to OuterReductionTest*.

- CMakeLists.txt
See https://github.com/NVIDIA/Fuser/pull/1010#issuecomment-1747648452
> Remove --no-allow-shlib-undefined as our dependencies may not have correct dependencies, e.g., c10

- csrc/id_model/id_graphs.cpp
- csrc/id_model/id_graphs.h
- csrc/id_model/utils.h
- test/test_gpu_indexing.cpp
This PR adds structural validations of loop graphs and promotions of one of the most important tests, `Indexing19`. In order to do so, it introduces a minimal set of changes as follows:
- Enable building loop graphs and promotion mappings even for `Fusion`
- Populate a map from loop ID groups to their promotion domains, which is temporarily done at the very end of `buildLoopPromotionMap`.
Some cleanups are needed, but I will iteratively work on cleanups as well as functional changes. This PR severs as the baseline for forthcoming PRs as well as making sure my understanding is correct.
> Fill the final loop promotion map 

- test/test_allocation_domain.cpp
1. s/NVFuserTest/AllocationDomainTest
2. Remove the legacy _CUDA suffix.
> Clean up test names.

- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/normalization_utils.h
- test/test_combined_inner_outer_reduction.cpp
In #1023, the iteration domain in inner reduction tv is not mapped to reduction domain in outer reduction tv.
I can reproduce the error with a simple fusion:
```
Inputs:
T0_g[ iS0{i0}, iS1{i2}, iS2{i3} ], float
Outputs:
T3_g[ iS9{i0}, iS10{i2}, iS11{i3} ], float
T4_g[ rS12{i0}, iS13{i2}, iS14{i3} ], float
%kernel_math {
T1_l[ iS3{i0}, iS4{i2}, rS5{i3} ]
= reduction( T0_g[ iS0{i0}, iS1{i2}, iS2{i3} ], op = add, initial value = float(0), allreduce = false )
T2_l[ iS6{i0}, iS7{i2}, bS8{1} ]
= broadcast( T1_l[ iS3{i0}, iS4{i2}, rS5{i3} ] )
T3_g[ iS9{i0}, iS10{i2}, iS11{i3} ]
= T2_l[ iS6{i0}, iS7{i2}, bS8{1} ]
+ T0_g[ iS0{i0}, iS1{i2}, iS2{i3} ];
T4_g[ rS12{i0}, iS13{i2}, iS14{i3} ]
= reduction( T0_g[ iS0{i0}, iS1{i2}, iS2{i3} ], op = add, initial value = float(0), allreduce = false )
}
}
``` …
> disable innerOuter schedule if iteration domain in inner reduction tv is not mapped to reduction domain in outer reduction tv

- test/test_combined_inner_outer_reduction.cpp
remove unnecessary fusion print from test
> remove unnecessary fusion print from test

- csrc/fusion.h
This makes it easier to trace down the return type. Previously, readers would have to find the members.
> Make the return type explicit.

- lib/dynamic_type/CMakeLists.txt
- lib/dynamic_type/README.md
- lib/dynamic_type/meson.build
- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- lib/dynamic_type/test/utils.h
Replacing https://github.com/NVIDIA/Fuser/pull/1037. Because `std::monostate` always define compare operators, `DynamicType` should do the same thing. There is no need for SFINAE. This PR also adds build on C++20. 
I suggest reviewing this PR hiding whitespaces:
> [DynamicType] Remove member SFINAE for compare ops

- csrc/polymorphic_value.h
- python_tests/test_nan.py
```
Traceback (most recent call last):
File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 122, in execute
result = self._execute(
RuntimeError: isSame(values_[it.first], it.second) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/evaluator_common.cpp":314, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Precomputed values failed to validate.
Something unexpected changed between the compilation and execution.
nan != nan
Exception raised from validate at /opt/pytorch/nvfuser/csrc/evaluator_common.cpp:314 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x8d (0x7fdc9919fe3b in /usr/local/lib/python3.10/site-packages/torch/lib/libnvfuser_codegen.so)
frame #1: …
```
> Fix a crash when a FusionDefinition is executed with a NaN tensor.

- csrc/id_model/id_graphs.cpp
`PairwiseRootDomainMap` by default allows mapping of broadcast and non-broadcast domains. We should probably disable that too.
The validation in the Indexing19 test passes. Some other tests are failing but that is the case without this PR too.
Fixes #1052
> Do not map broadcast and non-broadcast domains in EXACT

- csrc/id_model/id_graph.cpp
This doesn't seem necessary at this moment but required to stop using ALMOST_EXACT for permissive mappings.
Suppose domains A and B have uses as:
A: ExprGroup X and ExprGroup Y
B: ExprGroup X and ExprGroup Y
i.e., both have the same set of expr groups. Before this propagation, there's nothing to allow map X and Y. When A and B are mapped, we should map the uses of A and B, which means X and Y should be mapped. The check removed in this PR prevents the propagation.
> Fix mapping propagations through uses

- csrc/id_model/id_graphs.cpp
ALMOST_EXACT should not be necessary for PERMISSIVE and LOOP
Related: #1053
> Use the EXACT map as the starting map of the PERMISSIVE map

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_gpu2.cpp
- test/test_gpu_indexing_ops.cpp
This is a part of resolving Issue #670. Addresses https://github.com/NVIDIA/Fuser/pull/899#discussion_r1330908237.
> `evaluate` method for `ReductionOp`

- csrc/id_model/id_graphs.cpp
- test/test_gpu_indexing.cpp
When finding reusable promotion domains, make sure to reuse loop-mapped
domains since promotion domains should be part of mapped loop groups.
This should fix #1054. Additional checks are also added to the Indexing19 test.
> WIP: Loop promotion with IEL

- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
This makes it easier to debug TensorDomain, and happens to fix a bug where `indent_size` was ignored.
> Add a variant of TensorDomain::toString to print all domains.

- csrc/fusion_segmenter.cpp
- test/test_allocation_domain.cpp
Existing code relies on setAllocationDomain to update the allocation domain after tensor creation in `convertInputRfactorsToRoots`. However the initial contiguity flag isn't consistent with the root domain, which triggers assert.
> switch to TensorDomain constructor to set allocation_domain

- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/fusion_state.cpp
- csrc/python_frontend/fusion_state.h
This fixes a bug where we said
```
const auto& output_shape = fd.getFusionStateVector(...);
```
`output_shape` became a reference to a temporary object.
> getFusionStateVector returns a const&.

- csrc/fusion.cpp
- test/test_dynamic_transform.cpp
1. Fixing typo which causes alias error in #1109 
2. updating error message checking in test in #1114
> fixing typo in range

- csrc/kernel_cache.cpp
- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- test/test_alias_analysis.cpp
This is a follow up to #1097. See code comments and unit tests for why it's needed. 
This PR also changed the way we traverse `Expr`s in a fusion. Previously, we traverse from only fusion inputs and collect only `TensorView`s that alias an input. Now, we traverse each Expr and capture all local aliases even if they are not an alias of any input. This change gives us more test coverage.
> No alias when an expanded broadcast IterDomain is transformed. 

- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul.h
- csrc/scheduler/no_op.cpp
- csrc/scheduler/no_op.h
- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner.h
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_inner_outer.h
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/normalization_outer.h
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/pointwise.h
- csrc/scheduler/reduction.cpp
- csrc/scheduler/reduction.h
- csrc/scheduler/registry.cpp
- csrc/scheduler/transpose.cpp
- csrc/scheduler/transpose.h
(1) add a static member function in each scheduler to return heuristics type avoiding the use of hard coded heuristics types.
(2) Add failed reason when scheduling non-connected graph.
> add a static member function in each scheduler to return heuristics type

- benchmark/main.cpp
We currently record GPU name as the "GPU" field in additional context. This means it is printed when the benchmark runs, and it appears as an item in the "context" section when using `--benchmark_out_format=json`. This change simply extracts more fields and populates the context in the same way. Example output:
```
2023-10-24T09:10:50-04:00
Running build/nvfuser_bench
Run on (64 X 3579.95 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x32)
L1 Instruction 32 KiB (x32)
L2 Unified 512 KiB (x32)
L3 Unified 16384 KiB (x8)
Load Average: 2.21, 1.29, 0.77
gpu_clock_khz: 1065000
gpu_compute_capability_major: 8
gpu_compute_capability_minor: 0
gpu_gmem_bytes: 84990623744
gpu_l2_bytes: 41943040
gpu_max_threads_per_block: 1024
gpu_max_threads_per_sm: 2048
gpu_mem_bus_width_bits: 5120
gpu_mem_clock_khz: …
```
> Record GPU properties as context in nvfuser_bench

- python_benchmarks/core.py
The current benchmarks use the default mode in `pytest-benchmark` which determines the number of rounds and iterations the target function is run based on the minimum and maximum time allowed per benchmark. In this mode, smaller benchmarks can take a long time to run if the maximum time is not set properly.
This PR switches the benchmarks to use `benchmark.pedantic` which allows us to control the number of rounds each benchmark is run for. This change also supports running a setup function before each round that allows us to clear L2 cache everytime before the target function is executed instead of only before running the benchmark.
This is important for smaller input sizes where L2 cache impacts the measured timings.
For example: The following timings show that in the previous mode, the …
> Switch benchmarking mode in `pytest-benchmark`

- csrc/executor.cpp
- test/test_gpu3.cpp
This surprisingly passes all unit tests. Is it crazy? From the code comment, it seems fine to just return proxy tensors. Do you remember why alias outputs were treated differently?
> pushTensorProxy except for trivial forwarding.

- python_benchmarks/global_params.py
- python_benchmarks/normalization.py
- python_benchmarks/test_layernorm.py
- python_benchmarks/test_softmax.py
- Uses `torch.cuda.empty_cache()` to avoid OOM errors when running a large number of benchmarks.
- Reduce maximum size of 4D tensor to run on A100 80GB.
> Fix OOM errors in `batchnorm` and `instancenorm`

- lib/dynamic_type/CMakeLists.txt
Seeing CI failure:
```C++
FAILED: lib/dynamic_type/CMakeFiles/test_dynamic_type_23.dir/test/ForAllTypes.cpp.o 
/usr/bin/clang++  -I/home/runner/work/Fuser/Fuser/cmake/../third_party/benchmark/include -I/home/runner/work/Fuser/Fuser/lib/dynamic_type/src -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/googletest/googlemock/include -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/googletest/googletest/include -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/flatbuffers/include -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googletest/include -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googletest -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googlemock/include -isystem …
```
> Disable C++23 test

- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/ir/builder.cpp
- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
- test/test_expr_simplifier.cpp
- test/test_gpu2.cpp
- test/test_gpu3.cpp
- test/test_gpu_tensorcore.cpp
- test/test_gpu_utils.cpp
- test/test_optimization_pass.cpp
- test/test_resize.cpp
This replaces uses of evaluate(Int, Bool, Double) with evaluate which returns a PolymorphicValue.
This also replaces the uses of get(Int, Bool, Double) with value().
This PR is the first of a number of them to fix the issue. In the final PR, the older get* and evaluate* methods will be removed.
Fixes https://github.com/NVIDIA/Fuser/issues/643
> Staged replacement of the use of evaluate* and get* with evaluate() and value() [1/N] 

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_graphs.cpp
- csrc/id_model/id_graphs.h
- test/test_gpu_indexing.cpp
I prefer to have `IdGraph` and `IdModel`, rather than `IdGraph` and `IdGraphs`
> Renaming IterDomainGraphs to IdModel

- tools/codediff/diff_report.py
Fixes a failure in a recent codegen diff CI job. `diff_lines` should never be None, but check it anyway.
> Fix crash in diff_report.py when ptx_diff_lines is empty

- csrc/executor.cpp
- csrc/executor.h
- csrc/kernel_cache.cpp
- test/test_gpu3.cpp
This PR removed several unnecessary special cases for trivial input forwarding and aliasing. In most cases, e.g. when computing tensor proxies, forwarded outputs and aliased outputs can simply be treated as regular outputs. 
Similar to #1141 , I verified the number of memory allocation requests for trivial input forwarding. 
```
$ PYTORCH_NO_CUDA_MEMORY_CACHING=1 nsys nvprof bin/nvfuser_tests --gtest_filter=*TrivialInputForwarding_FusionExecutor 2> /dev/null | grep cudaMalloc
1.1            89400          2    44700.0    44700.0      3607     85793      58114.3  cudaMalloc
```
> More cleanups around trivial input forwarding and aliasing.

- csrc/codegen.cpp
- csrc/compute_at_map.cpp
- csrc/dynamic_transform.cpp
- csrc/evaluator_common.cpp
- csrc/expr_simplifier.cpp
- csrc/fusion.cpp
- csrc/index_compute.cpp
- csrc/kernel.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/non_divisible_split.cpp
- csrc/tensor_view.cpp
This replaces uses of evaluate(Int, Bool, Double) with evaluate which returns a PolymorphicValue.
This also replaces the uses of get(Int, Bool, Double) with value().
This PR is the second  of a number of them to fix the issue. In the final PR, the older get* and evaluate* methods will be removed.
Fixes #643
> Staged replacement of the use of evaluate* and get* with evaluate() and value() [2/N]

- test/test_gpu3.cpp
- test/utils.h
Fixes #1142 
To make it easy to understand why this fix is necessary, I temporarily added two new tests just to expose the issue.
```
./bin/nvfuser_tests --gtest_filter="*CaptureTest*"
```
This should run `CaptureTest1` and then `CaptureTest2`. The former fails before stopping the capture, so with the current TOT, the issue of #1142 should happen. This PR makes sure the capture is stopped no matter if the test itself succeeds.
> Make sure stdout capture is stopped at the end of each test

- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/multidevice/pipeline_ir.cpp
- test/test_gpu1.cpp
Previously, the check was done only at `FusionExecutor::compileFusion`. However, the segmenter [skips non-tensor
outputs](https://github.com/NVIDIA/Fuser/blob/bce26ef4589066bd9765cea2ca61254031cd26a3/csrc/fusion_segmenter.cpp#L3286) before `FusionExecutor::compileFusion` sees them. This happens for users of the higher-level `FusionExecutorCache`.
The only exception is that we allow PipelineVal whose original value is a TensorView. 
Fixes #1172.
> Forbid non-tensor outputs.

- benchmark/matmul.cpp
This refactors the matmul benchmarks. Currently we have separate functions for each combination of number of warps per block and number of double-buffering stages. Instead, these are now parameters passed along in `benchmark_state`. This PR also provides names for the args so that instead of `Baseline_Matmul/no_quant_eagermode_TT_Legacy/2048/3456/512/manual_time ` we have
`Baseline_Matmul/eagermode_legacyshapes_TT/M:2048/N:3456/K:512/manual_time` and instead of `NvFuserScheduler_Matmul_4warp4stage/no_quant_nvfuser_4warp_NT_TIMM/512/2048/128/manual_time` we have `NvFuserScheduler_Matmul/nvfuser_timmshapes_NT/M:512/N:2048/K:128/warps:4/stages:4/manual_time `
> Refactor matmul benchmarks for better code reuse

- csrc/codegen.cpp
Fix the failing MATest.LoadCompleteTensor*D test by handling constant Array types.
> Fix TMATest by handling constant Array type

- CMakeLists.txt
Missed to add version.txt and we are not updating the version number during build.
> fixing dependency on generating nvfuser/version.py

- csrc/device_lower/analysis/predicate_elimination.cpp
This small change just avoids adding predicates when an `IterDomain` is split by a constant factor of 1. The predicate is not needed in this case since 1 evenly divides any extent. It also moves a repeated independent check outside a loop.
> Don't predicate trivial splits

- tools/codediff/compare_codegen.sh
The run name argument to `run_command.sh` is missing in the current version so the outputs are named like `custom_command_20231030_212134` instead of something more informative. This change uses the short commit like `17e4d4f` instead of the `custom_command` string.
> Label runs by git commit in compare_codegen.sh

- tools/codediff/diff_report.py
Note that this leaves comments for the purposes of viewing each PTX, but will not highlight differences in lines where only comments changed. This should avoid false positives in cases where CUDA code for both kernel and preamble is not changing but PTX is (cf. https://github.com/NVIDIA/Fuser/issues/1186#issuecomment-1787599192).
> Strip comments in PTX before diffing

- csrc/dynamic_transform.cpp
- python_tests/test_python_frontend.py
Fixes #1192.
In that repro we had the following dynamic Fusion:
```
Fusion before concretization:                                                                                                                              
Inputs:                                                                                                                                                    
T0_g[ iS0{i0}, iS1{i1} ], int64_t                                                                                                                        
T1_g[ iS2{i3}, iS3{i4} ], float                                                                                                                          
Outputs: …
```
> Allow some unmapped producers in `DynamicTransform::propagateProducerToConsumer`

- examples/sinh_extension/test.py
- examples/sinh_libtorch/main.cpp
This should cut down on more false positives in CI.
See this failing test for example that recently failed: https://github.com/NVIDIA/Fuser/actions/runs/6710458836
> Set random seeds in examples

- python_benchmarks/conftest.py
- python_benchmarks/core.py
Records additional GPU properties under `machine_info` when saving benchmark output.
Sample record from saved benchmark output:
```
"gpu_name": "NVIDIA RTX 6000 Ada Generation",
"gpu_compute_capability_major": 8,
"gpu_compute_capability_minor": 9,
"gpu_gmem_bytes": 51010207744,
"gpu_sm_count": 142,
"gpu_max_threads_per_block": 1024,
"gpu_smem_bytes_per_block": 49152,
"gpu_regs_per_block": 65536,
"gpu_clock_rate_khz": 2505000,
"gpu_l2_bytes": 100663296,
"gpu_mem_clock_khz": 10001000,
"gpu_mem_bus_width": 384,
"gpu_max_threads_per_sm": 1536,
"gpu_peak_bandwidth_gbps": 960.096
```
Closes #1140 .
> Record GPU properties in python benchmarks

- tools/codediff/compare_codegen.sh
- tools/codediff/templates/command_env_info.html
I previously put the order backwards so that the left-hand (should be old) commit was actually the new commit. That means that currently we show improvements in red and regressions in blue or green, for example. This change just reverses those to have more sane behavior.
> Reorder compare codegen

- csrc/fusion.cpp
- csrc/fusion.h
- csrc/fusion_segmenter.h
This is separated out from #1203 to keep the PR small.
> getOutputAlias also returns the AliasInfo.

- tools/codediff/diff_report.py
This should reduce false positives like those seen in http://nv/e5M/nvfuser_github_ci/codegen_diff_p10551865_j73238023_1698902733422536803_codediff_f450ece_ed879b8_custom_command_20231101_213723.html associated with #1176.
> Standardize mangled kernel name in ptx

- python_tests/test_python_frontend.py
So the test covers serialization. #1043 missed this.
> Use self.exec_nvfuser to run a fusion.

- csrc/device_lower/analysis/bank_conflict.cpp
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/unroll.cpp
- csrc/device_lower/pass/warp_reduce.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/validation.cpp
- csrc/ops/alias.cpp
- csrc/ops/arith.cpp
- csrc/ops/utils.cpp
Replaces uses of evaluate(Int, Bool, Double) with evaluate which returns a PolymorphicValue.
This also replaces the uses of get(Int, Bool, Double) with value().
This PR is the third of a number of them to fix the issue. In the final PR, the older get* and evaluate* methods will be removed.
Fixes https://github.com/NVIDIA/Fuser/issues/643
> Staged replacement of the use of evaluate* and get* with evaluate() and value() [3/N]

- CMakeLists.txt
- csrc/fusion.cpp
- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- csrc/optimization/mark_alias.h
- csrc/optimization/pre_segmenter.cpp
- csrc/scheduler/no_op.cpp
- test/test_alias_analysis.cpp
- test/test_no_op.cpp
Summary of changes: 
1. Made `Fusion::isNoOp` return true when all outputs are aliases. When `Fusion::isNoOp` returns true, device lowering emits no expressions, leading to an empty kernel. 
2. Made `AliasAnalysisResult` a class with `add` and `findRoot`. 
3. Added a pre-segmentation pass (`MarkAliasPass`) to call `aliasOutputToInput` for aliases detected by `AliasAnalysis`. 
4. Added unit tests.
> Generate an empty kernel when all outputs are aliases.

- tools/codediff/diff_report.py
- tools/codediff/templates/benchmark_plot.html
- tools/codediff/templates/header.html
- tools/codediff/templates/test_diff_section.html
I looked up d3.js last night and figured out how to automatically plot benchmark runtimes. Here is a truncated example from a comparison I ran yesterday: 
[diff.html.gz](https://github.com/NVIDIA/Fuser/files/13251353/diff.html.gz)
This also silences some very verbose output that snuck in from #1214.
> Add simple benchmark plot linking to test

- CMakeLists.txt
- csrc/executor.cpp
- csrc/executor.h
- csrc/executor_utils.cpp
- csrc/executor_utils.h
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- csrc/optimization/mark_alias.h
- csrc/optimization/pre_segmenter.cpp
- csrc/scheduler/no_op.cpp
- csrc/serde/fusion_cache.fbs
- python_tests/test_python_frontend.py
- test/test_alias_analysis.cpp
- test/test_no_op.cpp
Instead, use `kernel->ioAlias()`. I believe this doesn't break anything: 
1. Aliases added when building `FusionDefinition`s (e.g. by calling `fd.ops.batch_norm` or `fd.add_output(..., alias_input=...)`) are replayed by `RecordFunctors`. 
2. Aliases added during scheduling or later (e.g. by `MarkAliasPass`) are re-added by optimization passes or schedulers.
We already have `test_alias_output_to_input` for case 1, and this PR added `test_mark_alias_pass` for case 2.
> Don't serialize I/O aliases for FusionCache. 

- csrc/options.cpp
This changes cleans up options that apparently no longer have any effect. The following are removed:
- `DebugDumpOption::AssertMemoryViolation`
- `EnableOption::Complex`
- `EnableOption::ConvDecomposition`
- `EnableOption::GraphOp`
- `EnableOption::LinearDecomposition`
> Remove unused debug dump and enable options

- csrc/options.h
The TOT fails as:
```
terminate called after throwing an instance of 'nvfuser::nvfError'
what():  available_options.size() == static_cast<int>(OptionEnum::EndOfOption) INTERNAL ASSERT FAILED at "/raid/nmaruyama/debug2/csrc/options.cpp":24, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Invalid available option map
Exception raised from parseEnvOptions at /raid/nmaruyama/debug2/csrc/options.cpp:24 (most recent call first):
```
Unused options were removed in #1218. Those options need to be done with the structs as well.
> Fix a regression due to #1218

- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/validation.cpp
- csrc/index_compute.cpp
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/mma_type.cpp
- csrc/mma_type.h
- csrc/scheduler/mma_utils.cpp
- csrc/tensor_view.cpp
- runtime/tensorcore.cu
Matmul support was initially developed before we invented the concept "allocation domain". Without the concept of "allocation domain", our codegen has lots of limitations. One limitation is, the allocation is always based on the order of the rFactor domain, even for tensors allocated on shared memory or local memory. For example, if I have a tenor `[M, N]`, and I do some splits and reorder to get `[BIDx{M/2}, TIDx{N/3/5}, 3, 2, 5]` and the memory layout of the register will always be `[2, 3, 5]`, regardless of how we reorder these three numbers in leaf domain.
Due to this limitation, scheduling the layout of MMA output was fundamentally impossible. For example, in the [memory layout for Volta MMA](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#matrix-fragments-for-mma-m8 …
> Set the allocation domain of mma output as leaf domain and remove `accumulator_stride`

- csrc/executor.cpp
The signature of `allocOutputs` has changed in #1190 just before #1022 was merged. This PR fixes the merge
> Fix build error and merge PR #1190 and #1022

- csrc/executor.cpp
I.e. when it fails to produce an alias when alias analysis thinks it does.
> Error out when `ExpressionEvaluator` doesn't comply with alias analysis.

- csrc/executor.cpp
This is why I prefer `static` for local functions :) It's hard to figure out whether a function is in an anonymous namespace when that namespace spans across hundreds of lines.
> Remove a redundant anonymous namespace.

- csrc/executor.cpp
- csrc/kernel_cache.cpp
- test/test_gpu3.cpp
Trivial forwarding is merely a special case of aliasing.
This PR removes the FusionExecutor-level test for trivial forwarding. FusionExecutor doesn't run MarkAliasPass, which calls `aliasOutputToInput` to mark aliases. This however shouldn't be a problem for integration.
> Remove the special handling for trivial forwarding.

- CMakeLists.txt
- csrc/multidevice/device_mesh.cpp
- csrc/multidevice/device_mesh.h
add printing utilities for DeviceMesh, which is really useful for debug.
We define the method `std::string toString() const` as usually done. This class will later inherit from Val and so this function is required anyway
We define the `operator<<` so that gtest can print the DeviceMesh on which there is failure
> DeviceMesh printing utilities

- csrc/executor.cpp
- csrc/tensor_metadata.cpp
- csrc/tensor_metadata.h
This requires to expose inferAndValidateAllocationSizesAndStrides from csrc/tensor_metadata.h.
The check should trivially pass **at this moment**, because `MarkAliasPass` doesn't proactively change allocation domains. However, it'll be more useful with changes staged in https://github.com/NVIDIA/Fuser/compare/wjy/slice. 
I could combine this PR into `wjy/slice` but figured sending small PRs probably makes code review easier. Let me know otherwise!
> Check allocation domain and contiguity of aliased tensors.

- CMakeLists.txt
- test/rng_helper.h
- test/rng_kernels.cu
- test/test_rng.cpp
Just move more code from `rng_kernels.cu` to `test_rng.cpp`.
Because nvcc can not build pytorch:
```CUDA
[5/8] Building CUDA object CMakeFiles/nvfuser_tests_kernels.dir/test/rng_kernels.cu.o
FAILED: CMakeFiles/nvfuser_tests_kernels.dir/test/rng_kernels.cu.o 
/opt/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/clang -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -Dnvfuser_tests_kernels_EXPORTS -I/home/gaoxiang/Fuser3/cmake/../third_party/benchmark/include -I/home/gaoxiang/Fuser3/csrc -isystem /home/gaoxiang/Fuser3/cmake/../third_party/googletest/googlemock/include -isystem /home/gaoxiang/Fuser3/cmake/../third_party/googletest/googletest/include -isystem /home/gaoxiang/Fuser3/cmake/../third_party/flatbuffers/include -isystem …
```
> Don't include pytorch in `rng_kernels.cu`

- test/test_gpu_transpose.cpp
1. Replace NVFuserTest with TransposeTest.
2. Remove the deprecated `_CUDA` suffix.
> Cleanup test_gpu_transpose.cpp.

- python_benchmarks/test_transpose.py
Ports the `transpose` benchmark at: https://github.com/NVIDIA/Fuser/blob/main/benchmark/transpose.cpp
As compared to the CPP benchmark, the intermediate output is transposed instead of the input. 
The fusion definition when one of the inputs/output is transposed does not include the `transpose` op in the fusion due to optimizations.
> Transpose benchmark

- csrc/ir/nodes.cpp
- csrc/ir/utils.h
- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- csrc/options.cpp
- csrc/options.h
- nvfuser/contrib/nn/normalization.py
- test/test_alias.cpp
- test/test_gpu_transpose.cpp
Other changes:
1. Move `computePermutation` to `ir/utils.h` so it can be reused. 
2. Use `OptOutConstDispatch` to simplify `findAliasesFromExpr`. 
3. `AliasAnalysis` computes the preferred allocation domain and contiguity for each potentially aliased tensor. `MarkAliasPass` enforces that when no conflicts. 
4. Fix transpose tests so the fusion is not intercepted by the no-op scheduler. 
5. Fix `normalization.py` so it doesn't produce a symbolic, broadcast, stride-1 IterDomain. This would fail `validateAllocationSizesAndStrides`.
> AliasAnalysis handles `Set.Permute`. 

- python_benchmarks/test_gelu.py
- python_benchmarks/test_scale_bias_relu.py
- `Gelu` forward and backward: Ports https://github.com/NVIDIA/Fuser/blob/main/benchmark/gelu_backward.cpp
- `Scale-bias-relu` forward and backward: Ports SBR benchmark at https://github.com/NVIDIA/Fuser/blob/main/benchmark/scale_bias_relu.cpp.
> Activation benchmarks

- csrc/ops/alias.cpp
- csrc/ops/alias.h
- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- test/test_resize.cpp
This is easier for C++ unit tests to use and is closer to the Python API. I also moved some error checking code from `python_bindings.cpp` to the new variants.
> Add variants of `slice` that takes `int64_t`s.

- python_benchmarks/test_rmsnorm.py
`rms_norm` fwd and bwd benchmarks: Ports the benchmarks at: https://github.com/NVIDIA/Fuser/blob/main/benchmark/rms_norm.cpp and https://github.com/NVIDIA/Fuser/blob/main/benchmark/rms_norm_backward.cpp
> RMS Norm benchmark

- csrc/ir/internal_nodes.h
I believe they are always `TensorView*` given how `SliceOp`s are created:
https://github.com/search?q=repo%3ANVIDIA%2FFuser+create%3Csliceop%3E&type=code
> `SliceOp::in` and `::out` return `TensorView*` instead of `Val*`.

- csrc/fusion.cpp
- csrc/iter_visitor.cpp
- python_tests/test_python_frontend.py
Fixes #1270.
When a `Val` is removed from the `Fusion`, we currently first loop over `val->uses()` and remove them all from the Fusion. This seems correct at first glance, but it is incomplete since `val->uses()` actually only gives all **live** uses. When there is dead code in the `Fusion` that includes some uses of a val that is to be removed, we can wind up with an expression that holds an invalid pointer to the removed value in its `inputs()`. In #1270 this caused a segfault when the fusion was cloned since that will clone not only live objects but also these dangerous dangling dead ones.
This PR iterates over `exprs_` in `Fusion::removeVal()` in order to definitively find uses, dead or alive. Note that we still do not check attributes for the presence of an `attributeVal` equal to …
> Fix dangling dead uses in Fusion::removeVal

- CMakeLists.txt
- csrc/linked_hash_map.h
- test/test_linked_hash_map.cpp
This is separated from #1281 to keep the PR small.
> Add LinkedHashMap and unit tests.

- csrc/kernel_cache.cpp
This is useful for debugging pre-segmenter optimizations.
> Print fusion IR with transforms after concretization.

- csrc/ir/nodes.cpp
- test/test_gpu2.cpp
Evaluate method for `UnaryOp::Tanh`, `UnaryOp::Sigmoid`, `UnaryOp::Relu`, `UnaryOp::Gelu`, `UnaryOp::Exp`.
> Evaluate method for additional unary operators

- csrc/kernel.cpp
- csrc/kernel.h
This saves build time when we change only the implementation.
> Move implementation to cpp.

- csrc/fusion_profiler.cpp
The kernel name change that was recently introduced made the kernel name printing ugly.  Therefore, I fixed it.
Here is an example:
```bash
Benchmarking nanogpt-GPTConfig(name='', block_size=1024, seq_len=128, vocab_size=50304, n_layer=48, n_head=25, n_embd=1600, dropout=0.1, bias=True)-block
Fus#  NSegs CuEvtTm(ms) HstTm(ms) CmpTm(ms) KerTm(ms) EffBw(GB/s) %PeakBw   S-Seg# S-KerTm(ms) S-EffBw(GB/s) S-%PeakBw S-In(MB)  S-Out(MB) S-Smem[Dyn,Stat] S-Regs S-Grid           S-Block          S-KerName
0     1     307.870   307.861   260.239     0.021     1846.41     95.40      0       0.021       1846.41     95.40    13.120    26.231        [512, 16]     41     [2048, 1, 1]      [128, 1, 1] nvfuser_inner_persistent_f0_c1_r0_g0
1     1      81.898    81.887    79.508     0.011     2288.27 …
```
> Fixing `NVFUSER_PROF` printing after kernel name change.

- csrc/linked_hash_map.h
- test/test_linked_hash_map.cpp
This was reported by https://nv/e2E/74290095 and I was able to reproduce it using gcc 12.3. 
```
$ gcc --version
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
> Fix a potential use-after-free.

- test/test_linked_hash_map.cpp
1. Move `Key` and `Value` out of the `nvfuser::{anonymous}` namespace. 
2. Call them `CopyableKey` and `MovableValue` to clarify their properties.
3. Move the unused `MovableValue::operator==` method.
> Minor cleanups. 

- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- csrc/serde/fusion_cache.fbs
- csrc/serde/fusion_record_serde.cpp
- python_tests/pytest_input_generators.py
- python_tests/pytest_opinfos.py
- python_tests/test_python_frontend.py
I modified the two APIs that have a `shape` parameter to take either a `Vector`, `py::list`, or `py::tuple` such that the user can specify the shape as a combination of `Scalar`s, Python Integers, or a `Vector` in order to utilize the output of nvFuser's shape ops.  The API was partially already there by allowing the user to specify the output shape with just a List of `Scalar`s.  I also cleaned up the API such that each Random Distribution has its own Record Type instead of relying on distinguishing each type by a string.  I also made the code more modular so the same code is used to handle each distribution.
Old syntax:
```python
ops.uniform(minval: Scalar, maxval: Scalar, shape: List[Scalar], dtype: DataType, *, rng_seed: Scalar, rng_offset: Scalar) -> Tensor
ops.normal(mean: Scalar, …
```
> Modified `uniform` and `normal`'s Python APIs to fully support Dynamic Shape Definitions

- csrc/executor.cpp
This functionality was broken. Note that `fusion_id_` is commonly 0 despite having a non-zero global fusion count. This uses the global count to search through the comma-separated string instead.
> Fix `NVFUSER_EXTERNAL_SRC` after kernel name change

- csrc/fusion_segmenter.cpp
- test/test_alias.cpp
Fixes #1305 
Patches duplicated outputs handling in segmenter.
Adding tests to verify proper behavior with aliasing handling for duplicated outputs.
> Duplicated outputs patch

- csrc/ir/nodes.cpp
- test/test_no_op.cpp
- test/test_scalar_hoisting.cpp
- test/test_swizzle.cpp
1. Clean `test_swizzle.cpp`.
2. Clean `test_scalar_hoisting.cpp` -- Add `UnaryOpType::sin` to evaluator.
3. Clean`test_no_op.cpp`
> Clean unit tests

- csrc/transform_replay.cpp
- test/test_allocation_domain.cpp
> TransformReplay::replayCasP sets the right contiguity.

- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- test/test_alias.cpp
Partially taken from #1281 to keep that PR small.
> AliasAnalysis handles non-packed reshapes.

- csrc/executor.cpp
- tools/codediff/diff_report.py
- tools/codediff/run_command.sh
The change of default kernel IDs broke the link between PTX and CUDA dumped filenames, e.g. for a given kernel we might have `__tmp_kernel5.cu` and `__tmp_kernel_pointwise_f0_c1_r0_g0.ptx`. Also this re-uses kernel names so we wound up with far fewer PTX files than .cu files when running code diffs. This can be avoided by setting `NVFUSER_ENABLE=static_fusion_count` which will revert to name very similar to the old behavior. This PR sets that in `run_command.sh` in order to fix the code diff script, and ensures the filenames match, i.e. `__tmp_kernel5.cu` is now `__tmp_kernel_5.cu`.
> Fix codediff ptx

- csrc/optimization/mark_alias.cpp
This will hide `MarkAliasPass skipped ...` messages unless `NVFUSER_DUMP=pre_segmenter_logging` is enabled.
> Guard MarkAliasPass debug output

- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/transform_view.cpp
Currently, `MergeTransform` and `SplitTransform`, which are the classes used to perform reshape operations, do not re-use the splitting and merging operations used in scheduling, namely the static methods `IterDomain::{split,merge}`. This leads to needing to maintain changes in both as I recently found out when debugging #1174. We can actually already notice they have diverged with respect to `IndexType::GatherScatter` handling.
This PR simply calls the static `IterDomain` method from each of the reshape `*Transform` classes. Since those classes also need to set the rfactor-product flag on the produced `IterDomain`s, I added a flag to the static methods that is only used during reshape.
> Unify `IterDomain::split` with `SplitTransform` and similar for merge

- csrc/fusion_segmenter.cpp
- python_tests/test_python_frontend.py
Fixes #1301 
That issue demonstrated a case where `forwardInputs` could skip an expression, then also fail to add its outputs as a new input; the result is a segment without any input including the original unforwarded one. This change follows `UnaryOp` output uses only if those uses are themselves `UnaryOps`; otherwise we terminate and add that output as a new forwarded input.
> Only forward inputs whose single use is UnaryOp (segmentation)

- CMakeLists.txt
- test/test_fusion_profiler.cpp
- test/test_matmul_scheduler.cpp
- test/test_memory.cpp
- test/utils.h
Add forward epilogue fusions tests for HSS/HSH/TSS/TST precisions:
- bias
- relu, relu+bias,
- relu+aux, relu+aux+bias,
- gelu, gelu+bias
- gelu+aux, gelu+aux+bias,
Some tests are disabled (aux) due to missing support. To be added in a follow up PR.
Other changes:
- update tolerance and reduced problem size, k 1024 -> 248,
- update arch ranges for new tests,
- fix issue with test env being left dirty after profiler option tests,
> Matmul scheduler - tests for forward fusions

- runtime/memory.cu
- test/test_matmul_scheduler.cpp
- fix issue #1359,
- fix helper function, rvalue is not needed anymore,
- update Turing testing on matmul fused tests,
- manually verified on tu102 and tu104 devices,
> Fix ldmatrix helper issue for Turing kernels

- csrc/codegen.cpp
- csrc/macros.h
- csrc/mma_type.cpp
- csrc/mma_type.h
- csrc/scheduler/matmul_heuristic.h
`MacroType` is a enum that specifies which mma instruction to use. In the past, the underlying type for this enum is just the default given by C++. This PR changes this to `uint64_t`, and explicitly specify a value for each macro, so that the first two bits represent arch, the second two bits represent `m`. This makes it possible to pull the information of an enum without using a `switch`. I am trying to avoid `switch` because hopper have a lot of macros, and having to write all of them down is so boring...
This PR also adds hopper macros, although they are not implemented yet.
> Encode mma macro enum as `uint64_t` and define hopper macros

- csrc/scheduler/matmul.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- csrc/tensor_view.cpp
- test/test_gpu_tensorcore.cpp
- test/test_mma.cpp
There should be no behavioral change, just code movement and removal of unused code.
- `scheduleTuringMmaWarpOutput` is removed. Its code is moved to `scheduleMmaWarpOutput`. Because after reading the documentation of Hopper MMAs, I feel that Hopper can share the same schdule.
- `scheduleTuringOperandRead` is removed, and its code copied to `scheduleOperandRead`, similar as above.
- `scheduleLdMatrix` now takes an `MmaOptions`.
- `TensorView::applyMmaSwizzle` will call `WarpMmaSwizzler::scheduleLdMatrix` if the tensor is the consumer of ldmatrix, this removes the need for manually calling `WarpMmaSwizzler::scheduleLdMatrix` in unit tests.
> More cleanup on matmul schedule

- csrc/transform_replay.cpp
> Assert TransformReplay::replayCasP only replays allocation for Set.

- csrc/mma_type.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- test/test_matmul_scheduler.cpp
Enable support for forward epilogue fusions with aux output tensor
for HSS/HSH/TSS/TST precisions:
- relu+aux,
- relu+aux+bias,
- gelu+aux,
- gelu+aux+bias,
Enable tests prepared in https://github.com/NVIDIA/Fuser/pull/1191
Verified on: a100, ad102, ad104, tu102, and tu104
> Matmul scheduler - support for fusion with aux output tensors

- test/test_gpu_view.cpp
This avoids an OOM when running this test in CI on V100, which allocates 1GB of memory. See here for a job that failed in this way: https://github.com/NVIDIA/Fuser/actions/runs/7005955828/job/19056753333.
> Call maybeClearAllocator in FusionReshapeVectorize

- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/normalization_utils.h
Issue: `ReductionParams` was printed before its member variable `project_persistent_buffers` was set.
Fix: set `project_persistent_buffers` before print.
> fix 'print before set' in norm para

- csrc/codegen.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/device_lower/pass/predicate.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/predicate_compute.cpp
- runtime/memory.cu
- test/test_loop_rotation.cpp
Inline PTX does not have a builtin constraint for boolean values, we have to convert the boolean to int first, and use `setp.ne.b32` to put this int to predicate register. With this new feature added, we can now lower `cp.async` as `kir::Asm`. This feature is also needed for supporting Hopper MMA.
> Support boolean inputs for `kir::Asm` and lower `cp.async` as `kir::Asm`

- csrc/executor_params.cpp
- csrc/executor_params.h
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/reduction_heuristic.h
Issue: compile para is not printed when run with `NVFUSER_DUMP=scheduler_params`, missing the info of register count and index type which are important info to check the scheulder.
Fix:
Add method `toString` to `CompileParams` and use it to print scheduler paras.
Sample output when `NVFUSER_DUMP=scheduler_params`:
```
Launch Parameters: BlockDim.x = 96, BlockDim.y = 4, BlockDim.z = -1, GridDim.x = -1, GridDim.y = 108, GridDim.z = -1, Smem Size = 0
Compile Parameters: index_type = int, maxrregcount = 168, enable_magic_zero = 1, enable_ptxas_verbose = 0
```
> add toString to CompileParams

- csrc/python_frontend/fusion_record.h
This would allow us to temporarily ignore the performance issue resulted from the lack of support on alloc_domain in vectorization support.
> Skip stride_order when it is a canonical row-major storage.

- csrc/fusion_segmenter.cpp
This change removes a redundant check and makes it explicit that `to_visit` includes only `UnaryOp`s. The comments are slightly modified for clarity as well.
> Clean up SegmentCandidateFinder::forwardInputs()

- csrc/python_frontend/fusion_record.h
- csrc/tensor_view.cpp
- test/test_allocation_domain.cpp
1. moved the skip trivial allocation logic on inputs from `TensorRecord` to `TensorViewBuilder`;
2. updated comment with issue/TODO linked.
3. Added c++ test coverage
> Alloc patch follow up

- test/test_gpu_view.cpp
This temporarily fixes #1407 but a longer-term solution would be to alter our cmake config so that each test file corresponds to a different test executable, in order to keep the CUDA context size small as we generate thousands of kernels that are not removed until the process terminates.
> Reduce size of input in FusionReshapeVectorize test

- CMakeLists.txt
- test/test_gpu3.cpp
- test/test_iter_visitor.cpp
Also, simplify the tests using gmock matchers.
> Move IterVisitor tests to a separate file.

- csrc/executor_utils.cpp
Without this change, we can not use mma instructions for hopper.
See https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#ptx-module-directives-target
> Target architectures with suffix “a”, such as `sm_90a`, include architecture-accelerated features that are supported on the specified architecture only, hence such targets do not follow the onion layer model. Therefore, PTX code generated for such targets cannot be run on later generation devices. Architecture-accelerated features can only be used with targets that support these features.
> Use `90a` target for hopper

- csrc/index_compute.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/mma_type.cpp
- csrc/mma_type.h
- csrc/tma.cpp
- csrc/tma.h
Because it is used not only in TMA
> Move `TensorMapSwizzle` to `mma_type.h` and rename as `MmaInputSmemSwizzle`

- csrc/executor.cpp
- csrc/fusion.cpp
- test/test_alias.cpp
- test/test_gpu_utils.cpp
1. disabling duplicated inputs (user registering input multiple times). It's scary to think about what the expectation is, when user register a single input tensor multiple times. Disabling it for now.
2. adding a test case to verify the proper behavior for duplicated output, which is supported by codegen.
> Disabling duplicated inputs

- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
Sample debug output:
```
$ NVFUSER_DUMP=pre_segmenter_logging bin/nvfuser_tests --gtest_filter=*AnotherOutput
...
Alias analysis result:
T3_g[ iS13{5}, iS12{( 2 * 3 )} ] is an alias of T2_g[ iS11{( 2 * 3 )}rf, iS8{5} ] if its layout is <allocation=[iS12{( 2 * 3 )}, iS13{5}], contiguity=[t t]>
T2_g[ iS11{( 2 * 3 )}rf, iS8{5} ] is an alias of T1_l[ iS3{2}, iS4{3}, iS5{5} ] if its layout is <allocation=[iS11{( 2 * 3 )}rf, iS8{5}], contiguity=[t t]>
```
> Print the alias analysis result when debugging.

- csrc/executor.cpp
Inputs are already bound at
https://github.com/NVIDIA/Fuser/blob/6b9e5b65f413338519dabd8e00c6ee3ec85c526e/csrc/executor.cpp#L1656 and
https://github.com/NVIDIA/Fuser/blob/6b9e5b65f413338519dabd8e00c6ee3ec85c526e/csrc/executor.cpp#L1268.
Cleanup for #1401
> Remove unnecessary input binding.

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/validation_utils.cpp
- csrc/id_model/validation_utils.h
- csrc/val_graph.cpp
- csrc/val_graph.h
Refactoring the almost exact graph construction. 
- The main logic is moved from ValGraph to IdModel
- Extended the validator to support the almost exact graph
> IdModel: cleanup almost exact

- test/test_iter_visitor.cpp
- test/test_segmentation.cpp
I forgot to `// clang-format on` after the license.
> Enable clang-format.

- CMakeLists.txt
Without this, I couldn't build nvFuser with Clang 14, which doesn't enable c++17 by default unlike gcc 11.4. I don't understand why I had to turn it on. I expected cmake would automatically figure out the default C++ standard and omit `-std=c++17` only when it's safe.
Wdyt?
> Turn on CXX_STANDARD_REQUIRED.

- csrc/optimization/alias_analysis.cpp
AliasAnalysisResult is usually printed with fusion IR so the short names are indicative enough.
> Print the shorter name in alias analysis results.

- csrc/transform_iter.cpp
- csrc/transform_iter.h
Taken out of #32. The `ForwardingInfo` class is going to be used from `IdModel`, so it's moved to the header file
> Minor cleanup of transform_iter

- tools/codediff/diff_report.py
- tools/codediff/templates/test_diff_section.html
Issue: When number of segments in a fusion is reduced from 2 to 1, the codegen diff script tries to compare 2 kernels.
Fix: only compare the first N kernels, where `N = min(number of kernels in old code, number of kernels in new code)`
> fix codegen diff failure when number of segments in a fusion is changed

- CMakeLists.txt
This was accidentally removed by #1462.
> Add test_segmentation.cpp back to CMakeLists.txt.

- csrc/optimization/alias_analysis.cpp
- test/test_alias.cpp
My #1295 changed some tests in the wrong way so this bug has been hidden since then.
> Fix a bug related to expanded broadcast IterDomains.

- python_benchmarks/test_gelu.py
- python_benchmarks/test_scale_bias_relu.py
The current benchmarks use 3D and 4D tensor (for parity with CPP benchmarks), however for benchmarking purposes, there is no specific requirements for the inputs to be 3D/4D. 
Switching to 2D tensors will also reduce time as we start to increase the number of inputs as pointed by @jacobhinkle earlier (https://github.com/NVIDIA/Fuser/pull/1199#discussion_r1387385506).
> Switch to 2D tensors in `gelu` and `scale-bias-relu` benchmarks.

- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- test/test_alias.cpp
This prepares #1478 for landing. We'll need to use AliasAnalysis before segmentation and during scheduling, so it's good to move common logic into AliasAnalysis.
> Move some logic from MarkAliasPass to AliasAnalysis.

- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/mark_alias.cpp
- test/test_alias.cpp
Currently, `MarkAliasPass` skips an output when its allocation domain is set at all. This PR makes it smarter to check compliance.
This PR prepares #1478 for landing. Before segmentation, we'll run alias analysis on the un-segmented fusion and mark layouts for aliasing. During scheduling, we'll run alias analysis again on segmented fusions and have to recognize the preferred layout is compliant with the previously marked layout.
> Relax the allocation domain constraint. 

- csrc/executor.cpp
- csrc/expr_evaluator.h
- test/test_alias.cpp
- test/test_gpu3.cpp
I also tried using output-to-output aliases to handle this. It didn't work well because `getOutputAlias` couldn't distinguish the same `Val*` at different indices. To allocate a tensor for the first output but not the second, I would still end up with something like `outputs_map`.
This PR removes the ad-hoc `outputs_map` in favor of `ExpressionEvaluator`. It also moves trivial-input-forwarding tests to `test_alias.cpp` to make `test_gpu3.cpp` (slightly) smaller.
> Handle duplicated outputs using ExpressionEvaluator.

- csrc/id_model/id_model.cpp
- csrc/id_model/validation_utils.cpp
- csrc/id_model/validation_utils.h
- csrc/val_graph.cpp
While working on comparing the Permissive graph with the CA Permissive map, I found one thing that I think should be considered inconsistency. When backward propagating mappings through a Merge expr, we require at least one of the input domain pairs should be already mapped or have equal extents, which makes sense, but the current code only checks the extents of one ID out of each ID group, which is fine with the Exact graph but in the case of the Permissive graph, each ID group may consist of domains that have different extents, so I think we would also need to check all domains in the group, and if there's one matching pair, we should allow propagation. 
This PR also adds the validation of the Permissive graph. It does not pass yet as the CA map does not map the compliment IDs.
> Fix mapping propagation through backward merge

- csrc/optimization/alias_analysis.cpp
- csrc/optimization/alias_analysis.h
- csrc/optimization/optimize_layout.cpp
- csrc/scheduler/mark_aliases.cpp
This removes the `const` qualifier from map values but not keys. It's getting more often to retrieve the source of an alias and modifies it, e.g., #1503.
> Drop some const qualifiers to avoid `const_cast`s.

- python_tests/test_python_frontend.py
The python frontend test `test_deterministic_random` was originally introduced in #546. It actually printed mismatches, but did not fail the test in those cases. It turns out it has been failing but it went unnoticed. This change unmasks that allclose check.
The test had assumed the offset should be advanced by 4 for every 4-byte RNG op. This is how PyTorch handles offsets. However, we base our offset on uint4, so our offset corresponds to 1/4 the pytorch offset. This means we should only advance by one for each op in the test. Doing this silences the warnings (which are now errors).
See https://github.com/NVIDIA/Fuser/blob/main/csrc/rng.cpp#L54-L64 for more info on our offsets and their equivalents in PyTorch.
> Fix test_deterministic_random

- csrc/fusion_profiler.cpp
- test/test_fusion_profiler.cpp
The scope of changes:
- implementation fix: `stop()` won't now access uninitialized data,
- tests fix: make sure that profiler state is defined at the beginning and at the end of each test case,
> FusionProfiler - fixes in implementation and tests

- test/test_mma.cpp
During development, I feel that it is super helpful to set one matrix as identity, and set another matrix as arange, and print out the result. By reading the result, I can easily tell the memory layout. I think this debugging technique is so helpful that it worth committing it to our codebase for future reference.
> Add utilities for debugging MMA

- python_benchmarks/test_batchnorm_bwd.py
- python_benchmarks/test_batchnorm_fwd.py
- python_benchmarks/test_gelu_bwd.py
- python_benchmarks/test_gelu_fwd.py
- python_benchmarks/test_instancenorm_bwd.py
- python_benchmarks/test_instancenorm_fwd.py
- python_benchmarks/test_layernorm_bwd.py
- python_benchmarks/test_layernorm_fwd.py
- python_benchmarks/test_rmsnorm_bwd.py
- python_benchmarks/test_rmsnorm_fwd.py
- python_benchmarks/test_scale_bias_relu_bwd.py
- python_benchmarks/test_scale_bias_relu_fwd.py
- python_benchmarks/test_softmax_bwd.py
- python_benchmarks/test_softmax_fwd.py
Tests within the same pytest file run in the same process. Pytest memory consumption increases with the number of tests, so splitting the individual benchmarks to different files to control memory usage.
> Split `fwd` and `bwd` benchmarks into different files

- csrc/multidevice/communication.cpp
Since the CommunicatorBackend argument is optional, it can be null, in which case the default backend is returned. Then we need to dynamic cast the backend to check if it is nccl
> fix detection of nccl backend in reduce_oop_

- csrc/codegen.cpp
- csrc/tma.cpp
The scope of introduced changes:
- modify the string representation of TensorMap object type for kernel
lowering phase,
- fix the type of TensorMap local variables in kernel (aliases),
- add local helper tool to detect TensorMap data type,
> Updated the usage of TensorMap in generated kernels

- tools/codediff/compare_codegen.sh
- tools/codediff/diff_report.py
- tools/codediff/templates/test_diff_section.html
This should fix the `assert self.current_test is not None` errors we see in CI sometimes.
Also, the default reference git ref was changed from `origin/main` to `git merge-base origin/main HEAD`. This can help when a branch is not up-to-date with upstream, since it prevents comparing against commits that have not yet been merged into the branch.
I also added a warning when the number of kernels in a test changes. We still compare the first N kernels where N is the minimum of the number of kernels between the two runs, but now if that number differs we give a warning. This helps alert us that we might not be comparing apples to apples and we should look at that specific test in more detail manually.
> Fix bug in codediff for pytest

- benchmark/matmul.cpp
Note that these should be re-enabled during or after #1510, since that should fix the slow compilation speeds.
Fixes #1389.
> Disable split-K benchmarks temporarily

- benchmark/matmul.cpp
This fixes a benchmark failure with large inputs due to hardcoded Int32 index type.
> Set index_type properly in matmul benchmarks

- python_benchmarks/core.py
- python_benchmarks/normalization.py
- python_benchmarks/test_gelu_bwd.py
- python_benchmarks/test_gelu_fwd.py
- python_benchmarks/test_layernorm_bwd.py
- python_benchmarks/test_layernorm_fwd.py
- python_benchmarks/test_rmsnorm_bwd.py
- python_benchmarks/test_rmsnorm_fwd.py
- python_benchmarks/test_scale_bias_relu_bwd.py
- python_benchmarks/test_scale_bias_relu_fwd.py
- python_benchmarks/test_softmax_bwd.py
- python_benchmarks/test_softmax_fwd.py
- python_benchmarks/test_transpose.py
This PR clears CUDA cache at the start of each test instead of at the end. This avoids CUDA OOM errors in tests due to any remaining allocated memory from the previous test.
Cache is only cleared when reserved memory is greater than 80% of GPU memory or there is allocated memory at the start of the test. This significantly reduces the overhead associated with gc collection/clearing cache.
Credit: @jacobhinkle.
Resolves GPU OOM errors in Issue #1537.
> Clear CUDA cache before running a test

- python_tests/test_python_frontend.py
Fixes #1277. The bug was actually fixed in #840, but the comment was inaccurate.
> Clean up comment in test_issue1277

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/id_model/validation_utils.cpp
- csrc/id_model/validation_utils.h
- csrc/val_graph.cpp
- csrc/val_graph.h
Added the Permissive graph. The main logic is at `IdModel::buildPermissiveMap`. 
While validating the generated graphs by comparing them with the corresponding ComputeAtMap Permissive maps, some mismatches were found. It turned out that `ValGraph::exprsMap` needed more thorough comparisons when back propagating Merge expressions. See `ValGraph::mapMergeBackward`.
> IdModel: Add the Permissive graph

- csrc/device_lower/pass/alias_memory.cpp
- test/test_smem_reuse.cpp
Fix shared memory reuse in softmax by:
(1) allow `expand` op and treat it similar to broadcast, that is `require matched iterdomains for reuse`
(2) Allow non-vectorized tv to reuse vectorized tv.
see https://github.com/NVIDIA/Fuser/issues/633 and https://github.com/NVIDIA/Fuser/issues/1562
> allow expand op and adjust vectorization check in memory alias

- csrc/alias_analysis.cpp
The comment already explained when an IterDomain is missing, but it's even better to verify/enforce that in code.
> Cleanup: make the check stricter.

- test/test_segmentation.cpp
As a follow-up to our previous meeting about segmentation for multi-device, I wrote this PR showing how to surround a sharding expression with `segment_set`s. This way, a sharding expression becomes its own segment without changing the current segmentation algorithm. I expect a pre-segmenter pass to add such `segment_set`s. See [`MarkAliasPreparePass`](https://github.com/NVIDIA/Fuser/blob/101530ec09a7eab9937f277715be0e3ecc1478b6/csrc/optimization/mark_aliases_prepare.cpp) for an example. I believe this is good enough for segmenting out CPU-initiated communication.
> A test that surrounds a sharding expression with `segment_set`s.

- csrc/dynamic_transform.cpp
- test/test_dynamic_transform.cpp
Fixes #1572
In that case, `concretizeReshape` is replacing some extents in the new shape, such as `(nvfuser_index_t)16` with non-constant values like `i0`. This leads to a downstream expression that originally was constant `0` to be non-constant, so it cannot be picked up by `RemoveEmptyPass`. This PR avoids concretizing constant extents with non-constants. This should be safe since even if those tensors are segmentation edges, we will not lose any scalars because the extent is constant so there are no free scalars to lose.
> Prevent replacing constant extents with non-const in concretization

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/utils.cpp
- csrc/utils.h
This is a follow-up to https://github.com/NVIDIA/Fuser/pull/1584#discussion_r1441862342. 
This also comes with a refactor to `mergeContiguity` so `handle(ViewOp)` can use `mapInLayoutToOutRoot`. I can split that out if you find it hard to review.
> Factor out code that maps input layout to output root.

- csrc/codegen.cpp
The scope of the changes prepared in this MR:
- replaced `unordered_map` with `unordered_set` for tracking what values have allocations during code generation phase; the stored kir::Allocate objects were unused
Note:
Removed change that added `ArrayConstruct` to allocations tracking infra.
For it to work we need to add `kir::Allocate` Expr to the kernel expression, which was missing.
> [CodeGen] Improvements in allocations' tracking

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/optimization/mark_aliases_prepare.cpp
- test/test_alias.cpp
This PR also refactors `AliasAnalysisResult::finalize` so that the `fusion` parameter is unnecessary. 
Question to reviewers: is it OK to leave alias-enabling allocation domains on intermediate tensors? I could remove them but would need to distinguish those added by users from those by `MarkAliasPreparePass`.
> Set allocation domains of intermediate tensors for aliasing.

- csrc/dispatch.cpp
- csrc/dispatch.h
- csrc/expr_simplifier.cpp
- csrc/expr_simplifier.h
This PR moves the `assoc_comm::FlattenedAssocCommOp` class declaration to the `expr_simplifier.h` header file. It also adds the appropriate `handle` functions to `OptOutConstDispatch` and `OptOutDispatch`, so it works with functions like `StmtSort::getStmts`. This PR is a prerequisite for https://github.com/NVIDIA/Fuser/pull/1566 which aims to serialize the entire IR.
> Move `assoc_comm::FlattenedAssocCommOp` class declaration to its header file

- csrc/polymorphic_value.h
Otherwise, toString on a monostate fails with "Can not print St9monostate : incompatible type".
> Fix printing a monostate (i.e. an empty variant).

- csrc/executor.cpp
- csrc/executor.h
- csrc/kernel_cache.cpp
- csrc/kernel_cache.h
- python_tests/test_python_frontend.py
This PR sets the `CompileOptions` in the `FusionExecutor` during deserialization to the appropriate device. It fixes errors encountered in a distributed setting.
> Set device index during deserialization.

- CMakeLists.txt
We'll migrate python binary to those provided in pypa manylinux images. This change in CMakeLists.txt is needed because some libpython developer library is not included.
Ref for similar changes: https://github.com/pypa/manylinux/issues/484, https://github.com/NVIDIA/TransformerEngine/pull/586
> Use Development.Module for find_python

- python_benchmarks/global_params.py
Numpy ints are not JSON serializable. The 2D inputs use numpy array for the hidden range which was causing the benchmark data to not be stored in the database with the error:
```
{
"status": "Bad Request",
"validation-failures": {
"l_sizes_GtsMcQ": [
16384,
"UNSERIALIZABLE[36864]"
]
}
}
```
> Convert benchmark output to JSON serializable format

- csrc/scheduler/mma_utils.cpp
This PR should have no behavioral change, it is just better code organization. Currently, in the main branch, for Hopper MMA operand B, `transpose2` is handled like
```C++
if (transpose2) {
// code A
} else {
// code B
}
```
this PR refactors this part to pull out the code that can be shared between code A and B.
> Simplify `WarpMmaSwizzler::scheduleOperandRead` for Hopper

- csrc/ir/nodes.cpp
- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- lib/dynamic_type/test/binary_ops.cpp
- test/test_evaluator.cpp
Fixes https://github.com/NVIDIA/Fuser/issues/1570
This PR adds a variant of comparison operators that returns `DynamicType`. This new variant is not implemented as operator overloading, instead, users need to explicitly call its function. The reason for not overloading it as operators is because it makes more sense to make comparison operators return bool, so that code like
```C++
PolymorphicValue pv = 2;
if (pv > 0) {
blabla();
}
```
will seamlessly work.
> [DynamicType] Add named comparison ops returning dynamic type

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- test/test_pipeline.cpp
Add two utils functions and tests:
```
// Returns the subset of tvs which elements have the same multi-device sharding
// as ref
std::unordered_set<TensorView*> haveDifferentSharding(
TensorView* ref,
std::unordered_set<TensorView*> tvs);
// Returns whether an Expr embbeds multi-device resharding
bool isResharding(Expr* expr);
```
> Multidevice utils: haveDifferentSharding and isResharding

- csrc/disjoint_set.h
- csrc/id_model/id_model.cpp
- csrc/id_model/to_string.cpp
- csrc/id_model/visitor.cpp
- csrc/val_graph.cpp
- csrc/val_graph.h
Simplify `getDefinitions()` and `getUses()` of `ValGraph` as they always have mappings for any valid ValGroups.
> [IdModle] Val graph cleanup

- csrc/device_lower/lower2device.cpp
- csrc/id_model/to_string.cpp
- csrc/val_graph.cpp
- csrc/val_graph.h
This is just code simplification as `getDefinitions` and `getUses` don't need to return pointers as there should always be mapped `ExprGroup`.
> [IdModel] valgraph cleanup

- csrc/optimization/mark_aliases_prepare.cpp
- test/test_alias.cpp
In #1579, I should have checked `tv` is a fusion output as well so the behavior remained the same.
> Fix #1646, a bug introduced by #1579.

- csrc/fusion_segmenter.cpp
when segmented due to `hasSegmentHints`, print out why.
> print has segment hints

- csrc/executor_utils.cpp
When we arrive at a CUDA compilation error, we print the kernel along with the entire preamble, which is thousands of lines. This blows away the scrollback buffer in our terminal and is not typically very useful.
> Don't print entire CUDA source on compile error

- csrc/ir/interface_nodes.h
- csrc/tensor_view.cpp
It's not exposed by API and not used by us.
> Delete unused constructor.

- csrc/device_lower/pass/alias_memory.cpp
The purpose of this change is to update the expected scope in which smem placeholder for mbarrier objects are alive before the memory can be reused. Life of such variable starts with its initialization, and ends with its invalidation.
The core change is switching from last write to last read for mbarrier invalidate helper function call.
> [Hopper] MBarrier storage scope update

- csrc/scheduler/registry_utils.cpp
I don't know why it was added, but it looks unnecessary. An alias TV (whether it's a pointer arithmetic or an in-place update) should be connected to some input TV via Exprs.
> Remove unnecessary code.

- csrc/device_lower/lower2device.cpp
- csrc/device_lower/validation.cpp
- csrc/device_lower/validation.h
- csrc/dynamic_transform.cpp
- test/test_dynamic_transform.cpp
This change inspects expressions at concretization to check for reductions and Welford ops. When finding those, we look for unexpanded broadcasts in the axes being reduced. If we find any, we re-run the appropriate op with the concretized input, to ensure that the output is squeezed exactly as it would be were the fusion not dynamic.
Fixes #1667
> Insert squeeze before trivial reductions at concretization

- csrc/device_lower/pass/expr_sort.cpp
- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/fusion_segmenter.cpp
- csrc/kernel_cache.cpp
- test/validator.h
This makes `getOutputAlias` easier to use. This will eventually help #1669 represent outputs that require evaluation but are not an alias. For that, we'll need to
1. Rename `Alias*` to `Allocation*`.
2. Rename `AllocationType::PointerArithmetic` to `AllocationType::Evaluate`. 
3. When a MmaOp segment needs ATen evaluation, set its output allocation to `.type=AllocationType::Evaluate,aliased_io=nullptr`.
> Move `aliased_io` into `AliasInfo`. 

- csrc/device_lower/validation.cpp
I vectorized fusion inputs by accicent and vectorization validation crashed when access the tv definition which doesn't exist.
print a more friendly err msg, if this happened.
> in vectorization validation, add err msg if tv has no definition

- csrc/dynamic_transform.cpp
- python_tests/test_python_frontend.py
We register extents for concretization when we concretize reshape. In order to do that, we line up `IterDomain`s in the symbolic reshaped TV and the new, concretized one. In cases where the concretized reshape is trivial, such as when the output shape is the same as the input, we do not create a new TV. In those cases, we will have the input to the original `ViewOp` as the concretized output. That input TV might have reduction domains, as in the provided test, in which case we need to filter those out when doing this alignment. This small PR just implements that filtering.
Fixes #1691.
> Accomodate Reduction IterDomains when concretizing reshape extents

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
Implements the `evaluate` method for `MmaOp`. 
The `evaluate` method assumes:
1. `MmaOp` is preceded by `broadcast`.
2. The inputs (non-broadcasted) are 2D.
3. The inputs to the `matmul` API and the broadcasts will be `[M, K] x [K, N]` which is the same as PyTorch.
This is intended to be used in default matmul scheduling .
(Issue #1669)
> `MmaOp::evaluate` method

- python_benchmarks/conftest.py
- python_benchmarks/test_softmax_bwd.py
- python_benchmarks/test_softmax_fwd.py
Adds `torch.compile` and `eager` baseline benchmarks to be used in weekly benchmark runs.
Issue #1668.
Update:
Building off of @jacobhinkle's suggestion:
1. `torch.compile` and `eager` mode are combined in a single benchmark function using parametrization.
2. By default, only nvfuser benchmarks are run. To enable eager/compile, the flags `--benchmark-eager` and `benchmark-torchcompile` are used. 
I'll update the wiki to describe and detail benchmarking options.
Future changes:
In a separate PR, I plan on renaming `disable-benchmarking` to `disable-nvf-benchmarking` since we are adding more executors.
> `torch.compile` and `eager` benchmarks for `softmax`

- test/test_tensor_factories.cpp
As a follow up to
https://github.com/NVIDIA/Fuser/pull/1696#discussion_r1473341455.
> Add a test for fusions with no inputs.

- csrc/python_frontend/fusion_cache.h
- csrc/python_frontend/python_bindings.cpp
By just removing entries when it fills up.
> Double the size of the fusion cache to workaround a CI issue.

- csrc/multidevice/lower_communication.cpp
Currently, a reduction is lowerable to a communication iff only one axis is reduced and this axis is sharded across devices on the **producer** side.
Before this patch, we would mistakenly check that the axis is sharded on **consumer** side, which led to some runtime assert error.
> Check that the reduced axis is sharded on producer in isLowerableToCommunication

- csrc/multidevice/lower_communication.cpp
- csrc/multidevice/lower_communication.h
isLowerableToCommunication is used in a few places to print error messages or short-circuit loops. Those places appear to be places that are intended to largely be used behind the distributed path. It's easier to just define the API instead of trying to conditionalize all the use sites and invent non-USE_DISTRIBUTED behavior.
> Add blank impl of isLowerableToCommunication.

- csrc/fusion.cpp
- csrc/fusion_segmenter.cpp
- csrc/fusion_segmenter.h
- csrc/kernel_cache.cpp
- test/test_gpu2.cpp
- test/test_pipeline.cpp
Add an option in the segmenter to segment resharding Expr in separate singleton segment.
To trigger it, set the segmenter's options as follows:
```
SegmentCandidateFinderOptions options{
.run_translate_welford = false,
.run_combine_reductions = false,
.run_herrmann_merge = true,
.run_final_merge = true,
.only_segment_resharding_exprs = true};
```
and use the segmenter as follows with any (possibly dummy) inputs:
```
KernelArgumentHolder dummy_inputs;
auto segmented_fusion = SegmentCandidateFinder::segment(std::move(fusion), dummy_inputs, options);
```
If `only_segment_resharding_exprs` is set to `false` (which is the case by default), the behavior of the segmenter is unchanged.
We also provide a quite wide testing suite to validate our implementation.
Resharding Exprs need to be handled …
> Multidevice segmenter

- csrc/ir/nodes.cpp
- csrc/ops/alias.cpp
- csrc/ops/alias.h
- csrc/ops/arith.cpp
- python_tests/test_python_frontend.py
- test/test_gpu3.cpp
See comment in arith.cpp for details.
One controversial change here is to allow squeezing expanded dimensions, both in our IR's `SqueezeOp` and in the user-facing functions `squeeze`. This results in actually removing those dimensions. This behavior diverges from PyTorch, whose `squeeze` command will ignore requested squeezes if the size is not 1 regardless of whether that dimension is expanded. I'm happy to discuss this change and potentially take another course, but I think we do need to be able to remove expanded axes (see https://github.com/NVIDIA/Fuser/issues/1174#issuecomment-1851998818 for another case where I encountered this limitation).
Fixes #1678
> Convert reduction of expanded dims to squeeze

- csrc/ops/alias.cpp
- csrc/ops/alias.h
- csrc/ops/arith.cpp
- python_tests/pytest_input_generators.py
- python_tests/test_python_frontend.py
This fixes current failures in `pytest_ops.py -k squeeze` and some integration failues.
This restores our previous semantics for squeeze, which **do not match PyTorch**. Namely, if squeeze is provided a dimension that cannot be squeezed, we will always raise an error.
> Fix squeeze-related errors

- CMakeLists.txt
- csrc/multidevice/allocator.cpp
- csrc/multidevice/allocator.h
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- csrc/multidevice/lower_communication.cpp
- csrc/multidevice/lower_communication.h
- csrc/multidevice/pipeline.cpp
- csrc/multidevice/runtime.cpp
- csrc/multidevice/runtime.h
- setup.py
- test/multidevice.cpp
- test/multidevice.h
- test/test_multidevice_communications.cpp
- test/test_multidevice_pipeline.cpp
- tools/gen_nvfuser_version.py
Adds `NVFUSER_DISTRIBUTED` macro and updates multidevice #ifdef guards to use `NVFUSER_DISTRIBUTED` instead of `USE_DISTRIBUTED`.
This will decouple nvfuser's distributed support from from Pytorch's `USE_DISTRIBUTED` macro so that our CI can build nvfuser without multidevice support.  `NVFUSER_DISTRIBUTED` is dependent `USE_DISTRIBUTED` being defined. 
From `setup.py` add `--build-without-distributed` to build without multidevice support.
FYI @samnordmann
> NVFUSER_DISTRIBUTED instead of USE_DISTRIBUTED

- csrc/python_frontend/fusion_cache.cpp
- csrc/python_frontend/fusion_cache.h
- csrc/python_frontend/python_bindings.cpp
- nvfuser/__init__.py
Currently, automatic serialization saves a single cache regardless of the number of devices. In a distributed setting, each process restores its fusion cache from the same common workspace. However, this workspace only contains the CUDA kernels for a single device. The remaining processes must recompile the kernels for their devices.
A separate process is created for each device with `ddp` or `fsdp` and each process contains a separate `FusionCache`. This PR associates each fusion cache with its local rank in a distributed setting, allowing automatic serialization to create a separate workspace for each device. During deserialization, each process loads the workspace associated with its local rank.
> Associate each fusion cache with its local rank in distributed setting.

- python_tests/test_normalization.py
skip failing test.
Please enable it once we patch #1728
> make ci green again

- csrc/device_lower/pass/expr_sort.cpp
- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/ops/normalization.cpp
- csrc/python_frontend/fusion_state.cpp
- csrc/scheduler/mark_aliases.cpp
- test/test_alias.cpp
This PR is strictly for renaming `AliasType` -> `AllocationType`.
Follows PR #1687.
The next PR will add `AllocationType::Evaluate` to mark Mma outputs to be evaluated through expression evaluator.
> Rename `AliasType` -> `AllocationType`

- csrc/executor.cpp
- csrc/fusion_profiler.cpp
- test/test_alias.cpp
I could change `compileFusion` to skip compilation as well. It turned out to be more complicated than I expected, so I took the easier route to skip just execution, which is at least an incremental improvement.
> Skip executing a kernel if it's empty.

- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
`MmaOp::evaluate` should return output with the same dtype as the `MmaOp->out()` for consistency.
> Make `MmaOp::evaluate` return output of the same dtype as `MmaOp`

- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- python_benchmarks/test_rope.py
This PR adds two implementations of the RoPE module and benchmarks them for #1597.
`rope_with_cat_fusion` mimics the Hugging Face implementation. `rope_without_cat_fusion` implements an idea from @nikitaved to avoid concatenation. Even though it looks difficult for the compiler to do it all automatically, it's still useful to keep a record of the idea. 
As a side change, I made `fd.define_tensor` to accept empty contiguity.
> Add benchmarks for RoPE.

- benchmark/matmul.cpp
This matches the `at::matmul` baselines.
This PR also adds a few more problem sizes, and runs each eagermode baseline with and without FP16 reduction allowed.
> Make nvfuser matmul benchmarks HSH instead of HSS

- python_benchmarks/global_params.py
For weekly benchmarks, we will focus on 3 states:
1. Steady-State - full machine
2. Just filled the machine
3. Latency limited
The batch sizes are selected to cover these 3 states and the hidden sizes will be varied at a finer granuarity of `step_size=8`.
No major changes are required in our setup for weekly benchmarks. However, pytest is memory intensive and we may need to split the tests in each file to avoid CPU OOM.
~As a solution, we can use `pytest-split` when integrating these into the CI.~
CI uses `pytest-shard` which should work well.
**Running weekly benchmark coverage:**
`BENCHMARK_MODE=weekly pytest <options> <benchmark_file.py>`
CC: @xwang233 @kevinstephano
> Weekly Benchmarks Input Range

- csrc/kernel.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- test/test_gpu_tensorcore.cpp
GridReduction can be lowered to either `gridReduce` or `serialReductionStep`. `gridReduce` requires a smem workspace in order to use multiple threads to aggregate partial sums. However, `serialReductionStep` does not coordinate among threads and has no use for a workspace. This change simply disables allocating that little bit of extra shared memory if our only grid reductions are serial, which currently only happens in split-K GEMM.
This reduces the smem allocated in a simple test from 16896 B to 16384 B (about 97%). More importantly, this makes the computation in `mma_utils::generateSharedMemoryEpilogueHeuristics()` more accurate. Tests are updated to check that this computation is accurate.
The change in `kernel.cpp` is responsible for reducing actual smem usage for split-K. The …
> Avoid unused smem workspace for serial grid reductions

- test/utils.h
Closes Issue #1748.
Apart from `c10::cuda::GetDevice`, no other functionality seems affected.
> Issue #1748

- test/utils.h
Fixes #1748 
guard c10::cuda::GetDevice API change on TORCH_VERSION
with this change, it ensures that we can build against stable release `< 2.2.0`, as well as TOT after  https://github.com/pytorch/pytorch/pull/119142
For 2.3.0 nightly, if someone accidentally checkout a commit before the patch, the build will still fail.
> Device index patch

- CMakeLists.txt
- csrc/device_lower/pass/expr_sort.cpp
- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/options.cpp
- csrc/options.h
- csrc/scheduler/matmul.cpp
- test/test_matmul_aten_evaluation.cpp
- test/test_matmul_default.cpp
Initial PR for Issue #1669.
1. Adds a `EnableOption::MatmulExprEval` to turn on expression evaluation for matmul while the API in under progress.
2. Currently, we only evaluate the `MmaOp`. The next PRs will amend this to _look ahead_ and evaluate Mma + Cast, which is what we should see in the fusion definitions. See discussion [here](https://github.com/NVIDIA/Fuser/issues/1669#issuecomment-1918383315). In the absence of this we may have casts such as `bfloat->float->bfloat.`
> Matmul default scheduling [1]

- csrc/ir/utils.cpp
- csrc/optimization/mark_aliases_prepare.cpp
- test/test_allocation_domain.cpp
Setting empyt allocatoin domain on rank-0 tensor shouldn't trigger assert.
> patch setAllocationDomain on rank-0 TensorView

- test/test_mbarrier.cpp
Tentatively fixes https://github.com/NVIDIA/Fuser/issues/1552. I can not reproduce it locally, but I think it does make sense to have the sync, so adding it.
```C++
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<float, 2, 2> T0, Tensor<float, 2, 2> T2) {
alignas(16) extern __shared__ char array[];
const unsigned smem_offset = 0;
nvfuser_index_t i0;
i0 = ((nvfuser_index_t)threadIdx.y) + (32LL * ((nvfuser_index_t)threadIdx.x));
nvfuser_index_t i1;
i1 = ((nvfuser_index_t)threadIdx.x) + (32LL * ((nvfuser_index_t)threadIdx.y));
float* T1 = reinterpret_cast<float*>(array + smem_offset + 0LL);
uint64_t* T3 = reinterpret_cast<uint64_t*>(array + smem_offset + 4096LL);
mbarrier::init(toSmem(T3), 1024U);
__syncthreads();
T1[i0]
= T0[i0];
uint64_t i2;
i2 = mbarrier::arrive(toSmem(T3)); …
```
> Sync after mbarrier init

- python_benchmarks/normalization.py
- python_benchmarks/test_dropout_rmsnorm_bwd.py
- python_benchmarks/test_gelu_bwd.py
- python_benchmarks/test_gelu_bwd_reduction.py
- python_benchmarks/test_reduction.py
Issue #1765.
Compute references in `double`, starting with the benchmarks where we have existing validation errors in CI.
> Compute validation reference in `double` [1]

- CMakeLists.txt
- csrc/optimization/move_split_cat.cpp
- csrc/optimization/move_split_cat.h
- csrc/optimization/pre_segmenter.cpp
- test/test_resize.cpp
For #1768.
`ghstack land https://github.com/NVIDIA/Fuser/pull/1771` failed for reasons that I don't understand. I'm trying to land it again without `ghstack`. See #1771 for review comments.
> Add a pre-segmenter optimization that cancels splits and cats.

- CMakeLists.txt
- csrc/device_lower/analysis/device_version.cpp
- csrc/device_lower/analysis/device_version.h
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/lower2device.h
- csrc/executor.cpp
- csrc/executor_utils.cpp
- csrc/executor_utils.h
- csrc/kernel.cpp
- csrc/kernel.h
- python_tests/test_python_frontend.py
- test/test_gpu3.cpp
This introduces a minimum device version attribute to the kernel summary and populates it by traversing the fusion early in lowering to find ops or data types introduced after sm70. This version constraint is checked in FusionExecutor::compileFusion and if the target arch doesn't satisfy the constraint then an informative error message is given. Currently BFloat16, cp.async and cp.async.bulk are checked, as are the various MMA macros.
Fixes #1760
> Target arch validation

- csrc/preseg_passes/move_split_cat.cpp
- test/test_resize.cpp
With this PR, MoveSplitCatPass can cancel the <split,cat> pair with `permute`s in between and horizontally merge those `permute`s. See code comments for details. 
For #1768.
> Optimize split->permute->cat. 

- CMakeLists.txt
So that users can change all of these at once without wading through the cmake for it.
> Use cache variables for language standards.

- csrc/executor.h
- csrc/executor_params.h
This fixes some link errors in internal benchmarking tools that arose from 9e480b4.
> Expose getStructuredCode and LaunchParams::print

- csrc/compute_at_map.cpp
- csrc/compute_at_map.h
- csrc/id_model/id_model.cpp
- csrc/id_model/validation_utils.cpp
- csrc/id_model/validation_utils.h
- test/test_id_model.cpp
Validation fails otherwise. Fixes #1791.
> Pass allow_self_mapping to IterDomainGraph.

- csrc/index_compute.cpp
- test/test_memory.cpp
- test/test_mma.cpp
- test/utils.h
This PR adds support for swizzling for TMA load by scheduling the allocation domain of the smem tensor. The swizzle mode (None, 32B, 64B, 128B) is determined by the schedule, in specific, the extent of the IterDomain that is an input/output of the `Swizzle` expr.
> Add swizzle support for TMA load

- benchmark/matmul.cpp
- test/test_combine_mul_sum.cpp
- test/test_gpu_tensorcore.cpp
- test/test_matmul_sass.cpp
- test/test_matmul_scheduler.cpp
- test/utils.cpp
- test/utils.h
This PR removes the `matmul` function in `test/utils.h`. In all unit tests and benchmarks, I am replacing code like
```C++
auto c = matmul(a, b, layout);
```
with
```C++
a = canonicalizeInputToBMNK(a, layout, MmaOperand::A);
b = canonicalizeInputToBMNK(b, layout, MmaOperand::B);
auto c = fusedMultiplySum(a, b, {-1});
```
I believe the latter is better because it is more explicit about how the fusion looks like, therefore more readable.
Besides, with this new coding style, it will be easier to define supported prologue fusions for matmul. For example, if I want to do `sin(A) x sin(B)`, I can just do:
```
a = canonicalizeInputToBMNK(a, layout, MmaOperand::A);
b = canonicalizeInputToBMNK(b, layout, MmaOperand::B);
auto c = fusedMultiplySum(sin(a), sin(b), {-1});
```
In the past, this was not …
> Remove function test/utils.h/matmul

- csrc/fusion_segmenter.cpp
- test/test_segmentation.cpp
It causes unnecessary edges between segments and confusing debugging output. For example, 
```
$ NVFUSER_DUMP=segmenter_logging bin/nvfuser_tests --gtest_filter=SegmentationTest.InputForwardingViaUnaryOps
...
**Segmenter** Considering fusion:
***Accepted*** as: no_op
...
```
The empty fusion considered is produced by merging an unnecessary edge between two segments before forwarded inputs.
> Fix a bug in input forwarding. 

- csrc/multidevice/executor.cpp
fix build error
```
csrc/multidevice/executor.cpp:268:7: error: variable 'communication_counter' set but not used [-Werror,-Wunused-but-set-variable]
int communication_counter = 0;
^
```
Thanks @naoyam
> Correct typo in MultiDeviceExecutor::print

- csrc/python_frontend/python_bindings.cpp
- python_tests/test_python_frontend.py
Changing the FusionDefinition's execute method to support both`List` and `Tuple` for vector of scalars.
> Python API (FusionDefinition::execute) to support tuple for vector inputs

- csrc/multidevice/lower_communication.cpp
- test/multidevice.cpp
- test/multidevice.h
- test/test_multidevice_pipeline.cpp
In this pr, we simplify the multidevice test validation implementation and make it run faster.
Before, we would allocate a shard of the inputs at each rank. Then, for validation, we needed to gather at a tester rank all the inputs and outputs shards, and compare them with the unsharded output obtained from running the Fusion on a single device with the unsharded inputs. This flow could be summarized as follows:
```
execution:
for all RANK k
- allocate input's shard k
- run Fusion on multidevice with input's shard k  --> get output's shard k
validation:
TESTER RANK:
- gather all input shards from other ranks 
- run Fusion on single device with unsharded input --> get unsharded output
- gather all outputs shards slices from other ranks
- compare all output shards with unsharded outputs
``` …
> Multidevice tests with unsharded inputs

- csrc/preseg_passes/move_split_cat.cpp
Previously, the NVF_ERROR did nothing but fallthrough.
> Fix an embarrassing bug.

- CMakeLists.txt
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/pass/expr_sort.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/device_lower/validation.cpp
- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/options.cpp
- csrc/options.h
- csrc/scheduler/mark_aliases.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- test/test_matmul_aten_evaluation.cpp
- test/test_matmul_default.cpp
PR #1743 was reverted due to the following issues:
1. Matmul scheduler does not support all architectures: This caused some tests to fail on V100. This is fixed by returning early in `getMatmulHeuristics` and only setting the required parameters.
2. Errors in `GpuLower::analysis`: `validateMma` and `PredicateElimination` are modified to skip expressions and outputs marked for expression evaluator.
> Matmul default scheduling 

- csrc/preseg_passes/move_split_cat.cpp
This makes it convenient to use an IdModel as a class member without having to pass it through many functions.
I examined the NVFUSER_TRACE. FusionKernelRuntime::FusionKernelRuntime is bottlenecked by
"Finding valid fusion segment solutions" not pre-segmenter passes. I added the FUSER_PERF_SCOPE for pre-segmenter passes anyway. 
For #1768
> Refactor so CancelSplitCat becomes a class.

- csrc/preseg_passes/move_split_cat.cpp
- test/test_move_split_cat.cpp
For #1768. 
Other changes:
1. Add a test that would have failed without this change. 
2. Roll forward https://github.com/NVIDIA/Fuser/pull/1483, which I believe got accidentally reverted by https://github.com/NVIDIA/Fuser/pull/1451. @samnordmann, let me know if you downgraded googletest intentionally.
> Use replayExprWithNewInput to replay permutes.

- python_benchmarks/core.py
- python_benchmarks/test_softmax_bwd.py
- python_benchmarks/test_softmax_fwd.py
For uniformity of IO bytes, and compairson between nvFuser and baselines of `eager` and `torch.compile` mode, set the IO bytes instead of computing based on inputs / outputs of the benchmarked function. 
The inputs / outputs to the torch functions may not always be the same as nvFuser.
For instance, in `layernorm fwd`, nvFuser definition returns the `mean` and `invstd`, but `torch.nn.functional.layer_norm` does not.
> Set IOBytes for benchmarks

- csrc/preseg_passes/pre_segmenter.cpp
> Add a perf scope for pre-segmenter passes.

- csrc/multidevice/utils.cpp
A small fix to avoid some hangs in the tests in case the runtime doesn't match the required multi-device setting.
More precisely, imagine we shard a tensor on the device mesh [0,2], and that, at runtime, the communicator is of size 2, then, there will be no device with index 2, so the runtime is incompatible.
Before this patch, the above situation would not be detected as an error.
> Fix MultiDeviceExecutor::requestedNumberOfDevices

- csrc/ir/nodes.cpp
- csrc/transform_iter.cpp
- csrc/transform_iter.h
- csrc/transform_replay.cpp
- test/test_replay.cpp
This PR adds a knob to copy isRFactorProduct from the IterDomain being replayed. I hate knobs but couldn't find a better way. Plenty of ReplayTransformations users (e.g. https://github.com/NVIDIA/Fuser/blob/a684e2a220ed6daa14673d4c492b8eb80c299ce0/csrc/scheduler/utils.cpp#L2171 triggered by https://github.com/NVIDIA/Fuser/blob/8226e61a2a843e8e4ad8c6c2801b019f654828d1/test/test_gpu3.cpp#L7320) replay rfactor transforms on a TensorView without rfactor. Therefore, ReplayTransformations cannot copy isRFactorProduct unconditionally. 
Fixes #1857.
> Fix ReplayTransformations to properly set isRFactorProduct. 

- csrc/preseg_passes/move_split_cat.cpp
- test/test_move_split_cat.cpp
Extends the optimization to ViewOp. This PR uses IdModel to (1) check equivalence between ID transforms and (2) compute the concatenated dimension after zipping. 
Unit tests are passing: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/13280916
For #1768
> Optimize split->reshape/permute->cat.

- python_benchmarks/global_params.py
@kevinstephano suggested benchmarking the hidden sizes at steps of `[256 + 0, 256 + 2, 256 +4, 256 + 8, 256 + 16]` instead of sweeping at step size of 8 to reduce the computation requirement and check vectorization.
This PR modifies the hidden sizes sweeped for weekly runs. The nightly runs are unaffected.
> Modify hidden size sweep in weekly python benchmarks

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/preseg_passes/move_split_cat.cpp
- csrc/val_graph.cpp
- csrc/val_graph.h
- test/test_id_model.cpp
- test/test_move_split_cat.cpp
As a follow up to https://github.com/NVIDIA/Fuser/pull/1799#discussion_r1513976524. This PR comes with a refactor that moves hasSelfMapping from IdModel to ValGraph, so it can be applied on cloned ValGraphs.
> sameIterDomainTransforms clones IdGraph.

- csrc/scheduler/normalization_utils.cpp
- test/test_persistent_buffer.cpp
Reverts NVIDIA/Fuser#1796
(1) when disable project to inputs should check do we still have enough register or smem for persistent buffers
(2) Need to eavaluate do we want to disable project to inputs at the cost of segment.
> Revert "don't project to inputs if calculate persistent buffer requires rng op"

- csrc/expr_evaluator.cpp
- test/test_evaluator.cpp
This fixes a bug which would cause the intermediate values to be updated to `known_values`.
> Update known values correctly

- csrc/codegen.cpp
- csrc/kernel.cpp
- csrc/scheduler/reduction.cpp
- runtime/grid_reduction.cu
- test/test_gpu_outer_reduction.cpp
- test/test_serial_gridreduce.cpp
Following #1800 
Add iteration domain grouped grid reduction.
**TODO:**
(1) revise outer reduction heuristics
(2) combine grouped with regular grid/block reduction function.
**Performance of outer reduction:**
(1) Reduction dim = 2048, iteration dim = 1 to 32K
(2) Reduction dim = 16K, iteration dim = 1 to 32K
More results avialable in the [doc](https://docs.google.com/document/d/1YI0KX_vmBMJurxooN2_Ya89Niki6zvYCvGDwURTEVCs/edit#heading=h.6behzp60hcgm).
> add iter grouped grid reduction

- csrc/ir/nodes.cpp
- test/test_matmul_aten_evaluation.cpp
Since PyTorch matmul maintains the input data type, we expect to see fusions of type `MmaOp + Cast`. To avoid roundtrip casts, we look ahead and skip casting the ATen output to float whenever MmaOp is followed by cast.
Nsys profiles for the test: `MmaOpAndCast`:
Main branch:
```
Start (ns)  Duration (ns)  CorrId  GrdX  GrdY  GrdZ  BlkX  BlkY  BlkZ  Reg/Trd  StcSMem (MB)  DymSMem (MB)  Bytes (MB)  Throughput (MB/s)  SrcMemKd  DstMemKd            Device             Ctx  GreenCtx  Strm                                                  Name                                                
----------  -------------  ------  ----  ----  ----  ----  ----  ----  -------  ------------  ------------  ----------  -----------------  --------  --------  ---------------------------  ---  --------  ---- …
```
> Evaluate `MmaOp + Cast` in a single call

- csrc/scheduler/matmul.cpp
- test/test_evaluator.cpp
- test/test_matmul_aten_evaluation.cpp
This PR skips matmul scheduling after combining a valid `mul-sum` pair to `MmaOp`.
> Support ATen evaluation for matmul represented as `mul-sum`

- csrc/scheduler/vectorize_helper.cpp
- test/test_allocation_domain.cpp
Fixes #1895
In `getVectorizationBreakPointOfReductionProducer`, the existing logic walks through mapped innermost iterdomain on reduction producer to find break_point. However, it doesn't account for case where no innermost iterdomain is mapped (i.e. `consumer_innermost_ndims == 0`) and triggers a false assert.
> avoid assert when consumer_innermost_ndims == 0

- csrc/device_lower/analysis/predicate_elimination.cpp
Right now, we have `PredicateChcker` and `PredicateAnalyzer`. From their name, we can not tell which is doing what. After reading the code, we can tell that, `PredicateChcker` is the global entry point for predicate elimination, and `PredicateAnalyzer` is a helper class for `predicateProducerConsumerPair`, which is only one condition of `PredicateChcker`: https://github.com/NVIDIA/Fuser/blob/638bfe00a29f582a337042c04a63c13410b8b17f/csrc/device_lower/analysis/predicate_elimination.cpp#L222
So I do this rename to indicate this fact.
> Rename `PredicateAnalyzer` -> `ProducerConsumerPairAnalyzer`

- csrc/executor.cpp
- csrc/executor.h
Example use case:
```C++
TEST_F(PredicateEliminationTest, ExtentEqualToMaxParallelTypeExtent) {
Fusion fusion;
FusionGuard fg(&fusion);
auto tv0 = makeContigTensor(1);
fusion.addInput(tv0);
auto tv1 = set(tv0);
auto tv2 = set(tv1);
fusion.addOutput(tv2);
tv1->setMemoryType(MemoryType::Shared);
std::vector<TensorView*> tvs = {tv1, tv2};
for (auto tv : tvs) {
tv->split(0, 32);
tv->axis(0)->parallelize(ParallelType::TIDx);
}
fusion.manage("interested_tvs", tvs);
auto validate_smem_predicate_elimination =
[](const std::vector<Expr*>& exprs) -> std::vector<Expr*> {
kir::Kernel* kernel = GpuLower::current()->kernel();
auto kernel_tvs =
kernel->getManaged<std::vector<TensorView*>>("interested_tvs");
for (auto tv : kernel_tvs) {
EXPECT_TRUE( …
```
> Lowering hook for `FusionExecutor`

- csrc/scheduler/vectorize_helper.cpp
- test/test_allocation_domain.cpp
Follow up on a previous fix #1896 
When break_point is at the boundary, added a short-cut to return 1 for vectorization factor.
Since existing vectorization analysis assumed to have a non-trivial break_point, which result in an out of bound access.
> Patch out of bound access in `getVectorizationFactor`

- csrc/ops/alias.cpp
- csrc/ops/utils.cpp
- csrc/ops/utils.h
This is just a small cleanup I noticed when combing through the ops code recently.
> Remove unused dtype parameter in ops::newOutputDomain

- csrc/executor.cpp
Our vectorization strategy depends on the number of multiprocessors (aka SMs).
> Print the number of multiprocessors for performance debugging.

- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/mma_utils.cpp
- test/test_gpu_tensorcore.cpp
This simply fixes an integer division by zero error in `generateSharedMemoryEpilogueHeuristics()` when `params.double_buffer_options.smem_double_buffer_stage == 0`. The modified test fails on main with
```
[ RUN      ] NVFuserTest.FusionAmpereMatmulSmemEpilogue_CUDA
[penny:1500 :0:1500] Caught signal 8 (Floating point exception: integer divide by zero)
==== backtrace (tid:   1500) ====
0 0x0000000000042520 __sigaction()  ???:0
1 0x00000000009f384f nvfuser::mma_utils::generateSharedMemoryEpilogueHeuristics()  /opt/pytorch/nvfuser/csrc/scheduler/mma_utils.cpp:158
2 0x0000000000be3b90 nvfuser::NVFuserTest_FusionAmpereMatmulSmemEpilogue_CUDA_Test::TestBody()  /opt/pytorch/nvfuser/test/test_gpu_tensorcore.cpp:2392
3 0x0000000000c5fdd9 …
```
> Fix stages=0 smem heuristic

- test/test_memory.cpp
This change should be a noop. But using negative axis is required for supporting tiling.
> Use negative axis for `scheduleTMASwizzle`

- csrc/device_lower/utils.cpp
- test/test_predicate_elimination.cpp
Because `get` will return things like `blockDim.x` instead of the actual extent unless it is constant:
https://github.com/NVIDIA/Fuser/blob/4621129399550b8a6f3994d5092ddd0d581a6dc0/csrc/parallel_dimension_map.cpp#L150-L156
which is not desired behavior we want here.
> Use `getRaw` in `isExtentEqualToMaxParallelTypeExtent`

- csrc/expr_evaluator.cpp
- csrc/expr_evaluator.h
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- test/test_evaluator.cpp
This PR is intended to add support for evaluating multiple ops together and skip evaluating intermediate inputs.
Current use cases:
1. CatOp: Currently, CatOp::evaluate uses the unpadded inputs, however the padded inputs are still evaluated.
2. Matmul Fallback path: We need the expression evaluator to evaluate patterns such as `MmaOp + Cast`, `MmaOp + Bias + Cast` in a single call instead of one op at a time.
> Evaluate multiple ops together

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/options.cpp
- csrc/options.h
- csrc/utils.h
- test/test_gpu_utils.cpp
This PR adds a new debug dump option `NVFUSER_DUMP="ftrace(regex)"`, which will print the call traces of functions satisfying the provided `regex`. In order for this to work, the function needs to be updated by putting a `DEBUG_PRINT_SCOPE(arguments...)` at the top of the function, and change the `return XXX;` into `RECORD_AND_RETURN(XXX);`. For this PR, I am adding this feature only for conditions in predicate elimination, see example output here:
<details>
<summary>example output</summary>
```C++
❯ NVFUSER_DUMP="ftrace(predicate.*)" ./bin/nvfuser_tests --gtest_filter=*PredicateEliminationTest.1*
Running main() from /home/gaoxiang/Fuser3/third_party/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = *PredicateEliminationTest.1*
[==========] Running 1 test from 1 test …
```
> Add `NVFUSER_DUMP="ftrace(regex)"`

- csrc/fusion_segmenter.cpp
(1) If segmented without hint:
```
***Runtime***: Try to schedule fusion un-segmented:
Scheduler _no_op_ ***rejected*** because : reduction of non-zero elements is not supported
Scheduler _matmul_ ***rejected*** because : Matmul scheduler supports fusions only with a single mma opor supports a mul-sum pair which can be replaced with a mma op
Scheduler _reduction_ ***rejected*** because : Inconsistent reduction axes 0x7fb74625f080is not 2
Scheduler _transpose_ ***rejected*** because : cannot find two mismatching inner most dimensions
Scheduler _pointwise_ ***rejected*** because : no support for reduction ops
Scheduler _inner_persistent_ ***rejected*** because : inconsistent reduction root size: T30_g[ rS55{i0} ], expected: 2
Scheduler _outer_persistent_ ***rejected*** because : …
```
> fix debug info of segment hints

- csrc/scheduler/normalization_inner.cpp
Following #1849 
(1) rename `free_registers` to `register_overhead`
(2) use `non_buffer_registers` when compare heuristics
(3) revised code comments
> revise comments in inner persistent heuristics

- test/test_gpu_transpose.cpp
- test/test_matmul_aten_evaluation.cpp
- test/test_matmul_scheduler.cpp
I realized some unnecessary complexity is copied here and there.
> Simplify the uses of OptimizationGuard.

- csrc/transform_iter.cpp
By definition, `Swizzle` is a new `Swizzle2D` that exclude all hackings. I accidentally included this `replay_swizzle_` hacking in my initial PR. This PR removes it.
> Always replay `Swizzle`

- tests/cpp/test_id_model.cpp
https://github.com/NVIDIA/Fuser/issues/1759
> repro of issue #1759

- csrc/mma_type.h
- csrc/tma.cpp
- csrc/utils.h
- tests/cpp/test_gpu_utils.cpp
Example print:
```C++
[ RUN      ] TMALdstTest/TMALdstTest.LoadCompleteTensor/4D_NoSwizzle_float
Entering EncodeTensorMapTiled(global_address=, 0x7ffd19e00000, global_dim=, 4 4 4 4, global_strides=, 16 64 256, box_dim=, 4 4 4 4, element_strides=, 1 1 1 1, data_type=, float, interleave=, NoInterleave, swizzle=, NoSwizzle, l2_promotion=, NoL2Promotion, oob_fill=, NoOOBFill, tensor_rank=, 4)
Leaving EncodeTensorMapTiled
[       OK ] TMALdstTest/TMALdstTest.LoadCompleteTensor/4D_NoSwizzle_float (299 ms)
```
> Enable ftrace only without `NDEBUG`, ftrace `EncodeTensorMapTiled`

- csrc/executor.cpp
- csrc/executor_utils.cpp
- csrc/kernel.cpp
- csrc/kernel.h
This PR adds `KernelSummary::validations`, a vector of `(boolean_expr, string_reason)` pairs. This field will serve as a unified framework for validations, and will also be used for validating TMA. The previous `KernelSummary::splits_to_validate` is removed and the corresponding validations are moved to this new framework.
> `KernelSummary::validations`

- csrc/device_lower/pass/index.cpp
https://github.com/NVIDIA/Fuser/pull/1962#pullrequestreview-1947575870
Example kernel:
```CUDA
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<__half, 1, 1> T0, const __grid_constant__ TensorMap var0, Tensor<__half, 1, 1> T2) {
alignas(16) extern __shared__ char array[];
const unsigned smem_offset = 0;
nvfuser_index_t i1;
i1 = 8LL * ((nvfuser_index_t)blockIdx.x);
nvfuser_index_t i2;
i2 = (-T0.logical_size[0LL]) + i1;
__half* T1 = reinterpret_cast<__half*>(array + smem_offset + 0);
#pragma unroll
for(nvfuser_index_t i3 = 0; i3 < 8; ++i3) {
T1[i3] = 0;
}
#pragma unroll
for(nvfuser_index_t i3 = 0; i3 < 8; ++i3) {
if ((i2 < (-i3))) {
T1[i3]
= T0[(i1 + i3)];
}
}
asm volatile("fence.proxy.async;\n");
Hopper::cpAsyncBulkTensorTileS2G((Hopper::CpAsyncBulkTensorTileS2GIndex<1>{ (&var0), …
```
> Add a fence before TMA store

- benchmarks/cpp/matmul.cpp
These were broken by #1927, but the fix is simple.
> Prevent matmul benchmarks from using ATen eval

- csrc/multidevice/lower_communication.cpp
Small refactor of `multidevice/lower_communications.cpp`. Moving arguments of `DeviceMesh` to `TensorView*`.  Current lowerings only need the DeviceMesh, but more complex lowerings will need to analyze both. 
Creating a separate PR for this refactor to make an upcoming PR a little cleaner (https://github.com/NVIDIA/Fuser/pull/1939)
> Communication lowering refactor

- csrc/device_lower/lower2device.h
- csrc/kernel.cpp
- csrc/non_divisible_split.cpp
- csrc/non_divisible_split.h
Now `KernelSummary::validations` is just a copy of `GpuLower::validations()`. The validations for non-divisible split is now added by `NonDivisibleSplitInfo`, instead of in `KernelIrScanner`. By refactoring this way, we can add other validations during lowering.
> Add `GpuLower::validations()`

- CMakeLists.txt
- csrc/executor.cpp
- csrc/global_allocator.cpp
- csrc/global_allocator.h
- csrc/options.cpp
- csrc/options.h
- tests/cpp/test_serial_gridreduce.cpp
This introduces a thread-local global memory allocator for each device and uses it whenever there is an intermediate tensor needed which requires zero-initialization.
To enable use `NVFUSER_ENABLE=reuse_zeroed_memory`. You can monitor the allocator using `NVFUSER_DUMP=global_zeroed_memory`.
Before we enable this feature by default, we need to have high confidence that every kernel using zero-initialized memory will always clean up their semaphores. This is currently only the case for serial grid reductions, as far as I know.
This enables the basic functionality of #1829. However, it does not modify existing algorithms to clean up their memory. See `NVFUSER_ENABLE=reuse_zeroed_memory NVFUSER_DUMP=global_zeroed_memory build/nvfuser_tests --gtest_filter=SerialGridReductionTest.Scheduling`, …
> Reusable zeroed memory

- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/grid_serialization.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/executor.cpp
- csrc/executor.h
- csrc/global_allocator.cpp
- csrc/global_allocator.h
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/serde/fusion_cache.fbs
- tests/cpp/test_serial_gridreduce.cpp
As suggested by @naoyam, this will allow us to incrementally enable reuse of zeroed memory (see #1984) on a case-by-case basis. To do so, when creating an `Allocate` node, if it is guaranteed to be "cleaned up" (i.e. reset to all zero values) by the end of the kernel, then you can pass `true` for the `resets_to_zero` argument in the `kir::Allocate` constructor. This will automatically enable reuse of zeroed memory for this buffer and avoid a memset call, regardless of whether
`EnableOption::ReuseZeroedMemory` is enabled or not. Eventually this will let us get rid of that option entirely, once all of our global memory semaphores are guaranteed to be reset.
> Add kir::Allocate::resetsToZero()

- benchmarks/python/core.py
- benchmarks/python/test_gelu_bwd.py
- benchmarks/python/test_gelu_bwd_reduction.py
- benchmarks/python/test_gelu_fwd.py
Part of resolving #1668.
Adds IObytes computation for bwd and bwd-reduction benchmarks for parity with nvFuser.
> Baseline benchmarks for GeLU fwd, bwd and reduction.

- csrc/device_lower/pass/alias_memory.cpp
This is a work-around for #2000.
It seems to address the issue in the only current use case for smem reuse: matmul with `params.use_smem_epilogue == true`. It is not ideal: for example it will insert a `cp.async.wait_all` instruction even if circular buffering is not used in the kernel.
Fixes #1996 but since this is a hack, I will not mark #2000 as fixed yet.
> Hack to ensure cp.async is waited before smem reuse

- tests/cpp/test_gather.cpp
Avoid potential OOM errors caught in https://github.com/NVIDIA/Fuser/pull/1961 in V100 test https://nv/e2E/87216881
The test uses a random input shape with a maximum size of 64^5 = 1G elements, 2 inputs and 1 output, the max requested mem can be 3 tensors  x 1G elments per tensor x 4 bytes per element = 12 GB.
> call clear allocator in gather test to avoid OOM

- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/double_buffer.cpp
- tests/cpp/test_loop_rotation.cpp
This just places a `cp.async.wait_group 0` instruction immediately after any circular buffer main loop which is the approach taken by CUTLASS for pipelining GEMMs: (see [mma_multistage.h#L664-L665](https://github.com/NVIDIA/cutlass/blob/c4e3e122e266644c61b4af33d0cc09f4c391a64b/include/cutlass/gemm/threadblock/mma_multistage.h#L664-L665)). The previous fix for #2000, #2001, is reverted.
This is an alternative to #2005.
Fixes #2000
> Drain cp.async jobs after main loop

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_matmul_aten_evaluation.cpp
Adds ATen evaluation for Matmul and Matmul + Bias. Based on PR #1921, when evaluating a `castOp`, we _look back_ to see if there is a preceding MmaOp and evaluate them together.
Issue #1775.
> Evaluate `Matmul+Bias`

- csrc/ops/composite.cpp
- csrc/ops/composite.h
- tests/python/pytest_opinfos.py
- tests/python/test_python_frontend.py
This commit refactors the matmul API so that:
1. The CastOp is part of the matmul interface. (based on discussions with @kevinstephano, @Priya2698 and @jacobhinkle )
2. The Matmul Impl function will be reused by the API for linear. (follow-up commit)
> make castOp part of matmul API

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- tests/cpp/test_multidevice_resharding.cpp
The test requires the distributed mode components to be compiled in, so cannot pass in single-GPU mode.
> Disable a test when distributed is off.

- csrc/ir/nodes.cpp
- tests/cpp/test_resize.cpp
I noticed the extent of a slice output IterDomain is not simplified as intended. Currently we do pattern matching of `a - b`, but we actually get `a + (-b)` due to `SimplifyingIrBuilder`. This is a quick fix to make sure the latter pattern is also detected. For example:
Before: `i0 + ( ( fmax(0, ( fmin(i0, 1) )) ) + ( -i0 ) )`
After: `fmax(0, ( fmin(i0, 1) ))`
> Simplify resize extent

- csrc/device_lower/pass/scalar_hoist.cpp
- tests/cpp/test_gpu_tensorcore.cpp
This detects when a loop has zero iterations and avoids contradictions when simplifying included expressions.
Fixes #1808
> Avoid contradicting assumptions from empty loops

- csrc/options.cpp
This reverts commit ef4cae963b44c048f67db795ccc0b997f250ba38.
> Revert "options should be thread local (#1913)"

- benchmarks/python/test_huggingface_attn_bwd.py
- benchmarks/python/test_huggingface_attn_fwd.py
- benchmarks/python/test_nanogpt_attn_bwd.py
- benchmarks/python/test_nanogpt_attn_fwd.py
Issue #1668
The benchmarks use `dropout_p=0.2` for benchmarking. For validating in forward pass, to ensure the same dropout_mask is applied, this is set to 0.
> Torch baselines for attention benchmarks

- benchmarks/python/test_layernorm_bwd.py
- benchmarks/python/test_layernorm_fwd.py
Issue #1668.
Adds IOByte computation and benchmarking for Layernorm baselines (eager & torchcompile)
> `eager` and `torch.compile` benchmarks for `layernorm`

- tests/cpp/test_multidevice_pipeline.cpp
Disabling failing multidevice unit tests until they are fixed.
1. PipelineTestTwoStage test with UCC backend.
`mpirun -np N test_multidevice_test --gtest_filter='*DISABLED_UCC_*' --gtest_also_run_disabled_tests` where N > 4
These tests cause UCC barrier to hang when the tests are run with more than 4 processes. Still investigating the cause and whether the bug is potentially in UCCProcessGroup. 
2. Distributed reduction tests that execute with FusionExecutorCache. 
`mpirun -np 4 test_multidevice_test --gtest_filter='*DISABLED_FusionExecutorCache_*' --gtest_also_run_disabled_tests`
These tests are failing because of the new `AllocationDomainPass`. @jjsjann123  Hopefully, this is a simple fix to ignore reordering reductions on a DeviceDim axis.
> Disable failing multidevice unit tests

- csrc/ops/arith.cpp
- csrc/ops/normalization.cpp
- csrc/ops/utils.cpp
- csrc/ops/utils.h
**Problem:** The `variance_mean` function uses the `dims` argument directly, which can be a negative number. 
**Solution:** This PR canonicalizes the reduction dimensions when `keepdim=True`, and moves `canonicalizeAxes` function to utils.h
> Canonicalize `dims` argument in `variance_mean` when `keepdim=True`

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- tests/cpp/test_id_model.cpp
This PR changes how Step 2 of the loop promotion analysis finds promotion domains. Loop promotion should be done to domains that are in the same loop group, but I thought this could be achieved by just checking the mapping for the final results at Step 5 and it wouldn't matter for intermediate results of promotion generated at Step 2. While that's probably the case, it also introduces some unexpected domain mappings and I found they were really confusing while working with some complex fusions. Besides, as suggested by @zasdfgbnm, the initial decision doesn't seem to buy much but just adds some extra complexity. 
The requirement flag is now removed. The change to the promotion code is pretty minimal, but unfortunately, it meant many of the promotion reference results needed to be updated …
> IdModel: Always require promotion to loop mapped domains

- csrc/multidevice/device_mesh.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- tests/cpp/test_multidevice_sharding.cpp
A simple sharding propagation pass that shards TensorViews without a DeviceMesh like it's first producer TensorView with a DeviceMesh.
Assumes global TensorViews are manually sharded.
> Sharding propagation pass

- CMakeLists.txt
- tests/cpp/test_reduction_pointwise.cpp
First step of #2063 
Added tests for:
(1) inner reduction + non-broadcast epilogue
(2) outer reduction + non-broadcast epilogue
(3) inner reduction + broadcast epilogue
(4) outer reduction + broadcast epilogue
> add tests for reduction with pointwise epilogue

- csrc/executor.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/scheduler/matmul.cpp
- tests/cpp/test_gpu_tensorcore.cpp
This introduces a mechanism for schedulers to declare the expected dynamic shared memory usage by optionally calling
`fusion->setExpectedDynamicSmemBytes(n)`. During execution, when validating that the shared memory fits within device limits, we will also check that the dynamic smem matches this value.
This is debugging information, but since it's quick to check I have enabled it unconditionally. This will give us more confidence that `mma_utils::computeExpectedSharedMemoryUsage` is accurate. If that function is inaccurate, we would not necessarily hit an error but we might have suboptimal heuristics and occasional errors where we specify MatmulParams that cannot be launched on the current device.
Note that the smem is dynamic, so it could instead be a `Val*`, but it is compile-time …
> Always validate dynamic smem usage for matmuls

- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
1. `fd.ops.linear` will take input shapes `[M, K] x [N, K]`. This is evaluated through `at::linear` for parity with PyTorch.
2. Fix the segmenter issue with Linear + Bias. See #2057.
Issue #1669
> ATen evaluation for linear primitive

- tests/cpp/test_multidevice_communications.cpp
Before:
```
[ RUN      ] CommunicationTest.Communication_ReduceScatter/0
[       OK ] CommunicationTest.Communication_ReduceScatter/0 (0 ms)
[ RUN      ] CommunicationTest.Communication_ReduceScatter/1
[       OK ] CommunicationTest.Communication_ReduceScatter/1 (0 ms)
```
After:
```
[ RUN      ] CommunicationTest.Communication_ReduceScatter/NCCL
[       OK ] CommunicationTest.Communication_ReduceScatter/NCCL (0 ms)
[ RUN      ] CommunicationTest.Communication_ReduceScatter/UCC
[       OK ] CommunicationTest.Communication_ReduceScatter/UCC (0 ms)
```
> Print better test names.

- csrc/index_compute.cpp
- tests/cpp/test_memory.cpp
This PR is stacked on https://github.com/NVIDIA/Fuser/pull/1991.
Besides https://github.com/NVIDIA/Fuser/pull/1991, another point that I feel very inconvenient when using TMA is, I am forced to do a split even if I want to treat the entire dimension as a box.
For example, if I want to load a shape `[100000000, 4]` tensor using a `[8, 4]` box, currently, I am required to schedule the tensor like `[100000000/8, 8 (bulk), 4/4, 4 (bulk)]`. This is inconvenient. This PR allows me to instead more conveniently schedule the fusion like `[100000000/8, 8 (bulk), 4 (bulk)]`.
Enabling this feature creates some complexity to the analysis in indexing. For example, if we have a contiguous tensor of shape `[1024, 4, 8, 16]`, if I schedule it like `[1024, 4, 8, 16(bulk)]`, I should be able to know that I …
> Bulk entire dim

- CMakeLists.txt
- tests/cpp/test_multidevice_sharding.cpp
- tests/cpp/test_resharding.cpp
- tests/cpp/test_sharding.cpp
1. Rename it to test_sharding.
2. Move it from binary test_multidevice to binary nvfuser_tests.
This is a follow-up to https://github.com/NVIDIA/Fuser/pull/2096.
CI: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/14326655
> Rename and move test_multidevice_sharding.

- csrc/index_compute.cpp
- tests/cpp/test_memory.cpp
Renames:
- originating bulk ID -> tile ID
- inner ID -> stride ID
> Remove legacy doc and rename variables in TMA indexing code

- csrc/scheduler/mma_utils.cpp
This prevents underestimation of smem epilogue use in the default heuristic, which is rarely used.
> Use proper dtype in generateSharedMemoryEpilogueHeuristics

- benchmarks/python/conftest.py
- benchmarks/python/core.py
1. Adds CLI options for controlling number of `warmup_rounds/rounds`: This will be useful when we run python benchmarks on the Github CI to control the total time required to run the benchmark suite.
2. Updates how complete test names are printed to allow for better filtering: Closes Issue #1693. The new format of test names is:
`test_name[argname=value]`. 
For example: `test_transpose_nvf_benchmark[axes=[0_1]-dtype=torch.float32-size=[2_2_16]]`. 
The tuple values are `_` joined to allow filtering.
> Add CLI options for benchmarking, update test name printing

- csrc/executor.cpp
This just checks that our smem usage matches the expected amount that was optionally set during scheduling before checking that it falls within device limits. This helps debugging in some cases since it can tell us that we are overrunning our smem because of misestimation or because of a heuristic decision that misused a correct estimate. This was helpful in discovering #2111.
> Check expected smem size before device limit

- benchmarks/python/core.py
- benchmarks/python/test_dropout_layernorm_bwd.py
- benchmarks/python/test_dropout_layernorm_fwd.py
- benchmarks/python/test_dropout_rmsnorm_bwd.py
- benchmarks/python/test_dropout_rmsnorm_fwd.py
1. Update the fusion definition to have 2 distinct inputs: `layernorm/rmsnorm (inp2 + dropout(inp1))`.
2. Add torch baselines
3. Add iobyte computation based on input/output dict listing size and dtype. This should make the computation clearer to the users and less error-prone
Issue #1668
> Update`dropout-layernorm/rmsnorm` benchmarks

- csrc/exceptions.cpp
- csrc/exceptions.h
- csrc/multidevice/c10d_mock.h
- csrc/serde/utils.cpp
- tests/cpp/test_ca_root_domain_map.cpp
- tests/cpp/test_combined_inner_outer_reduction.cpp
- tests/cpp/test_exceptions.cpp
- tests/cpp/test_persistent_buffer.cpp
- tests/cpp/test_reduction_pointwise.cpp
I noticed some of these were missing when editing them, since lintrunner did not automatically format them as expected.
> Add some missing "clang-format on" comments

- CMakeLists.txt
CMake does not forward private flags.
> Add sanitize link option to final object, too.

- doc/dev/tma/arbitrary-view.svg
- doc/dev/tma/box-and-tile.svg
- doc/dev/tma/box-by-compositing.svg
- doc/dev/tma/box-by-partitioning-and-compositing.svg
- doc/dev/tma/box-by-partitioning.svg
- doc/dev/tma/consumer-schedule.svg
- doc/dev/tma/dense-and-strided-tile.svg
- doc/dev/tma/invalid-smem-discontiguous.svg
- doc/dev/tma/matmul-tma-domain.svg
- doc/dev/tma/strided-tile.svg
- doc/dev/tma/swizzle-schedule.svg
- doc/dev/tma/swizzle.svg
- doc/dev/tma/valid-smem-contig.svg
- doc/reading/divisibility-of-split/allocate-6-as-2,4.svg
- doc/reading/divisibility-of-split/merge-split.svg
- doc/reading/divisibility-of-split/three-indivisible-splits.svg
- doc/reading/tma-modeling-in-depth/no-strong-correctness-data.svg
- doc/reading/tma-modeling-in-depth/no-strong-correctness-schedule.svg
- doc/reading/tma-modeling-in-depth/strong-correctness-2.svg
- doc/reading/tma-modeling-in-depth/strong-correctness.svg
- doc/reading/tma-modeling-in-depth/weak-correctness-holes-nonzero.svg
So that it is no longer transparent. This is not the best for dark mode, but at least readable because previously, we will just have black lines and texts in a black background.
> Add white background to all SVGs

- benchmarks/python/core.py
Re: https://github.com/pytorch/pytorch/pull/123247
This PR changed `self_cuda_time_total` to `self_device_time_total` in API calls.
> Fixed torch profiler API changes in python benchmarks

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/validation.cpp
- csrc/executor.cpp
- csrc/executor.h
- csrc/kernel_cache.cpp
- csrc/kernel_cache.h
- csrc/serde/fusion_cache.fbs
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
- tests/cpp/test_resize.cpp
This PR resolves Issue #1812.
1. Removes the workarounds added to support ATen evaluation for matmuls in PR #1775 (in `predicate_elimination.cpp` and `validation.cpp` (see comments in the PR)
2. `FusionExecutor::fusion_` is initialized only when compilation is skipped. So only one of `lowered_` or `fusion_` is non-null.
3. `FusionKernelRuntime/FusionExecutorCache/FusionExecutor::isCompiled()` indicates whether compilation was attempted (either marked for EE or via nvFuser).
> Skip compiling fusion segments when using expression evaluator

- csrc/executor.cpp
- csrc/executor.h
- tests/cpp/test_matmul_aten_evaluation.cpp
It seems to be unnecessary given `hasCompiledKernel`. Wdyt?
> Remove FusionExecutor::isExprEval.

- tests/cpp/test_multidevice_communications.cpp
When the check fails, the latter fails gracefully and doesn't stop other tests from running.
> Replace NVF_ERROR with EXPECT_TRUE.

- csrc/codegen.cpp
- csrc/kernel_ir.cpp
- tests/cpp/test_mma.cpp
Printed code:
```diff
4,5c4,5
<     "  setp.ne.b32 p0, %5, 0;\n"
<     "  wgmma.mma_async.sync.aligned.m64n8k16.f32.bf16.bf16 {%0, %1, %2, %3}, {%4, %5, %6, %7}, %8, p0, %9, %10, %11;\n"
---
>     "  setp.ne.b32 p0, %9, 0;\n"
>     "  wgmma.mma_async.sync.aligned.m64n8k16.f32.bf16.bf16 {%0, %1, %2, %3}, {%4, %5, %6, %7}, %8, p0, %10, %11, %12;\n"
```
As a result of this bug, the `transB` of the RS variant of mmas is always `1`, and the `transA` of the SS variant of mmas is also always 1, and the `transB` is `transA`. Because previously the mma tests are green, this means that their schedules are wrong but consistent with this wrong PTX, and we need to fix them. This is left as a future task.
> Fix printed PTX for hopper mma

- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
This implements https://www.sci.utah.edu/~tfogal/academic/Fogal-ParallelDebugging.pdf, authored by @tfogal.
I tested this manually.
stdout from the test being debugged:
```
Process 16662 is waiting for debugger. To continue debugging, start gdb, `attach 16662`, `set var waiting=false`, and `fini`.
Process 16662 finished waiting.
```
stdout from gdb:
```
(gdb) attach 16662
Attaching to program: /opt/pytorch/nvfuser/build/test_multidevice, process 16662
[New LWP 16667]
`/opt/pytorch/nvfuser/build/test_multidevice' has changed; re-reading symbols.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000056388b5e7fc5 in nvfuser::MultiDeviceTest::waitForDebugger (this=0x7f7e2c41d800) at …
```
> Make it easier to `gdb` an `mpirun`.

- CMakeLists.txt
- csrc/multidevice/c10d_mock.h
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- setup.py
- tests/cpp/test_multidevice_pipeline.cpp
- tests/cpp/test_resharding.cpp
- tools/gen_nvfuser_version.py
This PR reverts #2155.
The reason for that is we are hitting the following error on Jetson:
```
Traceback (most recent call last):
File "/opt/pytorch/fuser/setup.py", line 423, in <module>
main()
File "/opt/pytorch/fuser/setup.py", line 365, in main
cmake()
File "/opt/pytorch/fuser/setup.py", line 303, in cmake
raise RuntimeError(
RuntimeError: nvFuser requires PyTorch to be built with USE_DISTRIBUTED on.
```
cc @wujingyue @xwang233
> Revert "Remove NVFUSER_DISTRIBUTED.  (#2155)"

- csrc/tensor_view.cpp
- tests/cpp/test_allocation_domain.cpp
`TensorView::clearReductionIterDomains` constructs new contiguity vector on root domain, causing validation assert when output's allocation domain is not identical to its root domain.
This PR patches the logic and adds a test.
> Fix TensorView::clearReductionIterDomains specifies wrong contiguity flag

- benchmarks/python/conftest.py
- benchmarks/python/test_dropout_layernorm_bwd.py
- benchmarks/python/test_dropout_rmsnorm_bwd.py
- benchmarks/python/test_layernorm_bwd.py
- benchmarks/python/test_rmsnorm_bwd.py
Marke the used scheduler in python benchmarks, so when a scheduler is changed, we can select which benchmark to run.
For example, this PR marked 4 cases as inner_outer_persistent.
If `inner_outer_persistent` scheduler is changed, we can select the corresponding benchmarks with `pytest /opt/pytorch/nvfuser/benchmarks/python/  -m inner_outer_persistent`
> mark used scheduler in python benchmarks

- README.md
GCC officially provides a list of versions being supported. We should use the same list. This list will be a guidance for our decisions on things like, should we upgrade C++20?
> Specify supported gcc versions as the officially supported versions

- csrc/ir/interface_nodes.h
- csrc/tensor_view.cpp
- tests/cpp/test_mma.cpp
As a first step to supporting allocation domain in our matmul scheduler, this unit test demonstrates how we can use reordering to extend scheduling a Mma op when the input Tensorview (B) has an allocation domain.
The next PR on top this will extend the scheduler to support a strided input B in a unit test that schedules a matmul.
> Unit test for scheduling a Mma op where input B has an allocation domain.

- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/ir/interface_nodes.h
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- csrc/tensor_view.cpp
- tests/cpp/test_mma.cpp
This PR fixes the schedule and lowering of Hopper MMAs. Please see my own review on this PR for detail.
After https://github.com/NVIDIA/Fuser/pull/2194, the schedule and lowering of MMA finally makes sense now.
Note that MMA is still limited to have only one tile in smem. Supporting multiple tiles is the next step.
> Fix schedule and lowering of Hopper MMAs

- csrc/sys_utils.cpp
- csrc/sys_utils.h
- tests/cpp/test_alias.cpp
`FusionProfiler` and compute-sanitizer both use CUPTI, and running multiple CUPTI tools is not supported. Disabling two tests using FusionProfiler when compute-sanitizer is detected. Since using compute-sanitizer is supplemental and there are only two of affected tests, just disabling seems fine to me.
I didn't know about `dl_iterate_phdr` but just learned from Perplexity.
> Skip tests using FusionProfiler when compute-sanitizer is used

- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/lower_communication.cpp
- csrc/multidevice/lower_communication.h
- tests/cpp/test_multidevice_communications.cpp
This PR prepares for integrating Communication/Communicator into FusionExecutor. The lowering of a communication will be done by `FusionExecutor::compileFusion`, which is done <= once per shape and where sometimes only meta tensors are available. The execution will be done by `::runFusion`, which is on the critical path.
> Separate the lowering and the execution of a communication.

- csrc/scheduler/matmul_utils.cpp
- tests/cpp/test_matmul_scheduler.cpp
For #2199 
Broadcasts before Mma are optional. matmul_expr_eval still has problems with this, but I'll file a separate issue for that.
> Remove outdated checks from the matmul scheduler. 

- csrc/scheduler/matmul_utils.cpp
Temporarily have Hopper use Ampere matmul schedules in getMmaOp. 
This is so that distributed matmul tests can pass CI on H100s.
> Temporary hopper case for getMmaOp

- tests/cpp/test_matmul_scheduler.cpp
This adds a C++ test that checks that an external matmul heuristic plugin is loaded. This is useful in automated jobs where we build a matmul heuristic plugin and run some benchmarks. Without this test it is possible to improperly prepare the environment and wind up running benchmarks with the default core heuristics. Instead we can first run this test and fail the job early if it does not succeed. The test is disabled by default so that it does not cause default builds to fail. To run it use a command sequence like this:
```
export NVFUSER_MATMUL_HEURISTIC_PLUGIN=/path/to/plugin.so
build/test_matmul --gtest_also_run_disabled_tests --gtest_filter='MatmulSchedulerTest.DISABLED_RequireExternalPlugin`
```
> Add test that external matmul plugin is loaded properly

- tests/cpp/test_gpu_outer_reduction.cpp
Issue:
The current Shmoo test of iter grouped grid reduction relies on input sizes, its coverage of heuristic parameters depends on how the heuristics is generated.
Fix:
This PR introduces another Shmoo test that spans 7 heuristic parameters improving the test coverage.
> shmoo test of iter grouped grid reduction

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- tests/cpp/test_id_model.cpp
This is the final step of the loop promotion analysis. The promotion map is almost completed at Step 3, but some partially inlined domains need one more propagation, which is done by Step 4 and Step 5. Step 5 is mostly just a repeat of Step 3.
This basically concludes the loop promotion analysis, although there are a couple of issues that were found while working on indexing (#2218). Those issues will be addressed as further follow-up PRs.
- Step 1: #1650 
- Step 2: #1777 
- Step 3: #1830 
- Step 4: #2003
> IdModel: Step 5 of the loop promotion analysis

- csrc/dispatch.h
- csrc/ir/all_nodes.h
- csrc/ir/base_nodes.h
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- csrc/multidevice/lower_communication.cpp
- csrc/multidevice/lower_communication.h
- tests/cpp/test_multidevice_communications.cpp
This PR makes the "Communication" class a proper IR inheriting from Expr. This patch is needed for implementing Host Irs. It is also one step towards making the Communications (and more generally the multidevice module) fully symbolic.
By the way, we proceed to a couple of refactoring, and remove `Communicator::sendRecv` method.
Remarks:
1) This IR will be used for now in the context of Host Irs. Later, they could also serve as kernel IR (backed by device-side communication APIs at runtime).
2) Before this patch, we had a base class `Communication` and one derived class per collective type (Allgather, Allreduce, Broadcast, etc.). Now, there is only the class `Communication`, and the collective type is encoded through an enum class `CollectiveType` added to the parameter member …
> Make Communications IRs inheriting from Expr.

- runtime/grid_reduction.cu
In iter grouped grid reduction,threads with `TIDy == 0` in each block, write block reduction results to global memory for final grid reduction. 
When vectorized by 8, each thread writes 8 x sizeof(fp32) = 32 bytes, which exceeds the max vect write width of 16 bytes. In current main branch, the write is split into 2 vectoried writes without changing the data layout in global memory. It leads to a problem similar to using AoS. As shown in the figure, to serve these 256 bytes of data, the main branch needs 4 transactions but if we change to the bottom version, only needs 2 transactions.
After this change, the gmem store transaction is reduced but **no apparent influence on performance** since the memory bandwidth is dominated by the loading of the input tensor. The cache also helps the …
> ensure coalesced gmem access when each thread has 32 bytes

- csrc/multidevice/communication.cpp
- tests/cpp/test_multidevice_pipeline.cpp
Fixes a subtle [bug](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/92948751), exposed by #2168
> Fix bug in scatter

- csrc/executor_utils.cpp
- runtime/block_reduction.cu
- tests/cpp/test_gpu3.cpp
**Issue:**  smem_offset is the offset into shared memory for the current thread. It is calculated as:
` offset = reduction_idx * reduction_size + reduction_tid`.
For outer reduction where TIDy is in the reduction dimension and TIDx is in the iteration dimension and TIDz is not used.
We have `reduction_tid = TIDy` and `reduction_idx = TIDx`. The offset leads to stride access to shared memory since it equivalent to: `offset = TIDx * blockDim.y + TIDy`
**Fix:** To avoid this, we should use the offset based on the indexing of threads within a block.
`offset= threadIdx.x + threadIdx.y * blockDim.x + threadIdx.z * blockDim.x * blockDim.y;`
After this change, the index of the reduction peer element is no longer a simple offset with a stride of 1, it depends on the reduction dim. See code change …
> ensure coalesced access to shared memory in block reduction

- csrc/ir/graphviz.cpp
- csrc/ir/graphviz.h
This is a simple debugging utility that I started using for IdModel. Thought it may be of useful in general.
I'm not a Graphviz expert but just tried a bunch of things to make it the output look reasonably good to me. Any suggestions would be appreciated.
Here's an example output. The fusion is from one of the reshape shmoo tests.
> Generate a DOT representation of fusion transform.

- csrc/scheduler/matmul_utils.cpp
This small PR just ensures we won't accept matmul segments that we cannot schedule.
> Check that device is supported in matmul canScheduleCompileTime

- csrc/ir/nodes.cpp
- tests/cpp/test_gpu3.cpp
`TensorDomain::merge(i, j)` used to enforce merging outer and inner domains as the outer and inner input to the `Merge` expr. This changed a while ago to allow reordered merge, but the change was not enough.
This part assumes `axis_i` is larger than `axis_o`, which is not the case when `i` refers to an outer domain like below:
```
auto tv0 = makeSymbolicTensor(2);
fusion.addInput(tv0);
auto tv1 = set(tv0);
fusion.addOutput(tv1);
tv1->merge(1, 0);
```
> Fix: invalid TensorDomain after reordered merge

- csrc/val_graph_visitor.cpp
- csrc/val_graph_visitor.h
- tests/cpp/test_id_model.cpp
(Extracted from #2238)
Traversal for finding the shortest path from ValGroups to another ValGroups. The algorithm is based on the standard BFS traversal, however, since ValGraph is not an undirected graph, the dependencies of ValGroups and ExprGroups need to be
satisfied. Specifically, when visiting an ExprGroup, either its inputs or outputs must be visited before. Similarly, when visiting
a ValGroup, there must be at least one defining ExprGroup or one use ExprGroup that is already visited.
The main use case is tensor indexing (#2238), where a typical traversal would be from loop domains to allocation domains. Some indexing-specific specialization would be needed, for example, dependencies with broadcast domains can be ignored as their index is always just zero. The indexing …
> Shortest path between ValGroups in ValGraph

- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/mma_type.h
- csrc/scheduler/matmul.cpp
- csrc/tensor_view.cpp
- tests/cpp/test_matmul_scheduler.cpp
Besides, using `enum class UnitDim { K, M_or_N };` for representing what is the inner dim is a less confusing term.
> Kill `MmaOp::layout`

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/dynamic_transform.cpp
- csrc/python_frontend/fusion_record.h
Thanks to the suggestion by @zasdfgbnm while reviewing #2272, I found some additional cases where we took a short-cut to updating bools using the bitwise assignment ops. This is not ideal since its behavior is undefined (there's no guarantee that the underlying representation of `true` is `b1` and not `b10` or any other non-zero value). More importantly, writing `a |= b` as `a = a || b` allows us to short-circuit if `a == true`. Using bitwise `a |= b`, `b` will always be evaluated.
> Replace bitwise assignment ops on bools

- csrc/mma_type.h
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
We already have `MatmulRole::OUTPUT_D`. We populate both of these by reverse sorting all outputs that are downstream of the `MmaOp` first by number of uses then by `name()`. The first in that reverse sorted list is `OUTPUT_D` and all others are `OUTPUT_AUX`. After this PR, there is only the `OUTPUT_D` list but it might have more than one element: namely the former `OUTPUT_AUX` tensors are now appended in the same order to the `OUTPUT_D` list in the roles map.
I believe the main reason to reverse sort by uses is to find a reference tensor for reverse propagating transforms to epilogue inputs here: https://github.com/NVIDIA/Fuser/blob/0892405e5396820ffc4a300cba916cd6cb65e6be/csrc/scheduler/matmul.cpp#L660-L672
There should be no change to this section since we have not changed the first …
> Remove MatmulRole::OUTPUT_AUX

- csrc/scheduler/mma_utils.cpp
This was a change I made to handle casts that wound up breaking some tests and benchmarks in #2272, leading to dynamic cast errors or segfaults. The solution is to test the type of the left and right hand sides before processing the pattern matching.
> Do not assume mul-sum pattern inputs are TensorView

- benchmarks/python/core.py
PR: https://github.com/pytorch/pytorch/pull/125510 updates `torch.profiler` to increment to the Events list for a profiler instance instead of resetting the list to start afresh after `prof.stop`. This leads to the time measurements being accumulated which caused the benchmarking numbers to drop in the last week. Thanks to @xwang233 for identifying this.
Example for the difference in functionality:
```
prof.start()
target_fn()
prof.stop()
prof.start()
target_fn()
prof.stop()
```
> Clear `profiler` object to avoid `FunctionEvent` accumulation

- csrc/device_lower/lower2device.cpp
- csrc/id_model/loop_promotion.cpp
- tests/cpp/test_id_model.cpp
Fixes #2296 
In addition to stopping at view rfactor domains as mentioned in the issue page, I also put in a quick shortcut for the case where a view rfactor domain is a terminal domain. In that case, it's guaranteed that the domain is the right promotion domain. This is a shortcut and not strictly necessary for the correctness of the analysis, but I think it's simple enough to have as a quick optimization.
> Loop promotion fix for loop groups with view rf domains

- tests/cpp/test_gpu_outer_reduction.cpp
The newly added test takes about 35s on H100.
```
[ RUN      ] OuterReductionTest.IterGroupedBlockReductionShmooTests
[       OK ] OuterReductionTest.IterGroupedBlockReductionShmooTests (35704 ms)
```
Code change:
(1) The lambda test function in `IterGroupedGridReduction` is moved to a separate function to support both grid reduction & block reduction.
(2) Added `IterGroupedBlockReductionShmooTests`
> add shmoo tests of iter grouped block reduction

- csrc/scheduler/mma_utils.cpp
This fixes a bug introduced by #2272 in `test_multidevice` where we reject a matmul segment shaped like `[iDIDxMo, iMi, bN, iK]` for having too many M dimensions. Locally this still has a single M dimension so it is valid. This PR ignores device dims for the purposes of computing tensor roles and problem shape.
Further issues we should look into:
1. As mentioned in #2272 we should proceed to handle multiple M, N, K, and Batch dimensions, although in this case the restriction was useful for surfacing this bug.
2. Even if the matmul scheduler is completely broken or disabled, the _reduction_ scheduler should have been able to schedule this fusion. However, it identified the reduction tensor as `isResharding` and removed it from the `reduction_tvs` list, causing a failure in …
> Compute matmul dim roles with no-devices leaf domain

- lib/dynamic_type/CMakeLists.txt
- lib/dynamic_type/README.md
- lib/dynamic_type/meson.build
- lib/dynamic_type/src/dynamic_type/dynamic_type.h
- lib/dynamic_type/src/dynamic_type/type_traits.h
- lib/dynamic_type/test/dispatch.cpp
- lib/dynamic_type/test/examples.cpp
- lib/dynamic_type/test/typing.cpp
Please see the update in the `README.md` for description. 
This PR also updates `DynamicType`'s conversion operator to use this mechanism for testing purposes. In a followup PR, more operators will be changed to use this mechanism.
> Add `DynamicType::dispatch` as a general mechanism for dispatching function calls

- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/reduction.cpp
This PR makes the reject messages for reduction and normalization schedulers consistent.
> Cleanup reject messages for reduction and normalization schedulers

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
Currently, there's an assertion failure with `InstanceNorm3d_channels_last_fp32/1/32/128`:
```
what():  c_ids.size() == 1 INTERNAL ASSERT FAILED at "csrc/id_model/id_model.cpp":571, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. multiple sibling mapping: iS505{( (( (( getMetaData(T1) )).logical_size ))[0] )} mapped to  iS510{( (( (( getMetaData(T1) )).logical_size ))[0] )} iS511{( (( (( getMetaData(T1) )).logical_size ))[4] )} iS431{( ( (( (( getMetaData(T1) )).logical_size ))[0] ) * ( (( (( getMetaData(T1) )).logical_size ))[4] ) )}
```
This happens when building sibling mappings. Originally it was using the exact graph to find mappings between siblings, but it was recently changed to use the permissive graph (#2290), so mappings are not …
> Loop graph: Remove an assertion that no longer holds

- csrc/device_lower/lower2device.cpp
- csrc/id_model/loop_promotion.cpp
- csrc/id_model/loop_promotion.h
- tests/cpp/test_id_model.cpp
Fixes #2261 
Instead of blindly propagating the Step-3 results, just propagate those that matter for partially inlined groups. This fixes the issue of #2261 as well as works as a shortcut if there's no partially inlined groups.
> Loop promotion fix for #2261

- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/lower_communication.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
As a follow up to #2172. `mesh` will eventually go away after the input and output TensorViews of a communication are embedded in the base Expr. Anyhow, `is_root_in_mesh` can be computed from other parameters so is removed.
> Remove `is_root_in_mesh` from CommParams and add `mesh`. 

- tools/codediff/compare_codegen.sh
This prevents *.ptx files cluttering $CWD when a local run is interrupted or fails.
> Back up PTX files when compare_codegen.sh fails

- csrc/host_ir/executor.cpp
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/lower_communication.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
I initially intended to just make CommParams a data attribute. Then I realized the extra indirection of CommParams doesn't seem to give much practical value after various cleanups we've done, so I flattened CommParams as well and that saved a bit of typing.
> Remove CommParams and make the fields there data attributes.

- csrc/compute_at_map.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/transform_replay.cpp
- csrc/id_model/validation_utils.cpp
- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/python_frontend/python_bindings.cpp
- csrc/tensor_view.cpp
- csrc/transform_iter.cpp
- csrc/transform_replay.cpp
- csrc/transform_view.cpp
Was only used with shift, which was removed in #2299.
> Remove trim_out_of_bounds

- csrc/ir/interface_nodes.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- csrc/tensor_view.cpp
- csrc/utils.h
- tests/cpp/test_matmul_scheduler.cpp
In this PR we extend the matmul scheduler to support inputs with allocation domains.
To the fusion (with inputs tv_a and tv_b), we add two LoadStoreOps to both inputs.
The first Op corresponds to a load to shared memory, where we propagate the allocation domain. The second op corresponds to reading to registers, where we don't propagate the allocation domain since the scheduler takes charge of setting the allocation domain in the registers. Based on the difference in the (maybe)allocation domain of the producer and consumer of the second LoadStoreOp, we may do transposed load when reading to registers.
See also https://github.com/NVIDIA/Fuser/pull/2315.
> Handling allocation domain of the input TensorViews in the matmul scheduler 

- csrc/device_lower/pass/fusion_simplifier.cpp
- csrc/device_lower/validation.cpp
- csrc/dynamic_transform.cpp
- csrc/grouped_reduction.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/ir/builder.cpp
- csrc/ir/builder.h
- csrc/ir/container.cpp
- csrc/ir/nodes.cpp
- csrc/mutator.cpp
- csrc/ops/alias.cpp
- csrc/ops/arith.cpp
- csrc/ops/composite.cpp
- csrc/ops/normalization.cpp
- csrc/tensor_view.cpp
- csrc/transform_replay.cpp
- csrc/transform_rfactor.cpp
- csrc/transform_view.cpp
- tests/cpp/test_gpu_fused_reduction.cpp
- tests/cpp/test_host_irs.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
- tests/cpp/test_predicate_elimination.cpp
As a follow-up to https://github.com/NVIDIA/Fuser/pull/2312#discussion_r1625015218.
Currently, the two flavors of `IrBuilder::create` both accept variadic template arguments and therefore require the caller to type perfectly.
> Replacing one flavor of `IrBuilder::create` to `createInContainer`.

- csrc/compute_at_map.cpp
- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/pass/unroll.cpp
- csrc/device_lower/pass/warp_reduce.cpp
- csrc/dynamic_transform.cpp
- csrc/expr_simplifier.cpp
- csrc/fusion.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/nodes.cpp
- csrc/ops/alias.cpp
- csrc/ops/arith.cpp
- csrc/preseg_passes/remove_empty.cpp
- csrc/scheduler/vectorize_helper.cpp
- csrc/tensor_view.cpp
- csrc/val_graph.h
- tests/cpp/test_expr_simplifier.cpp
- tests/cpp/test_gpu3.cpp
When talking about design decisions in `DynamicType`, there are some subtle details that is hard to tell which is the best decision. For example, `at::Tensor == at::Tensor` returns an `at::Tensor`, but some C++ code assumes `operator==` always returns `bool`. For this case, should we make `PolymorphicValue == PolymorphicValue` always return `bool` and disable `at::Tensor == at::Tensor`, or make it return `PolymorphicValue` which is a superset of `bool` and can be casted to `bool`? There is no clear answer to this question. None is perfect, it's just a matter of choosing which bad you want to take. So far, I believe the decision is based on whatever the behavior is that makes `DynamicType` codebase simple.
Recently, I added `DynamicType::dispatch`, which is primarily for supporting …
> Convert from dynamic type to static type early

- csrc/disjoint_set.h
- csrc/id_model/schedule.cpp
- csrc/id_model/schedule.h
- csrc/val_graph.h
- tests/cpp/test_abstract_tensor.cpp
Currently, functions in `id_model/schedule.{h,cpp}` will invalidate the input `ValGroup` because it will create a new `ValGroup` with a new ID and map that new group with the input group. This is annoying and unnecessarily expensive. This PR changes the behavior by just appending the new ID into the existing `ValGroup`.
> Don't invalidate existing ValGroup when not necessary

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.cpp
The newly added `initializeVal` can avoid destroying existing ValGroup and creating new ValGroups.
> Clean up `IdModel::addReplayAs` to avoid unnecessary data movement

- csrc/device_lower/lower2device.cpp
- csrc/id_model/id_model.h
Disabled the validation with ComputeAtMap as it's costly. Still enabled in DEBUG build
> Disable IdModel validation by default

- tests/cpp/test_id_model.cpp
Previously an exception was thrown by ComputeAtMap when the validation of IdModel was done. Now that the validation is disabled by default, the error message changed.
> Test error fix

- tests/cpp/test_indexing.cpp
Fixes a failure of `IndexingTest.SimplePointwise1`.
```
IrBuilder::getItemExpr(
IrBuilder::getAttrExpr(
IrBuilder::metadataExpr(tv0), "alloc_stride"),
(int64_t)0)));
```
This was fine with clang, but with gcc `(int64_t)0` was interpreted as `nullptr`.
> (int64_t)0 is interpreted as nullptr with gcc

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- tests/cpp/test_id_model.cpp
Mostly just copied from https://github.com/NVIDIA/Fuser/blob/main/csrc/compute_at_map.cpp#L784
> Propagate parallel types in loop graph

- csrc/scheduler/reduction_utils.cpp
- tests/cpp/test_gpu_outer_reduction.cpp
**Issue:** when have multiple outer reductions in a fusion, if vectorized, only the first reduction tv is grouped.
**Fix:** ensure all reductions are grouped
**Influence:** about 1.1x speedup for case `NvFuserScheduler_BiasDropoutAddLayernormBwd1_tf32/1024/128/864/manual_time`, the name is confusing, it is just a simple fusion with 2 reductions. Before this PR, the first reduction is using iterGroupedGridReduction while the 2nd reduction uses regular grid reduction. After this PR, both reductions use iterGroupedGridReduction.
```
Inputs:
T0_g[ iS0{i0}, iS1{i2}, iS2{i3} ], float
T1_g[ iS27{i0}, iS28{i2}, iS29{i3} ], float
T2_g[ iS30{i0}, iS31{i2}, bS8{1} ], float
T3_g[ iS35{i0}, iS36{i2}, bS11{1} ], float
Outputs:
T6_g[ rS18{i0}, rS19{i2}, iS20{i3} ], float
T8_g[ rS24{i0}, rS25{i2}, …
```
> iter grouped multiple reductions

- csrc/dynamic_transform.cpp
- csrc/ir/nodes.cpp
- tests/python/test_python_frontend.py
The included test is the small one provided by @jjsjann123 in #2359 and it's actually tougher than the original repro. It necessitates either removing the check that concretized squeezed extents are constant 1 or to concretize Resized to broadcast extents as constant 1 so that we can evaluate `max(0, min(i0, 1))` as `oneVal()` without calling `simplifyExpr`. I went with removing the check, which means in this example we have broadcast dimension with a dynamic shape like `max(0, min(i0, 1))`. Since we're concretizing to Broadcast, we know that dimension is not zero; if it were then we'd concretize to `Iteration` and `SqueezeOp::checkConcretization` would fail the IterType check. Still, I don't love that the expression cannot be simplified so it appears in the kernel (`i9` and `i10`): …
> Move checkConcretization for reshapes

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- tests/cpp/test_multidevice_host_ir.cpp
Bootstrapping for simplifying the design. With this patch, the `Communication` class is used to post a collective, without the need of wrapping it inside a `PostOnStream` Ir.
There is no functional change, this is only a minor cleanup I would like to upstream before introducing the "collective wait" IR.
To achieve this, we need to add I/O TVs to the `Communication`'s constructor, and use those I/O directly. This patch aligns with the discussion from https://github.com/NVIDIA/Fuser/pull/2250 and should lead to further simplification in `MultiDeviceExecutor`, that I would like to leave to another PR for avoiding conflicts.
Note that the `Communication` class is used in two places: Host IRs and `MultiDeviceExecutor`. Since the former case should replace the latter eventually, we maintain for …
> Host irs: use `Communicator` directly instead of wrapped inside `PostOnStream`

- benchmarks/python/test_reduction.py
I think this explains why we didn't see any baseline results of reduction benchmarks from the weely runs
> fix reduction python benchmark

- csrc/ops/arith.cpp
This just opportunistically uses our unscaled runtime functions instead of the parametrized ones whenever we detect that the input parameters are constant 0 and 1.
I thought nvcc would remove an identity transformation like `(x * 1 + 0)` automatically but the PTX diff shows 8 removed add(0) instructions in `tests/python/test_python_frontend.py::TestNvFuserFrontend::test_nanogpt_mha_dpa`. This is also reflected in the SASS (for sm80).
> Use standard {uniform,normal} if params are 0, 1

- csrc/dispatch.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_multidevice_host_ir.cpp
add an equivalent to `c10d::Work::Wait` primitive as a host IR, to allow asynchronous execution of communications
Assuming https://github.com/NVIDIA/Fuser/pull/2384 is merged, the following illustration proves that we achieve overlap:
This illustration is generated from the test unit `Manual/MultiDeviceHostIrTest.SingleCommTwoFusionAndWait/useFusionExecutorCache_withShardingAnnotations` with 8 devices. In this test, we run the following comms, wait and compute primitive, with no data depedency:
```
compute
communication
wait
compute
communication
compute
wait
compute
```
The first `compute` `communication/wait` triggers some initialization overhead and are not representative. The profile screenshot displays on the last operations: communication, compute, wait, compute, and we can see …
> Host irs: add wait IR

- csrc/multidevice/communication.cpp
`allgather` primitive in c10d induces extra buffering time to copy out the received tensors into user buffer. It is therefore always preferable to use `_allgather_base`, which does not perform any extra copy at the cost of assuming that the receive buffers are placed contiguously.
Illustration, with `allgather`, you can see the red segment indicating `cudaMemcpyAsync`:
With `_allgather_base`, the `cudaMemcpyAsync` disappear
> Replace `allgather` by `_allgather_base`

- csrc/dynamic_transform.cpp
- csrc/dynamic_transform.h
- csrc/id_model/to_string.cpp
This just uses the pre-existing utility in `ir/iostream.h` instead of `ss << indent` style indenting.
> Use indent utility in dynamic_transform/id_model toString functions

- runtime/grid_sync.cu
Prior to this, we could potentially have a data race during split-K reduction. This missing fence is somewhat similar to that recently reported in https://github.com/pytorch/pytorch/pull/128455. Our `gridReduce` contains the proper fence already (inside `grid_sync::sync`), so this vulnerability only impacts split-K.
> Add threadfence to grid_sync::blockSerializeRelease

- benchmarks/python/test_pointwise_mul.py
- benchmarks/python/test_simple_pointwise.py
**What is in this PR?**
add a simple pointwise benchmark
```
def simple_pointwise_fwd_fn(inputs: list):  # in_tensor
return torch.mul(inputs[0], inputs[0])
```
**Why need to add this?**
(1) serve as a basline to check the best bandwidth we can expect for a specific problem size
(2) check whether the device is healthy.
**Current performance:** see [link](https://docs.google.com/document/d/1FtIU_s-iw_Q9C7psdJn5FMp9ApKdzqdkJe4p6R9TQkU/edit?usp=sharing).
> add pointwise benchmark

- tests/python/pytest_input_generators.py
- tests/python/pytest_opinfos.py
This PR is meant to fix the errors like this which have plagued our CI for a while now.
```
...
E       Mismatched elements: 1 / 1048576 (0.0%)
E       Greatest absolute difference: 0.002183660166338086 at index (785, 78) (up to 0.001 allowed)
```
The problem is that we generate samples uniformly in the range [-9, 9) for both numerator and denominator. We exclude zero itself (`exclude_zero=True`) and we don't add specific small values (`enable_small_value_testing=False`) but we don't currently _exclude_ small sampled values other than zero. This PR just excludes small values (only in the denominator) and uses this sample generator for div and truediv tests that have floating point dtypes.
> Avoid small denominator in pytest division samples

- csrc/dispatch.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_multidevice_host_ir.cpp
Pick up from #2338 which introduced [a bug](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/97151941#L925) and has been reverted in #2399
We apply the same patch here, plus [an additional commit](https://github.com/NVIDIA/Fuser/commit/d292a5fe9f7d86860aa4f4e9e479dd809a115843) that fixes the bug. The fix is to add a "wait" primitive after the collective is posted in the test `MultiDeviceHostIrTest.SingleFusionSingleComm`.
> Host irs/add collective wait

- csrc/mma_type.h
- csrc/ops/composite.cpp
- csrc/ops/utils.cpp
- csrc/ops/utils.h
- csrc/root_domain_map.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/matmul_utils.h
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
Also rename `MatmulRole::INPUT_C` to `MatmulRole::EPILOGUE_INPUT` and `MatmulRole::OUTPUT_D` to `MatmulRole::OUTPUT`. This is in preparation for generalizing our scheduler to handle any number of operands and `MatmulPattern`s.
Even when fusing a single `MatmulPattern` we might not have exactly one Fusion input for A or B. We could have zero if we use a factory method to create the operand, or we could have two if we do some pointwise operations in the prologue. I am trying to refactor our code to handle any of these cases gracefully.
Next steps in generalizing the matmul scheduler:
1. Change `MmaLayout` from an enum to a vector of inner allocation dimensions i.e. `std::vector<MatmulDomain>`. After that, the only reference to "A" and "B" will be the inputs to the actual MmaOp.
2. Modify …
> Combine MatmulRole::INPUT_{A,B} into MatmulRole::OPERAND

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/pointwise.h
- csrc/scheduler/pointwise_utils.h
- csrc/scheduler/utils.cpp
- tests/cpp/test_pointwise.cpp
Makes the pointwise scheduler DID compatible by ignorning DID axes from analysis and scheduling operations. It will schedule the compute of sharded pointwise fusion identically to its equivalent single device fusion.
Modifications:
- Remove DID extents from `getPointwiseHeuristics` so that any size based calculations (e.g. break point) only analyze allocated sizes.
- Inside `schedulePointwise`, DID axes are reordered to the front of the leaf domain. In the 2D scheduler merged axis are adjusted to ignore DID axes.
> Sharded pointwise scheduler

- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- tests/cpp/test_multidevice_matmul.cpp
Add `MultiDeviceExecutor::getFusionExecutorCaches` which returns a vector of pointers to the multidevice executor's fusion executor caches.
Note, Also renames the field `workspace` to `workspace_` to match naming conventions. 
cc @Priya2698 for https://github.com/NVIDIA/Fuser/pull/2386
> Multidevice Executor add accessor to fusion executor caches

- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_heuristic_plugin.h
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- tests/cpp/test_gpu_tensorcore.cpp
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/utils.cpp
- tests/cpp/utils.h
This is related to #2419 which is working toward generalizing our scheduler to handle any number of operands instead of exactly 2.
In order to keep the change small, I introduced a `MmaLayout getMatmulProblemLayout(Fusion*)` utility in `tests/cpp/utils.cpp`. This should give the same result that `mma_utils::getProblemLayout(fusion)` used to give, but asserting instead of wrapping in a `DataWrapperOpt`, so we don't need to change our supported layouts much. For new code, we could change to support vectors of inner dimension roles instead.
After this PR, `MmaLayout` should only be used in these places
- In `MmaOpUtils::getInputLayout` which finds the layout of the actual inputs to the `MmaOp` (not the Fusion inputs). This is the correct location to use `MmaLayout` since `MmaOp` supports a …
> Change getProblemLayout to getOperandInnerDims

- csrc/id_model/indexing.h
When writing analysis, we might store `ValGroup`s instead of `IterDomain`s as the result of the analysis, for the convenience of usage. It could be important to use the `ValGroup`s belonging to the same IdGraph as the indexer. So I make this public so analysis writer could access and write their analysis based on this graph.
> Make `TensorIndexer::traversalGraph` public

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
Will be used for indexing TMA, so make them public
> Add `TensorIndexer::computeIndex(valgroups)`

- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
Adds a fine grain control of the Communicator's backend cache
The `Communicator` is used as a singleton instance managing the different backends for communication. It internally holds a cache of the previously created backend to avoid the costly initial overhead of ProcessGroup creation.
One the one hand, it is important that this caching occurs at the Communicator's level and not at the caller site, because the communicator exists globally accross test instances.
On the other hand, in order to achieve communication/communication overlap, one must use multiple backends because each backend has one and only one internal stream on which it posts kernels.
We add an optional `std::string prefix=""` argument to the function `Communicator:: getBackendForTeam` that is prepended to the key used …
> Add prefix option to the communicator's backend cache

- tests/cpp/test_multidevice_matmul.cpp
Issue #2372.
Modifying the tests to use `matmul` in place of `mul-sum`.
Note: `matmul` API requires the logical shapes `[M,K] x [K,N]` and the output has the same dtype as the input.
> Use `matmul` in distributed tests

- csrc/ops/composite.cpp
- csrc/ops/utils.cpp
- tests/cpp/test_combine_mul_sum.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
Removing special handling for some cases in `MatmulOp` to avoid any performance regressions as compared to ATen, particularly for gemmv cases.
> Modify `matmul` API to always create `MatmulOp`

- csrc/preseg_passes/allocation_order_inference.cpp
- tests/python/test_python_frontend.py
Fixes #2354 
Disables allocation order inference propagation for matmul/mma/linear.
> Allocation domain inference patch mma like op

- csrc/fusion.cpp
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- csrc/multidevice/lower_communication.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
- tests/cpp/test_multidevice_matmul.cpp
The other constructor is still used in some tests. 
Communications created by the new constructor must be put in a non-SSA IrContainer. This is because multiple Communications can have the same input and output TensorViews, e.g., Gather with a receiver mesh of size 2.
> Add another constructor of `Communication` that takes I/O TensorViews instead of the mesh. 

- csrc/mma_type.h
- csrc/scheduler/matmul.cpp
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_matmul_scheduler.cpp
This is not a full reversion of #2419, which also renamed `INPUT_C` and `OUTPUT_D`, and made some modifications to
`map{Linear,Matmul}OpIterDomains`. This preserves those changes but allows us to keep distinguishing A and B operands.
Fixes #2434
> Split MatmulRole::OPERAND into OPERAND_{A,B}

- csrc/python_frontend/fusion_definition.cpp
Fixes #2430 since we _should_ error here but we _should not_ segfault ever.
> Check that users don't call `FusionDefinition` methods from uninitialized definitions outside a Python Context Manager or `definition()` method

- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/preseg_passes/exact_mapped_extent_substitution.cpp
- tests/cpp/test_gpu3.cpp
In the past, it was assumed that domains in a `TensorDomain` has linear structure `root -> logical -> allocation -> leaf`. I am removing this restriction. As the step 0 of the removal of this restriction, I am modifying the `validateDomainEquivalence`, which is called in the constructor of `TensorDomain`, to support arbitrary dependency order.
> Allow domains to be decoupled: validateDomainEquivalence

- csrc/scheduler/transpose.cpp
- tests/python/test_python_frontend.py
Issue #2317.
The issue arises in the following lines for reference 1: `[I0, I1, I2, r3]`:
After tiling:
```
reference1->split(inner_most_pos1_in_ref1, params.tile_size1);
reference1->reorder({{inner_most_pos1_in_ref1 + 1, -1}});
reference1->split(inner_most_pos2_in_ref1, params.tile_size2);
reference1->reorder({{inner_most_pos2_in_ref1 + 1, -1}});
```
Reference 1 is: [I0, I1/tile1, I2/tile2, r3, tile1, tile2]
```
// Merge remaining dimensions
int64_t lhs_i = -1;
for (int64_t i = reference1->nDims() - 2; i > 0; i--) {
auto axis_i = i - 1;
if (lhs_i == -1) {
lhs_i = axis_i;
} else {
reference1->merge(axis_i, lhs_i);
lhs_i = axis_i;
}
```
This tries to merge a reduction iterdomain with iteration type iterdomain.
This PR ignored the reduction axis when merging all non-tile dimensions.
> Transpose Scheduler: Ignore reduction axis in merge

- csrc/device_lower/analysis/tma.cpp
- tests/cpp/test_memory.cpp
Adding a test which mimics the way we'll be loading inputs for a matmul (which will one dimension being a broadcast dimension).  The figure below illustrates the scheduling strategy I use.  The broadcast dim is first pulled out, and then we schedule to achieve the layout explained here (https://github.com/NVIDIA/Fuser/blob/main/doc/dev/tma/swizzle.svg)
> Unit test for a TMA load of a TV with a dimension that is broadcast

- tests/cpp/test_gpu_view.cpp
Issue: #2463 
This is the 1st PR to change shmoo tests from test_f to test_p
namespace is used to avoid potentail name conflicts e.g. when have multiple suites using same named para structures and functions to generate paras.
> change FusionReshapeReductionShmoo from test_f to test_p

- csrc/dynamic_transform.h
I just noticed a typo in this signature and decided to fix it, then realized it's probably unused so I figured I'd just remove it.
> Remove unused method DynamicTransformInitialInfo::operator==

- csrc/id_model/indexing.cpp
Looks like in some of my PR, I failed to clean it up
> Remove `replaceValRecursively` from `TensorIndexer::computeIndex`

- csrc/abstract_tensor.cpp
- csrc/abstract_tensor.h
- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/scheduler/matmul.cpp
- csrc/type.h
After this PR, `swizzleSharedMemory` will no longer modify the tensor that should be swizzled. Instead, it returns an `AbstractTensor` that contains the swizzled domain. For now, this domain must be set as the loop domain of the swizzled tensor.
In the future, I will modify `swizzleSharedMemory` to use the new `Swizzle` instead of the deprecated `Swizzle2D`. The returned domain of `swizzleSharedMemory` will be the allocation domain instead of the loop domain of the swizzled tensor.
When everything is done, `Swizzle2D` will be removed.
> Refactor `swizzleSharedMemory` to return an `AbstractTensor`

- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- tests/cpp/test_mma.cpp
In the new unit test added we load the input B tensor to shared memory using TMA. These tests are for a single tile, where M=64, N=8 ... 256 and K=16. So for the TN layout B: {N, K} TT: {K, N}.  In the following figure we show how we tile the tensor to 4 loads. 
The figure below shows the scheduling for the above tiling. This schedule/tiling works for all inputs sizes (and TT and TN)
In addition to the above tiling/shedules, we could have scheduled the same shape above to reduce the number of TMA loads to 2 from 4. It's illustrated in the figure below. Please note that it correctly works for cases where we don't need to split the inner dimension. As future work we can try and make it work for all cases.
The schedule for the above tiling scheme is show below. This is illustrated in the …
> Adding unit tests to check TMA loads for input B

- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_combine_mul_sum.cpp
Previously we would generate this code for the epilogue in test `MatmulNodeTranslationTest.AutomaticSchedulerMatmulNode/2dA_2dB`:
```c++
__syncthreads();
#pragma unroll
for(nvfuser_index_t i147 = 0; i147 < 8; ++i147) {
nvfuser_index_t i148;
i148 = i53 + (1024 * i147);
Array<__half, 8, 8> T8;
#pragma unroll
for(nvfuser_index_t i149 = 0; i149 < 8; ++i149) {
__half T13[1];
T13[0]
= __float2half(T15[(i148 + i149)]);
float T3[1];
T3[0]
= __half2float(T13[0]);
float T4[1];
T4[0]
= sinf(T3[0]);
T8[i149]
= __float2half(T4[0]);
}
if ((b57 && (i62 < (-(32 * i147))))) {
loadLocalToGlobal<__half, /*vec_size=*/8, /*is_volatile=*/false>( &T5[(i55 + (i56 * i147))], &T8[0]);
}
}
}
```
With this PR, this becomes:
```c++
__syncthreads();
#pragma unroll
for(nvfuser_index_t i147 = 0; i147 < 8; ++i147) { …
```
> Skip round-trip cast when translating matmul and linear nodes

- csrc/device_lower/analysis/tma.cpp
This is a bug introduced in https://github.com/NVIDIA/Fuser/commit/5037d8a6a8f2056271282f87a20918142e2e375c but only get exposed by https://github.com/NVIDIA/Fuser/commit/57e3d4cc2d87f420fffb4b8f5a5a8a5bb352396c
cc: @protonu @rdspring1
> Fix TMA failure in CI

- csrc/host_ir/executor.cpp
- tests/cpp/test_host_irs.cpp
With this patch, we concretize the fusion inside `HostIrExecutor` before calling `FusionExecutor`.
Solves https://github.com/NVIDIA/Fuser/issues/2462
We also re-enable a test that was previously failing.
This has been lacking for a long time and this was preventing us to support some scenarios with dynamic shapes. We always made sure to never trigger those scenario, but with this patch we don't have this restriction anymore.
thanks @jacobhinkle for the recent patch https://github.com/NVIDIA/Fuser/pull/2465
We do not care to add the same patch to `MultiDeviceExecutor` because kernel execution will be removed there in favor of `HostIrExecutor` with https://github.com/NVIDIA/Fuser/pull/2457
> `HostIrExecutor`: Concretize fusions before calling `FusionExecutor`

- csrc/host_ir/executor.cpp
- tests/cpp/test_multidevice_overlap.cpp
We set the priority of Streams to "low" to match [torch's default API](https://github.com/pytorch/pytorch/blob/82c8fc3a2b500cded29b4bd6836b22f88e4d7047/c10/cuda/CUDAStream.h#L213), as request by @wujingyue [in this comment](https://github.com/NVIDIA/Fuser/pull/2401#discussion_r1653115772)
> Turn stream priority to low

- tests/cpp/test_gpu_view.cpp
**Issue:** Test function `reductionViewAddFusion` still loops over `has_implicit_broadcast = {true, false}`
**Fix:** move `has_implicit_broadcast` from test function to paras
**Further clean up:**
merged `ReshapeBeforeReduction` and `ReshapeAfterReduction` into `ReshapeReduction` by changing the para to:
```
struct ReshapeReductionParam {
ReshapeExample reshape_example;
bool has_implicit_broadcast;
bool reshape_before_reduction;
};
```
> merge all params into ReshapeReduction suite

- tests/cpp/test_mma.cpp
This adds a unit tests for a matmul (single tile) where both inputs are loaded to the shared memory. This builds on the PR (https://github.com/NVIDIA/Fuser/pull/2468)
> Adding a Hopper Matmul test for single tile with A and B read from shared memory (SS)

- runtime/memory.cu
This PR adds the `elect_sync` ptx wrapper, which elects a leader thread from a set of threads in a warp.
It will be used to replace `threadIdx.x == 0 && threadIdx.y == 0 && threadIdx.z == 0` predicate used in TMA circular buffering.
The common pattern is to select any thread from the first warp without creating a serialized, peeling loop.
Code example: 
```cpp
if (threadIdx.x / 32 == 0 && ptx::elect_sync(~0)) {
// do_something
}
```
Document Reference:
https://docs.nvidia.com/cuda/parallel-thread-execution/#parallel-synchronization-and-communication-instructions-elect-sync
> Add `elect_sync` PTX instruction

- csrc/alias_analysis.cpp
- tests/cpp/test_alias.cpp
Adding entry for `ExpandOp` in alias analysis to allow no-op for `broadcast + expand` pattern.
> Adding ExpandOp in alias analysis

- tests/cpp/test_multidevice_overlap.cpp
It fails in CI
(https://github.com/NVIDIA/Fuser/actions/runs/9721491546/job/26834237293) for unrelated PRs and I am able to reliably reproduce this locally on A100x2.
cc @samnordmann
> Temporarily disable the overlap test.

- csrc/fusion_segmenter.cpp
- tests/cpp/test_segmentation.cpp
Currently, when we segment at the output of a reduction, the consumer segment will have an input tensor that has a `Reduction` axis in it. This can be problematic; see #2481 and #2317. This PR strips reduction axes from the root and allocation domain in these cases.
> Strip reduction axes in segmentation edges

- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/ops/utils.cpp
- csrc/type.cpp
- csrc/type.h
`IterType::Gather` is no longer used after #2299 , so maybe we should also remove releated code about `IterType::Gather` or is there some special reason to keep it?
> remove iter gather

- CMakeLists.txt
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
Fixes https://github.com/NVIDIA/Fuser/issues/2497.
My other attempt (#2503) failed. There were errors that seem to be related to repeated create/delete the singleton Communicator, which I don't understand. This PR tries to create/delete the Communicator just once, keeping the behavior as close as before.
> Destruct the singleton Communicator via testing::Environment. 

- csrc/id_model/indexing.cpp
- tests/cpp/test_indexing.cpp
For non-global tensors, unless explicitly set, allocation domains are promotion domains of loop domains. Promotion can be a reduction domain even for non-reduction domains as there's no special handling for reduction domains. This can result in incorrect indexing with the current code. Specifically, we skip reduction domains from allocation, however, since we look at promotion domains, they may be reduction domains even though original loop domains are not. This can result in incorrectly skipping indexing. See the added unit test for a concrete example.
The fix in this PR is to use both the original loop domain and its promotion domain when determining the allocation domain of a given tensor to index.
> Fix for when allocation domains are promoted to reduction domains

- tests/cpp/test_multidevice_matmul.cpp
Update test to use symbolic tensorviews since https://github.com/NVIDIA/Fuser/pull/2487 was merged.
> Symbolic TV in tensor parallel MLP

- tests/cpp/test_multidevice_overlap.cpp
Re-enable a test originally introduced in #2401 but disabled by #2501 because it was failing in the CI. Looking at [the log](https://github.com/NVIDIA/Fuser/actions/runs/9721491546/job/26834237293), it appears the bug is solved by simply relaxing the tolerance error used for validating the obtained output.
> Re-enable overlap test

- csrc/host_ir/container.cpp
- csrc/host_ir/container.h
- csrc/host_ir/executor.cpp
- tests/cpp/test_host_irs.cpp
add in `HostIrContainer` an IR representation of the "default stream" as defined by torch
used in the overlap implementation
https://github.com/NVIDIA/Fuser/blob/3258fa5d3bf9e89c600c1615f6dbc24b00b8dcce/tests/cpp/test_multidevice_overlap.cpp#L220
`IrContainer::oneVal()` is a similar concept as what we try to achieve here. But the implementation there has some complexity
https://github.com/NVIDIA/Fuser/blob/3258fa5d3bf9e89c600c1615f6dbc24b00b8dcce/csrc/ir/container.cpp#L266
in particular, `oneVal` is not built with `IrBuilder::create` as one would expect, though I am not sure to understand the benefit.
Here, I didn't care to reproduce the implementation of `oneVal`, I propose something simpler relying on `IrBuilder::create`. Let me know if you prefer something in the same vein as the …
> HostIrContainer: add default stream

- benchmarks/python/global_params.py
This PR updates the batch size to be the same for nightly/weekly runs.
This will allow us to plot S-curves for the nightly results using the torch baselines from the previous weekly run.
We use `batch size = [16, 512, 2048, 8192, 16384]`
> Update batch size for nightly/weekly runs

- csrc/ops/composite.cpp
- tests/cpp/test_sdpa_node.cpp
This PR:
- modifies the variables `cum_seq_q/k` to have root_domain as `{iN}` and logical domain as `{iN+1}`.
- updates the tests to validate all inputs from the forward pass. This excludes the scalar outputs `query_seq_len/key_seq_len` which will added in the follow-up PR.
> Update pairwise mapping for `SDPAFwdOp` outputs

- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/scheduler/no_op.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/registry.cpp
- csrc/scheduler/transpose.cpp
- tests/cpp/test_sdpa_node.cpp
Resolves #2517.
`SdpaFwdOp` is not compatiable with computeAt map since the outputs of the op do not all have the same root domain.
For larger fusions containing `SdpaFwdOp`, `checkCanSchedule` runs into error due to this.
> Check for presence of ExprEval-only nodes early in canSchedule to avoid segmentation errors.

- CMakeLists.txt
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/ir/internal_nodes.h
- csrc/scheduler/matmul_utils.cpp
- tests/cpp/test_circular_buffering.cpp
- tests/cpp/test_gpu_fused_reduction.cpp
- tests/cpp/test_gpu_tensorcore.cpp
- tests/cpp/test_loop_rotation.cpp
This PR renames the tests in `tests/cpp/test_double_buffering.cpp` to circular buffering. It also cleans other references to double-buffering.
> Clean double buffering references

- csrc/iter_visitor.cpp
- tests/python/test_python_frontend.py
Fixes #2545 which was hitting stale values as `old_val->uses()` was updated in that loop. In some cases on my machine this resulted in processing the same `Expr*` twice, leading to segfaults or other strange errors.
> Copy uses when replacing val in uses

- csrc/fusion.cpp
- csrc/preseg_passes/mark_aliases_prepare.cpp
- csrc/transform_replay.h
- tests/cpp/test_alias.cpp
- tests/cpp/test_preseg_passes.cpp
- tests/python/test_pointwise.py
We currently do that to some extent by adding `segment_set` before aliased outputs. This PR modifies and extends the logic for aliased inputs as well. 
Fixes #2395
> Segment out meta ops from a fusion. 

- CMakeLists.txt
- csrc/multidevice/c10d_mock.h
- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- tests/cpp/multidevice.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_communicator.cpp
See code comments. This PR avoids a warning in PyTorch and makes the code safer. It also checks in a test to verify #2499 is fixed. 
cc @eqy
> Explicitly specify the device ID to ProcessGroup::barrier. 

- csrc/ops/alias.cpp
- tests/cpp/test_alias.cpp
- tests/cpp/test_resize.cpp
Fixes #2552. 
CI: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/16451691
> Fix the computation of slice's output TV. 

- CMakeLists.txt
- csrc/id_model/id_model_index_compute.cpp
- csrc/id_model/id_model_index_compute.h
- csrc/id_model/indexing.cpp
Just refactoring. No change other than moving `IdGraphIndexCompute` to its own file.
> Move IdGraphIndexCompute to its own file

- csrc/device_lower/analysis/tma.cpp
- csrc/device_lower/analysis/tma.h
- doc/dev/tma.md
- tests/cpp/test_memory.cpp
In the current main branch, the analysis in `csrc/device_lower/analysis/tma.cpp` mostly comes from copy-pasting the legacy indexing code of TMA with simple string replacement to fit for IdGraph. In this approach, although we are using IdGraph, I still don't consider it modern, because we are still assuming the traversal path to be like a TensorDomain (For example, traversal is only backward, no forward traversal is allowed, and each val group only have one definition).
This PR rewrites the TMA analysis to make it modern. This rewrite makes the analysis more extendable so that in the future I can easily add support for "define box by rotation". As a side effect of this rewrite, we now only requires a path from consumer's loop domain to gmem tv's allocation domain, and it does not matter if …
> Rewrite TMA analysis

- csrc/python_frontend/python_bindings.cpp
- tests/python/test_schedule_ops.py
This PR adds `cache_fork` operation to python frontend. It is used for intermediate tensors in a fusion that are saved as an output.
> [Python Frontend] Add cache_fork to user-scheduling

- benchmarks/python/conftest.py
- benchmarks/python/core.py
- benchmarks/python/global_params.py
A subset of inputs can be run for each benchmark using `--benchmark-num-inputs=num_inputs`.
Allows for quick functionality test. By default, the entire suite will be run.
Closes Issue #2348.
> Add option to benchmark a subset of inputs

- benchmarks/python/core.py
- benchmarks/python/test_many_pointwise_ops.py
- tests/python/test_python_frontend.py
1. Adds a fusion profiler based timer to measure the host timings for nvFuser.
2. To measure for uncached host overhead, the `setup` function resets `FusionCache` and initializes a new FusionDefinition
> Host benchmarking 

- csrc/ir/nodes.cpp
- csrc/ops/composite.cpp
- csrc/preseg_passes/exact_mapped_extent_substitution.cpp
- csrc/root_domain_map.cpp
- tests/cpp/test_sdpa_node.cpp
Temporarily add support for a sharded forward scaled dot product attention.
Currently, we only support DID parallelization on the logical domain which requires us to split and parallelize an axis at the logical level see https://github.com/NVIDIA/Fuser/issues/2563. This is a hack until we support DID parallelization on the loop domain after which this PR can be reverted.
Restrictions:
1. q,k,v inputs are manually sharded _before_ the SDPAFwdOp is created. We cannot rely on sharding propagation or sharding after the Fusion is created, because the dimension checks are called when the op is created. 
2. Only the head dimension is sharded and all inputs and outputs have either a sharded head dimension or unshaded. 
3. DID axis is the outermost axis. This is because during evaluation if we see …
> Sharded SDPAFwdOp

- csrc/executor.cpp
- csrc/executor.h
- tests/python/test_schedule_ops.py
When using TMA operations, we must use 32-bit indexing and disable magic zero support. Currently, we manually pass the correct `CompileParams` to `FusionExecutor::compileFusion`. This PR automatically updates the `CompileParams` if TMA operations are detected during compilation. It also includes a basic normalization kernel using TMA operations in the python frontend.
> Select CompileParams for TMA operations automatically at compile-time

- CMakeLists.txt
- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/cpp/test_multidevice_lower_communication.cpp
- tests/cpp/test_multidevice_matmul.cpp
- tests/cpp/test_multidevice_sharding.cpp
- tests/cpp/test_multidevice_transformer.cpp
Moves sharded mlp test from test_multidevice_matmul to test_multidevice_transformer. 
Add helper functions for replicated dropout, sharding tensors, and validation. Changes that are more than copy paste are highlighted.
> Move and cleanup sharded mlp test

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- tests/cpp/test_host_irs.cpp
add support for `SliceOp` in `HostIrExecutor`.
~~Stacked on top of #2533~~
Used in reduce-scatter overlap technic 
https://github.com/NVIDIA/Fuser/blob/bad998ae277ffc2f43fdc28dca07d01d737a1623/tests/cpp/test_multidevice_overlap.cpp#L129
We rely on `ExpressionEvaluator::evaluate` to execute the slice operation on the at::Tensor.
The `SliceOp` needs to be explicitly added to `HostIrExecutor::top_level_exprs_`, as illustrated in the provided unit test.
> Host IRs: support `SliceOp`

- tests/cpp/test_indexing.cpp
This PR fixes this compile error in `tests/cpp/test_indexing.cpp`.
```
/opt/pytorch/nvfuser/tests/cpp/test_indexing.cpp:87:7: error: ‘<unnamed>.GetReference::<unnamed>.nvfuser::{anonymous}::AbstractGetReference::circular_buffer_loop_stage_’ may be used uninitialized [-Werror=maybe-uninitialized]
```
> Fix compile error in test_indexing

- tools/apt-install-things.sh
hacking headers to workaround https://github.com/pytorch/pytorch/issues/130678
> install nlohmann-json3-dev to patch build failures related to pytorch distributed changes

- csrc/index_compute.cpp
- csrc/index_compute.h
- csrc/predicate_compute.cpp
Used to predicate root domains but not true anymore. No logic change.
> Rename RootPredicateInfo to just PredicateInfo

- tests/python/pytest_ops.py
CI at at [link](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/101537058/raw) detected many failed cases due to out of memory.
For example:
```
00:17:01 FAILED tests/python/pytest_ops.py::test_definition_op_in_schedule_error_sub_complex128 - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 39.39 GiB of which 11.94 MiB is free. Process 4101543 has 39.37 GiB memory in use. Of the allocated memory 9.27 GiB is allocated by PyTorch, and 8.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables …
```
> clear memory in pytest

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- tests/cpp/test_host_irs.cpp
Adds support for `MatmulOp` in `HostIrExecutor`
The implementation makes it very easy to support new ops that `ExpressionEvaluator` can handle.
Stacked on top of 
- #2533
- #2535
> Host irs: add support for `MatmulOp`

- csrc/multidevice/communicator.cpp
- csrc/multidevice/communicator.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/python_bindings.h
- csrc/python_frontend/python_bindings_extension.cpp
- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/python/mpi_test.py
As a follow-up to https://github.com/NVIDIA/Fuser/pull/2575#discussion_r1676563522. 
As the comment says, it's not the best practice but acceptable -- the lifetime concern is localized to the cleanup method, which can be educated.
> Make Communicator a singleton. 

- tests/cpp/test_multidevice_communications.cpp
Fixes #2091.
UCC tests seem to run just fine after #2504 and #2499.
> Renable UCC CommunicationTests.

- csrc/python_frontend/fusion_definition.cpp
- tests/python/pytest_ops.py
Fix #2617
`SchedulerRuntimeInfo` is created in `setupSchedule`. Normally, `finalizeSchedule` is called after scheduling, which destroys `runtime_info`.  When there is an exception, the program exits. During testing, we don't exit the program after an exception, so we accumulate `UserSchedule` objects. The fix is to clear the `FusionCache` after each test to destroy those objects.
> Clear fusion cache to fix OOM

- tests/cpp/test_indexing.cpp
Fixes a build error seen in CI runs:
```
/opt/pytorch/nvfuser/tests/cpp/test_indexing.cpp:2485:34: error: comparison of integer expressions of different signedness: ‘int64_t’ {aka ‘long int’} and ‘std::vector<nvfuser::ForLoop*>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
#12 123.3  2485 |       bool is_init = tv->nDims() > for_loops_.size();
#12 123.3       |                      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
#12 123.3 cc1plus: all warnings being treated as errors
```
> fix build error

- csrc/multidevice/communicator.cpp
This warning consistently shows up in single-GPU programs, which don't initialize the Communicator.
> Temporarily remove a warning.

- csrc/multidevice/c10d_mock.h
- csrc/multidevice/communicator.cpp
(Small annoyances; happy to drop)
It's suboptimal to see a warning printed out every time people run the unit tests. LOG(INFO) seems more appropriate or we should make sure MASTER_PORT is set.
> TORCH_WARN => LOG(INFO)

- csrc/device_lower/analysis/index_compute.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- csrc/id_model/predicate_indexing.cpp
- csrc/id_model/predicate_indexing.h
- csrc/predicate_compute.cpp
- tests/cpp/test_indexing.cpp
Adding support of generating predicates for unswitch/unroll and vectorize.
These predicates are generated by `UnswitchPredicate`. Unswitch and unroll are effectively the same for predication. Vectorize is also mostly the same with only one difference, which is that the predicate of the vectorized loop itself is altered.
For example, if a tensor has `[I0, I1, I2]` and `I1` is unswitched, the code structure would look like:
```
for i0 in I0:
if idx(i0, I1 - 1, I2 - 1) < N:
for i1 in I1:
for i2 in I2:
do_something
end-for
end-for
else
for i1 in I1:
for i2 in I2:
if idx(i0, i1, i2) < N:
do_something
end-if
end-for
end-for
end-if
end-for
```
Here, `idx` is a function to produce the linearized index using the loop indices, and `N` is the extent of the domain. Notice that both `I1` and `I2` …
> Support predicate indexing for unswitch/unroll/vectorize

- tools/gen_nvfuser_version.py
Rely on the NVFUSER_VERSION environment variable to set the gitSHA, when "git" command fails to find the commit sha, e.g. in an environment where "git" is not found.
> Make nvfuser.__version__ less unknown when "git" cannot find the commit id 

- csrc/fusion.cpp
- csrc/scheduler/mark_aliases.cpp
- csrc/scheduler/no_op.cpp
- tests/cpp/test_alias.cpp
Previously when we have
```
TensorView* in = makeContigConcreteTensor({2, 3});
TensorView* out = makeContigConcreteTensor({2, 3});
fusion->addInput(in);
fusion->addInput(out);
fusion->aliasOutputToInput(out, in, AllocationType::ReuseBuffer);
```
The inplace update instruction `fusion->aliasOutputToInput(out, in, AllocationType::ReuseBuffer);` would mistakenly be put into a no-op kernel (or mistakenly ignored by pointwise).
We need to generate a real kernel to perform the inplace update. This PR fixes that, as well as creating a cpp test to validate the behavior.
> support inplace update with FusionInput as source
