NVIDIA/Fuser

- tests/cpp/test_segmentation.cpp
This was a question I asked myself when working on #2639. Knowing this allows me to simplify some segment-set-inserting logic there.
> Add a test to verify a segment can hold multiple `segment_set`s.

- csrc/device_lower/utils.cpp
- csrc/expr_evaluator.cpp
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/kernel_cache.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/composite.cpp
- csrc/ops/composite.h
- csrc/scheduler/expr_eval_sched.cpp
- csrc/scheduler/registry.cpp
- csrc/utils.cpp
- csrc/utils.h
- tests/cpp/test_sdpa_node.cpp
This PR:
1. Removes `cum_seq_q/k` from `SdpaFwdOp` outputs and `SdpaBwdOp` inputs. These are undefined tensors for non-nested inputs which are not supported as fusion inputs. The nvFuser API now differs from torch/Thunder.
2. Adds pairwise domain mapping and scheduling support for `SdpaBwdOp`.
3. Allows tensor views marked as CPU scalars to be meta tensors. Detailed reasoning in code comments.
> SDPA Bwd Mapping

- csrc/codegen.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/circular_buffer.h
- tests/cpp/test_loop_rotation.cpp
- tests/cpp/test_scalar_hoisting.cpp
Note that CudaCodeGenerator currently always starts a loop with 0 even if ForLoop::start_ is non-zero. I think this change is safe since only use case of non-zero start should be the epilogue loop of circular buffering. The concern of degenerate loop should not be applicable.
> Fix epilogue loop generation

- csrc/host_ir/executor.cpp
- tests/cpp/test_host_irs.cpp
Fixes CI after merging #2584.
- [1st commit:](https://github.com/NVIDIA/Fuser/pull/2665/commits/60dc02ae15b4ceaa4f28079af9de057b25804292) This PR fixes the tests `HostIrTest.ForLoops/*` which were broken by merging #2584.
- [2nd commit:](https://github.com/NVIDIA/Fuser/pull/2665/commits/2e89f7b2b229732b6868cf3cac107a99951c80b8)This PR also fixes the test `OverlapTest.ReduceScatterBasedPipeliningHostIrImplementation`, where a typo was introduced in the implementation of `allConsumerValsOf` in [a commit right before](https://github.com/NVIDIA/Fuser/pull/2584/commits/c87084f4593d4a4ef1c946600d297d8342389007) merging #2584.
The test case `HostIrTest.ForLoops/*` features an accumulation buffer. Reusing a buffer for accumulation should always be marked through I/O aliasing. Instead, we were …
> Host IRs: Fix for-loop test

- csrc/device_lower/analysis/index_compute.cpp
- tests/cpp/test_gpu3.cpp
Currently, we generate predicates for vectorization as:
```
// 4-way vectorization
if (idx(i + 3) < N) {
local_tensor[0] = loadGlobalToLocal(gmem_tensor[idx(i)]);
}
```
where `idx(x)` returns an index of the tensor with the vectorized loop index as `x`. The predicate is to make sure that the access of the 4-way vectorized load is within the extent. 
This should be equivalent to:
```
// 4-way vectorization
if (idx(i) < N) {
local_tensor[0] = loadGlobalToLocal(gmem_tensor[idx(i)]);
}
```
Notice the predicate is the same as the index for the load access. I belive that these two patterns should be equivalent since we assert that the vectorized domain is divisible by the vectorization factor.
The latter pattern is likely to promote more effective hoisting as the indices of the predicate and …
> Promote hoisting of vectorize predicates

- csrc/device_lower/pass/replace_size.cpp
remove duplicated `isConstScalar()` check in `replaceSymbolicSizes()`
> remove duplicated isConstScalar check in replace_size

- csrc/device_lower/pass/index.cpp
- csrc/device_lower/utils.cpp
- csrc/dynamic_transform.cpp
- csrc/ir/builder.cpp
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_indexing.cpp
In #2634, an `IterDomain` is created during lowering (in `allocGlobalBufferForGridComm`) using an extent that is derived from parallel extents. In this case the computation is done with `Int` scalars, and the constructor of `IterDomain` asserts that the extent should be `Index` instead. This PR casts the stop value to `Index` if necessary before creating the `IterDomain` in `allocGlobalBufferForGridComm`.
The reason we have an `Int` parallel dimension is that we compute `SimplifyExpr::maxExpr` with two constant `IterDomain` extents each of which is `DataType::Index` and should return `DataType::Index`. However, it currently returns `Int`. This is similar to the problem encountered in #2646. This PR fixes this by computing the proper output type for `maxExpr`, `minExpr`, `bitwiseAndExpr`, …
> Fix incorrect DataType in allocGlobalBufferForGridComm

- benchmarks/cpp/matmul.cpp
This fixes a potential problem that's exposed by #2639, and is AFAIK the right order of actions. We almost never run preseg passes after scheduling, except for multi-GPU.
I could combine this #2639 so the fix is shipped with a regression test. However, the fix seems to be straightforward enough to stand alone, making #2639 a bit smaller. I don't have a strong opinion -- let me know if you prefer the other way.
> Run `preseg` before `schedule`.

- csrc/scheduler/no_op.cpp
- tests/cpp/test_no_op.cpp
I hit a serde error when I was working on #2639. This PR fixes that error. 
As a known limitation of serde, https://github.com/NVIDIA/Fuser/blob/446e24737cae95154aca5126a038a30b636ad512/csrc/kernel_cache.cpp#L1053-L1080 runs different code paths for default compilation and for deserialization. This usually leads to the same segmented fusion, but the added test case triggers an actual difference if without this PR. The default compilation path calls `findSegments`, which sets global memory type for attempted segment boundaries (via addInput/addOutput and removeInput/removeOutput). The deserialization path however doesn't call `findSegments`, so attempted segment boundaries remain local. As a result, `kernel->summary().global_allocations` is non-empty for default compilation and empty for …
> The no-op scheduler clears memory space.

- tests/cpp/test_gpu_tensorcore.cpp
- tests/cpp/test_matmul_sass.cpp
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/test_mma.cpp
- tests/cpp/test_translate_mma.cpp
- tests/cpp/utils.h
I suggest reviewing this PR hiding whitespaces:
This PR moves some common things into headers, and make many tests as parameterize tests with layout as parameter. Mostly code movement, no logical change.
> Refactor matmul tests

- csrc/id_model/id_model.cpp
- tests/cpp/test_gpu_view.cpp
Now, domains are no longer required to have a nice linear transformation from root domain to loop domain. We can take advantage of that and schedule reshape.
> Add an example to demonstrate schedule mismatching reshape

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- tests/cpp/test_host_irs.cpp
Add `SelectOp` to `HostIrExecutor`
Will be used in reduce-scatter overlap technic #2584, to simplify and potentially improve perfs, cf [item 3 here](https://github.com/NVIDIA/Fuser/pull/2584#issuecomment-2238833771) 
handle `SelectOp` through `ExpressionEvaluator`
> Host IRs: add `SelectOp`

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/kernel_cache.cpp
- csrc/logical_domain_map.cpp
- tests/cpp/test_sdpa_node.cpp
CC: @naoyam 
This PR allows outputs of the SDPA ops to have different root domains.
> Allow multiple outputs with different root domains for SDPAOp in IDModel

- CMakeLists.txt
- csrc/validator_utils.cpp
- csrc/validator_utils.h
- tests/cpp/utils.cpp
- tests/cpp/utils.h
- tests/cpp/validator.cpp
- tests/cpp/validator.h
I'm unsure about the difference between tests/cpp/utils.h and tests/cpp/validator.h. AFAICS, tests/cpp/validator.h is only used by tests not benchmarks, so it seems to be the right home for validateSegmentation. 
This PR comes with some other fixes I had to make along the way: 
1. Move non-trivial implementation to cpp files: https://google.github.io/styleguide/cppguide.html#Inline_Functions. 
2. Add missing `#pragma once`s. 
3. Move definitions of external methods in validation_utils.h out of anonymous namespaces.
> Move validateSegmentatation from tests/cpp/utils.h to tests/cpp/validator.h.

- benchmarks/cpp/timm.cpp
- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/preseg_passes/mark_aliases_prepare.cpp
- csrc/scheduler/mark_aliases.cpp
- csrc/scheduler/no_op.cpp
- csrc/scheduler/reduction_utils.cpp
- csrc/scheduler/reduction_utils.h
- tests/cpp/test_alias.cpp
- tests/cpp/test_gpu_view.cpp
- tests/cpp/test_pointwise.cpp
- tests/cpp/test_remove_bcast_squeeze.cpp
- tests/cpp/test_resize.cpp
- tests/cpp/test_scatter_gather.cpp
This PR improves segmentation around meta ops for #2599. It mimics Thunder's bookend optimization, although only the output end is implemented at this moment. Although the implementation isn't complete, I believe it's an improvement overall. It segments out meta ops more aggressively than before, making non-meta ops easier to schedule. 
1. `segment_set` enforces the segmenter to give up scheduling the complete fusion and instead trying to merge from singletons. In theory, merging should be able to reach a "local maxima". But in practice it's not always as powerful as expected, e.g., https://github.com/NVIDIA/Fuser/pull/2639/files#diff-cf6d314e82c49485e9039e700a04a678904e5c669abcd1610ade897ca8f57c78R1472. 
2. MarkAliasesPreparePass may set an suboptimal layout, because it runs before …
> MarkAliasesPrepare attempts to put segment_set after intermediate tensors.

- tests/cpp/test_translate_mma.cpp
These guard was lost in #2687 and this PR just adds it back.
This should prevent CI failures like this one: https://github.com/NVIDIA/Fuser/actions/runs/10149135993.
> Add arch guard to CombineMulSumAsMmaTestWithLayout tests

- csrc/scheduler/matmul.cpp
Smem epilogue tensor is now using TensorIndexer and new swizzle, so there is no need to schedule an "empty" swizzle just to make IDs match. The problem of self mapping still exist, but it can be easily workaround by a much simpler transformation.
> Cleanup `swizzleSharedMemory`

- tests/cpp/test_gpu_fused_reduction.cpp
- tests/cpp/test_host_irs.cpp
- tests/cpp/test_multidevice_host_ir.cpp
- tests/cpp/test_predicate_elimination.cpp
Cleanup uses of IrBuilder::createInContainer when IrBuilder::create is sufficient.
> Host IR Test Cleanup

- benchmarks/python/core.py
- benchmarks/python/test_layernorm_fwd.py
Add
```
def clear_dynamo_cache() -> None:
"""
Utility function to enforce re-compilation to avoid different results between
running a serials of tests and a standalone test due to kernel re-use.
It slows down the test but ensures the correctness of the benchmark results.
Ref: https://github.com/pytorch/pytorch/issues/107444
"""
torch._dynamo.reset()
```
Performance data of torch.compile looks more reasonable, the max speedup of nvFuser to torch.compile is 2.0x instead of 25.0x
see  [dashboard](http://nv/egW)
TODO:
(1) add to other tests
(2) check weekly CI time change
> dynamo reset

- csrc/ops/composite.cpp
- tests/cpp/test_sdpa_node.cpp
This PR marks the outputs as CPU scalars within the API so it doesn't need to be done in tests and avoids any errors stemming from tensorviews not setting this attribute.
> Mark SDPA variables as cpu scalars within API

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- csrc/id_model/predicate_indexing.h
- csrc/index_compute.h
- csrc/predicate_compute.cpp
- csrc/predicate_compute.h
- tests/cpp/test_indexing.cpp
This is a bug fix for #2691, which isn't sufficient when broadcast tensors are involved.
> Fix finding right non-divisible splits to predicate

- csrc/abstract_tensor.cpp
- csrc/abstract_tensor.h
- tests/cpp/test_abstract_tensor.cpp
- tests/cpp/test_swizzle.cpp
```C++
// AbstractId in AbstractTensor can be place holders std::monostate{}. For
// example:
//
// Example 10:
//   AbstractTensor v({{}, {}}); // [null, null]
//   v.split(0, 2); // [null, null, null]
//   v.merge(0); // [null, null]
//   v.swizzle(SwizzleType::XOR, 0, 1); // [null, null]
```
> Handle placeholders in AbstractTensor

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/composite.cpp
- csrc/ops/composite.h
- tests/cpp/test_sdpa_node.cpp
1. Since, we have deviated from torch API, making the following changes to have a leaner API:
-   Removes `debug_attn_mask` which is a 1D zero-tensor since `return_debug_mask=false` in `SdpaFwdOp`.
-   Removes `query_seq_len, key_seq_len`: These variables can be computed in the backward pass for non-nested tensors.
2. Adds `DIDx` axis to `log_sumexp` in `SdpaFwdOp::evaluate` and `logical_domain_mapping`. The `DIDx` axis is assumed when the tensorview is created but was not added everywhere. This removes discrepancy in different parts of the code. This will be revisited after work on sharded `SdpaBwdOp`. The `DIDx` can be removed from `log_sumexp` if not required.
> Remove `query/key_seq_len, debug_attn_mask` in `SdpaFwdOp`

- benchmarks/python/normalization.py
- benchmarks/python/test_dropout_layernorm_bwd.py
- benchmarks/python/test_dropout_layernorm_fwd.py
- benchmarks/python/test_dropout_rmsnorm_bwd.py
- benchmarks/python/test_dropout_rmsnorm_fwd.py
- benchmarks/python/test_gelu_bwd.py
- benchmarks/python/test_gelu_bwd_reduction.py
- benchmarks/python/test_gelu_fwd.py
- benchmarks/python/test_groupnorm_fwd.py
- benchmarks/python/test_huggingface_attn_bwd.py
- benchmarks/python/test_huggingface_attn_fwd.py
- benchmarks/python/test_layernorm_bwd.py
- benchmarks/python/test_nanogpt_attn_bwd.py
- benchmarks/python/test_nanogpt_attn_fwd.py
- benchmarks/python/test_pointwise_mul.py
- benchmarks/python/test_reduction.py
- benchmarks/python/test_reduction_epilogue.py
- benchmarks/python/test_rmsnorm_bwd.py
- benchmarks/python/test_rmsnorm_fwd.py
- benchmarks/python/test_scale_bias_relu_bwd.py
- benchmarks/python/test_scale_bias_relu_fwd.py
- benchmarks/python/test_silu_mul_bwd.py
- benchmarks/python/test_silu_mul_fwd.py
- benchmarks/python/test_softmax_bwd.py
- benchmarks/python/test_softmax_fwd.py
- benchmarks/python/test_transpose.py
following #2722, adding `clear_dynamo_cache()` to other torch.compile benchmarks.
> clear_dynamo_cache

- csrc/executor.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/composite.cpp
- csrc/ops/utils.cpp
- csrc/ops/utils.h
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
- tests/python/test_python_frontend.py
When K=1, we will be mapping a reduction axis to broadcast axis in `LinearOp/MatmulOp`. This is not allowed in nvFuser. This was first noticed in Issue #2532 but exists generally.
PR #2534 is included in this PR for checking `LinearOp`.
> Remove reduction axis when `K=1`

- csrc/multidevice/device_mesh.h
- csrc/ops/utils.cpp
- csrc/ops/utils.h
- tests/cpp/test_multidevice_matmul.cpp
- tests/cpp/test_resharding.cpp
Fixes #2721. 
#2721 uncovers a deeper problem: the existing preseg passes are not aware of shardings, and therefore generate TensorViews that have no meshes or have wrong DIDs, breaking communication lowering. 
The current flow is:
1. The user annotates meshes and DIDs to some TensorViews. 
2. MultiDeviceExecutor runs PropagateShardingsPass to ensure all TensorViews have a mesh and propagate DIDs to more tensors than annotated. 
3. FusionExecutorCache runs the preseg passes. MarkAliasesPrepare is the one in question, but the problem can happen to any preseg pass. 
This PR implements one solution, although I'm all ears for alternatives. It extends `newValLike` so most `csrc/ops` APIs will attempt to propagate shardings from inputs to outputs. This minimizes the changes to the passes. …
> newValLike tries to propagate sharding. 

- nvfuser/__init__.py
By splitting this helper function devs can get the repro by using `getReproString`.
> Split getReproErrorString in two

- tests/python/pytest_framework.py
- tests/python/pytest_ops.py
- tests/python/test_python_frontend.py
- tests/python/utils.py
This PR adds a serialization check to the pytest opinfo framework.
Details:
- The pytest framework `serde_check` only checks per-operator and per-dtype. It doesn't check every single sample input. We check more input variations in the pytest benchmarks than `test_python_frontend.py`. This is a timesaving measure.
- Creates `atexit_serde_create_op_test` pseudo decorator to test automatic serialization. Serializing error test cases embeds errors in the serialized binary. Normally, we call `FusionCache.reset()` to clear the cache after running an error test. In the pytest framework, the error tests are separate from the correctness tests. We use this decorator to apply this to the correctness tests.
- The pytest framework and `test_python_frontend.py` use different arguments. …
> Add serialization check to the pytest framework.

- tests/python/utils.py
`torch.allclose` does not support fp8 datatypes. The fix is to cast nvfuser result and torch reference to fp64.
Failing Test:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2918, in wrapper
method(*args, **kwargs)
File "/opt/pytorch/nvfuser/tests/python/test_python_frontend.py", line 216, in test_cast_fp8
fn(type0, type1)
File "/opt/pytorch/nvfuser/tests/python/test_python_frontend.py", line 210, in fn
nvf_out, _ = self.exec_nvfuser(fusion_func, inputs)
File "/opt/pytorch/nvfuser/tests/python/test_python_frontend.py", line 80, in inner_fn
test_fn(self, fusion_func, inputs_copy, **kwargs)
File "/opt/pytorch/nvfuser/tests/python/test_python_frontend.py", line 114, in exec_nvfuser …
```
> Cast tensors to fp64 for torch.allclose

- csrc/ir/nodes.cpp
Simple for-loops are used to initialize and invalidate mbarriers. The indexing pass is not used for these operations, so the `simplified_stop_` value is not initialized during lowering. This PR uses the original stop value if `simplified_stop_` is not initialized during lowering.
```cpp
if (hopper::elect_sync()) {
#pragma unroll
for(nvfuser_index_t i10 = 0; i10 < number_of_stages; ++i10) {
mbarrier::init(toSmem((&T3[i10])), 1U);
}
}
// remaining kernel
// mbarrier invalidation
if (hopper::elect_sync()) {
#pragma unroll
for(nvfuser_index_t i19 = 0; i19 < number_of_stages; ++i19) {
mbarrier::inval(toSmem((&T3[i19])));
}
}
```
> Fallback to stop in ForLoop::simplifiedStop

- csrc/python_frontend/fusion_cache.cpp
- csrc/python_frontend/fusion_cache.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/python_bindings.cpp
- nvfuser/__init__.py
- tests/python/test_schedule_ops.py
This PR fixes issue #2056.
In the python frontend, user scheduled fusions are cached based on their input arguments and cuda device. Currently, we cannot run a user-scheduled fusion with inputs on a multiple device.
Proposed fix:
1. Check if a user-schedule fusion exists for given input arguments and device. The associated functions are `FusionCache::existsUserSchedule` and `FusionDefinition::existsSchedule`.
2. If not, create a new user schedule.
Secondary Issues:
- We are now calling `setupSchedule` and `finalizeSchedule` for each new `UserSchedule`. During scheduling, new tensors are created and added to the `FusionDefinition`. These schedule-only tensors must be removed in `setupSchedule` prior to scheduling the fusion.
- To address this, we track the number of recording states in …
> Run user-scheduled fusions with input arguments on different devices.

- csrc/ops/utils.h
It seems unnecessary to include all nodes in this **header** file.
> Include less.

- tests/cpp/test_multidevice_overlap.cpp
This patch adds features and improve several aspects the reduce-scatter-based pipelining overlap experiments. We patch both the ATen and the host IR implementation.
For each slice of the tensor, we change the stream in a round-robin fashion. Before this patch, we used as many streams as there were slices (aka `params.S`, the extent of the outermost dimension). We observe in #2673 (see in particular [this message](https://github.com/NVIDIA/Fuser/issues/2673#issuecomment-2260235042)) that we want to:
- have at least one warm-up iteration
- keep the number of streams relatively low:
- `at::matmul_out` (and, in general, pytorch allocator cache) allocates buffers per stream.
- We only need a couple of streams to achieve overlap. I think using two or three streams should be sufficient …
> Host irs/overlap: add `number_of_streams` and `number_of_iterations`

- csrc/host_ir/host_ir.cpp
- csrc/ir/iostream.cpp
Continuation of https://github.com/NVIDIA/Fuser/pull/2720 to improve printing host IRs and make it more consistent with other parts of nvFuser
- `Expr::toString` should always contain a trailing new line
-  Hence `IrPrinter::handle(const hir::HostIrContainer*)` do not need to add a new line when printing top-level expressions
- `Expr::toInlineString` throw an error, as is commonly done in Fuser in general, e.g., https://github.com/NVIDIA/Fuser/blob/694a156aa4225b957d3d2045f12d10d5d29f5a80/csrc/ir/nodes.cpp#L68
> [Host IRs] fix trailing new line when printing

- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/ops/arith.cpp
- csrc/ops/arith.h
- tests/cpp/test_multidevice_communications.cpp
This PR removes the second constructor from the Communication class that takes the device mesh. It also updates the CommunicationTest gtests to construct a communication with the other constructor.
> Communication class refactor

- tests/cpp/test_multidevice_pipeline.cpp
Works around an "undefined symbol" error in https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/106423695. 
```
00:04:58 [1,2]<stdout>:[ RUN      ] Bcast_sharded/PipelineTestTwoStages.Communication/20
00:04:58 [1,2]<stderr>:bin/test_multidevice: symbol lookup error: /usr/local/ucx/lib/ucx/libuct_cuda_gdrcopy.so.0: undefined symbol: gdr_get_info_v2
```
To reproduce this error: 
```
mpirun --get-stack-traces --tag-output --report-state-on-timeout --allow-run-as-root -np 4 bin/test_multidevice | ts -s
```
According to @xwang233, `pjnl-20240813` works and `pjnl-20240814` fails. 08/13 has HPCX_VERSION 2.19 and 08/14 has HPCX_VERSION 2.20, so that might be the cause.
Tested: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/17572797
> Disable UCC for some tests.

- benchmarks/python/test_transformer.py
- nvfuser/__init__.py
For #2199
Thanks to https://github.com/Lightning-AI/lightning-thunder/pull/951, I'm now able to generate microbenchmarks with SDPA nodes! 
```
$ pytest benchmarks/python/test_transformer.py
```
Before:
```
--------------------------------------------------------------------------------------- benchmark: 2 tests --------------------------------------------------------------------------------------
Name (time in ms)                  Min                 Max                Mean            StdDev              Median               IQR            Outliers      OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Update the transformer block microbenchmark with SDPA nodes.

- csrc/fusion_segmenter.cpp
1. Print the heuristic, so instead of `g{1, 2, 3}` it'll print `pointwise{1, 2, 3}`. 
2. `<<` doesn't print the new line. `::print` still does.
> Improve the printing of SegmentedGroup.

- CMakeLists.txt
- csrc/polymorphic_value.cpp
- csrc/polymorphic_value.h
- tests/cpp/test_polymorphic_value.cpp
Previously, this method only compared the pointers held by two StructHandles. This PR changes it to check that the name, number of fields, and the DataType and value of each field match.
https://github.com/NVIDIA/Fuser/pull/2714#discussion_r1711746956
> Perform deep check in StructHandle::operator==

- csrc/id_model/circular_buffer_indexing.cpp
- csrc/id_model/indexing.cpp
- tests/cpp/test_indexing.cpp
We encounter an indexing issue when the main loop is trivial with TMA circular buffering.
Fusion Details:
- Inner Reduction on 2D tensor
- Number of Stages: 4
- Tensor Size: (128, 128)
NOTE: This TMA load is for the last stage in the pipeline. The y-axis index is not shifted by `(num_stages - 1)`.
**Incorrect indexing:**
```cpp
nvfuser_index_t i5;
i5 = 4 * ((nvfuser_index_t)blockIdx.x);
// tma load for last stage in main loop
Hopper::cpAsyncBulkTensorTileG2S((Hopper::CpAsyncBulkTensorTileG2SIndex<2>{ 
ptr4, (Array<nvfuser_index_t, 2, 1>{(256 * i17), i5}), toSmem((&T3[i19])) }), (i8 + (1024 * i17)));
```
**Correct indexing:**
```cpp
nvfuser_index_t i5;
i5 = 4 * ((nvfuser_index_t)blockIdx.x);
nvfuser_index_t i8;
i8 = 3 + i5;
// tma load for last stage in main loop …
```
> Fix index replacement for circular buffering with trivial main loop.

- csrc/python_frontend/python_bindings.cpp
- tests/python/test_schedule_ops.py
`_exist_schedule` forgot to return the value, ended up with each execution iteration re-schedule the same fusion.
existing python tests needs to clear cache. Since we use input look up for cache key, which doesn't distinguish scalar value changes.
> cache query patch

- csrc/evaluator_common.cpp
- csrc/polymorphic_value.cpp
- csrc/polymorphic_value.h
- tests/cpp/test_evaluator.cpp
- tests/cpp/test_polymorphic_value.cpp
Reverts NVIDIA/Fuser#2810, which broke ExprEvalTest.TensorMetaData and examples/sinh_extension/test.py.
> Revert "Print StructHandle in toString(PolymorphicValue)"

- csrc/evaluator_common.cpp
- csrc/polymorphic_value.cpp
- csrc/polymorphic_value.h
- tests/cpp/test_evaluator.cpp
- tests/cpp/test_polymorphic_value.cpp
I merged #2810 too hastily and wound up breaking CI. This was reverted in #2829. This PR is a second attempt to fix printing of `StructHandle`.
> Print StructHandle in toString(PolymorphicValue) [second attempt]

- csrc/index_compute.cpp
- tests/cpp/test_indexing.cpp
Adding `Index::getConsumerPerDimLogicalIndex` and `Index::getProducerPerDimLogicalIndex`. These are used, for example, when lowering `CatOp` (https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/pass/index.cpp#L1945).
Only added one simple unit test since these are really trivial with the new indexer, whereas previously we used an ugly WAR like `allocateToLogicalDomainGuard`.
> Support getPerDimLogicalIndices

- csrc/id_model/indexing.cpp
- csrc/options.cpp
- csrc/options.h
- csrc/val_graph.cpp
- csrc/val_graph.h
Also adds NVFUSER_DUMP=indexing_verbose option
This is just a utility for debugging and experimentation. There's no functional change.
> Adds a Graphviz graph printer for ValGraph

- tests/cpp/test_pointwise.cpp
Get PointwiseParams from getMostRecentKernelRuntime instead of getMostRecentExecutorLog. This avoids having to call FusionExecutorCache::profile(true).
> Clean test_pointwise.cpp.

- tests/cpp/test_gpu3.cpp
- tests/cpp/test_pointwise.cpp
NVFuserTest already sets up the seed for determinism.
> Remove unnecessary calls to `manual_seed`.

- csrc/fusion.cpp
- csrc/fusion.h
- csrc/ir/base_nodes.cpp
- csrc/ir/base_nodes.h
- csrc/kernel_cache.cpp
This caches `ir_utils::allTvs(fusion)` as `fusion->allTvs()`. The cache is automatically invalidated whenever the TV graph topology changes; this mechanism is the same one used to recompute `Expr` uses automatically.
> Cache `ir_utils::allTvs` as part of Fusion

- tests/cpp/test_alias.cpp
They can be inferred from `.shape`s.
> Remove unnecessary calls to `.ndims`.

- csrc/scheduler/registry.cpp
During scheduling, no data cache is provided when calling `checkCanSchedule`. However, when getting heuristics for a segment, specifically when we are checking whether we can re-use a compiled runtime for new input shapes, we do pass a `data_cache` so that we can re-use some objects for scheduling. In these cases, we have already passed the compile time checks so the check is redundant. In this PR, we avoid the scheduler-agnostic compile time checks added in #2526 when the `data_cache` is given.
> Skip op checks in checkCanSchedule if we are given a data_cache

- csrc/fusion.cpp
- csrc/tensor_view.cpp
- tests/python/test_python_frontend.py
This helps me to debug some numerical problems because nvFuser has a non-obvious dtype promotion rule. However, it has a large blast radius so I'd love to hear your opinions. 
Example:
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AliasTest
[ RUN      ] AliasTest.QKVSplitBackprop
Fusion IR after pre-segmenter optimization passes:
Inputs:
T0_g_float[ iS0{16}, iS1{128}, iS2{768} ]
T1_g_float[ iS3{16}, iS4{128}, iS5{768} ]
T2_g_float[ iS6{16}, iS7{128}, iS8{768} ]
Outputs:
T7_g_float[ rS24{16}, rS25{128}, iS26{2304} ]
T8_g_float[ iS32{( 16 * 128 )}rf, iS29{2304} ]
T9_g_float[ iS34{2304}, iS33{( 16 * 128 )} ]
%kernel_math {
T3_l_float[ iS9{16}, iS10{128}, iS12{2304}rf ]
= pad( T0_g_float[ iS0{16}, iS1{128}, iS2{768} ], …
```
> Print the dtype of a TensorView.

- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
It is the changes to the allocation lowering pass from https://github.com/NVIDIA/Fuser/pull/2773.
- `ldst_mbarrier_token_map_` maps `LoadStoreOp` to mbarrier tokens, which are represented as `TensorView` of number of pipeline stages.
- `mbarrier_token_smem_alloc_set_` tracks the `kir::Allocate` expressions for the mbarriers and their tokens.
- `ldst_mbarrier_index_map_` maps the cloned `LoadStoreOp` in the prologue and main loops to their indexed mbarrier.
- In the allocation pass, create shared memory allocations and operations around `LoadStoreOp` expression.
```cpp
// Created tokens, mbarriers, init, and inval operations in allocation pass.
for (circular_buffer_loop) {
__shared__ int64_t tokens[num_stages];
__shared__ int64_t mbarrier[num_stages];
init(mbarrier);
cp.async.bulk(data, …
```
> Allocation changes for TMA Circular Buffering

- nvfuser/__init__.py
- tests/python/test_pointwise.py
This PR sets the `is_cpu` flag in `define_tensor` instead of raising an error when `fd.from_pytorch` is called for CPU scalar tensors.
> Allow creating CPU scalar tensors using `fd.from_pytorch`

- csrc/transform_iter.cpp
- csrc/transform_iter.h
- tests/cpp/test_gpu3.cpp
Extracted from and required for #2875
> Allow silently ignore missing root-to-logical ops in BestEffortReplay

- csrc/scheduler/multi_matmul.cpp
Previously, this would give the following warning:
```
[1/17] Building CXX object CMakeFiles/codegen_internal.dir/csrc/scheduler/multi_matmul.cpp.o
/opt/pytorch/nvfuser/csrc/scheduler/multi_matmul.cpp:49:1: warning: multi-line comment [-Wcomment]
49 | //                                    \
| ^
/opt/pytorch/nvfuser/csrc/scheduler/multi_matmul.cpp:60:1: warning: multi-line comment [-Wcomment]
60 | //                                        \
| ^
/opt/pytorch/nvfuser/csrc/scheduler/multi_matmul.cpp:62:1: warning: multi-line comment [-Wcomment]
62 | //                                        /             \
| ^
```
Unfortunately, this cannot be ignored using `#pragma GCC diagnostic ignored "-Wcomment"`, so I added a . at the end of each line that ended in a backslash. See …
> Avoid warnings on gcc in multi_matmul.cpp

- csrc/scheduler/no_op.h
This was probably a cut/paste error. The result though is that comparing two `NoOpHeuristic`s will currently always return false, which leads to a recompile of the entire segmented fusion if it contains a single NoOp segment.
> Fix typo in NoOpHeuristic::sameAs

- tests/python/mpi_test.py
- tests/python/transformer_engine_test.py
... as a performance baseline for tensor parallelism. It currently runs the forward pass of a Transformer layer. As next steps, backprop will be added, and the test will be added to CI.
> Add a TransformerEngine test

- csrc/fusion_executor/executor.cpp
- csrc/fusion_executor/executor_utils.cpp
- csrc/options.cpp
- csrc/options.h
Adding `NVFUSER_ENABLE=kernel_debug` to enable debug option `-G` in nvrtc;
Moving `DebugDumpOption::DebugInfo` to `EnableOption::KernelLineInfo`.
> Modifying option for nvrtc

- tools/generate_validation_tolerances.py
Adds script to reproduce the computation that was used when generating the validation tolerances: 
https://github.com/NVIDIA/Fuser/blob/892b7ac5646b3b873f13f2b2ea1db15fa9b9effb/csrc/validator_utils.h#L25-L46
> Add script to generate val consts

- benchmarks/python/test_broadcast_add_fwd.py
Ports [CPP benchmark](https://github.com/NVIDIA/Fuser/blob/main/benchmarks/cpp/broadcast.cpp) to python.
The fusion definition corresponds to:
```
def bcast_add(x, bias, bcast_dim):
return x + bias.unsqueeze(bcast_dim)
```
This benchmark uses 2D inputs. The parameters here are:
`bcast_axis`: outer or inner (0 / 1), specifies which axis in bias is broadcasted.
`contiguous`: True or False, specifies if `x` is contiguous in memory.
> Benchmark `broadcast + add`

- csrc/id_model/schedule.cpp
- csrc/id_model/schedule.h
- tests/cpp/test_id_model.cpp
This introduces a tool to get a representative IterDomain for a ValGroup. A ValGroup might have IterDomains with different IterTypes. For example, the Exact graph maps Iteration domains with Reduction domains, and the permissive graph maps Broadcast domains with Iteration when the broadcasts are concretized.
The purpose of `representativeId` is to find an `IterDomain` that is most useful for scheduling. In particular, it is an ID that is easiest to merge with other IDs. Since we restrict merging Reduction domains with non-Reduction domains, we give the lowest priority to Reduction domains in the ValGroup; we only return a Reduction domain if there is no other choice. Other than that, we prefer Iteration to Broadcast, we prefer unexpanded Broadcasts to expanded ones, and we prefer IDs with …
> Scheduling tool: representativeId(const ValGroup&)

- csrc/device_lower/pass/index.cpp
- tests/cpp/test_memory.cpp
Extend the hard coded index generation to support 16x8 and 16x16.
Extend the unit tests for the same.
Correct an error in the existing unit test for stmatrix (for 8x8)
> Extend stmatrix to support 16x8 and 16x16 matrices in addition to 8x8.

- csrc/ops/composite.cpp
- tests/cpp/test_multidevice_transformer.cpp
- tests/cpp/validator.cpp
1. Fix some reference implementations to cast in the same way as nvFuser. 
2. Allow `validate` to take tolerances. 
3. Refine the tolerances so the tests pass up to 6 GPUs.
> Fix reference implementations and improve validation. 

- csrc/predicate_compute.cpp
- tests/cpp/test_resize.cpp
Fixes #2924 
Tensor indexing automatically uses the new indexer, but that wasn't the case for predicate indexing, and because of that no proper predicate was generated and resulted in the sanitizer errors.
Explicitly opted in using the new indexer in those tests. Also, make it more automatic whenever non-convention scheduling is used.
> Enable IdModel-based predication for new producer-based scheduling tests

- csrc/multidevice/communicator.cpp
- tests/cpp/test_multidevice_matmul.cpp
- tests/cpp/test_multidevice_transformer.cpp
This partially fixes the bug that Sam found in
https://github.com/NVIDIA/Fuser/pull/2804/files#r1761633706. One is also a more logical initial value when the communicator is unavailable -- the test is being run on single node and single GPU.
> Initialize size_ and local_size_ to 1.

- tests/python/multidevice.py
- tests/python/test_multidevice.py
- tests/python/test_transformer_engine.py
So it can be picked up by CI, similar to test_multidevice.py.
> Change test_transformer_engine.py uses pytest.mark.mpi.

- tests/cpp/test_fusion_profiler.cpp
- tests/cpp/test_matmul.cpp
Both use CUPTI, multiple of which cannot coexist
> Avoid using FusionProfiler if compute-sanitizer is used

- csrc/abstract_tensor.h
- csrc/device_lower/analysis/tma.cpp
This fixes failures in `TMAIndexingTest` tests on Hopper that result in a segfault due to unchecked accesses that result when `domain` has entries but `info` is empty in `AbstractTensorWithInfo`. Note that another approach would be to switch to a class instead of a struct and add accessors that guarantee we maintain the same length for each of these vectors.
This change also adds more assertions in scheduling methods of AbstractTensorWithInfo to check that the `domain` and `info` attributes maintain the same size.
> Append to AbstractTensor's info whenever we append to domain

- CMakeLists.txt
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/fusion_guard.cpp
- csrc/fusion_guard.h
- csrc/ir/builder.h
- csrc/ir/cloner.h
- csrc/ir/container.cpp
- Moved Fusion::manage from cloner.h to fusion.h
- Moved FusionGuard to its own file to allow only include FusionGuard without defining Fusion
- Removed include of all_nodes.h from builder.h
> Some minor cleanup of header include and declarations

- csrc/abstract_tensor.h
- csrc/device_lower/analysis/tma.cpp
- tests/cpp/test_abstract_tensor.cpp
`AbstractTensor` now has many methods and as of #2933 it is subclassed into `TaggedAbstractTensor` which has additional methods. Also, there is no longer just a single vector attribute `domain` but also `info`. Instead of requiring the user to manage those vectors and keep them the same length, this PR makes them `protected` members of a class and uses the existing accessors to adjust them, as suggested in https://github.com/NVIDIA/Fuser/pull/2963#discussion_r1765951724.
> Convert AbstractTensor from struct to class

- tests/python/multidevice.py
- tests/python/test_transformer_engine.py
```
$ mpirun -np 1 pytest tests/python/test_transformer_engine.py --only-mpi
------------------------------------------------------------------------------------------------- benchmark: 2 tests ------------------------------------------------------------------------------------------------
Name (time in us)                           Min                   Max                  Mean              StdDev                Median                 IQR            Outliers       OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_transformer_layer[forward]        952.7383 (1.0)      1,200.1079 (1.0) …
```
> Benchmark backprop of a te.TransformerLayer.

- csrc/fusion.cpp
- csrc/fusion.h
- csrc/id_model/id_model.cpp
- csrc/ir/cloner.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- tests/cpp/test_id_model.cpp
The primary use case is when setting a loop domain of a tensor that would be involved in broadcast forwarding in the conventional inlining approach. For example, think of a fusion like below:
```
t0 = [i0]
t1 = [i0, i1]
t2 = broadcast(t0, {false, true}); // [i0, b2]
t3 = t1 + t2
```
To inline all tensors together, t0 and t2 would be inlined with broadcast forwarding.
Suppose a loop domain of t3 would be set for all tensors, t0, for example, would have a loop domain of: {t0->axis(0), clone of t3->axis(1)}. In this case, however, the clone is almost an exact copy of the t3 ID, there's no use or def to define its exact mapping with the original t3 ID. This is problematic when inlining t0 since the inlining rule would use the Exact (or Broadcast) graph to determine the validity of inlining, …
> Add an experimental option to map cloned IterDomains in the Exact graph

- csrc/ir/nodes.cpp
- tests/cpp/test_gpu3.cpp
This is a follow-up to #2937, which allowed the loop domain of a tensor to have extra IDs (e.g., for inlining a 1D tensor to a 2D tensor).
When working on #2983, I realized `TensorDomain::allIDs` has a problem of finding all IDs with extra loop IDs. As mentioned in the added code comment, the issue is primarily because `IRBFS::getExprsBetween` is asymmetric with respect to its two domain parameters. See the added test for a simple concrete example.
> Fix TensorDomain::allIDs when loop domain has extra IDs

- csrc/scheduler/multi_matmul.cpp
- tests/cpp/test_multi_matmul_scheduler.cpp
`main` is currently not compiling due to the changes introduced in #2913. There was a change on main that I didn't see between when CI passed and when I merged. This PR fixes that.
> Fix compile error in multi-matmul scheduler

- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- tests/cpp/test_gpu3.cpp
It turned out it's necessary to remember the initial loop domain, which is either the logical domain set by the constructor or the new loop domain set by setLoopDomain. When a loop domain has an extra ID, TensorDomain::allIDs may miss IDs that solely depend on the extra ID.
> Add initial_loop_domain_ to TensorDomain

- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/circular_buffer.h
- csrc/device_lower/pass/index.cpp
This PR creates `TmaCircularBufferInfo` struct to consolidate data fields for TMA circular buffering.
Moved these fields to `TmaCircularBufferInfo` struct
* ldstMBarrierTokenMap
* mBarrierTokenSmemAllocSet
* ldstMBarrierIndexMap
Created new fields to track mbarrier init and invalidate expressions created for `cpAsyncBulk` in the allocation pass.
* ldst_mbarrier_init_map
* ldst_mbarrier_inval_map
In the circular buffering pass, we create new `MBarrierInit` and `MBarrierInvalidate` to handle the mbarrier create for each circular buffer stage.
> Create TmaCircularBufferInfo to consolidate data fields.

- benchmarks/python/core.py
- benchmarks/python/test_many_pointwise_ops.py
We currently measure the first time overhead of a fusion execution. The FusionCache is reset at the start of every benchmarking round to measure this overhead correctly. This work aims at extending the current setup for measuring host latencies in the python benchmarks to cover the following cases:
- Case 1: Compilation through NVRTC (Host time – first time overhead): This measures the first time overhead when executing a fusion definition (current setup)
- Case 2: Cache Hit overhead: This ignores the first time overhead, and measures the host latency when executing the same input multiple times.
- Case 3: Dynamic Shape overhead (not counting first time overhead): This ignores the first time overhead, and measures the host latency when executing different inputs shapes for the same fusion …
> Extend the host latency benchmarking for additional cases.

- benchmarks/python/test_transformer.py
This is a fresh dump from the latest
https://github.com/Lightning-AI/lightning-thunder/tree/wjy/sharded.
The main differences are:
1. The code size of the fusion is cut in half because shapes are inlined.
2. Two more outputs are added and therefore cached for backprop.
For #2199.
> Update test_transformer.py forward definition.

- csrc/device_lower/pass/magic_zero.cpp
I encountered an indexing error in `protectPredicateIndexWithMagicZero` in one of my matmul unit tests. Matmul doesn't use magic zero, so just completely short-circuit it when not needed.
> Short-circut magic zero pass completely when not needed

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/thread_predicate.cpp
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/expr_sort.cpp
- csrc/device_lower/pass/loop_rotation.cpp
- csrc/device_lower/pass/loops.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/device_lower/validation.cpp
Nothing should change with this PR.  Currently, it is just a thin wrapper of `ComputeAtMap::getConcreteMappedID` with `IdMappingMode::LOOP`. Will be extended to support IdModel in an upcoming PR.
Not all use case of `getConcreteMappedID` with the LOOP map are replaced. Those that should only be used with `ComputeAtMap` are left unchanged. Also, the fusion executor also uses `ComputeAtMap`, which I believe should be refactored, so I didn't change at this moment.
Remaining uses:
```
grep -r -A 2 getConcreteMappedID csrc | grep  IdMappingMode::LOOP                           
csrc/fusion_executor/executor_utils.cpp:          if (lower->caMap()->getConcreteMappedID(id, IdMappingMode::LOOP) ==
csrc/device_lower/utils.cpp-      loop_id, IdMappingMode::LOOP); …
```
> Add a util function to get a concrete loop ID

- setup.py
Add in `setup.py` an option `install-dir=<absolute path>` to specify the install directory. If not provided, the install dir defaults to `./nvfuser`, thus the current default behavior remains unchanged.
- Useful option in itself
- My use case: I develop by  mounting the source repo inside a docker. Since NFS is very slow, I want to restrict the write/read to the mounted repo to the bare minimum, i.e., reading the source files. I am therefore already building fuser on a local mount, using the option `--build-dir`. But I found out that changing also the install dir speeds up further the installation
- I hope this could help reduce the NFS usage, as [was requested](https://nvidia.slack.com/archives/C8JCM3DPY/p1727281989644789?thread_ts=1727238691.063249&cid=C8JCM3DPY) to @cowanmeg and myself
> Add option to configure the install directory in `setup.py`

- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.h
- csrc/device_lower/pass/index.cpp
From https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#table-alignment-multi-dim-tma, the shared memory address must be 128B aligned.
This PR enforces this alignment for all TMA shared memory allocations to avoid `CUDA_ERROR_MISALIGNED_ADDRESS` errors.
> Enforce 128B alignment for TMA shared memory allocation.

- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/circular_buffer.h
- csrc/device_lower/pass/index.cpp
This PR converts `TmaCircularBufferInfo` from a struct into a class.
It creates the following functions:
```cpp
// Map cpAsyncBulk, MBarrierInit, and MBarrierInvalidate to its mbarrier tokens
void recordMBarrierToken(const Expr* expr, TensorView* mbarrier_tokens);
// Check if expression has mbarrier tokens
bool existsMBarrierToken(const Expr* expr) const;
// Get mbarrier tokens for expression
TensorView* getMBarrierToken(const Expr* expr);
// Map cpAsyncBul to its tensor index
void recordTensorIndex(const Expr* expr, kir::TensorIndex* index);
// Check if tensor index exists for expression
bool existsTensorIndex(const Expr* expr) const;
// Get tensor index for expression
kir::TensorIndex* getTensorIndex(const Expr* expr);
```
> Create TmaCircularBufferInfo class

- CMakeLists.txt
- csrc/device_lower/lower2device.cpp
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_indexing_advanced.cpp
Renamed test_gpu_indexing.cpp to test_indexing_advanced.cpp. Changed the tests to exercise both the legacy and new indexers.
Added several tests originally developed for IdModel (#32). Some of them are disabled as they are not yet supported.
> Indexing test cleanup

- csrc/multidevice/c10d_mock.h
Fix the [build issue](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/113280838) when building on ARM with `NVFUSER_DISTRIBUTED` disabled. PR #2950 introduced that bug.
> Add coalescing in c10d_mock.h

- csrc/multidevice/communicator.cpp
Try to avoid collision with framework setting up ProcessGroup
Supporting Slurm with #2804 introduced a failure in some [test workload](https://nvidia.slack.com/archives/C02E2PYNVSL/p1727354241677569)
- add `NVFUSER_` prefix to env `MASTER_ADDR` and `MASTER_PORT`
- change default port
> Change default port and parsed env to avoid collision

- tests/python/test_transformer_engine.py
A non-default port has been unnecessary after #3040.
> Update the default port and the comment.

- tests/cpp/test_mma.cpp
They were due to a race condition between #3008 and #3029/#3031.
> Fix build failures.

- tests/cpp/test_multidevice_transformer.cpp
Update to make transformer test match reference:
(1) In the forward test, layernorm weights and biases are included. They are initialized to one and zero respectively. Names of variables are 0-indexed now to match other tests. 
(2) In the backward test, a sharding propagation was accidentally removed causing extra communication and is added back.
> Transformer test updates

- csrc/scheduler/multi_matmul.cpp
- tests/cpp/test_multi_matmul_scheduler.cpp
This patches a small bug that incorrectly counted dimensions. We use a different system (`MatmulDimRolesMap`) to detect device and batch dimensions now, and it was identifying some device dims as batch dimensions. Although these dimensions _are_ batch dimensions in the batch matmul sense, they are not _local_ batch dimensions, i.e. they are not realized on each rank, so we skip them when computing `num_local_batch_dims_`. By contrast, in the existing scheduler we simply look for a device dim then subtract that plus 3 from `mma_result->nDims()`, which is not as flexible for future supported use cases with multiple M, N, or K dimensions.
This is necessary to get #3043 working.
> Multi-matmul scheduler: Skip device dims when counting local batch dims

- tests/cpp/test_multidevice_transformer.cpp
Without this PR, `mpirun -np 2 bin/test_multidevice --gtest_filter=DistributedTransformerTest.Backward/__bfloat` fails with the following error:
```
/opt/pytorch/nvfuser/tests/cpp/test_multidevice_transformer.cpp:107: Failure
Value of: outputs[i].allclose(expected_outputs[i], rtol, atol)
Actual: false
Expected: true
Output 6 mismatches with atol 0.0040000000000000001:
max absolute error under rtol: 0.00662231
max relative error: 0.00326538
failing elements: 17, 0.00576443% of tensor
```
> Relax an error threshold.

- csrc/codegen.cpp
See https://github.com/NVIDIA/Fuser/pull/2934#discussion_r1783671457
PR #665 allowed us to re-use allocations that have different dtypes. We already check that our aliased tensors do not have vectorized accesses larger than those of the original tensors. However, when we have different dtypes we `reinterpret_cast` it to a different `Array` type. Previously we did not specify any alignment in that type's template args, meaning it assumed an alignment of size 1. Since the actual addresses will all still be aligned this does not caused misaligned accesses at runtime. This PR sets the template arg for alignment to be that of the vectorized access width for the alias tensor, so that the compiler could hypothetically do some optimizations knowing the address is aligned.
> Specify different-dtype alias TV alignment

- csrc/preseg_passes/remove_bcast_squeeze.cpp
- tests/cpp/test_remove_bcast_squeeze.cpp
Our current broadcast+squeeze simplification pass (introduced in #2291) only does replacements if the broadcast flags exactly match the squeeze flags for neighboring `BroadcastOp` and `SqueezeOp` IR nodes. However, there are additional simplifications that can be made, and missing these can interfere with ID mapping leading to issues with inlining, for example: see comment here: https://github.com/NVIDIA/Fuser/issues/3027#issuecomment-2377501846.
This PR enables us to do simplifications where only some of the axes are bcast+squeezed. It also lets us remove intermediate `set` ops that could otherwise interfere with this analysis.
Fixes #3027
When we use `broadcast_in_dim` with new sizes other than 1, we insert two operations: a `BroadcastOp` and an `ExpandOp`. If we use that repeatedly we …
> Use more detailed broadcast-squeeze analysis in preseg pass

- csrc/scheduler/registry.h
This PR makes all methods in SchedulerEntry visible. This is helpful for third-party libraries such as our internal matmul heuristic plugin. Prior to this we will get a linker error when trying to instantiate a `SchedulerEntry` and call `schedule`.
> Make SchedulerEntry symbols visible

- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_multidevice_matmul.cpp
See code comments for details. 
This is required to land #3045.
> Pick the most parallelized input as the reference.

- csrc/ir/iostream.cpp
This is useful when printing a vector of `Statement*` where some elements are null. For example,
https://github.com/NVIDIA/Fuser/blob/1aa6ed072d890d75b9f2114a2c00f918d4ab75b4/csrc/ops/composite.cpp#L80-L81.
> Allow to print null.

- csrc/dispatch.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_multidevice_overlap.cpp
- adds a Host IR representing a call to `c10::cuda::CUDAStream::synchronize()`, used to synchronise the current stream with another stream.
- adds a stream synchronization that was missing in RS+GEMM host IR implementation
- required in #3060
> Host IRs: stream Synchronize

- csrc/host_ir/host_ir.cpp
Apparently, clang-tidy isn't smart enough to pick up the null check [here](https://github.com/NVIDIA/Fuser/blob/9757ca34f8a0eaf9b5331afd076e2cbface4e800/csrc/ir/builder.h#L45) and generated the false warnings. 
This PR added explicit null checks closer to where `ir_container_` is used to suppress the warnings. 
Alternatively, I could have done `NOLINTNEXTLINE(clang-analyzer-core.CallAndMessage)` but the type `CallAndMessage` is too generic and is unclear that dereferencing null pointers was the concern.
> Work around a clang-tidy limitation.

- csrc/device_lower/pass/circular_buffer.cpp
- csrc/type.cpp
- tests/cpp/test_circular_buffering.cpp
Looks like instead of using the promoted loop, we should just skip broadcast completely.
> Skip broadcast when computing TMA's expect bytes in circular buffering pass

- csrc/disjoint_set.h
```
[257/438] Building CXX object CMakeFiles/codegen_internal.dir/csrc/val_graph_visitor.cpp.o
/opt/pytorch/nvfuser/csrc/val_graph_visitor.cpp: In member function ‘bool nvfuser::ValGraphVisitor::traverse()’:
/opt/pytorch/nvfuser/csrc/val_graph_visitor.cpp:179:28: warning: comparison of integer expressions of different signedness: ‘int64_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
179 |   if (visited_exprs.size() != graph().disjointExprSets().size()) {
|       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix a compiler warning.

- tests/cpp/test_multidevice_host_ir.cpp
Skip a test that requires at least two ranks.
Fixes a CI issue https://github.com/NVIDIA/Fuser/pull/2970#issuecomment-2393893166
> Skip p2p test if communicator size is 1

- csrc/ir/internal_base_nodes.h
- csrc/scheduler/mma_utils.cpp
`Expr::definition() == nullptr` is no longer a valid check to detect root domains.
> Fix detection of root domains

- csrc/ir/nodes.cpp
- csrc/ops/composite.cpp
- csrc/ops/utils.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
- tests/cpp/test_translate_mma.cpp
- tests/python/opinfo_input_generators.py
- tests/python/test_matmul.py
- tests/python/test_multidevice.py
As long as the extra dimensions are DID-parallel.
This allows a distributed transformer layer to use linear (instead of matmul+add) for speed and will simplify the pending #3045. 
To avoid ambiguity, this PR also removes the support for 1D weight and 0D bias; otherwise, it's unclear whether a 2D weight is one device dimension plus a non-device or two non-devices. This support can be added back by changing the thunder-to-nvFuser bridge to convert a 1D/0D linear to unsqueeze followed by a 2D/1D linear followed by a squeeze.
> Allow linear to take a >2D weight and a >1D bias.

- csrc/ops/composite.cpp
- csrc/python_frontend/python_bindings.cpp
This PR fixes a bug introduced in #3073. This bug causes `nvFuser.Tensor` to have a different rank than the corresponding `TensorView`. This didn't trigger any test failure until I wrote a more complicated test that `slice`s the output of a linear. 
Question for @rdspring1 and/or @kevinstephano: shouldn't this bug be caught earlier? I guess when the Python frontend finalizes the definition it should have checked the output `nvFuser.Tensor`s are consistent with the output `TensorView`s. Wdyt?
> Fix fd.ops.linear to compute the right output rank.

- csrc/device_lower/pass/allocation.cpp
- tests/cpp/test_matmul.cpp
TMA will automatically fill zero, besides, the initialization will race with TMA itself as there is no sync between initialization and TMA.
Matmul perf after enabling circular buffering:
```markdown
Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name
--------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
57.3          3218718          1  3218718.0  3218718.0   3218718   3218718          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
12.5           700153          1   700153.0   700153.0    700153 …
```
> Don't initialize TMA output buffer

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ops/composite.cpp
- tests/python/test_multidevice.py
Similar to #3073, `sdpfa_fwd` shouldn't assume DIDs are available at definition time. Instead, treat extra preceding dimensions as batch at definition time and check they are device parallel at evaluation time. 
This is required to land #3115.
> Fix sdpfa_fwd to not assume the presence of DIDs.

- csrc/multidevice/communicator.cpp
- csrc/options.cpp
- csrc/options.h
- tests/cpp/test_multidevice_overlap.cpp
- Add an option to disable setting up multidevice communicator at runtime through parsing the env `NVFUSER_DISABLE` with the new option `multidevice`.
- Add missing checks to gracefully skip some recently added tests when the communicator is unavailable.
Mainly for debugging. This option quickly disables the multidevice module even when Fuser is built with multidevice support. We need this in particular to investigate possible conflicts between nvFuser communicator and the framework also setting up `c10d::ProcessGroup`
> Add option to disable multidevice at runtime

- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- csrc/serde/fusion_cache.fbs
- csrc/serde/fusion_record.cpp
- tests/python/test_python_frontend.py
* Currently, the python frontend represents `broadcast_in_dims` as a `broadcast` and `expand` composite operation. 
* For cpp to python translation, when we encounter an `Expand` expression, we must create a `BroadcastInDimsOp`.
* This `BroadcastInDimsOp` creates a redundant `broadcast` because the original `broadcast` was handled separately from the `expand`. 
* By adding the `expand` operation to the python frontend, we can create a one-to-one mapping in the cpp to python translation.
> Add expand operation to python frontend

- csrc/device_lower/pass/circular_buffer.cpp
See diff in generated kernel: https://www.diffchecker.com/uFzYklHb/
There is a tiny perf improvement:
```C++
Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name
--------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
23.0          1664884          1  1664884.0  1664884.0   1664884   1664884          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
10.8           782010          1   782010.0   782010.0    782010    782010          0.0  nvjet_hsh_192x192_64x3_2x1_v_bz_coopB_NTN
```
(benchmarked with …
> Don't generate unnecessary loops for `mbarrier::wait`

- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/pass/inline_ptx.cpp
Currently, the code for Hopper matmul kernel looks like below
```C++
accumulator = 0
for (prologue) {
TMA load A;
TMA load B;
}
for (main) {
TMA load A;
TMA load B;
mbarrier wait;
wgmma.fence;
wgmma;
}
for (epilogue) {
mbarrier wait;
wgmma.fence;
wgmma;
}
```
where we do the fencing at  every iteration. This is not optimal because, according to https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-warpgroup-level-matrix-instructions-wgmma-fence:
> The wgmma.fence instruction must be issued by all warps of the warpgroup at the following locations:
> 
> - Before the first `wgmma.mma_async` operation in a warpgroup.
>
> - Between a register access by a thread in the warpgroup and any `wgmma.mma_async` instruction that accesses the same registers, either as …
> Only do `wgmma.fence.sync.aligned` once

- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/dispatch.h
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- add new IR node `kir::FenceAsyncProxy` and `kir::WgMmaFence`, which will be lowered as `fence.proxy.async` and `wgmma.fence.sync.aligned` in `inline_ptx.cpp`. While it is possible to just create the `kir::Asm` nodes in the passes, I believe it's better to have a separate IR node so that other passes will not need to worry about details of the PTX instruction.
- In the past, syncs for TMA store and MMA are inserted in `index.cpp` and `inline_ptx.cpp`, which is not optimal. I moved the insertion code to `insert_syncs.cpp`.
- For Hopper MMA whose inputs are not guarded by mbarrier, insert fences before each mma instruction. These fences were removed in https://github.com/NVIDIA/Fuser/pull/3139 and https://github.com/NVIDIA/Fuser/pull/3136, but I believe we should add them back for this …
> A few cleanups

- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/runtime_info.cpp
- tests/cpp/test_translate_mma.cpp
Previously we rejected matmul segments with non-trivial allocation domains. However, I believe we properly handle allocation domain now with the latest changes to the matmul scheduler. I am enabling this now so that we can run all the python benchmarks.
Note that we still reject fusions with non-trivial output allocation domains. That support is likely also working but requires more testing before we enable it I believe.
> Enable matmul operands with non-trivial alloc domains

- csrc/scheduler/normalization_utils.cpp
**In this PR:**
When loading from global memory (gmem), use `CpAsync` with a short data path of `gmem -> smem` to reduce temporary register usage. Otherwise, the data path from gmem to shared memory (smem) follows this sequence: `gmem -> L1 cache -> register -> smem`.
1. Only enabled when device major version > 8 
2. Enabled for shared memory persistent kernels.
**Performance:**
(1) Large speeup happens when 3 buffers are using shared memory.
(2) Has a regression at 18688, register spills slightly increased.
Without CpAsync
```
ptxas info    : 3 bytes gmem
ptxas info    : Compiling entry function '_ZN90_GLOBAL__N__00000000_50___tmp_kernel_inner_outer_persistent_f0_c1_r0_g0_cu_a2ef60c3_11326442nvfuser_inner_outer_persistent_f0_c1_r0_g0ENS_6TensorINS_8__bfloatELi2ELi2EEES2_NS0_IfLi1ELi1EEENS …
```
> use cpAsync in shared memory persistent kernels

- csrc/python_frontend/fusion_cache.cpp
- csrc/python_frontend/fusion_cache.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/python_bindings.cpp
- doc/dev/python_scheduling/autotune_pointwise.py
- nvfuser/__init__.py
This PR explores auto-tuning a Pointwise fusion in the python-frontend.
- Exposes `PointwiseParams` in python frontend.
- Enables scheduling a fusion with the `Pointwise` scheduler and specific parameter configuration.
- Create `autotune_pointwise.py` to test several parameter configurations then apply `DecisionTreeRegressor`
- Using trained `DecisionTreeRegressor`, iterate over parameter configurations for given input arguments and predict the performance metric. The configuration with the best predicted performance is used to schedule a fusion.
- Removes child class requirement for defining `schedule` function in `FusionDefinition`
- Recompiles user schedule if `profile == True` in `FusionDefinition.execute`
1. schedule(SchedulerType) -> schedule fusion with specified heuristic. It …
> Profile configurations for pointwise scheduler in python frontend

- csrc/scheduler/matmul_heuristic.h
A change of index_type caused the IMA encountered in #3157. This happened because an earlier fusion was compiled with the same matmul params but Int32 index type, then it was re-used when Int was needed, causing wraparound and an illegal index.
Fixes #3157
> Compare cparams in MatmulParams::sameAs

- csrc/device_lower/pass/index.cpp
- tests/cpp/test_memory.cpp
This PR adds support to store any 2D piece of memory in registers to shared memory using stmatrix.
We tile the 2D memory in registers and store it using multiple calls to stmatrix inside a for-loop. 
For example the 2D memory [32, 32] can be tiled to 16 stmatrix calls (.x1 8x8) or 8 calls (.x2 16x8) or 4 calls (.x4 16x16).
In this PR, we start with a 2D memory say [32, 64], tile it to [(2, 16), (4, 8) ] -> [4, 2, 16, 8] -> [8, 16, 8] -- That is 8 calls to stmatrix of type .x2 which stores 16x8 tiles.
For the input [32, 64] once we have transformed to [8, 16, 8], we swizzle the memory in registers. We then parallelize it such that that inner-most dims (after merging) is vectorized (with vector length being the same as the elements being store per thread).
After swizzling and parallelizing …
> Support using stmatrix to store any shape in registers by tiling to multiple calls to stmatrix for 8x8, 16x8 and 16x16 tiles.

- benchmarks/python/test_rmsnorm_bwd.py
Should apply `clear_dynamo_cache()` in baseline benchmark.
> clear_dynamo_cache in rms norm bwd baseline

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/device_lower/analysis/index_compute.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/id_model/circular_buffer_indexing.cpp
- csrc/id_model/predicate_indexing.cpp
- csrc/index_compute.cpp
- csrc/ir/interface_nodes.h
- csrc/tensor_view.cpp
- tests/cpp/test_circular_buffering.cpp
Today, a circular-buffered Hopper MMA kernel looks like below (assuming 4 stages):
```python
for i in range(3):
load to A_buffer[i];
load to B_buffer[i];
for i in range(N):
load to A_buffer[(i + 3) % 4];
load to B_buffer[(i + 3) % 4];
wait for A_buffer[i % 4] and B_buffer[i % 4] to be ready;
mma(A_buffer[i % 4], B_buffer[i % 4]);
wait for mma to complete
for i in range(N-3, N):
wait for A_buffer[i % 4] and B_buffer[i % 4] to be ready;
mma(A_buffer[i % 4], B_buffer[i % 4]);
wait for mma to complete
```
Note that the `wait for mma to complete` in the main loop is mandatory, because at the next iteration, TMA will write to the operands of the mma operation in the current iteration, and the wait in the end of the current iteration is to avoid WAR hazard. Due to this wait, we are actually …
> Allow both load and compute to be pipelined for circular buffering

- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/python_frontend/fusion_record.h
- tests/cpp/test_dynamic_transform.cpp
They have the same implementation -- not sure why they have co-existed. I prefer `shape` because it's shorter. To reduce blast radius, I only removed `tensor_sizes` from the C++ APIs. The python API, `fd.ops.tensor_sizes`, remains the same.
> Deduplicate tensor_sizes and shape.

- tests/python/mpi_fixtures.py
- tests/python/test_transformer_engine.py
Fixes #3129. 
This is done by using fixtures. 
It's unclear why this avoids #3129. However, this appears to be the best practice according to https://pytorch.org/docs/stable/distributed.html#shutdown, and is more efficient.
> Call init/destroy_process_group once. 

- csrc/mma_type.h
This standardizes how we convert `MmaMacroEncode` to `uint64_t`. Doing this with a bitcast actually gives us UB because we are not guaranteed to have the given order for struct fields defined as bitfields. I first noticed this was happening when using a `libnvfuser.so` compiled as C++20 with another project linking against that was compiled using C++17. In that case, the compilation and linking worked properly, but we wound up with garbage for the `MmaMacro`. I think this PR will address this kind of issue.
> Remove bit_cast to convert MmaMacroEncode to uint64_t

- csrc/ops/alias.cpp
This is required to land #3177. remove_bcast_squeeze may insert new broadcasts and squeezes.
> Fix broadcast and squeeze to propagate the input device mesh.

- tests/python/test_multidevice.py
As a follow-up to #3045. 
For #2199.
> Shard MHA. 

- csrc/preseg_passes/remove_bcast_squeeze.cpp
- tests/cpp/test_remove_bcast_squeeze.cpp
This fixes an error seen in `mpirun -np 6 test_multidevice --gtest_filter=PipelineTest.Pipeline` which requires a six-GPU system.
> Ignore reduction axes in inputs for bcast+squeeze analysis

- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- tests/python/test_alias.py
Fixes #3117 
This PR creates `verifyTensorDimensions` to check that `Tensor.dims` equals the rank of the corresponding `TensorView`. It is called in `FusionDefinition::finalizeDefinition` after `buildFusionIr`.
> Fix Issue 3117

- csrc/fusion_profiler.cpp
- csrc/fusion_profiler.h
This is a simple addition to the `FusionProfiler` API.
In our C++ tests, developers like to schedule a Fusion independent of our cache hierarchy that includes segmentation.  `FusionProfiler` is designed to work with the cache hierarchy to profile all the segments of a fusion.  In the simple C++ tests, developers only use the `FusionExecutor` that executes a single kernel, therefore, is convenient to allow the user to measure the time of a single kernel.  In some instance, nvFuser allocates outputs and the `FusionProfiler` picks up those allocations as kernels from CUPTI and aggregates them as part of `FusionProfile.kernel_time_ms`.  Often, the user just wants to know the kernel time of the kernel they scheduled.  The following API `FusionProfiiler::lastKernelTime()` enables the user to …
> Add function `lastKernelTime()` to `FusionProfiler` for FusionExecutor timing

- csrc/ir/nodes.cpp
For example,
```
The contiguity of a broadcast/reduction dimension must be None. The contiguity of a non-broadcast/reduction dimension must be true/false. alloation_domain=[bS33{1}, bS35{1 ex 96}, bS34{1}, iS36{2048}, iS37{128}], contiguity=[n, n, t, t, t]
```
> validateContiguity prints better error message.

- csrc/fusion_segmenter.cpp
- csrc/ir/nodes.cpp
- csrc/ir/utils.h
- csrc/logical_domain_map.cpp
- csrc/logical_domain_map.h
- csrc/ops/indexing.cpp
- csrc/ops/indexing.h
- csrc/python_frontend/fusion_record.h
- csrc/scheduler/pointwise_utils.cpp
- csrc/scheduler/pointwise_utils.h
- csrc/scheduler/registry_utils.cpp
- tests/cpp/test_gpu_fused_reduction.cpp
- tests/cpp/test_scatter_gather.cpp
- tests/python/utils.py
This PR renames some index operations from `snake_case` to `camelCase` for consistency.
* from `take_along_axis` to `takeAlongAxis`
* from `torch_gather` to `torchGather`
> Rename take_along_axis and torch_gather to camelCase

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- tests/cpp/test_host_irs.cpp
- tests/cpp/test_multidevice_overlap.cpp
support pre-allocated outputs for matmul
Prerequesite for https://github.com/NVIDIA/Fuser/pull/3181, where the matmul's output needs to be stored in a slice of a global buffer.
Use`at::matmul_out` if the output is already associated with a buffer.
> Host irs: support MatmulOp with pre-allocated outputs

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/device_lower/pass/allocation.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
A refactor of the circular buffering analysis and allocation pass pulled out from https://github.com/NVIDIA/Fuser/pull/3202. There should be no behavioral change, just code movement to make it easier to implement https://github.com/NVIDIA/Fuser/pull/3202.
Changes:
- Let `CircularBufferInfo` track the concrete loop id -> circular buffered tv mapping. To conveniently do that, `setCircularBufferAxis` is renamed as `setCircularBufferTv` which not only does the things of the original `setCircularBufferAxis` but also updates `circular_buffer_tvs_`, the container used to track the new mapping.
- Move the insertion of the mbarrier allocation, initialization, and invalidation to `handle(ForLoop* fl)` in the allocation pass.
> Refactor of the circular buffering analysis and allocation pass

- csrc/device_lower/pass/circular_buffer.cpp
Similar to https://github.com/NVIDIA/Fuser/pull/3212
> Cleanup of circular buffering pass: add `currentParity`

- csrc/python_frontend/python_bindings.cpp
- tests/python/test_define.py
This will fix a bug introduced by my https://github.com/NVIDIA/Fuser/pull/3145.
> Fill contiguity according to stride_order. 

- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- runtime/bf16_support.cu
- runtime/fp16_support.cu
- runtime/fp8_support.cu
`cat` is translated to CUDA code with a if-then-else block:
```
if (i < input0_ext) {
out[idx] = input0[idx];
} else if (i < input0_ext + input1_ext) {
out[idx] = input1[idx];
} else if ...
```
This is correct, but I believe this can be simplified to just `out[idx] = input0[idx] + input1[idx] + ...` since all of the inputs are padded by zero, so this result should be equivalent.
Since `+` is not defined for some low precision types, bitwise-or is instead used when addition is not available.
On A100, this simplification yielded about 5% perf improvement of a RoPE module.
I didn't add any specific test since I don't know if any new test would be beneficial. Half, bfloat16 and fp8 types are tested by `ResizeTest.CatMemoryPromotionReducedFloating`.
> Simplify cat implementation

- csrc/iter_visitor.cpp
When a cycle occurs in the fusion, a segmentation fault can occur when printing the statements in the cycle. In this case, the developer doesn't get any information and must use `gdb` to diagnose the segmentation fault. This PR adds a warning message to print that a cycle is detected before printing the cycle's statements.
> Update print message for cycle detection.

- csrc/device_lower/pass/allocation.cpp
We need to wait for all of them anyway, so why not just use a single mbarrier?
I suggest reviewing this PR hiding whitespaces, the diff ignoring spaces are very small:
Perf:
```C++
Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name
--------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
19.1          1309169          1  1309169.0  1309169.0   1309169   1309169          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
11.3           776119          1   776119.0   776119.0    776119    776119          0.0 …
```
> Use a single mbarrier to guard all TMA loads for circular buffering

- tests/cpp/test_multidevice_communicator.cpp
The test failed
[once](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/116949080/viewer), but it's unclear from the error message how off the expectations are.
> Print duration as seconds for better error message.

- tests/cpp/test_multidevice_transformer.cpp
Multiple updates to C++ transformer tests
(1) Updates MLP and MHA layer to use LinearOp instead of Matmul+add when possible. Change the layout of weights to be in a transposed format to reduce transposes.
(2) Removes activation rematerializations of gemms in the backward tests.
(3) Also ups tolerances of failing tests.
> Update multidevice transformer to use LinearOp

- tools/codediff/diff_report.py
- tools/codediff/run_command.sh
Our improper handling of pytest log output led to failures in codediff CI jobs in the past day or so. I removed the splitting-based parser code and improved the regex approach. I tested with the artifact from a recent failing job and it worked.
This also fixes a tricky bug where we were observing different numbers of kernels in tests that did not have any code changes that would cause such behavior. The problem was that the FusionCache was serialized to `/tmp/nvfuser_kernel_db` on the first run of the script then it was deserialized on the next run. This means the second run would show fewer new kernels being compiled since there would be some cache hits. Now I make sure to clear `/tmp/nvfuser_kernel_db` inside `run_command.sh` and reinstate it after.
> [codediff] Handle timestamps in pytest verbose mode

- benchmarks/python/core.py
- benchmarks/python/test_matmul.py
This changes the python matmul benchmark to run four times as many tests:
- We parametrize by reduction in float or in fp16/bf16, which is enabled by default in PyTorch.
- We parametrize by `eager`. If this is true we directly compute `torch.matmul` without involving nvFuser. Otherwise we use nvFuser. This lets us compute baselines in the same run as we compute the nvFuser result instead of needing to re-run the benchmark with different environment variables as we previously had to.
nvFuser does not support split-K in reduced precision (see #1719), so we skip these cases for now.
> Run with and without half-precision matmul reduction in benchmark

- tests/cpp/test_matmul.cpp
This shape makes more sense: https://github.com/NVIDIA/Fuser/issues/3137#issuecomment-2438559998, https://github.com/NVIDIA/Fuser/issues/3279
Perf:
```
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name
43.2           205150          1  205150.0  205150.0    205150    205150          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
18.5            87550          1   87550.0   87550.0     87550     87550          0.0 …
```
> Change shape of `HSH_NT_128BSwizzle`

- csrc/codegen.cpp
- tests/cpp/test_gpu3.cpp
**Issue:**  https://github.com/NVIDIA/Fuser/issues/3273
The original failure happened in test `DistributedTransformerTest.Backward/__bfloat` when shared memory persistent is used with async copy (after https://github.com/NVIDIA/Fuser/pull/3217, not merged yet). The reason is pointer to bool was treated as bool when handling kir::asm in codegen 
**Fix:** If pointer, reture pointer type not the type it points to
**Results:** Added a unit test, error is fixed.
> avoid treating pointer to bool as bool when handling kir::asm in codegen

- csrc/device_lower/pass/scalar_hoist.cpp
- csrc/ir/base_nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
This PR fixes https://github.com/NVIDIA/Fuser/issues/3199
Perf:
```C++
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)
Name
47.8           247326          1  247326.0  247326.0    247326    247326          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
17.0            88191          1   88191.0   88191.0     88191     88191          0.0  nvjet_hsh_256x128_64x4_1x2_h_bz_coopA_NTT
```
Perf nvFuser/cuBLAS: `35.6%`
Strangely, elect-sync hurt instead of help perf. I need to look into this, but anyway, this …
> Fix elect sync predicate

- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.cpp
Previously:
```C++
if (elect-sync) {
arriveExpectTx
TMA
} else {
arrive
}
```
Now:
```C++
if (elect-sync) {
arriveExpectTx
TMA
}
```
I am very surprised that this fixes all the latencies introduced in the elect-sync fix https://github.com/NVIDIA/Fuser/pull/3295, and even better! But in general, we should sync as less as possible, and avoid unnecessary wait, so I think this PR makes sense.
Perf:
```C++
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)
Name
39.0           172735          1  172735.0  172735.0    172735    172735          0.0 …
```
> Only the TMA thread arrive

- csrc/scheduler/reduction.cpp
Simple fix to padded bdimx in inner reduction scheduler.
**Performance changes:**
**(1) H100**
5 lines corresponds to batch size of 16, 512, 2048, 8192, 16384
**(2) A100**
> fix padded bdimx to use warp reduction in inner reduction scheduler

- benchmarks/python/test_adaptive_layernorm_host.py
This benchmark was added recently and did not have the changes added by PR #3252.
The benchmark will fail on the CI due to missing import function
> Remove deprecated `clear_cuda_cache`

- csrc/preseg_passes/remove_empty.cpp
- csrc/serde/fusion_record.cpp
- tests/python/test_python_frontend.py
For dynamic fusions, we detect empty tensors and set their extents to immediate constant 0. Later, in the remove_empty preseg pass, we do a shallow check that extents are empty so that we can simplify the fusion. When the fusion is not dynamic there is no concretization step where we would do this extent replacement, so we might have constant 0 extents that are compound scalars. This caused us to miss some empty tensors in #3292, particularly one of the inputs to a `cat`.
This PR:
- Uses a deep evaluation of each `getMaybeExpandedExtent()` to determine if an axis is empty
- Adds an ExpressionEvaluator field to `EmptyTensorRemover` to avoid repeating the deep evaluation when possible. This won't help prevent repeated evaluation of symbolic extents; we could track those in an …
> Use deep evaluation of extents in remove_empty pass

- tools/check_determinism.sh
For example, try running the following commands:
```bash
rm -rf /tmp/nvfuser_kernel_db
tools/check_determinism.sh -- pytest -vs tests/python/test_ops.py::test_correctness_var_mean_float64
rm -rf /tmp/nvfuser_kernel_db
export DEBUG_SERDE=disable
tools/check_determinism.sh -- pytest -vs tests/python/test_ops.py::test_correctness_var_mean_float64
```
Note that this script will delete any existing *.cu files in the current directory.
> Add script to check for non-determinism

- csrc/ir/nodes.cpp
I believe this is just a trivial bug, and, luckily, I don't think it would actually affect anything. This could matter if an expanded iter domain got merged with a non-broadcast iter domain as part of a reshape op, but reshape converts expanded iter domains to non-broadcast iter domains, so this bug won't matter.
In the case of normal scheduling, whether the output of a merge with an expanded broadcast is still a broadcast or not shouldn't matter, I believe.
> Fix IterDomain::merge with expanded inner input

- csrc/serde/fusion_record.cpp
- tests/python/test_python_frontend.py
This PR adds `ceilDiv` to serde, which enables `is_clonable` in `test_issue_3292`.
> Fix `is_clonable` in `test_issue_3292`

- csrc/device_lower/pass/circular_buffer.cpp
- csrc/index_compute.cpp
Before:
```C++
if (elect-sync) {
arrive-expect-tx1;
tma1;
}
if (elect-sync) {
arrive-expect-tx2;
tma2;
}
```
After:
```
if (elect-sync) {
arrive-expect-tx1;
tma1;
arrive-expect-tx2;
tma2;
}
```
Perf:
```markdown
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name
36.0           151775          1  151775.0  151775.0    151775    151775          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
20.7            87135          1   87135.0   87135.0     87135 …
```
> Use a single elect sync ite for all trasactions

- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_matmul.cpp
There is no reason for us to check the Mma layout anymore when defining an MmaOp, since that is all handled in the scheduler now. I also added a test where a new batch dimension is broadcasted before defining the MmaOp.
Fixes #2273.
> Remove MmaOpDetails::input_layout and getInputLayout

- nvfuser/__init__.py
This is just a simple code reordering to put the point at which I print a repro from `fd.execute()` after the pybind function `_execute()` to before the function to allow us to print repros prior to segfaults.
> Change where we print python repros to allow us to print repros prior to segfaults

- tests/cpp/test_matmul.cpp
- tests/cpp/test_matmul_sass.cpp
- tests/cpp/test_matmul_scheduler.cpp
This PR adds `NVFUSER_TEST_CUDA_ARCH_RANGE_GUARD` to the Ampere matmul tests because the Hopper `MultiMatmulScheduler` will not support them.
> Add cuda arch guard to skip ampere matmul tests on Hopper GPUs

- benchmarks/python/normalization.py
- benchmarks/python/test_dropout_layernorm_bwd.py
- benchmarks/python/test_dropout_rmsnorm_bwd.py
- benchmarks/python/test_gelu_bwd.py
- benchmarks/python/test_huggingface_attn_bwd.py
- benchmarks/python/test_layernorm_bwd.py
- benchmarks/python/test_nanogpt_attn_bwd.py
- benchmarks/python/test_rmsnorm_bwd.py
- benchmarks/python/test_scale_bias_relu_bwd.py
- benchmarks/python/test_silu_mul_bwd.py
- benchmarks/python/test_softmax_bwd.py
Currently, the backward benchmark for `torch.compile` are compiling the `output.backward(grads)` function.
This PR changes the benchmarks to compile the corresponding forward function. 
The benchmarking results are at: http://nv/emR
Earlier, I was observing similar performance for eager and torchcompile for these backward benchmarks.
The files `*_bwd.py` are changed in this PR. We observe improved performance with torchcompile as compared to eager now. Note, that, the results from weekly will have more data points than the CI pipeline.
**Question**: `test_gelu_bwd_reduction.py` reduces the gradient of the input. I am not sure what would be the right function to compile here :/
Thanks to @xwang233 for help with running the CI pipeline!
> Compile forward function in baseline backward benchmarks

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
Closes Issue #3037.
For the test: https://github.com/NVIDIA/Fuser/blob/f08bd5182df894019cfd07f04f7b2125750af713/tests/cpp/test_sdpa_node.cpp#L691
**`SdpaFwdOp::toString()`**
```
T3_l___half[ iS12{16}, iS13{32}, iS14{64}, iS15{64} ],
T4_l_float[ iS16{16}, iS17{32}, iS18{64} ],
T5_l_int64_t[ ],
T6_l_int64_t[ ]
= sdpa(T0_g___half[ iS0{16}, iS1{32}, iS2{64}, iS3{64} ],
T1_g___half[ iS4{16}, iS5{32}, iS6{128}, iS7{64} ],
T2_g___half[ iS8{16}, iS9{32}, iS10{128}, iS11{64} ],
dropout_p = double(0),
is_causal = false  )
```
**`SdpaBwdOp::toString()`**
```
T8_g___half[ iS23{16}, iS24{32}, iS25{64}, iS26{64} ],
T9_g___half[ iS27{16}, iS28{32}, iS29{128}, iS30{64} ],
T10_g___half[ iS31{16}, iS32{32}, iS33{128}, iS34{64} ]
= sdpa_bwd(T7_g___half[ iS19{16}, iS20{32}, iS21{64}, iS22{64} ],
T0_g___half[ …
```
> Print all outputs in `SdpaFwdOp`

- tests/cpp/test_matmul.cpp
- tests/cpp/test_matmul_sass.cpp
- tests/cpp/test_matmul_scheduler.cpp
This PR creates four tests for the `HopperMultiMatmulScheduler`. Each tests covers a different matmul layout - TT, TN, NT, and NN where the input arguments are already broadcasted.
> Add TT, TN, NT, NN tests for HopperMultipleMatmulScheduler

- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/transform_replay.cpp
- csrc/transform_rfactor.cpp
- tests/cpp/test_gpu3.cpp
Instead of manually creating output IDs and directly constructing Split and Merge nodes, IterDomain::split and IterDomain::merge are used. This would reduce duplication of logic.
There's some slight change in iteration types of IDs generated when `TensorView::rFactor` is used. See the inline comment.
As of [8321cfd](https://github.com/NVIDIA/Fuser/pull/3327/commits/8321cfdd27ac15e9464f551e0c2ea0e5159357db), everything seems fine.
Closes #2520
> Use IterDomain::split and IterDomain::merge

- doc/dev/python_scheduling/autotune_pointwise.py
Fix the `autotune_pointwise` script which was broken by https://github.com/NVIDIA/Fuser/pull/3275.
The earlier PR changed the pointwise setting from `unroll_factor` to `inner_unroll_factor`.
> Fix autotune_pointwise.py script

- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/mutator.cpp
- tests/cpp/test_gpu3.cpp
It would result in a recursive definition.
> Avoid replacing a Val with a dependent Val

- csrc/python_frontend/python_bindings.cpp
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_heuristic_plugin_api.h
I can't find any commit in which this option was ever actually used. This is the commit where the option was originally introduced: https://github.com/csarofeen/pytorch/pull/2488/files#diff-e7a5a84a2cfeddeb15669f07105bdb3722a796600ea9e1f2eb25afb29283457eR22 We've gone this long without the ability to disable loop rotation, so either we should change the condition in the schedulers to respect it, or just remove it.
> Remove MatmulParams::rotate_ldmatrix_out_of_main_loop

- csrc/device_lower/pass/replace_size.cpp
- tests/cpp/test_gpu3.cpp
can't repro but this seems to be the right thing to do
Update: added a standalone repro
> replaceSymbolicSizes

- csrc/multidevice/executor.cpp
- csrc/runtime/allocations.cpp
- csrc/runtime/allocations.h
It's only used there and doesn't need to be exposed via headers.
> Move allocOutputSpace to multidevice/executor.cpp

- csrc/runtime/executor.cpp
- csrc/runtime/fusion_kernel_runtime.cpp
During serialization, the executor dispatch PR only serializes executors that are `KernelExecutor`. Previously, all `FusionExecutors` were serialized. 
During deserialization, iterate over all executors in `FusionKernelRuntime`. If it is a `KernelExecutor`, use the `group_id` for the `SegmentedGroup` to find the corresponding serialized `KernelExecutors` buffer. Then, use the buffer to deserialize the `KernelExecutor`. For `HostIrExecutor` and `ExprEvalExecutor` compile normally.
> Fix serialization errors in executor dispatch

- csrc/device_lower/pass/replace_size.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_gpu3.cpp
Noticed while working on #3309 that `i0` is replaced with `ceilDiv(i0, 1)`. While it isn't incorrect, it would make generated code look simpler if `ceilDiv(i0, 1)` is replaced with `i0`. 
This PR just changes representative iter domains used for replacing extents. In addition to the existing priority rules, the iter domain with the simplest extent is preferred as the representative ID of a given ID group. The simplicity of extents is just defined based on the number of expressions defining the extent val. So, for example, an iter domain with extent of `i0` should be used as the representative ID instead of iter domains with extent `ceilDiv(i0, 1)`.
There should be no logic change.
> Prefer simpler vals in replace sizes

- csrc/python_frontend/fusion_record.h
The `index` argument does not have to be a `TensorView` for the `select` operation.
Reference: `NVF_API TensorView* select(TensorView* tv, int64_t dim, Val* index);`
> Fix typecast error in SelectOpRecord

- csrc/scheduler/cache_policy_refiner.cpp
Type error was detected with #3263 while I was testing it with a Debug build. 
```
pytest -v tests/python/test_python_frontend.py -k test_pad_dynamic
```
It has a fusion of:
```
Inputs:
T0_g_float[ bS0{1}, iS1{i1}, iS2{i2} ]
Outputs:
T1_g_float[ bS11{1}, iS12{( ( i1 + ( (nvfuser_index_t)(( (int64_t)(( float(2.5) * ( (float)(7) ) )) )) ) ) + ( (nvfuser_index_t)(( (int64_t)(( float(2.5) * ( (float)(7) ) )) )) ) )}, iS13{( ( i2 + ( (nvfuser_index_t)(( (int64_t)(( float(2.5) * ( (float)(7) ) )) )) ) ) + ( (nvfuser_index_t)(( (int64_t)(( float(2.5) * ( (float)(7) ) )) )) ) )} ]
%kernel_math {
f7 = (float)(7);
f9 = float(2.5) * f7;
i11 = (int64_t)(f9);
i14 = (nvfuser_index_t)(i11);
i16 = (nvfuser_index_t)(i11);
i18 = (nvfuser_index_t)(i11);
i20 = (nvfuser_index_t)(i11);
T2_l_float[ bS3{1}, …
```
> LoadStoreOp can have scalar inputs, so type check is required

- tests/cpp/test_scatter_gather.cpp
This test uses pseudo random numbers to generate index tensors, which can result in requiring too large grid dimensions. For instance, there was this error reported today:
```
C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/executor_params.cpp":41, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Invalid number of blocks in y direction: 69923
Exception raised from assertValid at /opt/pytorch/nvfuser/csrc/runtime/executor_params.cpp:41 (most recent call first):
```
The true fix would be making sure the scheduler to use a proper launch configurations, but these index operations are only there as experimental ops, I think this fix should be good enough for now.
> Fix launch configuration error with ScatterGatherTest.TorchGatherAllRankAllSelectedDim

- csrc/options.cpp
- csrc/options.h
- csrc/runtime/fusion_kernel_runtime.cpp
This adds a new debug dump option that simply prints out all of the segmented fusion segments as python FusionDefinitions at compile time. This is useful for debugging non-segmentation related errors whose repros contain many segments. To do so, when you notice a compile error the printout will tell you which segmented group it was found in. Then run your code again with `NVFUSER_DUMP=python_definition_segments` which will print a definition function for each segmented group using the C++ to python translation that was recently added. This lets you create a more targeted repro by copying that smaller definition into the repro printed in the error message then updating the inputs so that it executes.
> Add NVFUSER_DUMP=python_definition_segments

- csrc/device_lower/utils.cpp
When debugging the matmul scheduler, I noticed that we hit an error when generating Hopper MMA when we use `NVFUSER_DISABLE=expr_simplify`. This PR makes that possible again. Note that the option is disabled only within `proveLinearAndGetStride` so it has no direct effect on index expressions, which is what we want to look at when using that option.
> Ensure expression simplification is enabled in proveLinearAndGetStride

- csrc/device_lower/pass/circular_buffer.cpp
- csrc/ir/nodes.cpp
- tests/cpp/test_indexing.cpp
Noticed some easy simplification while working on #3309. Not necessary for correctness and the actual perf would probably have no effect ,if any, thanks to expr simplification and index hoisting, but examining generated code could be easier when simplification is possible.
> Use SimplyfingIrBuilder for circular buffering

- tests/cpp/test_allocation_domain.cpp
The change was accidentally reverted in
https://github.com/NVIDIA/Fuser/pull/3349.
> Redo #3326.

- csrc/scheduler/reduction.cpp
**What's in this PR?**
This PR separates inner reduction heuristics into distinct 2D and 3D heuristic functions.
**Why?**
The 2D and 3D reductions represent different domain structures within the reduction tensor view:
- 2D inner reduction: Domains in the reduction tensor view can be merged into a 2D structure, [I, R].
- 3D inner reduction: Domains can be merged into a 3D structure, [R, I, R].
These two configurations require different parallelization strategies, so keeping them in separate functions enhances maintainability and allows for individual optimization of each heuristic.
**code changes**
The existing `innerReductionHeuristic()` is duplicated as `inner2dReductionHeuristic` and `inner3dReductionHeuristic`, will clean  `inner2dReductionHeuristic` in a separate PR.
> split inner reduction heuristics into 2d and 3d heuristics

- csrc/index_compute.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- tests/cpp/test_matmul.cpp
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/test_multidevice_matmul.cpp
This PR modifies `schedulePrologues` to use TMA loads to move mma operands to shared memory. Stacked on https://github.com/NVIDIA/Fuser/pull/3324 and https://github.com/NVIDIA/Fuser/pull/3310.
1. Input operands are loaded into shared memory via `CpAsyncBulkTensorTile` LoadStoreOp.
2. Replace `LdMatrix` operation with basic set.
3. Modified `scheduleOperandSmemStores` to apply swizzling to avoid bank conflicts.
4. Refactor `swizzleSharedMemory` by moving the analysis component to a separate function named `analyzeSwizzleSharedMemory`.
5. Create `tmaSwizzleSharedMemory` function that uses `analyzeSwizzleSharedMemory` and then finds the appropriate tma swizzle format.
6. Disable loop rotation. There is an issue with tma loads and circular buffering. Not sure if loop rotation is required for …
> Load mma operands to shared memory with TMA

- csrc/parallel_dimension_map.cpp
- tests/cpp/test_gpu3.cpp
This is important for Hopper MMA (see #3278) in which we only parallelize TIDx on the allocation domain of the MmaOp output. Currently this leads to us generating a usable kernel but we are not able to launch it properly because we can't infer the x dimension of the block size. This PR fixes that by replacing `tv->getLoopDomain()` with `tv->domain()->allIDs()` which will inspect the root, logical, loop, allocation domains and even intermediate IterDomains to try and find parallelized dimensions.
> Inspect all IDs instead of just loop in ParallelDimensionMap

- csrc/python_frontend/fusion_cache.cpp
- csrc/python_frontend/fusion_cache.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/runtime/fusion_kernel_runtime.cpp
The goal is to set `fusion_id` and `device_id` when creating `KernelExecutor` for `UserSchedule. Previously, it was set during `FusionExecutor::compileFusion`. This PR is stacked on `executor_dispatch`
**Changes to `UserSchedule` cache system:**
**Current:** The map key is the integer value of input arguments. The vector is of size `device id`.
`std::unordered_map<size_t, std::vector<UserSchedule>> user_def_schedules;`
**New:** The key to first map is the integer value of input arguments. The key to second map is of `device`.
**Why?** We can set the the `fusion_id` and `device_id` in the constructor of `UserSchedule` and `KernelExecutor`.
> Set `fusion_id` and `device_id` of `KernelExecutor` in constructor for user scheduling.

- csrc/scheduler/ampere_multi_matmul.cpp
- csrc/scheduler/ampere_multi_matmul.h
As suggested by @zasdfgbnm in https://github.com/NVIDIA/Fuser/pull/3278/files#r1833466428, this just renames one method in the Ampere matmul scheduler for clarity. No functional change is expected.
> Rename addSetsForCacheReads to cacheOperandsToRegisters

- csrc/scheduler/reduction.cpp
Following https://github.com/NVIDIA/Fuser/pull/3330
Removed paras and computations related to 3D inner reduction.
> clean 2dInnerReductionHeuristic

- tests/cpp/test_sdpa_node.cpp
A global functor doesn't buy us anything.
> Change a functor to a regular function.

- tests/cpp/test_id_model.cpp
Unit tests are supposed to clean themselves. If the purpose is to test toGraphvizDotGraph, I'd keep just that statement without storing the result to a file, the content of which isn't validated anyway.
> Remove debug prints

- csrc/device_lower/analysis/index_compute.cpp
- tests/cpp/test_indexing.cpp
This is a temporary WAR for #3374. It's temporary since the repro has no problem with the IdModel-based indexer. This is for unblocking @IvanYashchuk until we can make the new indexer enabled by default.
The root cause of the issue is when we attempt to find a correct indexing path from the loop domain to the allocation domain of the indexed tensor, the algorithm fails to find a path visiting a backward merge when the indexed tensor has only one of the inputs. That happens when the tensor is broadcast and gets inlined with broadcast forwarding. In the current code, in that case, it just picks the first traversal option, which I think happens to be working fine, but that's not necessarily the right chose, particularly because we are looking at all candidate next traversal targets that are …
> Fix the legacy loop indexing traversal

- csrc/preseg_passes/allocation_order_inference.cpp
- csrc/preseg_passes/allocation_order_inference.h
- tests/cpp/test_allocation_order_inference.cpp
This
1. makes the tests closer to reality because inferenceAllocationOrder is not the only thing that the pass does, and 
2. simplifies the tests so they don't have to specify sources and destinations.
> Change tests to call runPass directly.

- benchmarks/cpp/lstm_cell.cpp
- csrc/ops/composite.cpp
- csrc/tensor_metadata.cpp
- csrc/utils.h
- tests/cpp/test_gpu1.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/test_sharding.cpp
Currently, GetMetaData::evaluate validates allocation sizes and strides
only when the TV has allocation that's different from logical. With this
PR, it will validate allocation even when it's the same as logical.
This extra validation captured many bugs including #3386 and #3194.
These bugs are either fixed in this PR or in follow-ups.
Prepares for #3282
> Validate allocation sizes and strides more widely.

- CMakeLists.txt
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/fusion_state.cpp
- csrc/python_frontend/fusion_state.h
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/segmentation.cpp
- csrc/python_frontend/segmentation.h
- nvfuser/__init__.py
- tests/python/test_python_frontend.py
Segmentation decomposes a fusion into a directed acyclic graph (DAG) of sub-fusions. After applying the segmentation algorithm, we can translate the sub-fusions into their corresponding python definitions. Then, given the fusion's input arguments, the segments are run in the correct order to produce the output results.
The original FusionDefinition stores the sequence of sub-fusions and acts as an argument manager. It gathers the input arguments before running the sub-fusion and stores its results. To perform this function, it requires a map from the segment index space to the original index space. This mapping is generated while creating the python definition for each sub-fusion.
Step 1: `setupSegmentation` runs the segmentation algorithm on the CPP Fusion to create the …
> Build Segments for User Schedule Segmentation

- csrc/preseg_passes/mark_aliases_prepare.cpp
Previously, we sort by pointer values.
Fixes #3396
> Make sorting deterministic.

- tests/cpp/test_multidevice_overlap.cpp
Although `MultiDeviceTest::SetUp` early returns when the communicator isn't available, it doesn't automagically make the *caller* exit early.
> Skip SetUp when the communicator isn't available.

- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/segmentation.cpp
- csrc/python_frontend/segmentation.h
- nvfuser/__init__.py
- tests/python/test_python_frontend.py
-  `buildSegment` creates the CPP Fusion for a given segment id, translates it to a python FusionDefinition, then returns a mapping from the segment fusion state indices to the original fusion state indices.
- `FusionDefinition.segment` calls `setupSegmentation`, `buildSegment`, and `finalizeSegmentation` to create python definitions for the sub-fusions and their index mappings.
This PR implements `buildSegment` function for user-scheduler segmentation. It is the second PR in a stack, preceded by https://github.com/NVIDIA/Fuser/pull/3334 and followed by https://github.com/NVIDIA/Fuser/pull/3025.
1. Implement `buildSegment` function in `csrc/python_frontend/segmentation.cpp`.
2. Complete `segment` function in `nvfuser/__init__.py`
```python
def nvfuser_fusion_id1(fd : FusionDefinition) -> …
```
> Translate segments to python definition

- csrc/python_frontend/python_bindings.cpp
- csrc/runtime/executor_params.cpp
- csrc/runtime/executor_params.h
The `LaunchParams` class can act as a scheduler parameter or an executor constraint. The `bind` function uses `checkAndSet` to enforce that the value for a `ParallelType` cannot be set multiple times. The only way to modify a `LaunchParams` is construct a copy and replace the desired value.
This PR adds `bindUnsafe` to `LaunchParams` that allows setting value of `ParallelType` multiple times. It is only for use when `LaunchParams` is a configuration parameter.
* The `LaunchParams` class is exposed in the python frontend via `PointwiseParams` class.
> Add `unsafeBind` to `LaunchParams` to allow modification.

- csrc/scheduler/reduction.cpp
**Code Changes**
In outer reduction heuristic, set register count to achieve 50% occupancy with 1024 threads per SM. 
**Why**
nvFuser calculates register count based on one block per sm in `getMaxRegCount`, if compiler follows this register count, we may lose the opportunity to get 2 or more blocks per sm.
Another approach is to use `__launch_bounds__(max threads per block)` but that requires modify `__launch_bounds__` if launch para is changed, which doesn't seem as convenient as directly setting maxrregcount. Tried in [PR-3413](https://github.com/NVIDIA/Fuser/pull/3413), then closed.
**Performance changes:**
see [doc](https://docs.google.com/presentation/d/199smuyiLyWFdilOgAPYF7v9nmzIiFGmrm1K2lSXtWSs/edit?usp=sharing).
> set maxrregcount in outer reduction heuristic

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/ir/interface_nodes.h
Change `CircularBufferInfo::setStageDepthAndPrefetchDistance` to `CircularBufferInfo::setCircularBufferOptions` so that it will automatically work if in the future we add more fields to circular buffer options.
> Add interface to directly work with CircularBufferOptions

- csrc/compute_at_map.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/type.h
Don't hard code the list of all stages. Instead, get them. This will make it easier to add new stages in the future.
> Allocate index for all circular buffer stages

- csrc/device_lower/pass/circular_buffer.cpp
- Rename it to `ClonePipelinedTmaCircularBufferLoopAndInsertSync`.
- Use `circular_buffer_load_tvs_` instead of getting the data again.
- Fix an error in comment.
> Minor cleanup in `CloneTmaCircularBufferLoopAndInsertSync`

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/device_lower/analysis/index_compute.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/id_model/circular_buffer_indexing.cpp
- csrc/id_model/predicate_indexing.cpp
- csrc/index_compute.cpp
- csrc/ir/interface_nodes.h
- csrc/runtime/executor_utils.cpp
Remove `CircularBufferInfo::getStageDepthFor`, `CircularBufferInfo::getPrefetchDistanceFor`, `TensorView::circularBufferDepth`, and `TensorView::circularBufferPrefetchDistance`.
It is trivial enough to get the these fields from options, so they do not deserve a separate function.
> Remove `getStageDepthFor`, `getPrefetchDistanceFor`, `circularBufferDepth`, `circularBufferPrefetchDistance`

- csrc/python_frontend/python_bindings.cpp
This PR add support for `ReductionParams` to the python frontend. All parameters are exposed except `std::vector<TensorView*> smem_persistent_buffers` and `CompileParams`.
> Add ReductionParams to python frontend

- csrc/scheduler/reduction.cpp
This PR fixes the setting of `gdimx` in 2d and 3d inner reduction heuristics. 
Previously, `gdimx == LaunchParams::UNINITIALIZED_VAL` in the else block, so the `gdimx > scheduler_utils::x_grid_limit` if statement was always false and `gdimx` was not set.
> Fix the setting of `gdimx` in 2d and 3d inner reduction heuristics

- tests/cpp/test_multidevice_transformer.cpp
Add gtest skip when for distributed transformer sequence parallel when number of devices=1.
> Skip sequence parallel test when D=1

- csrc/device_lower/pass/circular_buffer.cpp
Refactor PR, no behavioral change.
- change `currentLoadStage` to work on all stages
- rename `createMbarrierArriveExpectTx` as `createRawMbarrierArriveExpectTx`, drop second parameter
> Cleanup `currentLoadStage`

- csrc/scheduler/normalization_inner_outer.cpp
when total_reduction_numel <= 1024, scheduler may use multiple reductions per block with bdimy > 1, this leads to race condition in shared memory when using async copy. Adding `cp.async.wait_all`after the 1st async copy can avoid the race, but needs to figure out the root cause before we can safely use it. So, here we put all buffers in registers.
race detected with:
```
NVFUSER_DUMP=scheduler_params,cuda_to_file NVFUSER_ENABLE=kernel_debug PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer --tool racecheck --racecheck-detect-level info  ./nvfuser_tests --gtest_filter='CombinedSchedulerTest.LayerNormBackward/dtype_double_batch_216_hidden_96'
```
> use bdimy = 1 to WAR smem race

- csrc/device_lower/pass/circular_buffer.cpp
This PR is just a refactor with no behavioral change. Things changed:
- Rename `mbarriers_to_wait_` -> `raw_mbarriers_to_wait_`
- Rename `getAllMbarriersToWaitFor` -> `getAllMbarriersToWait`
- Split `insertMBarrierWaitBeforeFirstRead` into two functions: `insertMBarrierWaitBeforeFirstRead` (same name), and `updateRawMbarrierToWaitMap`, where `insertMBarrierWaitBeforeFirstRead` checks if there are wait ready to be inserted, and insert these waits, and `updateRawMbarrierToWaitMap` updates `raw_mbarriers_to_wait_`.
> Split `insertMBarrierWaitBeforeFirstRead`

- tests/cpp/test_multidevice_matmul.cpp
I forgot why we added it. Probably no longer an issue with FusionExecutorCache.
> Remove an unnecessary segment_set.

- csrc/scheduler/matmul_utils.cpp
In the current main, `concrete_contig[(size_t)i]` can be a out-of-bound access. Changed it to `.at`, the following test results in an error as shown below:
```
./bin/test_matmul --gtest_filter='*CombineMulSumAsMmaTest.AmpereMulSumToMatmul_MultipleBroadcasts'
C++ exception with description "vector<bool>::_M_range_check: __n (which is 2) >= this->size() (which is 2)" thrown in the test body.
```
I suspect it's missing `push_back(false)` when the ID is broadcast, but not entirely sure.
> Fix memory access error

- csrc/docs/fuser.doxygen
This changes our doxygen config to assume we have the `dot` executable in our `$PATH`. This enables a number of diagrams to be built by default by doxygen. This PR also enables some non-default graphs: the call graph which shows functions called by each function and the caller graph which shows all other functions that call the function at hand. If you make a change to a function and want to see the potential impact, it is useful to inspect the caller graph.
Call graph:
Caller graph:
> Enable call/caller graphs in Doxygen

- csrc/device_lower/analysis/tma.cpp
- tests/cpp/test_memory.cpp
In our TMA support, there is a mechanism "Define box by compositing" which is used to reduce the dimensionality of TMA when possible. The reason for doing so is because our hardware has a limitation that the tensor dimension can not be more than 5D, and by collapsing some dimensions, we will be able to support tensors higher than 5D by viewing it as a tensor of less than 5D.
While I do believe this mechanism makes great sense in general, mindlessly collapsing as much as possible can cause trouble. For example, if the box size is `(2, 256)`, collapsing it into `(512,)` is a mistake because our hardware has another limitation that the box size can not be larger than `256`.
This PR makes the "Define box by compositing" mechanism smarter: instead of always collapsing, we check if collapsing …
> TMA: Don't merge dims when proven wrong

- csrc/device_lower/pass/circular_buffer.cpp
Originally, I thought that I would need a `ClonePipelinedTmaCircularBufferLoopAndInsertSync` and a `CloneWarpSpecializedTmaCircularBufferLoopAndInsertSync`. Now I changed my mind, and I believe it makes more sense to make the both the pipelined and warp specialized cloner the same class because the warp specialized code and the pipelined code with mbarrier for WAR really isn't that different.
> Change `CloneTmaCircularBufferLoopAndInsertSync`'s name back

- csrc/multidevice/utils.cpp
- tests/cpp/test_sharding.cpp
We used to put DID on reduction IterDomains and therefore needed noReductions.
> Remove an unnecessary filter

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
Instead of tracking these pairs of cache tensors and outputs, this PR just uses `fusion_->outputs()`. This change is a response to a tricky issue I found when translating matmul patterns whose output is a `dc` tensor. In such case if the translation replaces the output tensor, it will modify `cached_outputs_` leading to confusion. I'm removing this attribute to avoid this situation and because it doesn't offer us much convenience anyway.
> Remove HopperMultipleMatmulScheduler::cached_outputs_

- csrc/id_model/id_model.cpp
- tests/cpp/test_indexing.cpp
Just found that we can extend the AlmostExact graph by considering not just the factor of a split but its output extents. For example, splitting of an iter domain of extent 2 by a factor of 2 results in generating iter domains of extents 1 and 2, respectively. Previously, this didn't trigger any mapping, but it should be valid to consider the input ID and the inner ID mapped in the AlmostExact graph.
Codediff check shows a bunch of differences with matmul tests. As far as I see, they are just negligible changes like:
```
1: MatmulTest.AmpereMatmulSmemEpiloguePromotionRequiredA100
Kernel 1 CUDA PTX    ceed503d Diff c5a95cab -5 +5index type: int registers: 116 gmem: 3 static smem: 0 stack frame: 0 spill stores: 0 spill loads: 0 cmem[0]: 440 cmem[1]: 0 cmem[2]: 0 cmem[3]: 0 cmem[4]: 24
--- …
```
> More AlmostExact mappings

- csrc/runtime/fusion_kernel_runtime.cpp
Preseg passes (i.e. MarkAliasesPrepare and AllocationDomainInference) take care of allocation domain propagation. I found it more useful to print out the transforms as well as the math.
> NVFUSER_DUMP=fusion_ir_preseg prints out transforms.

- csrc/id_model/id_model_index_compute.cpp
- tests/cpp/test_indexing.cpp
This is a follow-up to #3454. Specifically, as we now allow updating of index mappings in `TensorIndexer::setIndex`, there can be a case like below:
```
merge b0(1), i1(8) -> i2(8)
```
When propagating the index of `i2`, `i2_idx`, backward, the input IDs would get `i2_idx / 8` and `i2_idx % 8`, respectively.  However, if `i2_idx` is not guaranteed to be less than 8 (for example, due to a non-divisible split of `i2`), the broadcast `b0` id would potentially get a non-zero index, which means that we would need to predicate `b0` as well, i.e., `i2_idx / 8 < 1`, if it's part of the allocation domain. However, this would not be predicated as we ignore broadcast IDs. The new unit test would fail at the validation due to this predication problem.
To fix the issue, we could also predicate …
> Fixing indexing issue with almost-exact mapping

- tests/cpp/test_multidevice_communicator.cpp
to get a better idea when the mismatch happened.
> Print iteration number

- csrc/runtime/executor.cpp
- csrc/runtime/executor_utils.h
executor_utils::CudaKernelTimer is no longer used, likely due to the switch to FusionProfiler.
> Remove executor_utils::CudaKernelTimer 

- csrc/device_lower/pass/circular_buffer.cpp
Another refactor that makes no behavioral change, but makes it naturally generalizes to warp specialization.
Removes `handlePrologueLoop` and `handleMainLoop`, move its logic into `processExpr`. This way, `processExpr` is not directly referring to any loop stage, but doing things like "if this loop stage has circular buffer load, then do this".
> More refactor on `CloneTmaCircularBufferLoopAndInsertSync`

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- tests/cpp/test_matmul_scheduler.cpp
* Create cache structure from registers -> shared memory -> global memory
* Shared memory uses regular `LoadStoreOp::Set` instead of `LoadStoreOp::StMatrix`
* Apply swizzle to shared memory allocation domain. Apply `scheduleStMatrixForMmaOutput` transformations to shared memory loop domain.
* Apply swizzle to global memory loop domain for TMA store.
* Avoids shared memory bank conflicts during store phase of matmul scheduler.
* Uses parameterized test fixture to test TMA store epilogue.
> Support TMA store in hopper matmul scheduler.

- tests/cpp/test_circular_buffering.cpp
Inner reduction uses block reduction, which implies block sync, which is not supported in warp specialization. So adding another test so that we can test warp specialization with reduction. Note that we will not support persistent + warp specialization. I can not think of a way to writing persistent kernel without using block syncs. We can of course replace that block sync with mbarrier, which provides finer-grained control to only synchronizing on the compute warp, but that needs labor and is not what we are prioritizing now.
> Add an outer reduction test for TMA circular buffering

- tests/cpp/test_circular_buffering.cpp
- Fixes a minor bug where the code and comment does not match
- Reduces the tile size on Y from 32 to 16 (because 32 means 1024 threads/CTA, already the max and no extra space for warp specialization)
> `TmaCircularBufferingTest.Matmul` change

- csrc/mma_type.h
- tests/cpp/test_matmul.cpp
- tests/cpp/test_memory.cpp
This was causing errors in one of my development branches. We need to be consistent with types that we manage with fusion when storing and getting.
> Fix type consistency in st matrix testing

- csrc/bfs.h
- csrc/id_model/indexing_traversal.cpp
- tests/cpp/test_indexing.cpp
Fixes this error of #3505 
```
Error from segmentation group 9:  INTERNAL ASSERT FAILED at "/Fuser/csrc/id_model/indexing_traversal.cpp":102, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Indexing path for resize not found: iblockIdx.y376{( ceilDiv(1280, blockDim.x) )}
```
The error happens when trying to use the indexing WAR for resize that was recently added (#3454). The war itself is limited, in particular it does not work with promoted loop IDs. The limitation should be fine for the RoPE scheduling I've been working on, but it's a real issue in general.
This PR avoids the issue by limiting the use of the WAR. Currently, the WAR is used whenever there's at least a single resize expr in a single math expr. That is actually overly pessimistic …
> Limit use of the indexing war for resize

- csrc/tensor_metadata.cpp
- tests/cpp/test_allocation_domain.cpp
with unsupported logical-to-allocation transforms.
https://github.com/google/googletest/blob/main/docs/advanced.md#death-tests
> Add some death tests to make sure we don't fail silently

- csrc/id_model/loop_promotion.cpp
Currently we check all loop groups, no matter if they correspond to loop IDs. For loop promotion, we only need to consider loop domains when checking if the full loop promotion analysis can be skipped. This refinement was necessary when playing with scheduling approaches for resize, although it is not currently necessary in #3425. I think this is generally better than the current method.
> Skip loop promotion analysis a little more aggressively

- tests/cpp/test_utils.cpp
This fixes a failure on TOT that has probably been present since #3126 was merged. This might not have been noticed previously since this test only runs in Debug mode.
> Update FunctionTrace{1,2} tests to reflect renamed file

- benchmarks/cpp/matmul.cpp
Currently the C++ matmul benchmarks are defined with broadcasts and we do not strip them in the Hopper automatic scheduler. Instead we assert that there are no extraneous ops in the prologue like `BroadcastOp`, which causes the benchmark to fail. This PR simply skips these tests on Hopper.
> Skip C++ matmul benchmarks on Hopper

- csrc/id_model/#id_model.cpp#
- csrc/id_model/id_model.cpp
- csrc/scheduler/tools/loop_domain_scheduler.cpp
- csrc/scheduler/tools/loop_domain_scheduler.h
- tests/cpp/test_loop_domain_scheduling.cpp
Extracted from #3425 
A simple scheduling utility that replays a single transform expr on the loop domain of a given tensor. It is conceptually similar to the existing transform propagator, but this interface can also replay a transform expr not just as a forward expr but also as a backward expr. 
The existing `scheduler_tools::scheduleLoopDomainsLike` can also be used to propagate loop domains across tensors, but I encountered with a couple of issues due to the resize mapping [issue](#3455). This `scheduleLoopDomainsBy` gives more explicit control to set loop domains with resize ops.
> add scheduler_tools::scheduleLoopDomainsBy

- csrc/host_ir/executor.cpp
- csrc/multidevice/communication.cpp
- tests/cpp/test_multidevice_overlap.cpp
I wrote this to make the allgather-related issue discovered in https://github.com/NVIDIA/Fuser/pull/3284#discussion_r1868843000 easier to expose. And it seems a good runtime check to have in extra, because `_allgather_base` treats I/O tensors as flat buffers and ignores the shapes.
> Harden assertBuffersHaveSameSize to check shapes.

- csrc/ir/builder.cpp
- tests/cpp/test_indexing.cpp
- If the simplification result is 1 or 0, use the cached IR node from fusion.
- Simplify `x + y - y` into `x`
> More pattern matching in  `SimplifyingIrBuilder::addExpr`

- csrc/id_model/indexing_traversal.cpp
- tests/cpp/test_indexing.cpp
This is a second attempt to fix #3505. The first attempt is #3515. As mentioned [here](https://github.com/NVIDIA/Fuser/issues/3505#issuecomment-2519021709), the first fix isn't sufficient when an expr has multiple resized inputs, like concat. The actual condition we need to check is between each producer and consumer pair, not between producers, so this second attempt is just changing how we check the condition.
> Resize war follow-up fix

- csrc/codegen.cpp
- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
In codegen, don't generate hard-coded `blockDim.x * blockDim.y * blockDim.z` for reduction buffer size. Instead, generate the size according to the parallel dimension map and subtract the extra warp due to warp specialization.
> Use parallel dimension map for reduction buffers in codegen

- benchmarks/python/core.py
- benchmarks/python/normalization.py
- benchmarks/python/test_broadcast_add_fwd.py
- benchmarks/python/test_dropout_layernorm_bwd.py
- benchmarks/python/test_dropout_layernorm_fwd.py
- benchmarks/python/test_dropout_rmsnorm_bwd.py
- benchmarks/python/test_dropout_rmsnorm_fwd.py
- benchmarks/python/test_gelu_bwd.py
- benchmarks/python/test_gelu_bwd_reduction.py
- benchmarks/python/test_gelu_fwd.py
- benchmarks/python/test_groupnorm_fwd.py
- benchmarks/python/test_huggingface_attn_bwd.py
- benchmarks/python/test_huggingface_attn_fwd.py
- benchmarks/python/test_layernorm_bwd.py
- benchmarks/python/test_layernorm_fwd.py
- benchmarks/python/test_nanogpt_attn_bwd.py
- benchmarks/python/test_nanogpt_attn_fwd.py
- benchmarks/python/test_pointwise_mul.py
- benchmarks/python/test_reduction.py
- benchmarks/python/test_reduction_epilogue.py
- benchmarks/python/test_rmsnorm_bwd.py
- benchmarks/python/test_rmsnorm_fwd.py
- benchmarks/python/test_scale_bias_relu_bwd.py
- benchmarks/python/test_scale_bias_relu_fwd.py
- benchmarks/python/test_silu_mul_bwd.py
- benchmarks/python/test_silu_mul_fwd.py
- benchmarks/python/test_softmax_bwd.py
- benchmarks/python/test_softmax_fwd.py
- benchmarks/python/test_transpose.py
- benchmarks/python/torch_ops.py
This PR restructures the baseline benchmarks:
1. use `with_executor` to centralize executor definitions. Thanks to @jacobhinkle for this suggestion.
2. Move torch definitions to a separate file for reuse between forward and backward benchmark files.
> Restructure baseline benchmarks

- csrc/device_lower/pass/index.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/utils.h
This PR adds support for 32B and 64B swizzles to StMatrix indexing and to the hopper matmul scheduler.
The number of distinct swizzle rows is number of bytes for swizzle divided by size of megabank (16B). The number of times a swizzle pattern is repeated to fill core (8, 8) matrix is number of swizzle rows (8) divided by number of distinct
rows.
```cpp
MmaInputSmemSwizzle swizzle = getSwizzle(out_tv);
int64_t swizzle_bytes = getBytesFromSwizzle(swizzle);
constexpr int64_t megabank_size_bytes = 16;
const int64_t distinct_swizzle_row_size = swizzle_bytes / megabank_size_bytes;
int row = ...;
int col = ...;
constexpr int64_t swizzle_row_size = 8;
const int64_t swizzle_row_repetitions = swizzle_row_size / distinct_swizzle_row_size;
int64_t  row_in_swizzle_pattern = (row % swizzle_row_size) / …
```
> Add support for 32B and 64B swizzles to hopper matmul scheduler

- csrc/codegen.cpp
When used with https://github.com/NVIDIA/Fuser/pull/3545, this contribute a speedup of 5% of cuBLAS!
Perf together with https://github.com/NVIDIA/Fuser/pull/3545 on H100:
```
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name
33.8           136319          1  136319.0  136319.0    136319    136319          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
22.7            91487          1   91487.0   91487.0     91487     91487          0.0 …
```
> Unroll warp-specialized loops

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- tests/cpp/test_matmul.cpp
This PR unblocks `MmaOp` from being used in warp specialized kernel.
> Eliminate the predicate of the consumer of circular buffer in compute warp

- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/kernel_ir.cpp
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- csrc/multidevice/lower_communication.cpp
- csrc/runtime/allocations.cpp
- csrc/runtime/allocations.h
- tests/cpp/test_host_irs.cpp
- Add `Allocate` node support in `HostIrExecutor`
- Update `MultiDeviceExecutor`'s lowering and execution to use this host node. This allows to greatly simplify the implementation and address a bunch of longstanding TODOs. Also, this way, host allocation is exercised through all the multi-device test using `MultiDeviceExecutor`.
Running
```
mpirun -x NVFUSER_DUMP=host_ir -np 8 test_multidevice --gtest_filter=Gather/PipelineTestTwoStages.Communication/87
```
prints
```
%HostIrContainer { (T0_g_float[iS0{3}, ideviceIdx.x1{3}, iS2{3}, iS3{5}] (DeviceMesh{0 2 3})) -> (T3_g_float[iS11{3}, iS12{3}, iS13{3}] (DeviceMesh{0 2 3})) :
PostOnStream (HostUnit0, Inputs:{T0_g_float[iS0{3}, ideviceIdx.x1{3}, iS2{3}, iS3{5}] (DeviceMesh{0 2 3}), }, Outputs:{T4_g_float[ideviceIdx.x15{3}, iS14{3}, iS16{3}] …
```
> Host irs: Allocate

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/python_bindings.cpp
- nvfuser/__init__.py
- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/python/mpi_fixtures.py
- tests/python/test_communication.py
- tests/python/test_multidevice.py
For #2563 
List of major changes: 
1. Add `FusionDefinition.sched.set_allocation_as_loop` to set the allocation domain of a TensorView to be the same as loop. 
2. Add a convenience helper `shard_tensor` to be used in unit tests. This leads to some refactoring on the C++ side. 
3. Remove _create_device_mesh with a DeviceMesh constructor. This way, mesh construction doesn't require `self.sched` and is made more flexible. 
4. Add setup/finalizeMultideviceSchedule to set the active fusion for multidevice_schedule. 
5. Add a Python test to exercise DID parallelization of loop domains.
> DID-parallelize a loop split in Python.

- csrc/device_lower/pass/index.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/utils.cpp
- tests/cpp/utils.h
This PR contains the actual code changes from https://github.com/NVIDIA/Fuser/pull/3552.
1. Fix `hardCodedIndexGenerationForStMatrixSwizzle` for stmatrix (16, 8). The lane column is always `lane_id / 16` not `lane_id / stsm_n_tile`.
2. Fix `tmaSwizzleSharedMemory` by ensuring box inner dimension is evenly divisible by swizzle size.
3. Clean `scheduleTMAStoreForMmaOutput` and `scheduleStMatrixForMmaOutput` by remove unnecessary scheduling and correcting `num_ids_to_skip`.
4. Replace `mma_macro_to_str_map` with `macroToString` function.
> Refactor StMatrix Logic

- CMakeLists.txt
- csrc/scheduler/tools/loop_domain_scheduler.cpp
- csrc/scheduler/tools/resize_utils.cpp
- csrc/scheduler/tools/resize_utils.h
- tests/cpp/test_loop_domain_scheduling.cpp
- tests/cpp/test_resize.cpp
Added a scheduler util function schedule a fusion with resize-based ops such as slice, pad and concat. This propagates resize ops to producers so that all tensors have the exact-mapped loop domains. 
Part of #3425. Extracted so that it can be individually tested.
(There's a follow-up PR: #3555)
> Propagating slice/pad/cat to inputs

- csrc/codegen.cpp
- tests/cpp/test_matmul.cpp
This PR adds a super naive CGA support. It is by no means how we should design CGA, and not even an incremental step. But this PR is simple enough and it does provide us with an additional parameter to tune about.
Perf on H100:
```
Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name
33.4           134047          1  134047.0  134047.0    134047    134047          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
22.9            92031          1   92031.0 …
```
> Very naive and stupid CGA support

- tests/python/test_transformer_engine.py
```
$ nvidia-smi -L
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3
$ mpirun -np 8 --output-filename /tmp/test_transformer_engine pytest tests/python/test_transformer_engine.py --only-mpi
$ cat /tmp/test_transformer_engine/1/rank.0/stdout
------------------------------------------------------------------------------------------ benchmark: 4 tests ------------------------------------------------------------------------------------------
Name (time in ms)                          Min                Max               Mean             StdDev            Median                IQR            Outliers       OPS …
```
> Benchmark sequence parallelism in test_transformer_engine

- csrc/multidevice/communication.cpp
- tests/cpp/test_multidevice_lower_communication.cpp
- tests/python/test_communication.py
For #2563
Tested: http://nv/eoZ
> ReduceScatter with DID loop split

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/reorder_sharded_axis.cpp
Patch resharding detection routines in `multidevice/utils` to handle expressions with multiple I/O
As a step toward https://jirasw.nvidia.com/browse/NVFUSER-106, the motivation for this patch is to be able to keep the MatmulOp (and potentially other ops in the future) as a resharding OP, which will undergo a special HostIr lowering (bypassing `ReorderShardedAxisPass`)
> Sharding Detection with multiple IO

- csrc/device_lower/lower2device.cpp
- csrc/id_model/indexing.cpp
- tests/cpp/test_resize.cpp
I'm pretty much always assuming the new indexer is used when resize is involved, so enabling the new indexer automatically when resize is detected.
There are a couple of new issues found while running the tests.
> Always enable IdModel-based indexing when resize is used

- csrc/scheduler/ampere_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_heuristic_plugin_api.h
- csrc/scheduler/matmul_utils.cpp
- tests/cpp/test_matmul_scheduler.cpp
Previously we had hardcoded to use `smem_circular_buffer_stage - 1` but this gives us more flexibility in our heuristic. We will use `smem_circular_buffer_stage - smem_circular_buffer_prefetch_gap` as the prefetch distance. Parametrizing this way lets us modify the number of stages without needing to adjust the prefetch gap each time, since it will most commonly just be 1.
> Add MatmulParams::CircularBufferOptions::smem_circular_buffer_prefetch_gap

- csrc/device_lower/utils.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- csrc/tensor_view.cpp
- csrc/transform_rfactor.cpp
- tests/cpp/test_matmul_scheduler.cpp
This PR implements `scheduleSplitKSum` function to support split-k gemm with the hopper matmul schedule.
- It support all operand formats such as TT, NT, TN, NN.
> Implement basic split-k gemm for hopper matmul scheduler

- csrc/device_lower/pass/expr_sort.cpp
- csrc/device_lower/pass/replace_size.cpp
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/iter_visitor.cpp
- csrc/iter_visitor.h
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_loop_domain_scheduling.cpp
- tests/cpp/test_resize.cpp
Stacked on #3585 
`StmtSort::getStmtsTo` may not grab all active iter domains if IDs are connected in an unconventional way. For example, we can set the loop domain of a tensor as a producer of its logical domain, but due to the nature of `IterVisitor`, such ID dependency patterns are not supported, meaning `StmtSort::getStmtsTo` would fail to grab all valid IDs and their exprs.
I just recently noticed this issue while working on #3556, specifically the issue got exposed as an inconsistent replacement of extent vals. I've been experimenting such patterns of domains, but I hadn't seen this before, likely because I was using just static shape tensors for convenience.
To fix the issue, I added a variation of `StmtSort::getStmtsTo`, which traverses a fusion as usual but stops at TensorView. …
> Grab all IDs and exprs with StmtSort::getAllStmts (and fix replaceSymbolicSizes)

- tests/cpp/test_multidevice_overlap.cpp
Implementation using ATen of https://docs.google.com/document/d/1Fzr9Zs2Dqfj3e4yR8LKxFrRqC1EkMUfQczJMYQGJQUI/edit?tab=t.0#heading=h.5x7hptdjzhet
> Ring-based decomposition for Allgather+GEMM overlap ATen implementation

- csrc/device_lower/lower2device.cpp
Followup to #3567. I just found the Loop option is also necessary. With this option, the inlining analysis uses IdModel to understand if inlining is possible. The loop generation lowering pass also uses IdModel loop promotion to figure out which iter domains to use for each `ForLoop` node. The latter is not necessary for the resize scheduler at this moment, though.
> Enable the Loop option of IdModle for resize

- csrc/python_frontend/python_bindings.cpp
This PR updates the comments for `__truediv__` operator defined in python bindings. The current comment does not reflect what the code actually does.
Reference: https://github.com/NVIDIA/Fuser/pull/2837#pullrequestreview-2282427318
> Update __truediv__ comment in python bindings.

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- tests/cpp/test_matmul_scheduler.cpp
This adds support for scheduling epilogue for the hopper matmul scheduler.
We don't support smem epilogue as yet.
We also don't honor the vectorization_factor as yet for the store to output. That'll be covered in a separate PR.
> Schedule epilogue (for Hopper Matmul) by propagation backward from output - smem epilogue not supported.

- tests/python/test_transformer_engine.py
It doesn't show a clear win for overlapping, but it's worth checking in the benchmark so we have a common ground to start with. 
```bash
$ mpirun -np 8 --output-filename /tmp/test_transformer_engine pytest tests/python/test_transformer_engine.py --only-mpi
```
```bash
$ cat /tmp/test_transformer_engine/1/rank.0/stdout
```
```
------------------------------------------------------------------------------------------------ benchmark: 6 tests ------------------------------------------------------------------------------------------------
Name (time in ms)                                     Min                 Max               Mean             StdDev            Median                IQR            Outliers       OPS            Rounds  Iterations …
```
> test_transformer_engine measures SP with overlapping.

- csrc/ir/nodes.cpp
Followup to #3514. Use `compareDomainWithReference` from the TensorDomain constructors too.
This change is required for #3556.
> Fix loop domain validation in TensorDomain constructors

- tests/cpp/test_matmul.cpp
This replicates the HSH_NT_128BSwizzle test using the automatic scheduler. I verified that this gives the same perf on H100. I did this to make it easier to experiment with perf tuning on this particular single-wave problem.
> Add Hopper matmul test that uses automatic scheduler

- tests/cpp/test_mma.cpp
This was causing errors in one of my development branches. We need to be consistent with types that we manage with fusion when storing and getting.
> Fix type consistency in SingleTileWithTMALoadStoreStMatrix for fusion.manage.

- CMakeLists.txt
- csrc/scheduler/vectorize_helper.cpp
- csrc/scheduler/vectorize_helper.h
- tests/cpp/test_resize.cpp
- tests/cpp/test_vectorization_analysis.cpp
Previously, vectorization analysis can only support resize in `PadOp` with positive extents: 1. General resize operation or negative extent would exclude the resized iter domain to participate in vectorized data movement; 2. Sliced inputs wouldn't have vectorized load.
This is a series of stacked PRs to adds support in vectorization analysis for general resize and it allows vectorized load on sliced inputs as well.
Order of PRs:
**1. Adding general support for `resize` op in `propagateResize` during projection; Adding support for negative resize extent in propagation.**
2. Adding alignment check on stride for resize-introduced non-contiguity, where a contiguous dimension becomes non-contiguous due to resize on its immediate inner dimension. #3528
3. Enable vectorized load on slice, …
> General resize support in propagateResize

- benchmarks/python/core.py
This extra `prof.start()` should not be present, since we are toggling the profiler in the try-except block at the start. This line restarts the profile after the first round finishes, and then the profiler tries to extract CUDA events at the beginning of the next round, when the target function has not run yet. Since, we clear L2 cache between rounds, we do not always see an error, and alternate rounds get correctly timed.
I think it is remnant from https://github.com/NVIDIA/Fuser/commit/9fc7bb39a6adaf78c49bedb469f4e410cd31d49a around the same time when we first saw this error in the CI.
Thanks to @jacobhinkle for the following deterministic repro which currently fails on main:
`pytest "benchmarks/python/test_matmul.py::test_matmul_baseline_benchmark[60456-8968-387936-TT-fp16-executor='ea …
> Remove extra prof.start

- csrc/scheduler/ampere_multi_matmul.cpp
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_matmul_scheduler.cpp
This removes some barriers to horizontal fusion and updates the test which is currently Ampere-only.
Note that most of the horizontal fusion code hasn't been exercised much so we might continue hitting small snags as we start using it more. My intention with this PR is to test it automatically by modifying the test. Likewise, we will need changes to the canSchedule checks and default heuristics to ensure sane behavior when doing horizontal fusions, so there will likely be more PRs of this flavor soon.
> Test horizontal matmul fusion in Llama2FFN test

- csrc/scheduler/resize.cpp
- csrc/scheduler/tools/resize_utils.cpp
- csrc/scheduler/tools/resize_utils.h
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_resize.cpp
Followup to #3556. Currently, the resize scheduler is only allowed with a single slice or pad. This PR allows for fusing multiple ops as long as they don't conflict. Please see the [comment](https://github.com/NVIDIA/Fuser/pull/3611/files#diff-b066c49d399243d3be36a44f1221490b9a2f50e41074feab836bc9bb6ee71180R25-R100) for `getNonExclusiveResizeInfo`.
In this PR, if there's a conflict, the fusion is simply rejected. A followup PR will address this limitation by replicating computations.
> Allow fusion of multiple exclusive resize ops

- tests/cpp/test_matmul.cpp
This PR adds the remaining layouts with customizable hopper matmul scheduler configurations for M=2048, N=2048, K=8192,
> Add TN, NN, TT UseScheduler Matmul tests

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
I think this is a bit more convenient.
> Show operator name with unary and binary nodes in graphviz dot outputs

- csrc/device_lower/analysis/device_version.cpp
- tests/cpp/test_gpu1.cpp
fp8's supported has been lifted to sm89 since PTX ISA 8.1 and later per https://docs.nvidia.com/cuda/parallel-thread-execution/
> Enable fp8 on sm89

- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_heuristic_plugin_api.h
This allows heuristic plugins to set cluster dimensions. By default, the cluster dims are set to {1, 1, 1}, which disables this feature, so if a plugin does not explicitly handle cluster dims, then it will just not make use of this feature. This is necessary because setting to an invalid value can cause a launch failure. This PR also prints the cluster dims in `MatmulParams::toString`.
> Allow matmul heuristic plugin to set cluster dimensions

- csrc/device_lower/pass/index.cpp
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/test_mma.cpp
The dtype for stmatrix should have never been constrained to only Half. The only constraint we have is that the dtype size is 16-bit. This PR is needed for us to actually use stmatrix in bfloat16 matmuls.
> Enable BFloat16 in stmatrix

- csrc/scheduler/utils.cpp
- tests/cpp/test_resize.cpp
Previously, vectorization analysis can only support resize in `PadOp` with positive extents: 1. General resize operation or negative extent would exclude the resized iter domain to participate in vectorized data movement; 2. Sliced inputs wouldn't have vectorized load.
This is a series of stacked PRs to adds support in vectorization analysis for general resize and it allows vectorized load on sliced inputs as well.
Order of PRs:
1. Adding general support for `resize` op in `propagateResize` during projection; Adding support for negative resize extent in propagation. #3457
[with updated more restrictive analysis on 1, the second PR is only optional at this point.]
2. Adding alignment check on stride for resize-introduced non-contiguity, where a contiguous dimension becomes non-contiguous …
> Enabling vectorization load for Slice

- csrc/codegen.cpp
- csrc/device_lower/analysis/circular_buffer.cpp
- tests/cpp/test_loop_rotation.cpp
Currently for dynamic shapes with circular buffered loops we unroll the following loops to different depths:
- epilogue: stages - 1 supposedly, but often specified as `#pragma unroll` probably due to use of `ensureStaticIndexing` in the indexing pass since this loop always has constant extent.
- main loop: unrolled as `#pragma unroll stages`
- prologue: fully unrolled `#pragma unroll` similar to epilogue.
This PR unrolls each of these loops explicitly by `#pragma prefetch` where prefetch is the circular buffering prefetch distance which is usually set to `stages - 1`.
When using static shapes like in Fusions we receive from Thunder, I noticed that our matmul main loops are being fully unrolled (at least this is requested but the compiler likely does not fully unroll). For example I have …
> Limit unrolling of all circular buffered loops to depth equal to prefetch

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/mma_utils.cpp
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/test_mma.cpp
Support non-stmatrix stores from regs to shared memory and then TMA when the output of mma op is not cast back to half precision - stmatrix works with half precision only.
> Add support for smem_epilogue when mma output is not cast to half

- tests/python/test_sdpa.py
When investigating context parallelism, I got conflicting signals about the meaning of the logsumexp output. For example, https://github.com/NVIDIA/TransformerEngine/blob/838345eba4fdd2a169dd9e087d39c30a360e684a/transformer_engine/pytorch/cpp_extensions/fused_attn.py#L1028 seems to suggest its `log(sum(e^(x-max)))` instead of `log(sum(e^x))`. This test verifies that we are returning the latter.
> Add a test for SDPA's logsumexp output

- csrc/scheduler/tools/loop_domain_scheduler.cpp
- tests/cpp/test_loop_domain_scheduling.cpp
Just fixing a simple bug that I didn't consider before. In `scheduleLoopDomainsLike`, when updating the existing loop domain, obviously it should not reuse the existing ID exprs.
> Fix scheduleLoopDomainsLike when the update-only mode is used

- CMakeLists.txt
- tests/cpp/test_rope.cpp
These are just for convenience when developing the resize scheduler. Converted from the RoPE python benchmarks. Currently only the forward and backward fusions of the Mistral case and the forward fusion of the Litgpt case. More cases may be added later.
> C++ tests for some of the RoPE benchmark cases

- csrc/scheduler/tools/domain_map.cpp
- tests/cpp/test_pointwise.cpp
Fixes #3653
This PR adds another projection to source ID after permissive mapping. This allows us to correctly identify coverage when the broadcast IDs are not source ID directly.
> Fixing `DomainMap::areAllTargetIdsCoveredBy` to handle broadcast to non-root IDs 

- tests/cpp/test_matmul_sass.cpp
In #3627 we reduced unrolling. This doesn't lead to a reduction in syncing, but it does reduce the number of sync instructions we see in the compiled SASS. That change broke a test which I'm updating in this PR.
Fixes #3661
> Fix expected BAR instructions in AmpereModifiersSharedMemoryEpilogue

- csrc/bfs.h
- csrc/ir/utils.cpp
- csrc/iter_visitor.h
- csrc/val_graph_visitor.h
- tests/cpp/test_bfs.cpp
Currently, the permissive BFS is only implemented for IRBFS. This change introduces the same traversal for ValGraphBFS, which is used in #3657. There should be no change for anything existing. There's a simple test for IRBFS (`BFSTest.IRBFSPermissiveTraversal`), which I still think should be enough.
> Generalize IRBFSWithPermissiveDependence to BFSWithPermissiveDependence

- csrc/host_ir/executor.cpp
- tests/cpp/test_multidevice_overlap.cpp
This PR implements the HostIR version of the Ring AG+GEMM overlap scheme. It also has some minor code-cleanliness updates to the ATen version.
> Ring Allgather + GEMM Overlap HostIR Implementation

- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/dispatch.h
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
This PR adds `kir::SetMaxNReg` and `kir::Return` nodes for register sharing with warp specialization.
`kir::SetMaxNReg` corresponds with [setmaxnreg](https://docs.nvidia.com/cuda/parallel-thread-execution/#miscellaneous-instructions-setmaxnreg) ptx instruction to add a compiler hint to increase or decrease the number of registers in a warp group.
`kir::Return` corresponds with an empty `return` statement. It is necessary to terminate the load warps early. Otherwise, cuda kernel will have poor performance.
> Create SetMaxNReg and Return kir nodes

- csrc/scheduler/tools/loop_domain_scheduler.cpp
- tests/cpp/test_loop_domain_scheduling.cpp
In `scheduleLoopDomainsLike`, I originally thought the reference should not have broadcast IDs, but that's not necessary the case with the RoPE cases. I'm not aware of any particular issue with allowing to have broadcast IDs, so removed the assertion and added a unit test.
> Relax broadcast constraint in scheduleLoopDomainsLike

- csrc/codegen.cpp
- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/ir/interface_nodes.h
- csrc/tensor_view.cpp
- tests/cpp/test_circular_buffering.cpp
- Add optional argument `warp_specialized_num_registers` to `circularBuffer`
- Create `RegisterSharingCircularBufferingPointwiseCustom` and `RegisterSharingCircularBufferingPointwiseNested`
- Create check to ensure that warp-specialized circular buffer loop is the outermost for-loop if register sharing is enabled.
> Add outermost for-loop check for warp specialized register sharing

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/ir/interface_nodes.h
- csrc/tensor_view.cpp
- tests/cpp/test_circular_buffering.cpp
- When `num_registers` is `std::nullopt` in `struct WarpSpecialized`, register sharing is not applied.
- Add `std::optional<std::pair<int64_t, int64_t>> num_registers` field to `struct WarpSpecialized`
- Add `std::nullopt` and default register sharing option to `tmaCircularBufferingParams`, so both configurations are tested in `Hopper/TmaCircularBufferingTest`
> Move `num_registers` configuration from `struct CircularBufferOptions` to `struct WarpSpecialized`

- tests/cpp/test_matmul.cpp
I'm adding this test to go along with the other `MLPBenchmarkFwd*` tests, as this is our target segmentation for our mistral-nemo MLP.
This test is currently failing validation except for one of the linears, which might indicate some syncing issues.
> Add test with horizontal fusion of linear ops

- .github/workflows/build.yml
- .github/workflows/lint.yml
Re: https://github.com/actions/runner-images/issues/10636
> If you see any issues with your workflows during transition period:
> 
> - Switch back to Ubuntu 22 by changing workflow YAML to use `runs-on: ubuntu-22.04` We support two latest LTS Ubuntu versions, so Ubuntu 22 will still be maintained for the next 2 years.
> Use ubuntu 22.04 runner in github actions

- csrc/id_model/indexing.cpp
- tests/cpp/test_indexing.cpp
Fixes #3688 
The error of #3688 is because some of the broadcast logical IDs are not reachable when indexing. Specifically, this happened when indexing the logical IDs of a consumer tensor of a pad op. https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/pass/index.cpp#L2698-L2699
When a consumer has broadcast logical IDs, they may not be reachable from the loop domain when inlined, and that's why the indexing traversal fails as seen in #3688. Note that for usual indexing paths such as `getLinearIndex` and `getPredicates`, they always filter out broadcast IDs from indexing because they should always use zero.
This PR always excludes broadcast IDs from indexing by changing `computeIndex`, which is the common indexing interface for all use cases including `getLinearIndex`, …
> Don't try to index broadcast IDs as they should always be zero and there may not be a valid path from loop IDs

- CMakeLists.txt
- csrc/python_frontend/communicator_bindings.cpp
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/python_bindings.h
- tests/python/test_multidevice.py
This is for #3091 and #3092, limitations of mpi4py that are hard to get rid of. This PR adds the bare minimum to get the sizes and the ranks. The next PRs will expose more methods in Communicator.
> Add pybind for Communicator

- csrc/device_lower/analysis/device_version.cpp
- tests/cpp/test_circular_buffering.cpp
Register sharing is only supported for hopper. This PR updates fusion checks and tests for this constraint.
> Enable register sharing only for hopper

- csrc/python_frontend/communicator_bindings.cpp
- tests/python/multidevice_fixtures.py
- tests/python/test_communication.py
- tests/python/test_multidevice.py
- tests/python/test_transformer_engine.py
except for test_transformer_engine.py. That test still uses the old mpi_test fixture, because it's a performance baseline that's intended to not depend on nvFuser for easy debugging.
For #3091 and #3092
> Use nvfuser.Comunicator in python tests

- csrc/device_lower/pass/insert_syncs.cpp
We previously did not insert fences before each MMA if they were guarded by mbarrier. The compiler warned us that these needed to be inserted and did so automatically. This PR inserts them in order to silence the warning.
Before:
```c++
#pragma unroll 3
for(nvfuser_index_t i21 = 0; i21 < i4; ++i21) {
nvfuser_index_t i22;
i22 = (3 + i21) % 4;
nvfuser_index_t i23;
i23 = i21 % 4;
unsigned i24;
i24 = i11 + (4096 * i23);
unsigned i25;
i25 = i7 + (8192 * i23);
if (((Hopper::electSync(4294967295U) && b16) && b17)) {
mbarrier::arriveExpectTX(toSmem((&T9[((3LL + i21) % 4)])), 8192U);
Hopper::cpAsyncBulkTensorTileG2S((Hopper::CpAsyncBulkTensorTileG2SIndex<2>{ ptr5, (Array<nvfuser_index_t, 2, 1>{(48 + (16 * i21)), i6}), toSmem((&T9[((3LL + i21) % 4)])) }), (i7 + (8192 * i22))); …
```
> Always insert wgmma.fence before MmaOp

- csrc/preseg_passes/pre_segmenter.cpp
For a fusion with pad ops, as long as it can be accepted by the resize scheduler, the move-pad pass is no longer necessary. This PR disables the pass only when the resize scheduler is enabled.
> Disable the move-pad preseg pass when the resize scheduler is enabled

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
Just small minor refactoring to add `TensorIndexer::getIndexingPath`, which is required in #3708. Nothing should change with this PR itself.
> Refactoring for PR #3708

- csrc/python_frontend/python_bindings.cpp
> Expose Tensor::index via Python API

- csrc/ir/nodes.cpp
- tests/python/test_multidevice.py
This PR adds a test case demonstrating DID loop split for linear.
The test does not require any changes to the `LinearOp::evaluate` method and works out of the box. DID split on logical domain continues to work for linear using the additional WARs present that squeeze/unsqueeze the DID dimension. Those WARs can be removed once we completely switch to representing device parallelism using allocation and loop domain.
> Linear with DID loop split

- CMakeLists.txt
- csrc/dispatch.h
- csrc/host_ir/container.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_host_ir_integration.cpp
- tests/cpp/test_multidevice_host_ir_integration.cpp
In this PR I add a vector of KernelExecutor* to HostIrContainer, and new HostIR called LaunchKernel that takes an index to the vector and launches the kernel. I also add a test to verify correctness.
This is the first in a series of PRs for integration with FusionExecutorCache.
> HostIR integration to FusionExecutorCache PR 1/n

- csrc/instrumentation.h
Tested:
```bash
$ nsys profile pytest tests/python/test_pointwise.py -k test_issue_2395
$ nsys stats --report nvtx_sum report1.nsys-rep | grep FusionExecutorCache
13.5         82349003          1  82349003.0  82349003.0  82349003  82349003          0.0  PushPop  :FusionExecutorCache::runFusionWithInputs
2.1         12982267          1  12982267.0  12982267.0  12982267  12982267          0.0  PushPop  :FusionExecutorCache::getKernelRuntimeFor
2.1         12946720          1  12946720.0  12946720.0  12946720  12946720          0.0  PushPop  :FusionExecutorCache::getKernelRuntimeFor::compileNewKRT
0.0           118345          1    118345.0    118345.0    118345    118345          0.0  PushPop  :FusionExecutorCache::prepareInputs
0.0              200          1       200.0       200.0 …
```
> nvtx2 is deprecated

- csrc/fusion.cpp
Quite commonly, debug dump like `NVFUSER_DUMP=fusion_ir_math` gets truncated when a device-side error happens. This should at least avoid that with some of fusion dump.
> Flush debug print to avoid truncated output

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/id_model/loop_promotion.cpp
- csrc/id_model/loop_promotion.h
- tests/cpp/test_id_model.cpp
This PR extends the condition to skip the full loop promotion analysis. Specifically, previously, it skips only if each loop group has a single exact group, in which case it's obvious any ID can be a promotion ID. That has been good enough so far, but I'm discovering a case where I can't avoid having a loop group that includes both concrete and broadcast IDs. As long as each loop group has only one single concrete exact group, loop promotion is still a trivial problem since we can just pick any ID from the concrete group.
This change should have no actual change but since different IDs may be picked as promotion IDs, actual generated code may look different, but differences should be just variable name changes.
> Extend the shortcut logic for loop promotion with cyclic graphs

- csrc/ir/nodes.cpp
This doesn't seem to break anything, but it's just strange to have iter domains like `iS1{8 ex 8}`, i.e., a concrete iter domain that appears to be extended to the same actual extent.
> Clear expanded extent in TensorDomain::flatten

- csrc/id_model/loop_promotion.cpp
- tests/cpp/test_id_model.cpp
I really want to spend some significant time to redesign the loop promotion so that we don't need the loop promotion WAR for cyclic graphs, but just found a simple bug with the WAR. Specifically, for whatever reasons, I thought it's safe to skip the full analysis whenever `inlining_info_.p2c_root_broadcast_resolution_map` is empty and just thought it's fine to pick which ID out of a loop group as its promotion ID. This map is filled when a broadcast ID is used with a concrete ID, so I think I thought if that's empty, there's no inlining, so there should be nothing to worry about.
However, that is not actually right. Even if a broadcast is not concretized, if its merged with a concrete ID, we can't just randomly pick an ID as the promotion. For example, here's a snippet from the added …
> Don't skip the full loop promotion analysis just because there's no root resolution map

- csrc/runtime/executor.cpp
- csrc/runtime/executor.h
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_resize.cpp
- tests/cpp/test_rope.cpp
It's no longer necessary after https://github.com/NVIDIA/Fuser/pull/3263. 
This partially rolls back https://github.com/NVIDIA/Fuser/pull/1930.
> Remove KernelExecutor::fusion_

- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/runtime/allocations.cpp
- csrc/runtime/allocations.h
- tests/python/test_multidevice.py
This PR modifies the `hasTrivialAllocationDomain` to consider if the tensorview has a DID loop split. In this case, we compare the corresponding iterdomains for logical and allocation domain across all but the sharded logical axis.
Note: This does not guarantee that `MatmulOp` with non-trivial stride order will work for DID loop split. I suspect it will require some additional changes to the `MatmulOp::evaluate` method.
> Matmul with DID loop split

- tests/python/test_multidevice.py
In this PR, I explicitly parallelize the outputs `attn`, `log_sumexp` of `sdpfa_fwd`. Sharding propagation for loop split does not work correctly in this case at the moment.
> DID loop split for SDPA

- CMakeLists.txt
- csrc/python_frontend/distributed_tensor.cpp
- csrc/python_frontend/distributed_tensor.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/multidevice_bindings.cpp
- csrc/utils.h
- nvfuser/__init__.py
- tests/python/multidevice_fixtures.py
- tests/python/test_communication.py
- tests/python/test_multidevice.py
This is done by adding a `nvfuser.DistributedTensor` that wraps a local tensor, a mesh and a mesh-axis-to-tensor-axis mapping.
> FusionDefinition.execute returns output shardings. 

- csrc/codegen.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/predicate.cpp
- csrc/kernel_ir.cpp
- csrc/runtime/allocations.cpp
- csrc/type.cpp
- csrc/type.h
- csrc/validator_utils.cpp
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_mbarrier.cpp
Add int16 (short), uint16, int8 (char), and uint8 (byte). 
Rename uint -> uint64 to be more consistent with PyTorch.
> Add missing integer and unsigned integer types.

- tests/python/test_dtensor.py
This is a proof of concept for integrating nvFuser's model parallelism to the framework.
> A FusionDefinition wrapper that takes/produces DTensors.

- csrc/codegen.cpp
- runtime/random_numbers.cu
Stacked on top of https://github.com/NVIDIA/Fuser/pull/3737
> Move RNG in runtime/random_numbers.cu to use Array instead of uint4/uint2.

- CMakeLists.txt
- benchmarks/cpp/transformer.cpp
My last PR for this (https://github.com/NVIDIA/Fuser/pull/3684) added a transformer benchmark to the existing google benchmark suite, but I ran into some problems:
1. You can't profile the benchmark unless you disable the profiler by commenting out the code that enables it, otherwise there is a CUPTI_MULTIPLE_SUBSCRIBERS error
2. Google benchmark does not allow a fixed number of warmup iterations, just some amount of warmup time
3. It's helpful to only profile the measured iterations, and the benchmark framework does not give enough control for that
Because of these I opted to just update Meghan's benchmark with new ATen inputs, since she had made some changes to the model.
> Transformer benchmark

- benchmarks/python/test_rope.py
#3349 removed grad accumulation, but rope benchmark implementation needs an update to get that working.
Reference implementation.
```
Model  Batch-Size  Sequence-Length  ... Forward-Time(ms)  Backward-Kernels  Backward-Time(ms)
0  Llama-2-7b-hf                      2             4096  ...            0.166                 5              0.857
0  Llama-3-8B                         2             8192  ...            0.567                 5              1.433
0  mistralai/Mistral-Nemo-Base-2407   1             4096  ...            0.138                 6              0.166
0  Qwen/Qwen2.5-7B-Instruct           1             4096  ...            0.072                 8              0.397
0  microsoft/Phi-3.5-mini-instruct    1             8192  ...            0.236                 6 …
```
> fixing rope pytest benchmark grad accumulation

- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/normalization_utils.h
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_persistent_buffer.cpp
- tests/cpp/test_pointwise.cpp
- tests/cpp/utils.h
Summary of major changes:
**1. Pointwise scheduler:** Add unroll in inner or outer dim, unroll factor is estimated from ops in the fusion & bytes in flight.
```
(1) Added function getUnrollFactor() to estimate unroll factor
// The unroll factor is calculated based on the following:
// (1) ensure enough bytes in flight to cover gmem access latency
// (2) ensure enough blocks for thread level parallelism (TLP)
// (3) don't unroll if split is not divisible and don't have enough TLP.
(2) Apply unroll to inner or outer dim
If the fusion is outer broadcast dominated, apply unroll to outer dim, otherwise, apply to inner dim.
Based on break point, when lhs byte multiple is smaller than rhs byte multiple, lhs has larger broadcast domains, the fusion is outer broadcast dominated.
(3) Revised bdimx …
```
> optimize pointwise, reduction, and normalizaiton schedulers for blackwell

- csrc/scheduler/utils.cpp
There are different versions of hardware and power is configurable.
> remove specific numbers for blackwell to avoid confusion

- csrc/device_lower/analysis/predicate_elimination.cpp
- tests/cpp/test_predicate_elimination.cpp
- Rename functions to accommodate our domain name change:
- `predicateNonDivisibleRootDomains` -> `predicateNonDivisibleLogicalDomains`
- `getZeroLeafIds` -> `getZeroLoopIds`
- Update `getZeroLoopIds` to use `ir_utils::isMemorySharedAcross` and `ir_utils::isMemoryPartitionedAcross`.
> Minor code cleanup on predicate elimination

- csrc/bfs.h
- tests/cpp/test_bfs.cpp
Just found some unintuitive traversal with the permissive BFS. For example, when there's a graph like:
```
a -> b, c (e.g., split)
```
When traversing from just `{b}`, the normal BFS won't allow any move since the backward traversal requires both `b` and `c`. The permissive BFS, on the other hand, allows to visit `a` since it allows traversal whenever there's at least one node already visited.
That's all I had in mind when I added the permissive BFS, but it turned out that it also visits `c` as well. The first move is `b, c -> a` while allowing the missing `c`, and the second move is `a -> b, c` since `a` is now visited and `c` is not yet visited. This doesn't seem to make sense since the reason `a` is visited is because we take the backward traversal of the edge. That in turn allows the …
> In the permissive bfs traversal, don't allow reverse traversal

- csrc/device_lower/pass/replace_size.cpp
- csrc/fusion.cpp
- csrc/fusion.h
- csrc/host_ir/container.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- tests/cpp/test_gpu3.cpp
Fusion managed exact mappings may need to be updated when iter domains are replaced. See the added test for a concrete example.
This isn't really a robust way to maintain exact mappings, but I don't have any other idea, either.
> Preserve registered extent mappings

- csrc/runtime/compiled_kernel.cpp
PR #3468 changed to using `CompiledKernel` and in the shuffle, we switched from using the incoming fusion before compilation to the lowered `kir::Kernel`. This PR just moves the printing to occur just before lowering, inside the constructor for `CompiledKernel`. I believe this is enough to restore the previous behavior.
Fixes #3765
> Print scheduled fusion instead of kernel for NVFUSER_DUMP=fusion_ir

- csrc/codegen.cpp
Currently, it is generating things like: `Array<int, 2>{ 1, 2}`, super ugly.
> Remove space to make generated code look better

- csrc/runtime/compiled_kernel.cpp
- tools/codediff/compare_codegen.sh
Generated CUDA files were previously named like `__tmp_kernel_32.cu` and `compare_codegen.sh` matched that pattern when copying kernels. That broke codediff since these filenames were changed in #3468. This PR fixes `compare_codegen.sh` to match `__tmp_*.cu` instead. It also fixes the outputs of printed PTX and cubin files so that they use the same base filenames: currently that is the previous naming scheme `__tmp_kernel_32.cu` (if using `NVFUSER_ENABLE=static_fusion_count`).
This should fix the problems seen recently in codediff CI jobs.
> Accomodate name change of printed kernel files

- tests/cpp/test_allocation_domain.cpp
This was fixed in the interim, either by some work on `replaceSymbolicSizes` or by #2706.
Fixes #3480
> Enable previously-failing symbolic allocation split test

- csrc/codegen.cpp
- csrc/ir/utils.h
- csrc/kernel.cpp
- csrc/tensor_view.cpp
- csrc/type.cpp
- csrc/type.h
Extracted from https://github.com/NVIDIA/Fuser/pull/3755 to make it easier to review.
> Add `MemoryType::Tensor`

- csrc/runtime/compiled_kernel.cpp
Minor change extracted from: https://github.com/NVIDIA/Fuser/pull/3755
> Use arch-specific PTX on Blackwell

- csrc/runtime/compiled_kernel.cpp
This uses the function name as the filename. Since #3778 we have been generating filenames like `__tmp_.ptx` since the `kernel_name` is not yet filled when cubin and ptx files are output. Now we will get `__tmp_nvfuser_none_f0_c0_r0_g0.{cu,cubin,ptx}` or if `NVFUSER_ENABLE=static_fusion_count` is provided
`__tmp_nvfuser_1.{cu,cubin,ptx}`.
> Fix names of printed ptx and cubin files

- CMakeLists.txt
- csrc/runtime/compiled_kernel.cpp
- runtime/cluster.cu
- runtime/mbarrier.cu
- runtime/memory.cu
1. Add distributed arrive for mbarriers. It allows synchronization of CTAs in the same CGA.
2. Fix clusterSync.
3. Add multicast variants of tma tensor loads. These functions do not have the L2 cache hint argument.
This PR adds the functions necessary for implementing https://github.com/NVIDIA/Fuser/issues/3689.
> Update cuda runtime files for TMA Multicast and cluster

- csrc/python_frontend/python_bindings.cpp
- csrc/scheduler/hopper_multi_matmul.h
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
This introduces a new type `MatmulParams::ClusterDims` and wraps it in the python frontend. This is essentially just a triple of `int64_t`s but I named the elements x, y, and z to make it easy to bind.
> Expose MatmulParams::cluster_dims in python frontend

- csrc/device_lower/pass/index.cpp
- csrc/scheduler/mma_utils.cpp
The current stmatrix scheduling assumes all iterDomains are parallelized to the left of the mma output allocation domain.
Therefore, it moves the stmatrix serial iterDomain to the 0th position. This is incompatible with persistent gemm kernels, which have a grid strided serial iterDomain.
This PR fixes this moving the stmatrix serial iterDomain back one position and using the 3rd from the end for-loop during index generation. The 3rd from the end for-loop is the 0th position from the mma output allocation domain.
> Fix stmatrix scheduling for persistent GEMM

- CMakeLists.txt
- csrc/codegen.cpp
- csrc/device_lower/analysis/tensor_memory.cpp
- csrc/device_lower/analysis/tensor_memory.h
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/kernel_ir.cpp
- csrc/type.cpp
- csrc/type.h
- tests/cpp/test_loop_rotation.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/utils.h
Extracted from https://github.com/NVIDIA/Fuser/pull/3755 to make code review easy.
This PR adds a new unit test `TMemTest.GmemRegTMemRegGmemCopy` that schedules a copy kernel gmem -> register -> tmem -> register -> gmem, and update our system with the minimum required changes to make this test pass.
The purpose of this PR is not to provide a good implementation of TMem support, but just to provide the absolute minimal requirement for us to start. Limitations are:
1. The index is hard coded zero, so this PR is not touching the interesting topic of "how to schedule TMem tensor?"
2. The TMem is used without allocation. Using a memory that is not allocated is clearly a wrong way to program, but as described in the code comment, if a fusion only has one TMem TensorView, it is guaranteed to …
> Naive register <-> tmem load/store support

- csrc/codegen.cpp
- tests/cpp/test_gpu3.cpp
Partially solve https://github.com/NVIDIA/Fuser/issues/3629
Currently, `genPowerWithMul()` only handles case with factor of 2 & 3, for `y = pow(x, 1.0)`, it should be lowered to `y = x` which is much faster than the power version.
> lower pow(x,1) to x

- csrc/scheduler/normalization_inner.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/normalization_utils.h
- tests/cpp/test_persistent_buffer.cpp
**Changes in this PR:**
(1) Use  `getSharedMemoryOverheadPerBlock` to calculate shared memory overhead in `getMaxRegOrSharedMemorySizeForPersistentBuffer`. This avoids error when the fusion has Welford ops, e.g. https://github.com/NVIDIA/Fuser/issues/3781
(2) When calculating shared memory size in `getMaxRegOrSharedMemorySizeForPersistentBuffer`, needs to consider the influence of non-divisible split by persistent batch size, e.g. shared memory is allocated as `vect x persistent batch x threads x sizeof(dtype)`
**Following works**
Further refactor to use `PersistentBufferStorageParams` is added at https://github.com/NVIDIA/Fuser/pull/3804
This refactor ensures a similar process is used for both inner persistent scheduler and inner outer persistent scheduler.
> fix error when calculating smem overhead

- tests/python/test_multidevice.py
given #3480 has been fixed. This simplifies the test as well by not having to pass in all dimension sizes to the model definition.
> Harden the test with dynamic shapes

- csrc/codegen.cpp
Minor change to `genPowerWithMul()`, to ensure a new line is added before indentation. Generated code changes from
```
T4[0]
= T2[0]        
* T2[0];
```
to
```
T4[0]
= T2[0]
* T2[0];
```
Bad format was introdued in https://github.com/NVIDIA/Fuser/pull/3774 by accident.
> format genPowerWithMul

- CMakeLists.txt
- csrc/fusion_segmenter.cpp
- csrc/preseg_passes/pre_segmenter.cpp
- csrc/preseg_passes/translate_no_reduction_matmul_to_mul_squeeze.cpp
- csrc/preseg_passes/translate_no_reduction_matmul_to_mul_squeeze.h
- tests/cpp/test_preseg_passes.cpp
- tests/python/test_matmul.py
When `MatmulOp` has `k=1`, there's no reduction, so it can be translated to a pointwise multiplication and a squeeze. It may not matter much by itself, but the mul+squeeze case can be easily fused with other operations, which is important in some of the RoPE benchmark cases as can be seen in the below performance results.
Closes #3646 
On H100 with #3776.
Before:
```
------------------------------------------------------------------------------------------------------------------- benchmark: 2 tests -------------------------------------------------------------------------------------------------------------------
Name (time in us)                                                                         Min                Max               Mean            StdDev             Median …
```
> Translate matmul to multiply and squeeze

- tests/cpp/test_matmul_scheduler.cpp
[CI](https://nv/e2E/138931416) detected the failure of `PreBroadcastMmaBiasNeg` on blackwell
> disable PreBroadcastMmaBiasNeg on blackwell

- csrc/scheduler/tools/maxinfo_propagator.cpp
- tests/cpp/test_sdpa_node.cpp
- tests/python/test_multidevice.py
This modification allows us to use `transform_like` to propagate loop domain split to other tensors in a fusion based on the input reference tensors. I will use this approach in `propagateShardings` preseg pass
> Disable sibling propagation by default in SetSelector to support SDPA

- csrc/codegen.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- tests/cpp/utils.h
This PR modifies `codegen.cpp` to allowing wrapping inline asm as utility functions.
A new method `utility` is added to `kir::Asm`, which either returns an empty string, which indicate that we should generate the PTX code directly into the kernel, or some valid identifier, which will be the name of the utility function that this PTX will be wrapped as.
In `CudaKernelGenerator`, instead of having a single string stream `code_`,  we now have two string streams `utility_` and `code_`, where `utility_` will hold all utilities generated by the codegen. Today, the utility section only contains PTX wrappers, but in the future, we can extent it to include more items as needed.
By generating utilities on the fly as needed, we can have the benefit of both the better readability of the kernel, and …
> Generate inline asm as utility function

- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/scheduler/tools/loop_domain_scheduler.cpp
- csrc/tensor_view.cpp
- tests/cpp/test_rope.cpp
Llama 3 RoPE backward is currently failing at https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/resize.cpp#L472. That is due to issue #3571. Specifically, a new concrete ID is created to fill a missing loop ID, which is then resized by another scheduleLoopDomain. At that point, due to the issue described in #3571, the tensor loses the access to the added extra ID because `scheduleLoopDomain` uses `TensorDomain::setLoopDomain`, which then [reinitializes the initial loop domain](https://github.com/NVIDIA/Fuser/blob/main/csrc/ir/nodes.cpp#L3837).
Maintaining extra IDs needs a better design. Extra broadcast IDs are maintained in `additional_ids_` but currently that's implicitly assume to contain only broadcast IDs. 
To workaround the issue, this PR avoids using `setLoopDomain` by using …
> Fix RoPE llama 3 backward

- csrc/device_lower/id_model_options.h
- csrc/device_lower/lower2device.cpp
- csrc/device_lower/validation.cpp
- csrc/options.cpp
- csrc/options.h
Changed to build an IdModel at the beginning of lowering by default. Also added a Disable option to disable it just in case.
These results are all collected on my workstation. The "steady" and "dynamic" results can be ignored as they shouldn't be impacted by this change. Not quite stable, but we can say that generally, as expected, there's some latency increase. For example, in the case of the adaptive layernorm, it increased to 258,445.3081 from 247,156.3010. Not too concerning, I would say.
Before
```
---------------------------------------------------------------------------------------------------------------------- benchmark: 3 tests ----------------------------------------------------------------------------------------------------------------------
Name (time in us) …
```
> Always build an IdModel during lowering

- csrc/host_ir/executor.cpp
- csrc/host_ir/lower.cpp
- csrc/host_ir/lower.h
- csrc/multidevice/device_mesh.cpp
- csrc/multidevice/device_mesh.h
- csrc/multidevice/utils.cpp
- csrc/type.cpp
- csrc/type.h
- tests/cpp/test_multidevice_host_ir.cpp
- tests/cpp/test_sharding.cpp
1. Extends DeviceMesh to support multidimensional meshes. Representation is a flat vector of devices and a vector of shapes. Since we only have plans to support DIDx, DIDy, and DIDz this naturally restricts the max dimensions to 3D.
2. Key functionality is in `getSlice(DeviceIdxType, ParallelType)` which gives a set of devices that a tensor is sharded over and communicates with given the (device) parallel type which translates into a dimension into the mesh.
3. Trivially modifies communication lowering to analyze a slice instead of the entire mesh for collectives that use the same mesh (AllReduce, ReduceScatter, AllGather). Collectives without this property assert that it is operating over a 1D mesh.
4. Adds ParallelType's DIDy, DIDz. These are not used anywhere except to index into 2D …
> Multidimensional device mesh

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
The function no longer needs to be template and is large enough to justify putting in cpp.
> Move getTvsWithDifferentSharding to cpp

- tests/cpp/test_persistent_buffer.cpp
I was wondering why there is an additional no op scheduler when the input data is `float32`. It turns out due to the redundant cast, we only need the cast when the input is `float16`.
This PR removes that cast for fp32.
> remove redundant cast in a test

- csrc/host_ir/executor.cpp
- csrc/host_ir/lower.cpp
- csrc/host_ir/lower.h
- csrc/multidevice/device_mesh.cpp
- csrc/multidevice/device_mesh.h
- csrc/multidevice/utils.cpp
- csrc/type.cpp
- csrc/type.h
- tests/cpp/test_sharding.cpp
Reverts NVIDIA/Fuser#3821 due to https://github.com/NVIDIA/Fuser/issues/3856
> Revert "Multidimensional device mesh"

- csrc/evaluator_common.cpp
- tests/python/test_multidevice.py
in the same way as ExpressionEvaluator::bindTensorDomain and several other places. Caveat: having to fix multiple places in the same way probably indicates a pre-existing duplication of logic.
Fixes #3817
> Fix PrecomputedValues::bindTensorMetaData for DID loop split

- csrc/multidevice/communicator.cpp
- csrc/options.cpp
- csrc/options.h
Using NVFUSER_ENABLE naturally comes with a type check. If the user mistyped wait_debugger, nvFuser will detect  that instead of ignore the option. 
Also, this naturally supports debugging multiple ranks with comma-separated arguments. For example,
```
mpirun -np 2 -x NVFUSER_ENABLE='wait_debugger(0,1)' bin/test_multidevice --gtest_filter=*ReduceScatter
```
> Make NVFUSER_MULTIDEVICE_WAIT_DEBUGGER_AT_RANK an EnableOption.

- csrc/scheduler/hopper_multi_matmul.cpp
This PR makes register sharing the default option for hopper matmul scheduler. For two warp groups, the load warp group gets 40 registers, while the compute warp group gets 232 registers. The hopper matmul scheduler enforces at most two warp groups are active in matmul fusion.
Register sharing is a matmul optimization that transfers registers from load warp group to compute warp group. The load warp group uses a single thread to launch tma loads, so it doesn't need many registers. The compute warp groups run the matrix multiplication and epilogue computation, so they can hit the register limit.
```
ptxas info    : Overriding maximum register limit 256 for 
'_ZN72_GLOBAL__N__00000000_33___tmp_nvfuser_none_f0_c0_r0_g0_cu_2efd3c58_9746224nvfuser_none_f0_c0_r0_g0ENS_6TensorINS_8__bfloatELi2ELi …
```
> Enable register sharing by default in matmul scheduler for better performance.

- csrc/device_lower/pass/insert_syncs.cpp
- tests/cpp/test_matmul.cpp
This PR adds special logic to `WarAsyncWaitInserter` that handles warp specialized circular buffering. This logic inserts the missing `wgmma` WAR sync before `mbarrier::arrive` in `ComputeWarp` for-loop.
Fixes https://github.com/NVIDIA/Fuser/issues/3561
The for-loop for the k dimension in matmul expressions is circular buffered. TMA loads are launched to load mma operands into shared memory, which are consumed by mma expression. A WAR sync is necessary for the wgmma expession to avoid overwriting the circular buffer stage while it is being read.
Special logic is required for warp specialized circular buffering because the TMA loads and wgmma ops are separated by an `IfThenElse`. `kir::ExprMutator` traverses the fusion in depth-wise order, so TMA loads in the `LoadWarp` are detected before …
> Add WAR sync for wgmma expressions in compute warp 

- benchmarks/python/test_matmul.py
- nvfuser/__init__.py
This small PR makes it so that python matmul benchmarks are run properly even when no `NVFUSER_ENABLE` or `NVFUSER_DISABLE` env var are set.
> Use _enable_options in benchmarks/python/test_matmul.py

- csrc/device_lower/pass/insert_syncs.cpp
- tests/cpp/test_matmul.cpp
This PR is stacked on #3863. When CTA tile k dimension is 64, incorrect results occur with pipelined circular buffering. The fix is to insert the wgmma WAR sync expressions before `kir::BlockSync`.
> The mandatory .sync qualifier indicates that wgmma.wait_group instruction causes the executing thread to wait until all threads in the warp execute the same wgmma.wait_group instruction before resuming execution.
The `wgmma.wait_group` ptx instruction only guarantees that a warp executes the instruction together. The entire warp group must complete `wgmma` instruction before loading next circular buffer stage.
From failing example: `./build/test_matmul --gtest_filter='*MLPBenchmarkTest.FwdGEMM/data_parallel_non_warpspec*'`
```cuda
#pragma unroll 3
for(nvfuser_index_t i20 = 0; i20 < i4; ++i20) …
```
> Fix WAR async issue with pipelined circular buffering

- csrc/codegen.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
This PR is a followup of https://github.com/NVIDIA/Fuser/pull/3844 that further wraps all instructions used by Hopper matmul as utility functions. The trick here is some PTX instructions requires some operands to be immediate numbers, so it must be a template parameter instead of a function parameter, so I have to extend our current implementation of codegen for `kir::Asm` to support it.
The `kir::Asm::AsmOptions` is extended with a new option specifying which input is always an immediate.
<details>
<summary>Example kernel:</summary>
```CUDA
__device__ __inline__ void wgmmaFence() {
asm volatile("wgmma.fence.sync.aligned;\n");
}
__device__ __inline__ void fenceAsyncProxy() {
asm volatile("fence.proxy.async;\n");
}
template <int in3, int in4, int in5, int in6>
__device__ __inline__ void …
```
> Wrap inline PTX as utility for Hopper matmul

- csrc/id_model/id_model.cpp
- csrc/id_model/id_model.h
- csrc/scheduler/matmul_utils.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/utils.cpp
- tests/cpp/test_bfs.cpp
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_id_model.cpp
- tests/cpp/test_loop_domain_scheduling.cpp
- tests/cpp/test_matmul_aten_evaluation.cpp
- tests/cpp/test_sdpa_node.cpp
This is just a cleanup PR. Changed `IdModel` to not build the full set of graphs by default since most of the times we just want to build the EXACT or BROADCAST graphs.
The `false` argument of `/*build_graphs=*/` can be omitted, but I didn't change that for clarity.
> Do not build all ID graphs automatically

- CMakeLists.txt
Upgraded to gcc 14.2.1, seeing some new failure:
```
[195/505] Building CXX object CMakeFiles/codegen_internal.dir/csrc/device_lower/pass/index.cpp.o
In file included from /home/gaoxiang/Fuser/csrc/iter_visitor.h:13,
from /home/gaoxiang/Fuser/csrc/fusion.h:18,
from /home/gaoxiang/Fuser/csrc/device_lower/analysis/index_compute.h:11,
from /home/gaoxiang/Fuser/csrc/device_lower/pass/index.cpp:8:
/home/gaoxiang/Fuser/csrc/bfs.h: In function ‘std::unordered_set<typename BFSType::ValType> nvfuser::projectTo(const typename BFSType::ValType&, const std::vector<typename BFSType::ValType>&, Direction, const AdditionalArgs& ...) [with BFSType = ValGraphBFS; AdditionalArgs = {ValGraph}]’:
/home/gaoxiang/Fuser/csrc/bfs.h:899:10: warning: ‘((const nvfuser::type*)<unknown>)[4611686018427387902]’ may be …
```
> Fix gcc 14.2.1

- tests/python/test_dtensor.py
This PR demonstrates how to wrap a forward and a backward fusion definition in a `torch.autograd.Function` that takes PyTorch DTensors as input and outputs PyTorch DTensors.
> Demonstrates autograd integration with NVFuser multidevice

- csrc/device_lower/analysis/device_version.cpp
- csrc/index_compute.cpp
- tests/cpp/test_circular_buffering.cpp
**Two changes in this PR:**
(1) circular buffer tests are extended to test both `LoadStoreOpType::CpAsyncBulkTensorTile` and `LoadStoreOpType::CpAsyncBulk`
(2) use IdModel indexing for 1D TMA, avoid offset bug when using warp specilization with prefetch
> extend circular buffer tests to test 1d TMA and fix index for 1dtma

- csrc/scheduler/utils.cpp
use default 128 cores per sm instead of report error
> use default 128 cores per sm instead of report error

- csrc/host_ir/lower.cpp
> [HostIr Lowering] Add sync stream at start of for-loop

- CMakeLists.txt
- tests/cpp/test_tutorial.cpp
Our CI missed running `tutorial` because we have a filtering rule `./bin/test_*`. Instead of adding another filtering rule, @xwang233 suggested that we should name all tests as `test_*`, which I believe makes sense.
> Fix test file names

- csrc/scheduler/utils.h
- doc/dev/tmem.md
Followup of https://github.com/NVIDIA/Fuser/pull/3874#issuecomment-2664791060, adding an example demonstrating how to schedule a performant copy kernel using tmem. This new test will give the reader an idea on how the special characteristics of tmem interact with the scheduling demand of vectorizing and coalescing gmem access.
> Add `TMemTutorialR.PerformantVectorizedCopy`

- csrc/python_frontend/python_bindings.cpp
- doc/dev/python_scheduling/profile_matmul.py
- doc/dev/python_scheduling/single_matmul.py
This PR adds a script to run a single matmul configuration with custom `MatmulParams`. It profiles the nvfuser kernel and compares its runtime against nvjet kernel runtime. The nvjet kernel runtimes are stored in a json file, generated by python benchmarks.
* Update python bindings to support constructing Matmul Options.
> Add a script to run a single matmul configuration with custom MatmulParams

- csrc/instrumentation.h
- csrc/preseg_passes/add_axioms.h
- csrc/preseg_passes/allocation_order_inference.h
- csrc/preseg_passes/consecutive_cast.h
- csrc/preseg_passes/exact_mapped_extent_substitution.h
- csrc/preseg_passes/insert_reshardings.h
- csrc/preseg_passes/make_resharding_contiguous.h
- csrc/preseg_passes/mark_aliases_prepare.h
- csrc/preseg_passes/move_pad.h
- csrc/preseg_passes/move_split_cat.h
- csrc/preseg_passes/optimization_pass.h
- csrc/preseg_passes/pre_segmenter.h
- csrc/preseg_passes/propagate_shardings.h
- csrc/preseg_passes/remove_bcast_squeeze.h
- csrc/preseg_passes/remove_empty.h
- csrc/preseg_passes/reorder_sharded_axis.h
- csrc/preseg_passes/segment_inplace_update.h
- csrc/preseg_passes/translate_no_reduction_matmul_to_mul_squeeze.h
- csrc/preseg_passes/translate_repeat_to_expand.h
- tests/cpp/test_preseg_passes.cpp
The name for the derived child class is destroyed before calling `Trace::endEvent`, so a bad name is created and chrome tracing cannot open the trace. This PR changes the return type of `OptimizationPass::name` from `std::string` to `constexpr char*`.
Error:
```
While importing:
SyntaxError: Bad control character in string literal in JSON at position 307792 (line 3203 column 14)
at JSON.parse (<anonymous>)
at new TraceEventImporter (chrome://tracing/tracing.js:6244:19)
at Import.createImporter_ (chrome://tracing/tracing.js:2033:8)
at chrome://tracing/tracing.js:2025:167
at Task.run (chrome://tracing/tracing.js:3149:95)
at runAnother (chrome://tracing/tracing.js:3152:371)
at runTask (chrome://tracing/tracing.js:2913:57)
at processIdleWork (chrome://tracing/tracing.js:2918:116)
at …
```
> Return constexpr char* from name function in OptimizationPass

- benchmarks/python/test_matmul.py
This fixes `benchmark/python/test_matmul.py` which currently fails unless `--disable-validation` is provided.
Related to #3886
> Fix call to fd.validate in python matmul benchmark

- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/reduction_utils.cpp
- csrc/scheduler/reduction_utils.h
**What?**
Code clean up, removes `multiReductionInliner()`
**why?**
This function was used in reduction scheduler and inner persistent scheduler, however, the usage are different and it takes many paras to differentiate the different usages.
This PR removes `multiReductionInliner()` and adds inlined function calls in  reduction scheduler and inner persistent scheduler, separately. This change makes further extension of inner persistent scheudler to use TMA easier.
> remove multiReductionInliner

- csrc/host_ir/executor.cpp
- csrc/host_ir/lower.cpp
- csrc/host_ir/lower.h
- csrc/multidevice/communication.cpp
- csrc/multidevice/communication.h
- csrc/multidevice/executor.cpp
- csrc/multidevice/executor.h
- tests/cpp/test_multidevice_pipeline.cpp
Add a way to specify the communication type per `Communication*` and expose the option at the API throuhg `MultiDeviceExecutor` and `HostIrLower`
> [Multidevice] Add backend type to Communication and expose to API

- tests/cpp/test_gpu3.cpp
For such a small reduction, the heuristic may pick a vectorization factor of 2 on some hardwares. Didn't see 1 is being used yet, if happens, we can add that.
Note: heuristic is not benchmarked on all hardwares.
> revise ground truth of vectorization factor in test VectorizeBackToBackReductions

- csrc/scheduler/reduction.cpp
- csrc/scheduler/reduction_utils.cpp
- csrc/tensor_view.cpp
- csrc/transform_rfactor.cpp
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_tutorial.cpp
- tests/python/test_communication.py
- tests/python/test_schedule_ops.py
> Fix rfactor replay for DID loop split

- tests/python/utils.py
Tested by running: 
```
DEBUG_SERDE=disable pytest tests/python/test_python_frontend.py -s -v -k enable_disable_options
```
> Remove skip_serde_check when disable_serde is on

- tests/cpp/test_scatter_gather.cpp
Some intermittent errors due to using too large inputs. To make things deterministic, std::srand is done at the beginning of each test. Also, the shmoo sweeping of the rank variable is currently set to done up to 5, but reduced to 4 as that's probably just enough.
> Adjust the scatter-gather tests

- manual_ci.sh
- setup.py
- tests/cpp/utils.h
- tools/codediff/codediff.py
- tools/codediff/compare_codegen.sh
- tools/codediff/run_command.sh
Following https://github.com/NVIDIA/Fuser/pull/3881, this PR replaces all `nvfuser_tests` with `test_nvfuser`
> replace nvfuser_tests with test_nvfuser

- csrc/device_lower/analysis/tensor_memory.cpp
- csrc/device_lower/analysis/tensor_memory.h
- csrc/tensor_view.cpp
- doc/dev/tmem.md
- runtime/tensor_memory.cu
- tests/cpp/test_memory.cpp
This PR updates the logic in the tensor memory lowering analysis to remove the hardcoded "32 columns". We are now doing a real analysis on the allocation domain, and compute the number of columns based on the schedule. This PR also adds validations of the allocations. 
As a result, we can enables two tests: `TooManyLanes`, `TooManyCols`.
> Tensor memory allocation analysis

- csrc/codegen.cpp
- csrc/runtime/compiled_kernel.cpp
- tests/cpp/test_loop_rotation.cpp
- tests/cpp/test_scalar_hoisting.cpp
Example error message:
```CUDA
[ RUN      ] TMemTest.AddKernelSameRegion
unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at "/home/gaoxiang/Fuser/csrc/runtime/compiled_kernel.cpp":169, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
// Codegen generated utilities
namespace tmem {
__device__ __inline__ void alloc(uint32_t in0, uint32_t in1) {
asm volatile("tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;\n"::"r"(in0), "r"(in1));
}
__device__ __inline__ void relinquishAllocPermit() {
asm volatile("tcgen05.relinquish_alloc_permit.cta_group::1.sync.aligned;\n");
}
__device__ __inline__ void store(uint32_t in0, Array<float, 1, 1> in1) {
asm volatile(
"tcgen05.st.sync.aligned.32x32b.x1.b32 [%0], {%1};\n" …
```
> Show codegen generated utilities in error message

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/mma_utils.h
- tests/cpp/test_matmul.cpp
- tests/cpp/test_memory.cpp
- tests/cpp/test_mma.cpp
The `MmaInputSmemSwizzle` swizzle argument is not used by `mma_utils::stMatrixForMmaOutput` so this PR removes it.
> Remove swizzle argument from stMatrixForMmaOutput

- csrc/codegen.cpp
- tests/cpp/test_circular_buffering.cpp
Register sharing using `setmaxnreg` requires compile time register usage, it was set by adding `__launch_bounds__(/*MAX_THREADS_PER_BLOCK=*/)` in https://github.com/NVIDIA/Fuser/pull/3669, however, we also need to add `MIN_BLOCKS_PER_SM` to calculate register usage per thread, otherwise, the compiler ignores `setmaxnreg`.
Before this PR, the test `RegisterSharingCircularBufferingPointwiseCustom` outputs `ptxas info    : (C7508) Potential Performance Loss: 'setmaxnreg' ignored; unable to determine register count at entry.` if compiled with ptxas_verbose.
Add hardcode `MIN_BLOCKS_PER_SM = 1`, it is only used for case with register sharing.
> setmaxnreg requires compile time register usage

- csrc/codegen.cpp
- tests/cpp/test_circular_buffering.cpp
Reverts NVIDIA/Fuser#3972
It caused some of the circular buffer tests hangs, the requested register size of `(40,240)` is too large for some of the tests.
> Revert "setmaxnreg requires compile time register usage"

- csrc/device_lower/analysis/tensor_memory.cpp
- csrc/device_lower/analysis/tensor_memory.h
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/inline_ptx.cpp
- csrc/type.cpp
- csrc/type.h
Today, we are hard coding the data path and vectorization size as `32x32b` and `1` in `inline_ptx.cpp`.
This PR moves one step further: it adds a hard-code pattern matcher `computeTMemLdStDataPath` that always outputs `32x32b` for data path, and uses `ir_utils::getVectorizeSize` to compute vectorization size. Now `inline_ptx.cpp` will use the information from the analysis of `computeTMemLdStDataPath` to generate PTX instructions. This makes our system less-hard-coded, although it is still hard coded.
> Add a hard-coded TMem data path pattern matcher

- tests/python/test_transformer_engine.py
Reverts NVIDIA/Fuser#3759
TE has apparently been fixed
> Revert "Temporarily skip the overlap test"

- csrc/utils.h
- examples/sinh_extension/setup.py
- examples/sinh_libtorch/CMakeLists.txt
- tests/cpp/test_utils.cpp
Add `zip` and `enumerate` as a convenient utility, which have the same behavior as Python's `zip` and `enumerate`. This PR also drop support for C++17.
> Add `zip` and `enumerate` as utility

- tests/cpp/test_host_irs.cpp
This had been broken consistently in CI although I couldn't reproduce the error. This PR seems to be able to fix it
> Make LinearHostIrTest.HostIrLinearOut less flaky

- tests/cpp/test_scatter_gather.cpp
Failing likely due to a race condition (#4003)
This should be enabled back as part of the ongoing work on cross entropy.
> Temporarily disable a take_along_axis test

- doc/dev/tmem.md
Move `NOT_IMPLEMENTED` down so our CI is running lowering tests on TMem tutorial. We can not run the fusion and check the result yet because the indexing is not done, but lowering to a cuda kernel with wrong index is already supported.
> Enable compilation test for TMem

- csrc/device_lower/pass/index.cpp
- tests/cpp/test_matmul.cpp
In the indexing lowering pass, getInnerMmaLoopGroup is used to determine the inner and outer MMA strides, which is used to create the wgmma descriptor. The purpose of that function is to obtain the ValGroup of the consumer loop ID corresponding to the innermost allocation domain of the producer. So we do need to be able to traverse from consumer loop to the innermost allocation group in the ValGraph, but we do not care about visiting any other groups.
See https://github.com/NVIDIA/Fuser/issues/3962#issuecomment-2695415388 for an example where we cannot currently reach some of the outer allocation dimensions if grid swizzling is used.
This PR just sets `require_all_to_visited` to false when performing the BFS. A more involved fix might update
`ValGraphBFS::getExprGroupsBetween` to accept a …
> Relax BFS target constraint in getInnerMmaLoopGroup

- csrc/scheduler/registry.cpp
This should also work around #4013
> Don't try to schedule EmbeddingFwdOp

- csrc/logical_domain_map.h
- tests/cpp/test_embedding_node.cpp
Fixes #4013 
`ComputeAtLogicalDomainMap` needs `handle` for `EmbeddingFwdOp` to analyze broadcast resolutions.
> Add missing handle for EmbeddingFwdOp

- csrc/runtime/allocations.cpp
We forgot to consider output with aliases when constructing kernel arguments.
This ended up giving us wrong arguments passed for kernel, producing wrong results.
> fixing wrong stride retrieved from fusion

- csrc/scheduler/matmul_utils.cpp
On main, our default Hopper heuristic gets poor perf:
This PR does some optimization to determine better tile sizes and load stages:
1) We always use instruction tile M/N equal to warp tile M/N, but warp tile K can vary from 16 to 256
2) We always use 1 or 2 math groups. When 1 math group is used the CTA tile matches the warp tile. When 2 math groups are used, the CTA tile is double the warp tile in either the M or N dimension.
3) We choose tile sizes by estimating the total amount of data transferred in the fusion, ignoring caching altogether. The configuration that minimizes bytes transferred is selected. **NOTE: currently we require all M, N, and K sizes to be multiples of 64. Other configurations are valid, but I got poor perf when enabling them.**
4) After choosing tile size, we …
> Update Hopper default matmul heuristic

- nvfuser/__init__.py
Small change in python execute function to avoid setting a torch.device call with an integer and then converting back to an integer.
> Avoid redundant integer conversion in Python `FusionDefinition.execute()`

- csrc/python_frontend/distributed_tensor.cpp
- csrc/python_frontend/distributed_tensor.h
- csrc/python_frontend/fusion_definition.cpp
- csrc/python_frontend/fusion_definition.h
- csrc/python_frontend/multidevice_bindings.cpp
- csrc/python_frontend/python_bindings.cpp
- nvfuser/__init__.py
- tests/python/test_communication.py
- tests/python/test_dtensor.py
- tests/python/test_multidevice.py
[Unpacking](https://github.com/NVIDIA/Fuser/blob/22d4f9702ea4a13028776b63e5ca39fcf8d3edc1/nvfuser/__init__.py#L328) in Python is apparently slow. 
This PR changes FusionDefinition.execute to return the output tensors and the output shardings separately. This way, single-GPU programs don't pay the overhead of packing/unpacking shardings. 
As a side benefit, this allows FusionDefinition::execute to return KernelArgumentHolder, making it possible for FusionDefinition.execute to return scalars.
> [python] return output tensors and output shardings separately

- nvfuser/__init__.py
This fixes a merge conflict between #4035 and #4042
> Move defined_multidevice_schedule out of the `if` scope

- csrc/fusion_segmenter.cpp
- csrc/fusion_segmenter.h
Fixes https://github.com/NVIDIA/Fuser/issues/3510 
Fixes https://github.com/Lightning-AI/lightning-thunder/issues/1490
With the repro from https://github.com/Lightning-AI/lightning-thunder/issues/1490 and n_layers=25 this PR takes it the time from 28.7s to 4.9s
There were two problems in `SegmentCandidateFinder::resetLevels` compounding to get terrible algorithmic complexity.
First is that there was n^2 traversal of the graph due to the way started the traversal, the second was we would reprocess nodes after they would be visited, adding in other nodes as they would be visited. I haven't even tried to figure out how bad the complexity is between the two, but given the timings above and how simple this function is supposed to be it's easy to imagine it was really bad.
Before this PR:
``` …
```
> Fix segmenter complexity in resetLevels

- csrc/fusion_segmenter.cpp
- csrc/fusion_segmenter.h
- tests/cpp/test_resharding.cpp
Similar to how resetLevels had relatively poor complexity and performance the validateDAG pass in fusion segmenter also does, it's not as bad, but scales poorly when trying to get a full llama model into nvFuser.
Should be merged after https://github.com/NVIDIA/Fuser/pull/4049
For https://github.com/kevinstephano/thunder_model_blocks
`python thunder_model_blocks/llama/llama_model_inference.py --execs Thunder-nvFuser-more-ops`
with `config.num_hidden_layers=5`:
Before using resetLevels to check DAG:
```
Time (%)  Total Time (ns)  Instances    Avg (ns)       Med (ns)      Min (ns)     Max (ns)    StdDev (ns)   Style                                  Range
--------  ---------------  ---------  -------------  -------------  -----------  -----------  -----------  ------- …
```
> Reuse resetLevels to validateDAG of segmented fusion.

- csrc/device_lower/pass/alias_memory.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/kernel_ir.cpp
- csrc/type.cpp
- doc/dev/tmem.md
- tests/cpp/test_memory.cpp
This PR adds the indexing of TMem load and store, and enables the tests that are now passing. Note that there are still tests disabled, and I believe the failing reason is due to missing block sync, not indexing.
> Indexing for TMem ld and st

- tests/cpp/test_tutorial.cpp
Previously disabled due to lack of tensor indexer support. Tensor indexer is now fully implemented, so enable it.
> Enable `TMABankConflictFreeTranspose`

- csrc/utils.h
- tests/cpp/test_utils.cpp
The current implementation can not be composed with `reverse`, like `zip(v, w) | std::views::reverse`, which is different from C++23's behavior. This PR fixes that issue by add the missing `operator--` when the input views are bidirectional. I also added `enumerate_view` and uses it to implement `enumerate`. This implementation is closer to how C++23 implements `enumerate`.
> Fix C++23 backport of `zip` and `enumerate`

- CMakeLists.txt
- tests/cpp/test_index_select.cpp
- tests/cpp/test_select.cpp
Just moving tests and renaming.
test_gpu_indexing_ops.cpp has tests of `select` and `index_select`. Moved them to their own files.
> Cleaning up test_gpu_indexing_ops.cpp

- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/utils.cpp
- csrc/dispatch.h
- csrc/fusion_segmenter.cpp
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/logical_domain_map.cpp
- csrc/logical_domain_map.h
- csrc/ops/indexing.cpp
- csrc/ops/indexing.h
- csrc/python_frontend/fusion_record.h
- csrc/python_frontend/python_bindings.cpp
- csrc/python_frontend/translation.cpp
- csrc/scheduler/registry_utils.cpp
- csrc/scheduler/tools/domain_map.cpp
- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.cpp
- csrc/serde/fusion_cache.fbs
- csrc/serde/fusion_record.cpp
- tests/cpp/test_gather.cpp
- tests/cpp/test_gpu_fused_reduction.cpp
- tests/cpp/test_resize.cpp
We used to have `gather` for a different op, which we removed.
> Rename TorchGather to Gather

- doc/dev/debug.md
We may want to do this for other Wiki pages, so 
1. Doc changes can be reviewed. 
2. It's easier to keep docs up to date when they are in the same repo as the code. E.g. https://github.com/NVIDIA/Fuser/wiki/Developer-guide#developer-guide still mentions `bin/nvfuser_tests`
> Move debugging instructions from Wiki to main

- tests/python/test_python_frontend.py
For #3856
is_clonable=False is an overkill.
> Mark supports_segmentation=False in test_issue1273

- csrc/scheduler/hopper_multi_matmul.cpp
In a case like this, there are 128 math threads and 128 dma threads per CTA, so 256 threads total per CTA. On Hopper, the register file holds 64K registers, which is 256*256, meaning in this case there is no sense in trying to increase registers for the math threads (you cannot increase past 256 registers per thread).
With this, I believe we can revert the reversion of #4061
> Disable register sharing with only one math warp group

- csrc/codegen.cpp
- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/kernel.cpp
- csrc/kernel.h
- csrc/utils.cpp
Reverts NVIDIA/Fuser#4093
Matmul scheduler is fixed in #4094
> Revert "Revert "add register count checks for warp specialization with register sharing""

- csrc/device_lower/analysis/tma.h
- csrc/device_lower/pass/alias_memory.cpp
- csrc/mma_type.cpp
- csrc/mma_type.h
This PR enforces the bytes alignment requirements for TMA LoadStoreOps, which prevents IMA and incorrect results.
If TMA LoadStoreOp is not detected, then alignment is 16.
1. None: 128 bytes aligned --- This default is to prevent IMA.
2. 32 byte swizzle mode: ... the starting address is 256 bytes aligned
3. 64 byte swizzle mode: ... the starting address is 512 bytes aligned
4. 128 byte swizzle mode: ... the starting address is 1024 bytes aligned
Reference: https://docs.nvidia.com/cuda/parallel-thread-execution/#swizzling-modes
> Enforce shared memory alignment for TMA LoadStoreOps

- tests/python/utils.py
This fixes a bug introduced in #3967 that is only exposed when the environment variable `DEBUG_SERDE=disable` is given when running the python tests. This is the case for the codediff CI jobs, so it is currently causing codediff failures.
> Avoid KeyError in python tests with DEBUG_SERDE=disable

- csrc/python_frontend/fusion_definition.cpp
We could in the future have a scalar-in-scalar-out fusion with some intermediate TensorViews being sharded. This is to make the check robust against that.
> getOutputShardings checks all TVs to decide single-GPU vs multi-GPU

- tools/codediff/run_command.sh
This fixes a bug in codediff CI where we currently do not recognize some tests as GOOGLETEST because they are launched through a script that shards the tests. This adds a substring to match that case and adds a couple other cases.
> Cover more command strings in run_command.sh

- tests/cpp/test_multidevice_host_ir.cpp
Each test takes >50 seconds on CI currently. While I understand more iterations are needed to get a stable reading on time, CI doesn't read time so doing so by default is a waste.
Consider adding a flag to control the number of iterations, or create a separate benchmark with the fusion definition extracted.
cc @samnordmann
> Reduce the number of iterations

- csrc/alias_analysis.cpp
The alias analysis pass has a `return` where there should be a `continue`. The loop is traversing over a `std::unordered_map` so the order differs from run to run. When we hit the return it will short-circuit the function, leading us to skip subsequent aliases that would be marked in other traversal orders. This has been causing failures in codediff in the `tests/python/test_python_frontend.py::TestNvFuserFrontend::test_bcast_squeeze_replace_aliased_output` test.
> Fix non-deterministic incomplete alias analysis

- csrc/alias_analysis.cpp
- csrc/exceptions.h
which always prints out lhs and rhs for better error messages.
For #1169
> Add the NVF_ERROR_EQ macro

- csrc/id_model/indexing.cpp
Not sure if there's any case where this change actually matters, but this should be the right way. I'm trying to remove some of the overlap between the allocation domain settings of the allocation pass and indexing.
> Indexing minor fix

- CMakeLists.txt
- tests/cpp/utils.cpp
- tests/cpp/utils.h
tests/cpp/utils.h is a busy header file used by all tests.
> Move definitions to cpp

- tests/cpp/test_multidevice_overlap.cpp
- tests/cpp/utils.cpp
- tests/cpp/utils.h
https://github.com/google/googletest/blob/main/docs/faq.md#CtorVsSetUp
> Move code from SetUp/TearDown to constructor/destructor

- csrc/device_lower/pass/alias_memory.cpp
- tests/cpp/test_tmem.cpp
To use TMem, we must have a smem tensor for storing the address of TMem, and uses `smem_tv[0] = tcgen05::alloc()` to store the allocated TMem address. The liveness of this smem tv should be from the `tcgen05::alloc` to the `tcgen05::dealloc`. However, we are currently unable to get that due to `tcgen05::dealloc(smem_tv[0])` is not a "TV Op". Due to this bug, the smem address tensor is allocated overlapping with other smem tensors. This PR fixes this bug by handling both TV Op or non-TV op correctly.
> Fix liveness of TMem address smem TV

- csrc/scheduler/reduction.cpp
Also, updated max_dtype_size_for_vectorization to include output TV as well.
> renaming arguments to avoid confusion

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- tests/cpp/test_indexing.cpp
This PR adds a `TensorIndexer` version of [ensureStaticIndexing](https://github.com/NVIDIA/Fuser/blob/6ff60e2a320733a2f49de57007d6bb45000107cd/csrc/index_compute.cpp#L1194).
> Unroll for-loops whose indices are used for indexing register tensors

- csrc/id_model/loop_promotion.cpp
- csrc/id_model/loop_promotion.h
- tests/cpp/test_id_model.cpp
This PR attempts to not promote a loop group when it only consists of broadcast IDs. For example, consider a fusion as shown below:
```
auto tv0 = makeContigConcreteTensor({-1, 1});
fusion.addInput(tv0);
auto tv1 = makeContigTensor(2);
fusion.addInput(tv1);
auto tv2 = set(tv0);
auto tv3 = add(tv2, tv1);
fusion.addOutput(tv3);
for (auto tv : fusion.allTvs()) {
tv->split(1, 1, false);
tv->reorder({{0, 1}, {1, 0}});
}
for (auto tv : fusion.allTvs()) {
tv->inlineAt(2);
}
```
```
Inputs:
T0_g_float[bS8{1}, iS0{i0}, bS9{1}]
T1_g_float[iS12{1}, iS2{i4}, iS13{i5}]
Outputs:
T3_g_float[iS14{1}, iS6{i0}, iS15{i5}] ca_pos( 2 ) produce_pos( 2 )
%kernel {
T2_l_float[bS10{1}, iS4{i0}, bS11{1}] ca_pos( 2 )
= Set( T0_g_float[bS8{1}, iS0{i0}, bS9{1}], cache_op=Streaming )
T3_g_float[iS14{1}, iS6{i0}, …
```
> Do not promote broadcast only groups

- csrc/device_lower/pass/magic_zero.cpp
- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- csrc/index_compute.h
- tests/cpp/test_gpu3.cpp
This PR just ports the magic zero WAR to `TensorIndexer`. We should revisit if magic zero is still meaningful, but for now, this is yet another PR to fill remaining missing pieces of `TensorIndexer`.
I also ended up changing some of the functions I just added in #4158. For example, `TensorIndexer::getUsedLoops`, which was added in #4158, is replaced with `getUsedForLoopsOf` since `getUsedLoops` does not guarantee a loop index is indeed used in the final index (e.g., when unswitched, loop indices are replaced with 0 or `N - 1`, where `N` is the extent of the iter domain).
NOTE: Magic zero has just been ignored in `TensorIndexer`. If it should not be used, please explicitly disable it, which is already done in [the matmul scheduler](https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/ma …
> Porting magic zero to TensorIndexer

- csrc/device_lower/pass/insert_syncs.cpp
- tests/cpp/test_matmul.cpp
I believe this check was to ensure that if a sync did exist in the scope, that it was last, but no RAW sync is inserted when `blockDim.y == 1`.
If there is no actual RAW sync, do we need the block sync to protect against WAR for wgmma async? If so then we could instead check for its existence in the scope and insert if needed.
Fixes #4138
> Insert block sync if it doesn't exist in WarAsyncWaitInserter

- tests/cpp/test_matmul.cpp
- tests/cpp/test_matmul_scheduler.cpp
- tests/cpp/test_mma.cpp
- tests/cpp/utils.h
- Renames:
- `matmulAtInput3DHopperSS` -> `matmulAtInput3DSS`
- `HopperMmaSSTestParams` -> `MmaSSTestParams`
- `class HopperSS : public HopperBase` -> `class SSTest : public Base`
- `testNameHopperSS` -> `testNameSS`
- `mmaHopperSSParamsGenerator` -> `mmaSSParamsGenerator`
- Add Blackwell macro lists to `tests/cpp/utils.h`
> Misc changes on matmul tests to make it Blackwell-friendly

- csrc/compute_at_map.cpp
- csrc/device_lower/lower2device.cpp
`ComputeAtMap` is considered almost deprecated but the gap with `IdModel` results in small but many changes in generated index exprs, mainly because some mappings are missed in `ComputeAtMap`, which then results in different index exprs. 
To make the transition from the legacy indexer smoother, this PR augments the exact and almost-exact disjoint sets of `ComputeAtMap` with the exact and almost-exact graphs of `IdModel`, respectively. This should make the code diff results cleaner when comparing the legacy and the new indexers.
> Expand ComputeAtMap exact and almost_exact disjointsets by IdModel

- csrc/id_model/id_model.cpp
- tests/cpp/test_circular_buffering.cpp
Loop indices for newly added stages were missing.
Also changed to use `TensorIndexer` with `CircularBufferTest`.
The code diff results show many changes. As far as I can see, none of them seems problematic as they are all one of:
- Bug in the legacy indexer (#4189)
- Different insertion of `nvfuser_zero`. I'm not sure why, but I don't think it's worthwhile investigating in the context of circular buffering.
- Different replacement of predicate indices for IDs that are exact mapped with vectorized IDs. The legacy indexer replaces it with `N - 1` for both the start and stop predicates, whereas the new indexer uses 0 for the start predicate. Both are valid.
> Fix TensorIndexer for circular buffering

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- csrc/index_compute.cpp
- tests/cpp/test_rng.cpp
There's a bug in `getLinearLogicalIndex`, which causes `RNGTest.ManualScheduleValidateWithCURand2` to fail.
Also added an option to use magic zero since that's the case with the legacy indexer.
All of the codegen diff results look benign.
> Fix the order of accumulating logical indices

- csrc/codegen.cpp
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/insert_syncs.cpp
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
- tests/cpp/test_circular_buffering.cpp
This PR modifies the `RAW` and `WAR` sync passes to insert `kir::BlockSync` nodes that track if it's inside a warp-specialized for-loop. 
- Add `optional_compute_or_load_sync` attribute to `kir::BlockSync` node.
- If the attribute is `std::nullopt`, then it is a regular block sync. If `true`, then it is inside a `ComputeWarp`. If `false`, then it is inside a `LoadWarp`.
- When creating the CUDA kernel, the correct number of threads is generated using `parallel_dimension_map`.
- Created `BarSyncWarpSpecializedPointwise` to test that the block syncs are added correctly to the `ComputeWarp`.
- I added support for block syncs in `LoadWarp`. However, since only TMA Loads are cloned to `LoadWarp`, I couldn't create a unit test.
```cuda
__global__ void cuda_kernel(args) {
// boilerplate
#pragma …
```
> Create block sync that runs inside of warp specialized IfThenElse

- setup.py
switched to `find_packages`, so we no longer need to package `.py` files in package_data.
> adding a missing directory in packaging

- csrc/driver_api.cpp
It's no longer needed after #4197
> Remove CUDADriverAPIDynamicLoader

- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- tests/cpp/test_matmul.cpp
This fixes an indexing error for MmaOp producer tensors. It seems the true root cause may be a lack of parallelization, but that doesn't seem to cause anything with the legacy indexer. This PR partly mimics what is done by the legacy indexer in the new indexer.
For example, in `MatmulTest.MatmulMatmulAmpere`, there is an MmaOp of:
```
T17_l_float[iS234{4}, iS236{2}, rS262{4}, rS288{2}, ithreadIdx.z280{2}, ithreadIdx.y282{2}, iS284{4}, iS286{4}, ithreadIdx.x429{32}, iMMA424{1}, iMMA423{2}, iMMA427{2}, rMMA432{2}, rMMA433{4}, rMMA431{2}] ca_pos( 2 ) produce_pos( 8 )
= mma(T3_l___half[iS238{4}, bS240{1}, iS264{4}, iS298{2}, iS300{2}, bS302{2}, iS304{4}, bS306{4}, bS307{8}, iS400{1}, iS395{8}, iS399{4}, iS398{2}, iS401{2}, iS397{2}] ca_pos( 7 ) produce_pos( 7 ),
T4_l___half[bS250{1}, …
```
> WAR for producer indexing of MmaOp

- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
This PR refactors the `domainReorderAsLogicalMap` to allow reuse of some code in upcoming changes to `propagateShardings` presegmentation pass (PR #3838).
> Refactor `domainReorderAsLogicalMap`

- csrc/device_lower/pass/allocation.cpp
- tests/cpp/test_matmul.cpp
- tests/cpp/utils.h
TensorIndexer generates incorrect indices for shared memory tensors that are used by TMA. In that case, the set allocation domain should be honored. 
Similarly, set allocation domains are used when consumed by MmaOp. This doesn't seem to be necessary for correctness, but it seems to make sense to do so.
> Use set allocation domains if used by TMA or MmaOp

- csrc/host_ir/lower.cpp
A recent PR https://github.com/NVIDIA/Fuser/pull/3913 fixed a bug in the comms/compute overlap algorithm, consisting of adding a stream synchronization when entering the host for-loop. Namely, currently, the host generated program reads
```
$ mpirun -x NVFUSER_DUMP=host_ir -np 2 python -m pytest tests/python/multidevice/test_overlap.py --only-mpi
```
```
%HostIrContainer { (T0_g___bfloat[iS0{8}, ideviceIdx.x1{2}, iS2{64}, iS3{1024}] (DeviceMesh{0 1}), T1_g___bfloat[iS4{1024}, iS5{1024}] (DeviceMesh{0 1}), T2_g___bfloat[iS6{1024}] (DeviceMesh{0 1})) -> (T3_g___bfloat[iStream7{8}, iS8{2}, iS9{64}, iS10{1024}, rS11{1024}] (DeviceMesh{0 1})) :
GetCurrentStream into Stream 0
T4_g___bfloat[iS12{8}, iS13{2}, iS14{64}, iS15{1024}] (DeviceMesh{0 1}) = ALLOCATE(buffer=T4_g___bfloat[iS12{8}, …
```
> [Overlap] Move initial stream sync into separate for loop

- tests/python/conftest.py
prints the parameters in the test properly, e.g., taking the example from https://github.com/NVIDIA/Fuser/pull/3928
> [s=1-backend_type=CommunicatorBackend.ucc]
instead of 
> [1-backend_type1]
> [Python test] add `conftest.py` to improve printing

- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/inline_ptx.cpp
Instead of explicitly initializing to zero, we use `mma(use-input-d=is_not_first_iteration)`
> Skip initialization for Hopper & Blackwell matmul

- CMakeLists.txt
- csrc/compute_at_map.cpp
- tests/cpp/test_compute_at_map.cpp
- tests/cpp/test_gpu3.cpp
Fixes #4238
This is to fix an error when a tensor has exprs that are outside of TensorDomain::allIDs().
> Do not map unregistered IDs

- csrc/python_frontend/python_bindings.cpp
- csrc/scheduler/ampere_multi_matmul.cpp
- csrc/scheduler/ampere_multi_matmul.h
- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_utils.cpp
- tests/cpp/test_matmul.cpp
This PR prepares hopper matmul scheduler to use 2d grid traversal pattern.
* Rename `grid_swizzle_factor` to `grid_traversal_factor` in matmul schedulers. 
* Changes `grid_swizzle_factor` from an `int` to `std::pair<int, int>`
* If `grid_traversal_factor.second == 1`, then`grid_traversal_factor.first` == `grid_swizzle_factor`.
* Rename `swizzleBlockTiles` function to `reorderBlockTileTraversal`.
> Prepare matmul schedulers for 2d grid traversal pattern

- csrc/ir/iostream.cpp
Currently, when we call `tv->printTransforms()`, we print root->logical then logical->loop expressions. In case the allocation domain is not on the path from logical to loop, those allocation expressions were not printed at all.
This PR uses `tv->domain()->allExprs()` instead to print all the ID expressions.
For an example, see this test:
```c++
TEST_F(AllocationDomainTest, PrintTransforms) {
auto fusion = std::make_unique<Fusion>();
FusionGuard fg(fusion.get());
// iS0{i0}
auto* root0 = IterDomainBuilder(
fusion->zeroVal(), IrBuilder::create<Val>(DataType::Index)).build();
// iS1{ceilDiv(i0, 5)}, iS2{5} = split(iS0)
IterDomain *logical0, *logical1;
std::tie(logical0, logical1) = IterDomain::split(
root0,
IrBuilder::create<Val>(5L, DataType::Index),
/*inner_split=*/true);
// …
```
> Print all ID expressions in tv->printTransforms

- csrc/codegen.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/dispatch.h
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
This PR adds support for `continue` in the generated CUDA kernels. 
**Why?** For persistent kernels, we need to efficiently skip OOB tiles to avoid unnecessary work. 
Required for: https://github.com/NVIDIA/Fuser/pull/4243
> Create kir::Continue for persistent grid short-circuit

- csrc/multidevice/c10d_mock.h
- csrc/multidevice/ipc_handle.cpp
- tests/cpp/test_multidevice_ipc.cpp
`#ifdef NVFUSER_DISTRIBUTED` tends to be contagious if not controlled, making code diverge.
> Remove several uses of NVFUSER_DISTRIBUTED

- csrc/scheduler/hopper_multi_matmul.cpp
- csrc/scheduler/hopper_multi_matmul.h
- csrc/scheduler/multi_matmul.cpp
- csrc/scheduler/multi_matmul.h
- tests/cpp/test_matmul.cpp
Introduces `cacheBefore` to match `cacheAfter` utility, which just propagates entries in `graph_` corresponding to new IDs in the cached tensors. Also avoids re-scheduling tensors if they are split-K sum tensors.
There is a current limitation for 32-bit outputs where we skip stmatrix but our current vectorized stores encounter 2-way bank conflicts. This is probably not that important to perf and can be fixed in scheduling of that store in another PR.
Fixes #4159
> Fix scheduling of split-K with smem_epilogue on Hopper

- tests/cpp/test_combined_inner_outer_reduction.cpp
This test may fail as the trick using a divisible batch size also depends on circular buffer stages.
Diable it and will re-enable after predicate is added.
> disable TmaWarpSpecializedTes, it needs predicate

- csrc/device_lower/pass/insert_syncs.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
For better pipelining of TMA store and `wgmma`, we should treat the `fence`, `commit`, and `wait` phases of `AsyncGroup` separately.
* Replace `getSyncExprs` with `getAsyncCommit` and `getAsyncWait`.
* Create `getAsyncFence` for `WgMmaFence` and `FenceAsyncProxy`.
* No change to the CUDA kernel in this PR.
```cuda
#pragma unroll
for(nvfuser_index_t i57 = 0; i57 < 16; ++i57) {
if ((b42 && (i43 < (-(16 * i57))))) {
stmatrix4((uint32_t)((toSmem(T8) + ((((nvfuser_index_t)threadIdx.y) * 32768) + (((i57 / 4) * 8192) + ((i12 * 128) + (((((((nvfuser_index_t)threadIdx.x) % 32) / 16) + ((i57 % 4) * 2)) ^ (i12 % 8)) * 16)))))), (*reinterpret_cast<Array<uint32_t, 4, 1>*>(&T7[(8 * i57)])));
}
}
block_sync::sync<false>(dim3(128, 2, 1));
#pragma unroll
for(nvfuser_index_t i58 = 0; i58 < 4; ++i58) { …
```
> Create separate AsyncGroup helpers for fence, commit, and wait operations

- csrc/fusion_segmenter.cpp
- tests/cpp/test_segmentation.cpp
Follow-up to #3776 
This PR removes duplicated cast exprs from `SegmentedGroup`. There's nothing wrong leaving them there as they won't be picked up anyway, but `stablyOrderedExprs()`, which is used when printing `SegmentedFusion`, complains.
Not sure why this could cause codegen diffs.
> Remove stale exprs

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/insert_reshardings.cpp
By default, `shardAllLike` propagates all DID parallel types. This allows us to control exactly which parallel types to propagate, essential for #3838.
> `shardAllLike` accepts a list of parallel types

- csrc/kernel_ir.cpp
- tests/cpp/test_tmem.cpp
> Use `tcgen05` as namespace for TMem ld/st

- tests/python/multidevice/conftest.py
- tests/python/multidevice/test_communication.py
- tests/python/multidevice/test_deepseek_v3.py
- tests/python/multidevice/test_dtensor.py
- tests/python/multidevice/test_matmul.py
- tests/python/multidevice/test_multidevice.py
- tests/python/multidevice/test_overlap.py
- tests/python/multidevice/test_transformer_engine.py
Move fixtures to conftest.py according to https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files
Make setup_default_process_group a common fixture
> Clean up multi-GPU python test fixtures

- csrc/dispatch.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_host_ir_integration.cpp
This PR adds the Deallocate HostIr, which erases an Allocation from the expression evaluator. It also modifies LaunchKernel to take in preallocated output arguments. Lastly, it adds a gtest which allocates and deallocates a buffer in a loop, then checks the memory used is 0 bytes.
> Deallocate HostIr Op and Test

- csrc/dispatch.h
- csrc/host_ir/executor.cpp
- csrc/host_ir/executor.h
- csrc/host_ir/host_ir.cpp
- csrc/host_ir/host_ir.h
- tests/cpp/test_host_ir_integration.cpp
Reverts NVIDIA/Fuser#4286 because of http://nv/eF0
> Revert "Deallocate HostIr Op and Test"

- benchmarks/python/core.py
- nvfuser/benchmark_utils.py
The motivation is to use them in Thunder.
> Extract benchmarking timers into a separate class

- .lintrunner.toml
This PR fixes the clang-tidy lintrunner. The `build_dir` argument needs to change from `./build` to `./python/build`.
> Change build directory for clang-tidy in lintrunner

- benchmarks/python/test_matmul.py
- csrc/scheduler/matmul_utils.cpp
#4242 turned on "grid traversal factor" which is a good thing. However, it exposed a bug in how we limit that factor to prevent overrun in case the swizzled axis has fewer tiles than the factor. This led to a regression from 58% to 35% geomean perf compared to eager on H200.
This PR swaps the axes used to compute the number of swizzled tiles and takes us from a geomean of 35% to 65% on `benchmarks/python/test_matmul.py` on H200.
> Switch axis we use to compute swizzled_tiles

- csrc/multidevice/ipc_handle.cpp
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_host_ir.cpp
A synchronization is needed at the `IpcHandleCache::exchangeHandles` to avoid the exporter exporting twice before the importer delete the key to the store.
Should fix a bug [observed in the CI](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/160018431).
cc [Team thread](https://teams.microsoft.com/l/message/19:e875a0fc9d0747b9bde9715c9b6093ae@thread.tacv2/1745028577674?tenantId=43083d15-7273-40c1-b7db-39efd9ccc17a&groupId=74537292-c203-4a6d-aea0-40c527b969f7&parentMessageId=1745028577674&teamName=csarofeen-staff-and-guests&channelName=nvFuser-MultiGPU&createdTime=1745028577674)
> [Cuda Ipc] Add barrier at the end of `IpcHandleCache::exchangeHandles`

- csrc/preseg_passes/propagate_shardings.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
Since we only propagate across each expression at a time, we can directly use `TransformReplay`. This will avoid building the `MaxLogicalDomainInfoSpanningTree` or using the Propagator object.
> Use TransformReplay directly instead of TransformPropagator

- csrc/codegen.cpp
- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
This PR renames `getRawLoad` to `getRawAsync` in `ParallelDimensionMap`. Recently, `CircularBufferLoopStage` changed `LoadWarp` to `AsyncWarp`. This function corresponds with `LoadWarp` and needs to be updated accordingly.
> Rename getRawLoad to getRawAsync

- csrc/driver_api.cpp
- csrc/driver_api.h
- tests/cpp/test_multidevice_ipc.cpp
> Replace cudaGetDriverEntryPoint with cudaGetDriverEntryPointByVersion

- csrc/kernel.cpp
- csrc/kernel.h
- csrc/runtime/compiled_kernel.cpp
It's subsumed by KernelSummary::dynamic_lmem_allocations.
> Remove KernelSummary::has_dynamic_local_memory_allocations

- examples/sinh_extension/README.md
- examples/sinh_extension/nvfuser_extension/__init__.py
- examples/sinh_extension/pyproject.toml
- examples/sinh_extension/setup.py
This PR updates the `sinh_extension` example to use `pyproject.toml`. It fixes the failing test `jit_examples_sinh_extension_20`, which fails because `python setup.py install` is depreciated with ToT of `setuptools`.
The new build command is `pip install --no-build-isolation .`
> Update sinh extension to use pyproject.toml

- csrc/predicate_compute.cpp
- tests/cpp/test_memory.cpp
This PR changes `createElectSyncPredicate` to skip adding ElectSync to `TMA Store` expressions.
* TMA Store is a warp-collective, so it is issued by a single warp. Using ElectSync to pick a single thread is unnecessary.
1. In the Unroll pass, all non-circular buffered Async operations are assigned the `ElectSync` Predicate with their **expression**. See https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/pass/unroll.cpp#L160-L171.
2. Any `ElectSync` Predicate with its **expression** is handled by [PredicateCompute::createSingleExpressionElectSync](https://github.com/NVIDIA/Fuser/blob/main/csrc/predicate_compute.cpp#L550-L552).
3. `createSingleExpressionElectSync` uses the predicate's expression to determine if it is TMA Store.
4. Then, `createElectSyncPredicate` will skip the …
> Skip ElectSync when creating predicate for TMA Store in PredicateCompute

- python/utils.py
This might just show my ignorance of CMake. Let me know if you have a better fix. 
When I run `python setup.py --build-with-asan` and then `python setup.py`, the second build still has asan enabled. 
The first build runs `cmake -DNVFUSER_BUILD_WITH_ASAN=ON`, which adds `NVFUSER_BUILD_WITH_ASAN:BOOL=ON` to CMakeLists.txt
The second build runs `cmake` without `-DNVFUSER_BUILD_WITH_ASAN` specified. `cmake` chooses to use the cached value and therefore doesn't change the existing `NVFUSER_BUILD_WITH_ASAN:BOOL=ON` in CMakeLists.txt to `OFF`. 
Let `setup.py` always specify `-DNVFUSER_BUILD_WITH_ASAN`.
> Always specify -DNVFUSER_BUILD_WITH_ASAN to cmake

- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.cpp
- csrc/scheduler/utils.h
- tests/cpp/test_multidevice_sharding.cpp
1. Fixes the bugs surfaced by PR #4306 due to missing shardings on fusion inputs. See code comment for detailed explanation
2. Makes `parallelize_inputs` in `parallelizeAllLike` specific to DID parallel types. This is really only needed for DID since BID/TID have no meaning for fusion inputs. This also allows me to only call `parallelizeAllLike` once, and hence, build the ComputeAt map only once. The alternative would be to call this twice to avoid parallelizing fusion inputs on BID/TID.
> Preserve DID loop split in transpose scheduler

- README.md
> Update readme release matrix to reflect torch 2.7 builds and releases

- csrc/scheduler/matmul_utils.cpp
This is a small update to our default Hopper matmul heuristic
I noticed a case where we had a 13x10 tile grid. We rightly chose row-major `cta_order` since 10 is smaller than 13 so it should be the fast dimension. However we then set `grid_traversal_factor` to 13. When we set the `grid_traversal_factor` equal to the size of the other dimension, the traversal order is no different than swapping to column major, which is no longer optimal. Instead, we should only consider swizzles that are smaller than the number of tiles in the slow dimension.
Using `benchmarks/python/test_matmul.py`:
Before: 61.8% of cublas
After: 67.4% of cublas
This is a 9% speedup.
> [Hopper matmul] Limit grid traversal factor to prevent suboptimal CTA order

- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
- tests/cpp/test_circular_buffering.cpp
This PR refactors `adjustMappingsForWarpSpecialization` for future multi-role specialization support.
* Change `get_threads_count_in_dim` lambda to `ParallelDimensionMap::getThreadCountInDim` private member function.
* Create `TEST_F(NVFuserTest, TmaRegisterSharingDynamicShapesExpectFail)` to test for assertion.
* Rename `TEST_P(TmaRegisterSharingTest, RegisterSharingCtaShapes)` to `TEST_P(TmaRegisterSharing, CtaShapeShmoo)`
* Change `TEST_P(TmaRegisterSharing, CtaShapeShmoo)` to have static thread dimensions.
> Refactor adjustMappingsForWarpSpecialization

- python/utils.py
This is a follow-up to https://github.com/NVIDIA/Fuser/pull/4319
Before this PR, we don't pass -D for default values. This confused me
several times, so I'm making this change to ensure consistent behavior
across clean and dirty builds. Refer to code comments for details.
> Pass -D even for default values

- tests/cpp/test_resize.cpp
Disabling ResizeTest.ReshapeAfterRef while working on a fix.
See #4376
> Temporarily disable ReshapeAfterRef due to validation failures

- csrc/multidevice/utils.cpp
- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_sharding.cpp
When propagating shardings to a tensorview, we skip device parallel types already present on that tensorview. We ignore reduction dimensions for this.
I discovered a bug in the backpropagation of shardings. Since I was passing an empty set as selected parallel types to `selectiveReorderDIDToFront`, no backpropagation was occuring (An earlier version of propagation used excluded parallel types instead of selected parallel types which led to this bug). This got masked in the `ShardingTest.ResidualAdd` since the allocation domain of tvs was not set and `getShardedLogicalAxis` uses that.
> Ignore device parallelization on reduction axis in sharding propagation.

- CMakeLists.txt
That file is the result of tests/cpp/rng_kernels.cu, which does not use anything from nvfuser so it does not need to be linked against nvfuser. Doing so causes a multiply defined symbol, leading to this type of asan error:
https://github.com/google/sanitizers/wiki/AddressSanitizerOneDefinitionRuleViolation.
NOTE: It seems `$NVFUSER_TESTS` is never set in CMakeLists.txt. I am unsure what the original intended name was for this file but I think we should just hardcode that name instead of the current version which leads to `lib_kernels.so` being generated..
Fixes #4369.
> Don't link lib_kernels.so against codegen_internal

- CMakeLists.txt
A follow-up to https://github.com/NVIDIA/Fuser/pull/4378
> Stop using NVFUSER_TESTS, which isn't defined anywhere

- csrc/scheduler/resize.cpp
- csrc/scheduler/utils.cpp
- tests/cpp/test_resize.cpp
In the resize scheduler, there's an assumption that, when reordering the reference tensor using an input tensor, the innermost ID of the reference is reachable from the IDs of the input tensor. That's actually not the case when the innermost ID is repeated, which hits [this assertion](https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/resize.cpp#L509).
This PR ensures the innermost reference ID always stays at the innermost position by excluding it from reordering.
> Fix reference reordering in resize scheduler

- python/nvfuser/testing/utils.py
- tests/cpp/utils.cpp
- tests/python/multidevice/conftest.py
Our unit tests heavily depend on this flag and our CI already sets this when running any tests. I think it's better to set this in test fixtures instead so we don't have to remember to do so when running tests locally.
> NVIDIA_TF32_OVERRIDE=0 in test fixtures

- CMakeLists.txt
- python/python_next/bindings.cpp
- python/python_next/bindings.h
- python/python_next/ir.cpp
This PR creates the bindings for Statement, Expr, and Val bindings. It corresponds with [Step 1: Create python bindings for basic Fusion IR](https://docs.google.com/document/d/1ftdNKu952EFmLANa36g0IrVaqAJ0eLKzgJESkQFnuVI/edit?tab=t.0#heading=h.e2plo2gt0gnb).
Details:
* All nodes inherit `std::unique_ptr<[Node Name], py::nodelete>` to disable destructor. Disable memory management because it is handled automatically by `IrContainer`. A segmentation fault will occur when destroying a node twice.
* `bindBaseNodes` contains the ir nodes found in `ir/base_nodes.h`
Pythonic Changes:
* Mapped `toString` to `__str__` dunder method
* Mapped `sameAs` to `__eq__` dunder method
* Changed from CamelCase to snake_case.
* Added numpy-style docstrings
All `Statement` nodes are held by the `Fusion`, so we …
> Create Statement, Expr, and Val bindings

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
- csrc/preseg_passes/mark_aliases_prepare.cpp
- csrc/scheduler/expr_eval_sched.cpp
- csrc/scheduler/mark_aliases.cpp
- tests/cpp/test_alias.cpp
The previous version checks allocation of intermediate tensors in finalization stage and doesn't try to propagate it in dispatching stage. 
The most immediate use case is to be able to run mark-aliases-prepare after reorder-sharded-axis. Reorder-sharded-axis sets allocation so scattered/gathered dimensions are allocated outermost for NCCL and UCC. It's beneficial for mark-aliases-prepare to respect these allocations even though they are on intermediate tensors. 
There may be other benefits, e.g., making fd.ops.stride_order(sdpa_out) more effective as a performance hint.
> Alias analysis propagates allocation of intermediate tensors.

- csrc/multidevice/utils.cpp
Follow-up: This is used in reduction scheduler which only checks for the position of DIDx. We should generalize it.
> Fix `getShardedLoopAxis` to check parallel type

- python/python_next/bindings.cpp
- python/python_next/bindings.h
- python/python_next/extension.cpp
- python/python_next/ir.cpp
This PR creates the bindings for `IterDomain`, `TensorDomain`, and `TensorView` bindings.
It corresponds with [Step 1: Create python bindings for basic Fusion IR](https://docs.google.com/document/d/1ftdNKu952EFmLANa36g0IrVaqAJ0eLKzgJESkQFnuVI/edit?tab=t.0#heading=h.e2plo2gt0gnb).
PR Stack:
#4403 Create IterDomain, TensorDomain, and TensorView bindings **<<< This PR.**
#4406 Add support for defineTensor
#4407 Add binding for Fusion IrContainer 
#4408 Create bindings for FusionDefinition and Add Binary op
#4409 Create python FusionDefinition for nvfuser_next
> Create IterDomain, TensorDomain, and TensorView bindings

- python/python_frontend/python_bindings.cpp
It should match the beginEvent in _setup_definition.
> Fix a bug in tracing

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
It currently NVF_ERRORs TensorView* anyhow. This PR simply promotes that runtime check to a compile-time check, which is a strict improvement.
> preferredLayout takes TensorView* instead of Val*.

- csrc/device_lower/lower2device.cpp
- csrc/runtime/compiled_kernel.cpp
I'm changing the dump timing of `fusion_ir` and `fusion_ir_math` to the beginning of lowering rather than the nvrtc compilation time. The debug dump does not help when GpuLower crashes.
> Move Fusion::printMath and Fusion::print to the lowering time

- csrc/host_ir/pass/stream_parallel_type.cpp
- tests/cpp/test_host_ir_stream_lowering.cpp
port https://github.com/NVIDIA/Fuser/pull/4217 to stream lowering
> [Stream Lowering] Move initial stream sync to separate for-loop

- csrc/parallel_dimension_map.cpp
- csrc/parallel_dimension_map.h
- tests/cpp/test_circular_buffering.cpp
- tests/cpp/test_combined_inner_outer_reduction.cpp
This PR enforces same padding rules for non-register sharing warp specialization.
* Replaced `std::unordered_set<ParallelType> warp_specialized_types_` with `std::optional<ParallelType> warp_specialized_parallel_type_` because we only support a single ParallelType.
> Enable same padding for non-register sharing warp specialization

- csrc/driver_api.cpp
For https://github.com/NVIDIA/Fuser/pull/4349#issuecomment-2877822093
> Add CUDA_VERSION check for cudaGetDriverEntryPointByVersion

- csrc/id_model/to_string.h
- csrc/val_graph.h
~Don't know why but these change seem to eliminate link errors with sinh_libtorch~.
It's probably due to these two lines:
https://github.com/NVIDIA/Fuser/pull/4390/files#diff-3b542a1c1dfdbad787cd9dcda9961a37a9c2e0e5a3e4b19cebb46600ef2c4f7cR13-R14
```
#include <val_graph.h>
#include <val_graph_visitor.h>
```
> Fix sinh_libtorch build error

- tests/cpp/test_combined_inner_outer_reduction.cpp
New restriction on warp specialization was added in https://github.com/NVIDIA/Fuser/pull/4395
Needs to temporarily skip `ThunderRMSNormBwd`
> skip ThunderRMSNormBwd

- CMakeLists.txt
- csrc/scheduler/multi_matmul.cpp
- csrc/scheduler/multi_matmul.h
- csrc/scheduler/multi_matmul_ampere-.cpp
- csrc/scheduler/multi_matmul_ampere-.h
- csrc/scheduler/multi_matmul_hopper+.cpp
- csrc/scheduler/multi_matmul_hopper+.h
- tests/cpp/test_matmul_scheduler.cpp
Renames:
- Ampere -> Ampere- (Turing & Ampere)
- Hopper -> Hopper+ (Hopper & Blackwell)
I am planning to use the same class for Hopper and Blackwell, because I expect the scheduling to be mostly the same.
> Renames on matmul schedulers to prepare for Blackwell

- csrc/device_lower/analysis/bank_conflict.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/evaluator_common.h
- csrc/fusion_segmenter.cpp
- csrc/id_model/to_string.h
- csrc/ir/builder.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/runtime/compiled_kernel.cpp
- csrc/runtime/compiled_kernel.h
- csrc/runtime/executor.cpp
- csrc/runtime/executor.h
- csrc/runtime/executor_utils.cpp
- csrc/runtime/executor_utils.h
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_inner_outer_multi_wave.cpp
- csrc/scheduler/normalization_inner_outer_tma_ws.cpp
- csrc/scheduler/normalization_inner_outer_utils.cpp
- csrc/scheduler/vectorize_helper.cpp
- csrc/utils.h
- csrc/val_graph.h
- csrc/val_graph_nodes.h
Follow-up to #4452 
lower2device.h includes a lot of other mostly internal headers, so I think we should avoid including it from the runtime files.
> Header inclusion cleanup

- csrc/expr_evaluator.cpp
With this, I'm able to capture more ExpressionEvaluator::evaluate calls for #4431 
Host latency changes are neutral. 
Before: 
```
-------------------------------------------------------------------------------------------------------------------------- benchmark: 18 tests --------------------------------------------------------------------------------------------------------------------------
Name (time in us)                                                                 Min                     Max                    Mean                 StdDev                  Median                   IQR            Outliers          OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------- …
```
> Trace all ExprssionEvaluator::evaluate

- tests/cpp/test_multidevice_pipeline.cpp
Prep PR for Issue #3900.
I am modifying the `reorderShardedAxisPass` to set allocation domain consistent with the memory layout requirements of ProcessGroup NCCL and UCC, without changing the logical shape (see PR #4170 for example).
MultiDeviceExecutor does not respect allocation domain, hence, removing these tests. Issue #4453.
> Remove tests with inner sharded dimensions when using MultiDeviceExecutor

- CMakeLists.txt
- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/ir/interface_nodes.h
- csrc/parallel_dimension_map.cpp
- tests/cpp/test_circular_buffering_ping_pong.cpp
This PR adds `stage_slice_position` to `struct WarpSpecialized` to control the shape of circular buffer stage. It detects the ping-pong circular buffer pattern and changes the CUDA kernel so all the compute warp groups to work independently.
Derived from #4396.
Multiple TMA Loads can be launched for a single `mbarrier::arriveExpectTx`. Currently, we always insert the `mbarrier::arriveExpectTx` at the first serial IterDomain left of the ComputeAt position.
For ping-pong kernels, the circular buffer pipeline is parallelized by the compute warp groups. Using the computeAt position to select the `mbarrier::arriveExpectTx` position is restrictive.
Furthermore, persistent normalization and matmul kernels have different patterns, so more flexibility in defining the circular buffer stage state is …
> Support Independent Compute Warp Groups

- benchmarks/python/benchmark_overlap.py
Add a benchmark unit test for AG+Matmul with/without overlap. The test uses pytest framework and defines a custom Timer based on Cuda Events.
Results obtained show significant performance benefits of pipelining with ucc for large matrices. Results obtained for DGX 8* H100 GPU:
```
--------------------------------------------------------------------------------------------------------------------------------------------- benchmark: 16 tests ---------------------------------------------------------------------------------------------------------------------------------------------
Name (time in ms)                                                                                                                                 Min                Max               Mean             StdDev …
```
> Benchmark for distributed matmul with overlap

- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_hopper+.cpp
- csrc/scheduler/matmul_hopper+.h
- Create `isCooperative` and `isPingPong` checks in `HopperPlus`.
- Guard all existing `ParallelType::TIDy` with `isCooperative`
- Create `findFirstRole` helper function to find the first `MatmulDimRole` from left to right in a vector of roles. It is used in `reorderBlockTileTraversal` and will be used in `schedulePingPong`.
> Minor refactor to HopperPlus in preparation for ping-pong matmul

- csrc/alias_analysis.cpp
- csrc/alias_analysis.h
> isCompliantWith doesn't need to be exposed.

- CMakeLists.txt
- python/python_direct/bindings.cpp
- python/python_direct/bindings.h
- python/python_direct/runtime.cpp
This PR creates the bindings for `Fusion` and `FusionGuard`.
It corresponds with [Step 1: Create python bindings for basic Fusion IR](https://docs.google.com/document/d/1ftdNKu952EFmLANa36g0IrVaqAJ0eLKzgJESkQFnuVI/edit?tab=t.0#heading=h.e2plo2gt0gnb).
PR Stack:
#4403 Create IterDomain, TensorDomain, and TensorView bindings
#4406 Add support for define_tensor
#4407 Add binding for Fusion IrContainer **<<< This PR.**
#4408 Create bindings for FusionDefinition and Add Binary op
#4409 Create python FusionDefinition for nvfuser_next
> Add binding for Fusion IrContainer

- csrc/scheduler/normalization_inner_outer_tma_ws.cpp
- csrc/scheduler/utils.h
Add register sharing to warp specialized normalization kernel when there are more than 256 threads in each CTA.
If threads per CTA <= 256, each thread can use 256 registers, no need to enable register sharing.
The `tma_branch_registers` is set to `32`, which is a tunable heuristic parameter.
> add register sharing to warp specialized normalization kernel

- tests/python/multidevice/test_dtensor.py
I removed biases because they are not used in DS. See https://huggingface.co/deepseek-ai/DeepSeek-V3/blob/main/configuration_deepseek.py#L150, https://huggingface.co/deepseek-ai/DeepSeek-V3/blob/main/modeling_deepseek.py#L383-L385 and other occurrences of `bias=False` in the same file.
> Test row parallel linear layers.

- csrc/ir/nodes.cpp
- csrc/scheduler/matmul_hopper+.cpp
- csrc/scheduler/matmul_hopper+.h
- tests/cpp/test_matmul_scheduler.cpp
Example kernel:
<details>
<summary>General/HopperPlusMatmulSchedulerTest.FusedMultiplySum/MN_512_256_128_MmaMacro_m128_n128_k16</summary>
```CUDA
// Codegen generated code
namespace tcgen05 {
__device__ __inline__ void alloc(uint32_t in0, uint32_t in1) {
asm volatile("tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;\n"::"r"(in0), "r"(in1));
}
__device__ __inline__ void relinquishAllocPermit() {
asm volatile("tcgen05.relinquish_alloc_permit.cta_group::1.sync.aligned;\n");
}
__device__ __inline__ void mma_f16(uint32_t in0, uint64_t in1, uint64_t in2, uint32_t in3, bool in4) {
asm volatile(
"{\n"
"  .reg .pred p0; \n"
"  setp.ne.b32 p0, %4, 0;\n"
"  tcgen05.mma.cta_group::1.kind::f16 [%0], %1, %2, %3, p0;\n"
"}\n"
:
:"r"(in0),
"l"(in1),
"l"(in2),
"r"(in3), …
```
> Support Blackwell in HopperPlus matmul scheduler: step 1 - no splitk, no smem epilogue

- tests/python/multidevice/test_dtensor.py
bfloat16 is more commonly used for Transformers than float32. 
I had to reduce tensor sizes and use randint to reduce rounding errors between CPU and GPU.
> Change linear tests to use bfloat16

- tests/python/multidevice/conftest.py
- tests/python/multidevice/test_deepseek_v3.py
- tests/python/multidevice/test_dtensor.py
- tests/python/multidevice/test_transformer_engine.py
as recommended by https://docs.pytorch.org/tutorials/beginner/ddp_series_multigpu.html#constructing-the-process-group
This PR also avoids some warnings during init_process_group:
```
tests/python/multidevice/test_deepseek_v3.py [rank0]:[W522 22:27:03.825695149 ProcessGroupNCCL.cpp:4789] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can specify device_id in init_process_group() to force use of a particular device.
```
> set_device before init_process_group

- python/nvfuser_direct/__init__.py
- tests/python_direct/test_import.py
- tests/python_direct/test_python_direct.py
This PR creates the python class `FusionDefinition` and adds `test_fusion_definition` to exercise the support Fusion Ir bindings.
PR Stack:
#4403 Create IterDomain, TensorDomain, and TensorView bindings
#4406 Add support for define_tensor
#4407 Add binding for Fusion IrContainer 
#4408 Create bindings for FusionDefinition and Add Binary op
#4409 Create python FusionDefinition for nvfuser_next **<<< This PR.**
#4513 Add bindings for FusionExecutorCache
> Create python FusionDefinition for nvfuser_next

- CMakeLists.txt
- csrc/host_ir/lower.cpp
- csrc/preseg_passes/finalize_multidevice_domains.cpp
- csrc/preseg_passes/finalize_multidevice_domains.h
- csrc/preseg_passes/pre_segmenter.cpp
- tests/cpp/test_sharding.cpp
Rename to better reflect the current aim of the presegmentation pass.
> `MakeReshardingContiguousPass` -> `FinalizeMultideviceDomainsPass`

- csrc/scheduler/matmul_utils.cpp
This reverts commit 6b5de266ab25fbb61930f1fc935a04764ce19aa9 (PR #4458)
That change increased perf on a small private problem set, but it drastically reduced perf on `benchmarks/python/test_matmul.py` from 60% to 40% compared to eager. Until this is better understood, I'd like to revert the change and follow it up with an improved PR.
> Revert "Limit CTA tile K dimension to problem K + 15 (#4458)"

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/utils.cpp
- tests/cpp/test_circular_buffering_ping_pong.cpp
**Issue:**
The current main branch allocates memory based on `tv->getComputeAtPosition();`, which is equivalent to `size_per_stage × stages × number_of_computation_warp_groups` for cases with multiple computation warp groups. However, this should be revised to `size_per_stage × stages`, since different warp groups operate on different circular buffer stages.
For example, for `T1_s_float[iblockIdx.x11{132}, iS12{12}, iS13{2}, | stage_slice_position |, iUR9{4}, iB3{128}] ca_pos( 2 )`, the current allocation is `iB3{128} × iUR9{4} × iS13{2} × circular_stages`. This should be corrected to `iB3{128} × iUR9{4}  × circular_stages`.
More generally, the allocated size should depends on `stage_slice_position` not `ca_pos`
**Fix:**
Update `getAllocPosInfo()` and …
> fix smem buffer size and indexing for pingpong

- csrc/alias_analysis.cpp
- csrc/ir/allocation_utils.cpp
- csrc/ir/allocation_utils.h
> Move some helpers from alias_analysis to allocation_utils

- csrc/multidevice/utils.cpp
1. Includes device and stream parallel types.
2. Ignores DID parallel types on reduction dimensions. In this case, the DID dimension can be present on another iterdomain. For eg, in reduce scatter.
I attempted to include all but Serial parallel type initially. However, the MMA parallel type can also be present on multiple iterdomains. So I am limiting this to device and stream parallel types.
> Extend `mapDeviceParalleTypeToId` to include Stream

- csrc/ir/nodes.cpp
Nightly pytorch no longer supports broadcast on index tensor.
Our IndexPutAccumulateOp has
```
self [ vocab, hidden ]
index [ seq, broadcast ]
value [ seq, hidden ]
```
This won't work with `at::index_put`, we need to change index to `index [ seq ]`
> fix fallback at::index_put API on nightly

- csrc/device_lower/analysis/circular_buffer.cpp
- csrc/device_lower/analysis/circular_buffer.h
- csrc/device_lower/pass/circular_buffer.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/id_model/id_model.cpp
- tests/cpp/test_circular_buffering_ping_pong.cpp
For ping-pong warp specialized kernels, the `compute_at_position` must be to the left of the warp-specialized thread axis because of parallel type propagation rules. If not, the warp-specialized thread axis will incorrectly appear in the `AsyncWarp`. For example, see `TEST_F(PingPongCircularBuffering, ProducerWarpSpecializedError)`.
The `compute_at_position` is defined from producer to consumer. Thus, sibling TMA load operations cannot be inlined unless they are inlined with their consumer.
This PR uses the `stage_slice_position` to inline AsyncWarp operations together. #4460 added the concept of `stage_slice_position`, which defines the shape of circular buffer stage and how the `mbarrier` synchronization is inserted in `AsyncWarp` and `ComputeWarp`.
* In the circular-buffer analysis …
> Modify IdModel Loop map to be aware of `stage_slice_position`

- python/python_direct/ops.cpp
This PR add the `max`, `min`, `prod`, and `sum` reduction operations in preparation for creating python reproducers from Fusion IR.
PR Stack:
#4513 Add bindings for FusionExecutorCache
#4516 Add the remaining binary operations
#4517 Add the bindings for unary operations
#4518 Add the bindings for reduction operations   **<<< This PR.**
#4519 Move helper functions from python_frontend to python_common
#4520 Create python reproducer from Fusion IR for nvfuser_direct
#4521 Recreate python_frontend test_basic for nvfuser_direct
> Add the bindings for reduction operations

- python/nvfuser/testing/benchmark_utils.py
- tests/python/multidevice/test_deepseek_v3.py
- tests/python/multidevice/test_transformer.py
```
me @ viking-prod-232 : dev | /opt/pytorch/nvfuser (wjy/benchmark)
$ mpirun -np 8 -output-filename /tmp/test_deepseek_v3 pytest tests/python/multidevice/test_deepseek_v3.py --only-mpi
$ cat /tmp/test_deepseek_v3/1/rank.0/stdout
----------------------------------------------------------------------------------------- benchmark: 2 tests -----------------------------------------------------------------------------------------
Name (time in ms)                        Min                Max               Mean             StdDev             Median                IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Make test_deepseek_v3.py a benchmark as well as a test

- tests/cpp/test_multidevice_lower_communication.cpp
I thought this would trigger https://github.com/NVIDIA/Fuser/issues/4230?
> Enable host IR tests in test_multidevice_lower_communication

- csrc/host_ir/executor.cpp
- csrc/runtime/executor_dispatch.cpp
- csrc/runtime/executor_dispatch.h
- csrc/runtime/fusion_kernel_runtime.cpp
- tests/python/test_pointwise.py
to avoid unnecessary ::supported calls. HostIrExecutor::supported is expensive in particular, because it calls isResharding.
```
$ NVFUSER_TRACE=/dev/stdout pytest benchmarks/python/host/test_many_pointwise_ops_host.py -s | grep 'HostIrExecutor::supported' | wc -l               
```
Before this PR: 144
After this PR: 0
> Pass SchedulerType to makeExecutor

- csrc/scheduler/normalization_inner_outer_tma_ws.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/reduction_heuristic.h
- `is_circular_buffer_regs_cached` - Controls whether TMA loaded buffers are cached to registers for faster access
- `is_non_circular_buffer_gmem_to_regs` - Enables direct loading of non-circular buffered tensors from global memory to registers, bypassing shared memory
- Added parameter definitions to `ReductionParams` class
- Updated `sameAs()` and `hash()` functions for proper parameter comparison
- Enhanced `movePersistentBufferToSmem()` to optimize outer broadcast tensor handling  
- Added conditional register caching logic in TMA warp specialized scheduler
- Set appropriate default values in heuristics
- Enables ping-pong computation optimization for independent warp groups
- Reduces memory traffic by optimizing register vs shared memory usage
- Improves performance for TMA-based …
> Add `is_circular_buffer_regs_cached` and `is_non_circular_buffer_gmem_to_regs` to heuristics parameters

- csrc/utils.h
Because
```
root@9f70c885dbce:/opt/pytorch/nvfuser# g++-13 -std=c++2b -Wall -o test m.cc
root@9f70c885dbce:/opt/pytorch/nvfuser# ./test
1
root@9f70c885dbce:/opt/pytorch/nvfuser# cat m.cc 
#include<ranges>
#include<vector>
#include<type_traits>
#include<iostream>
int main(int argc, char* argv[]) {
std::vector<int> vec = {0};
for (const auto& [i, v] : std::ranges::enumerate_view(vec)) {
std::cout << std::is_signed_v<decltype(i)> << std::endl;
}
}
```
On a separate note I have to explicitly cast the index into `int64_t` in order to avoid signed vs unsigned comparison.
> Minor change on enumerate to iterate on signed index

- doc/dev/python_scheduling/profile_matmul.py
- python/python_frontend/python_bindings.cpp
At some point `doc/dev/python_scheduling/profile_matmul.py` seems to have stopped actually applying the custom schedule. This PR switches to subclassing `FusionDefinition` and implementing the `schedule` and `definition` methods there instead, which seems to work.
> Use subclass method for scheduling in `profile_matmul.py`

- tests/cpp/test_multidevice_lower_communication.cpp
Errors were seen on nightly CI using 6 GPUs.
With the update, test passes with 8 devices on viking node.
> Use `randint` to avoid accumulation errors in nightly CI

- CMakeLists.txt
- python/python_direct/bindings.cpp
- python/python_direct/bindings.h
- python/python_direct/python_translate.cpp
This PR adds support for creating a succinct python reproducer from the CPP Fusion IR.
* `PythonTranslator` is based on  `python_frontend::FusionTranslator` class in https://github.com/NVIDIA/Fuser/blob/main/python/python_frontend/translation.cpp#L53.
* It traverse the Fusion container and converts IR nodes to python strings.
* It uses the same DAG traversal function from `python_frontend::FusionTranslator`, but I stripped out some functionality for this initial PR.
* `PythonPrinter` class handles pretty printing of Fusion IR.
* Bound `translate_fusion` to `nvfuser_direct`, which corresponds with `translateFusion` defined in `python/python_direct/python_translate.cpp`
PR Stack:
#4513 Add bindings for FusionExecutorCache
#4516 Add the remaining binary operations
#4517 Add the bindings for …
> Create python reproducer from Fusion IR for nvfuser_direct

- csrc/device_lower/pass/index.cpp
- csrc/id_model/id_model.cpp
- csrc/id_model/indexing.cpp
- csrc/id_model/indexing.h
- csrc/id_model/utils.h
- doc/dev/ldmatrix_stmatrix.md
This is the second out of three PRs which modifies IdModel indexing to use `alternate_loop_domain` to generate shared memory index for `ldmatrix` or `stmatrix`.
PR Stack:
1. #4578
2. #4579 **<<< This PR**
3. #4551
* Modified `TensorIndexer::buildLoopIndexMap` to use the same index variable for `alternate_loop_domain` and `loop_domain`
* `TensorIndexer` automatically uses `alternate_loop_domain` when it detects the shared memory TensorView for `ldmatrix` or `stmatrix`.
* Revised LdStMatrixSet tutorial to schedule `alternate_loop_domain`
* Created a shmoo test to exercise swizzle modes with different tile sizes.
<details>
<summary> HopperLdStMatrixTutorial.SetShmoo/swizzle_128B_cta_m_128_cta_n_256 </summary>
```cuda
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<__bfloat, 2, 2> T0, const …
```
> Generate ldstmatrix shared memory address using IdModel

- csrc/device_lower/validation.cpp
- tests/cpp/test_tmem.cpp
`dataTypeSizeByte(fp4)` always fail. But we do want to support fp4 as long as we are vectorizing it to at least 1 byte.
> Validate vectorization using bit instead of byte

- csrc/host_ir/executor.cpp
- tests/cpp/test_host_ir_integration.cpp
This is for @naoyam to understand #4230. 
```
[ RUN      ] HostIrIntegrationTest.ExprEvalAndKernel
%HostIrContainer { (T0_g_float[iS0{i0}, iS1{i2}]) -> (T3_g_float[rS6{i2}, iS7{i0}]) :
T1_l_float[iS3{i2}, iS2{i0}]
= Set.Permute( T0_g_float[iS0{i0}, iS1{i2}], cache_op=Streaming )
Deallocate {
T0_g_float[iS0{i0}, iS1{i2}]
}
T2_g_float[iS4{i2}, iS5{i0}]
= SegmenterSet( T1_l_float[iS3{i2}, iS2{i0}] )
Deallocate {
T1_l_float[iS3{i2}, iS2{i0}]
}
T3_g_float[rS6{i2}, iS7{i0}] = ALLOCATE(buffer=T3_g_float[rS6{i2}, iS7{i0}], mem_type=global, size=i0, zero_init=false, resets_to_zero=false)
LaunchKernel(
Group ID: 0,
Inputs: {T2_g_float[iS4{i2}, iS5{i0}]},
Outputs: {T3_g_float[rS6{i2}, iS7{i0}]},
)
Deallocate {
T2_g_float[iS4{i2}, iS5{i0}]
}
} // %HostIrContainer
[       OK ] …
```
> Add a test to exercise a mix of meta Exprs and kernels.

- csrc/device_lower/utils.cpp
- csrc/dispatch.h
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/arith.cpp
- csrc/ops/arith.h
- csrc/scheduler/expr_eval_sched.cpp
- csrc/scheduler/registry.cpp
- csrc/serde/fusion_cache.fbs
- csrc/serde/fusion_record.cpp
- python/nvfuser/testing/utils.py
- python/python_frontend/fusion_record.h
- python/python_frontend/python_bindings.cpp
- python/python_frontend/translation.cpp
- tests/python/opinfo_input_generators.py
- tests/python/opinfos.py
Adding grouped matmul in nvfuser:
1. Adding fusion node added `GroupedMMOp`;
output = GroupedMMOp (matrix1, matrix2, offsets, scale1 [optional], scale2 [optional], output_dtype);
2. Plumbed through python, c++ api -> `fd.ops.grouped_mm` / `grouped_mm`;
3. Current fallback execution goes through `torch._grouped_mm` and `torch._scaled_grouped_mm` accordingly;
A couple note:
1. Semantics about `scaled_grouped_mm` is tricky. I have a note as code comment.
```
NOTE -- [ Grouped Matrix Multiplication semantics ]
This operation performs a grouped matrix multiplication.
Parameters:
- out: output tensor
- matrix1: first input tensor matrix
- matrix2: second input tensor matrix
- offsets: 1D offsets tensor, specifying the ending index of each group
- scale1: scale tensor for matrix1 (optional)
- …
```
> adding fallback for grouped_mm

- csrc/evaluator_common.cpp
- csrc/expr_evaluator.cpp
- csrc/runtime/allocations.cpp
- csrc/runtime/executor.cpp
- csrc/runtime/executor_kernel_arg.cpp
- csrc/runtime/executor_kernel_arg.h
- csrc/type.cpp
- csrc/type.h
- tests/cpp/test_gpu1.cpp
See code comment:
```C++
// NVFuser's DataType is much wider than PyTorch's ScalarType, and we do support
// input/output TensorViews with these data types not supported by PyTorch.
// For these cases, we use a PyTorch ScalarType as a proxy. If there exists
// a scalar type with the same size, we use that. Otherwise, we use Byte and
// and adjust the size of the last dimension. For example, if we have a
// TensorView with shape [10, 4], and dtype is 3 bytes, then the corresponding
// ScalarType is Byte, and the shape of the corresponding at::Tensor is [10, 12].
```
> Support non-aten `DataType`s as input/ouput `TensorView`

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ops/indexing.cpp
- tests/cpp/test_index_put.cpp
Need `indexPutAccumulate` for 1D tensors for MOE index shuffling. #4660 extends the op by removing the rank assumption. This PR first removes the automatic broadcasting.
> Remove broadcast from index put accumulate

- CMakeLists.txt
- csrc/scheduler/matmul_ampere-.cpp
- SASS tests are skipped in whole. The disassembled cubin string format has no compatibility guarantee, so these tests might fail.
- Allow running ampere matmuls on all devices: Ampere's `mma` instruction is available on all devices, not just Ampere. `mma` on Hopper/Blackwell is not as fast as `wgmma` or `tcgen05.mma`, but is functionally available and can deliver Ampere-level performance. Ampere tests are still skipped on Hooper & Blackwell, to save CI time.
> Some adjustments on Ampere matmul

- python/python_common/python_utils.cpp
Previously we hit a segfault in `getExpanded` when using `define_tensor` and providing a `contiguity` vector that does not match the length of `shape`. This provides an error message instead.
Fixes #4661
> Check dimensions match in getExpanded python utility

- csrc/codegen.cpp
- csrc/device_lower/analysis/device_version.cpp
- csrc/device_lower/utils.cpp
- csrc/device_lower/utils.h
- csrc/ir/base_nodes.h
- csrc/ops/utils.cpp
- csrc/runtime/allocations.cpp
- csrc/type.cpp
- csrc/type.h
- csrc/type_promotion.cpp
- csrc/validator_utils.cpp
- python/nvfuser/pytorch_utils.py
- python/nvfuser/testing/utils.py
- python/python_common/python_utils.cpp
- python/python_direct/enum.cpp
- python/python_frontend/python_bindings.cpp
- runtime/array.cu
- runtime/fp4_support.cu
- runtime/tensor.cu
- tests/cpp/test_gpu1.cpp
- Renamed `DataType::Float4_e2m1` as `DataType::Float4_e2m1fn` to be more consistent with PyTorch
- Added `DataType::Float4_e2m1fn_x2`, which in theory should be the data type to represent fp4 tensors. This new data type in theory should correspond to `at::ScalarType::Float4_e2m1fn_x2`. Unfortunately, because `at::ScalarType::Float4_e2m1fn_x2` is only added recently and not available in the latest stable release of PyTorch (2.7.1), I have to comment out some code, so effectively we are still using `at::ScalarType::Byte` to represent fp4 tensor. Per our internal discussion, we are only interested in supporting nightly release, so I will uncomment these code in my next PR. I want to split the "add feature" and "break stable" as two PRs, so that in the future we can easily revert just in …
> Misc updates on fp4

- tests/cpp/test_matmul.cpp
This fixes failures introduced by CUDA 13's NVRTC caching.
> Disable NVRTC caching when observing ptxas output in matmul tests

- csrc/runtime/executor.cpp
- csrc/runtime/executor.h
- tests/cpp/test_gpu3.cpp
Previously we checked that the required static+dynamic smem of our kernels are < the device limit. This causes problems on some unlucky matmul problem sizes were we'd like to use the entire range of shared memory. This PR changes that condition to <=.
I also added a test that tries to exercise this and noticed that the kernel required 16 bytes of static smem surprisingly.
> Fix condition for smem limit in kernel executor

- csrc/runtime/compiled_kernel.cpp
Disable nvrtc caching when ptxas_verbose is needed, otherwise, no PTX information will be printed.
> disable nvrtc caching when ptxas_verbose is required

- csrc/multidevice/communicator.cpp
The old code probably got off sync at some point. I fixed it according to
https://docs.pytorch.org/docs/stable/elastic/run.html#environment-variables.
> Read the right environmental variables for torchrun

- CMakeLists.txt
- tests/cpp/test_moe.cpp
Added unit tests to demonstrate nvFuser representations of `prepare_moe_input` in SGLang MoE. For the Python version, see this internal [repository](http://nv/eLz).
The intention is just demonstrating how the MoE gate logic could be represented, including prefix sum. We would need more pluming work to make it work through Thunder.
> C++ representation of SGLang's MOE prepare_input kernels

- runtime/casts.cu
- Use all hardware instructions that are available.
- fp8 only has vectorized casts, so we implement vectorized cast and call the vectorized cast in non-vectorized casts.
> Improve fp8 casting

- CMakeLists.txt
- csrc/driver_api.h
- csrc/scheduler/matmul_utils.cpp
This fixes the recent wheel build failure in CI. The issue was caused by the use of the [CUDA Library Management API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__LIBRARY.html) introduced in version 12.8 of the CUDA runtime. Compiling on older versions like 12.6 failed.
This PR instead uses the driver API, which should work on older CUDA versions.
> Use driver API in getMaxActiveClusters

- csrc/scheduler/normalization_utils.h
The kernel for embedding fused with RMS norm uses the correct `bfloat16` buffer, but the output msg is confusing since it prints the originally detected buffer which is float32.
Revise the msg to avoid confusion.
> revise msg to `originally detected persistent_buffers`  to avoid confusion

- csrc/driver_api.cpp
- csrc/driver_api.h
- csrc/type.cpp
- csrc/type.h
This is necessary because funcPtr can be null even when cudaGetDriverEntryPoint returns cudaSuccess. https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DRIVER__ENTRY__POINT.html
> Check driverStatus for cudaGetDriverEntryPoint

- csrc/preseg_passes/pre_segmenter.cpp
- csrc/preseg_passes/translate_no_reduction_matmul_to_mul_squeeze.cpp
- tests/cpp/test_preseg_passes.cpp
-> Inserts `castOp` in translation: `matmul->out()` has the same dtype as the inputs, whereas `mul` returns a float output
-> Move this pass to the start, since meta ops can be candidates for aliasing and other optimizations.
> Move `TranslateNoReductionMatmul` to start

- csrc/scheduler/normalization_inner_outer.cpp
- tests/cpp/test_combined_inner_outer_reduction.cpp
Current implementation of warp specialized TMA normalization assumes persistent buffers are projected to inputs, making TMA loading beneficial.
If not, shared memory persistent buffers cannot use TMA since their producers are not inputs.
Project to inputs is not supported for fusion contains viewOps.
> use tma only when persistent buffers are projected to inputs

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- tests/python/multidevice/fusion_definition_wrapper.py
- tests/python/multidevice/test_matmul.py
- tests/python/multidevice/test_multidevice.py
Allocation domain is not set during concretization. Hence, switching to use loop domain for DID parallelization instead.
> Use loop domain in  `unshardedSizes` for fusion inputs with DID parallelization

- tests/cpp/test_combined_inner_outer_reduction.cpp
This is a simple PR simplifies test of ws tma normalization with viewOps. **It was created through Chat with AI.** The process is as follows:
User wanted to simplify a complex C++ test (`ViewOps`) in `nvfuser/tests/cpp/test_combined_inner_outer_reduction.cpp` while keeping ViewOp functionality and ensuring inner-outer scheduler usage.
1. **Element Count Mismatch**
- **Problem**: Reshape operations had mismatched element counts (16384 vs 32768)
- **Solution**: Fixed reshape from `{1024, 16}` → `{64, 32, 8}` to `{512, 32}` → `{128, 4, 32}`
2. **Compilation Errors**
- **Problem**: `expand()` function expected `Val*` objects, not literal integers
- **Solution**: Used `IrBuilder::create<Val>(64)` instead of literal `64`
3. **Scheduler Rejection**
- **Problem**: "no persistent buffer …
> simplifies test of ws tma normalization with viewOps

- csrc/ir/nodes.cpp
- csrc/polymorphic_value.h
- tests/cpp/test_evaluator.cpp
- tests/python/test_repro.py
**Add `where` function to PolymorphicValue_functions**
Before this PR, evaluation fails for ops `where(a,b,c)` when b or c is a scalar.
1. This PR added where function (csrc/polymorphic_value.h):
- New function that handles all combinations of tensor and scalar inputs for the where operation
- Properly dispatches to at::where with appropriate overloads
- Supports tensor-tensor, tensor-scalar, scalar-tensor, and scalar-scalar combinations
2. Added cpp tests and revised one python test to use `fd.validate()`
3. Other TernaryOps also need fix, but they are not used yet in python or cpp tests.
> fix eval where

- CMakeLists.txt
- tests/cpp/test_multidevice_host_ir_overlap.cpp
These tests run manually-written host IR programs via HostIrEvaluator, so I'm giving the test file a more specific name.
> Rename test_multidevice_overlap to test_multidevice_host_ir_overlap

- CMakeLists.txt
- tests/cpp/test_overlap.cpp
These fusion definitions obviously don't run with FusionExecutorCache yet. I'm adding them merely to clarify the use cases for stream lowering.
> Add test fusion definitions for stream lowering

- csrc/scheduler/matmul_heuristic.h
- csrc/scheduler/matmul_heuristic_plugin.cpp
- csrc/scheduler/matmul_hopper+.cpp
- csrc/scheduler/matmul_hopper+.h
- csrc/scheduler/matmul_utils.cpp
- python/python_frontend/python_bindings.cpp
- tests/cpp/test_matmul.cpp
We always require `cluster_dims.z==1` in the matmul scheduler and it is sometimes confusing to have x, y, z instead of m and n. Since we now always map x to m and y to n, I thought it would be more clear to rename those parameters.
> Switch ClusterDims from XYZ to MN

- python/nvfuser_direct/__init__.py
I think this was just part of a refactor from a method to a separate function in #4689.
Fixes #4806
> Rename self to fd in nvfuser_direct.execute_with_dtensors

- csrc/device_lower/pass/allocation.cpp
**Changes:**
Refactor `getAllocationDomainsAndContiguity`
- Extracted function `canUsePresetAllocationDomain`
- Extracted function `usePresetAllocationDomain`
**Motivations:**
`getAllocationDomainsAndContiguity`mainly does 3 things:
- Determine whether the preset allocation domain can be reused
- Check how to reuse it if possible
- set a new allocation domain if can't use the preset domain
Each section contains many deeply nested if-else branches, making it hard to follow and maintain.
This refactor abstracts the first two tasks into two helper functions.
After refactor, the logic of `getAllocationDomainsAndContiguity` is:
```
if(canUsePresetAllocationDomain()){
return usePresetAllocationDomain()
}
Derive domains that should be allocated from loop domain & allocation position.
```
> refactor getAllocationDomainsAndContiguity

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/opinfo/opinfos.py
- tests/python/opinfo/test_direct_ops.py
This PR adds support for replacing linear layers with TensorParallel NvFuser layer in deepseek model using Direct Python Bindings.
PR Stack:
- #4689
- #4697
- #4698
- #4704
- #4701 **<<< This PR.**
- #4809
> Add support for permute operation to Direct Python Bindings

- csrc/id_model/loop_promotion.cpp
- tests/python/test_repro.py
This PR fixes the following error with the added repro:
```
Error from segmentation group 1:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/val_graph_visitor.h":123, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. The graph has an infinite loop. The following Vals should be visited but are never ready:
```
This happens in the loop promotion analysis, which assumes the graph is acyclic. Cycles are unavoidable with patterns like RoPE, at least with the current definition of the Exact graph, for which we are using the quick [shortcut](https://github.com/NVIDIA/Fuser/blob/main/csrc/id_model/loop_promotion.cpp#L1255) whenever possible. The shortcut can only be used with limited cases where the broadcast forwarding isn't used.
The error …
> Allow the quick promotion analysis even with broadcast and non-broadcast mixed loop groups

- csrc/multidevice/device_mesh.cpp
- csrc/multidevice/device_mesh.h
- csrc/preseg_passes/propagate_shardings.cpp
- tests/cpp/test_sharding.cpp
1. Backpropagates parallel types not already present on a tensorview
2. Extends some functionality of device mesh for DIDy, DIDz.
Issue #4787.
> Backpropagate shardings to already sharded tvs

- csrc/scheduler/resize.cpp
- csrc/scheduler/tools/loop_domain_scheduler.cpp
- tests/cpp/test_rope.cpp
- tests/python/test_repro.py
I decided to disable the cancellation of reshape in the resize scheduler. It was originally added in #3679. 
It results in about 10% perf regression in the RoPE benchmarks http://nv/eO-.
The optimization should be reenabled but rather than ad-hoc patching, I feel we should investigate fixing the root cause of the issue, which is cycles in the exact graph. Tracking issue: #4839
> Do not attempt to cancel reshape when not all tensors are dominated

- csrc/fusion_segmenter.cpp
- csrc/ir/utils.cpp
- csrc/ir/utils.h
- csrc/ops/alias.cpp
- csrc/scheduler/matmul.cpp
- csrc/scheduler/normalization_inner_outer.cpp
- csrc/scheduler/normalization_utils.cpp
- csrc/scheduler/reduction.cpp
- csrc/scheduler/resize.cpp
- csrc/scheduler/transpose.cpp
- csrc/scheduler/utils.cpp
- runtime/helpers.cu
- tests/cpp/test_gpu3.cpp
- tests/cpp/test_low_precision_recipe.cpp
This reverts commit a70e0f545a4b0b7ba104b140384037987206bb43.
Fixes https://github.com/NVIDIA/Fuser/issues/4852. The potential proper fix https://github.com/NVIDIA/Fuser/pull/4853 seems to hit issues. So I created this to fix CI sooner.
> Revert "Pipe quantize kernel through `FusionExecutorCache` (#4760)"

- python/python_direct/ops.cpp
- #4876   **<< This PR.**
- #4877
- #4878
- #4879 
- #4880 
- #4881
- #4882
- #4883
- #4884
> Add threshold and clamp operations to direct_bindings

- csrc/host_ir/lower_to_communication.cpp
- csrc/multidevice/device_mesh.cpp
- csrc/multidevice/device_mesh.h
- csrc/multidevice/utils.cpp
- python/python_direct/multidevice.cpp
- python/python_frontend/multidevice_bindings.cpp
- tests/cpp/test_multidevice_host_ir_overlap.cpp
- tests/cpp/test_multidevice_tutorial.cpp
- tests/cpp/test_sharding.cpp
The benefits are:
1. We don't have to implement existing at::Tensor APIs, e.g., DeviceMesh::getSlice. 
2. `dist.DeviceMesh.mesh` is a torch.Tensor, which will seamlessly connect to `DeviceMesh::devices_`. This will lead to a better UX for the Thunder/DTensor integration.
3. Memory saving. at::Tensor contains a shared pointer of TensorImpl. Therefore, `DeviceMesh`es of the same content will more likely reuse the same storage. 
cc @kshitij12345
> Change the underlying storage of DeviceMesh to Tensor

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
- #4876   
- #4877
- #4878
- #4879   **<< This PR.**
- #4880 
- #4881
- #4882
- #4883
- #4884
> Add Iota operation to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
- #4876   
- #4877
- #4878
- #4879 
- #4880   **<< This PR.**
- #4881
- #4882
- #4883
- #4884
> Add full operation to direct bindings

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/opinfo/opinfos.py
- #4876   
- #4877
- #4878
- #4879 
- #4880 
- #4881 
- #4882 
- #4883
- #4884  **<< This PR.**
> Add scatter operation to direct bindings

- tests/cpp/test_multidevice_host_ir_overlap.cpp
This PR adds a gtest for Ring Allgather Pipelining with CudaIpc. The code is similar to the existing test without CudaIpc, except that it will exchange the memhandles when necessary.
> Ring Allgather Pipelining with CudaIpc

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/opinfo/opinfos.py
* Create `generateOutputs` helper function to replace unused, optional outputs with `_` instead of incorrectly printing `None`.
- #4907
- #4908
- #4909 
- #4910 
- #4911   **<< This PR.**
- #4912
- #4913
- #4914
- #4915
> Add scaled_mm and grouped_mm operations to direct bindings

- csrc/runtime/compiled_kernel.cpp
- csrc/runtime/compiled_kernel.h
- csrc/runtime/executor.cpp
- csrc/serde/fusion_cache.fbs
"watermark" is one word.
Returning an int& is unnecessary.
> Rename and simplify

- csrc/fusion_segmenter.cpp
- csrc/fusion_segmenter.h
- csrc/host_ir/lower.cpp
- csrc/runtime/fusion_cache_utils.cpp
- csrc/runtime/fusion_cache_utils.h
- csrc/runtime/fusion_kernel_runtime.cpp
Change the API to follow https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs
Reuse the toposort implementation from resetLevels. 
Move prepareRuntimeOrder to fusion_segmenter.h
> Clean prepareRuntimeOrder

- tests/python/direct_utils/utils.py
- tests/python/utils/utils.py
`check_captured_python_definition` casts all values to `fp64` for correctness checking. However, this does not work for complex values because it discards the imaginary part. This PR fixes this warning by casting all dtypes except `complex` types to `fp64`.
```
/opt/pytorch/nvfuser/tests/python/direct_utils/utils.py:51: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/Copy.cpp:307.)
ref_out.to(torch.float64),
```
> Avoid discarding imaginary part of complex number in python correctness tests

- python/python_direct/multidevice.cpp
For https://github.com/Lightning-AI/lightning-thunder/pull/2423
I got the wrong impression that an integer list can be automatically converted to torch.Tensor. I was probably looking at a test with legacy bindings. 
cc @kshitij12345
> Add DeviceMesh(devices: list[int]) for backward compatibility

- python/python_common/python_utils.cpp
- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/test_python_frontend.py
- tests/python/opinfo/opinfos.py
* Add support for `triu` and `take_along_axis`
* Explicitly skip `define_vector_constant`, `at`, and `index_put_accumulate` for direct bindings
* Ensure only floating point outputs are generated by `uniform` and `normal`
> Handle remaining composite operations in opinfo tests

- csrc/host_ir/lower_to_communication.cpp
nvfErrorFail is marked as [[noreturn]]
> Remove an unnecessary return

- csrc/host_ir/lower_to_communication.cpp
- csrc/index_compute.cpp
- tests/python/multidevice/test_communication.py
`sum` leads to a `SqueezeOp` when the reduction dimension is size-1. 
Tested with
```
mpirun -np 1 pytest tests/python/multidevice/test_communication.py --only-mpi
```
which I'll add to CI after this PR is merged.
> Extend lower_to_communication to handle SqueezeOp

- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/ops/alias.cpp
The expanded_extents API is not used after #5005 and any potential uses could have been replaced with `out()`'s logical domain sizes.
> Remove expanded_extents from ExpandOp

- tests/python/opinfo/test_legacy_ops.py
Only `test_correctness_index_put_accumulate` remains because it isn't used in Thunder.
All of the tests in `test_errors` and `test_definition_op_in_schedule_error`
The remaining 552 tests finish in in 9.33s.
> Reduce CI time by only running legacy opinfo tets not supported by direct bindings

- CMakeLists.txt
This reduces the output of our build command which makes scrolling back less painful.
> Skip "Up to date: ..." messages in cmake output

- CMakeLists.txt
- cutlass/nvf_cutlass.h
- cutlass/nvfp4_scaled_mm_blockscale.cu
- python/python_direct/cutlass.cpp
- tests/python/direct/test_cutlass_nvfp4_gemm.py
This PR creates a nvfp4 `scaled_mm` with blockscale quantization fused in the epilogue. The kernel returns an `nvfp4` output along with the `fp8` blockscale factor.
The epilogue builder uses `cutlass::epilogue::fusion::LinCombBlockScaleFactor`, which implements `D = alpha * acc + beta * C with BlockScaleFactor generation`.
> Create nvfp4 `scaled_mm` with fused blockscale quantization

- tools/check_symbol_visibility.sh
`nm -u` shows no symbols.
```
$ nm -u /opt/pytorch/nvfuser/python/nvfuser/_C.cpython-312-x86_64-linux-gnu.so
nm: /opt/pytorch/nvfuser/python/nvfuser/_C.cpython-312-x86_64-linux-gnu.so: no symbols
```
Is it because we removed the regular symbol table from the .so?
This PR allows the tool to capture the following wrong change:
```diff
diff --git a/csrc/host_ir/evaluator.h b/csrc/host_ir/evaluator.h
index 7394d9a2..5e0fec21 100644
--- a/csrc/host_ir/evaluator.h
+++ b/csrc/host_ir/evaluator.h
@@ -48,7 +48,7 @@ struct HostIrEvaluatorParams {
//
// Note: most of the implementation is copy pasted for MultiDeviceExecutor. This
// duplication will be resolved in the future.
-class NVF_API HostIrEvaluator final : public OptOutDispatch {
+class HostIrEvaluator final : public OptOutDispatch {
public: …
```
> `nm -u` => `nm -uD`

- csrc/options.h
- python/nvfuser_direct/__init__.py
- python/python_direct/bindings.cpp
- python/python_direct/runtime.cpp
- tests/python/direct/README.md
- tests/python/direct/test_python_direct.py
- tests/python/direct/test_python_frontend.py
This PR adds the remaining functions necessary to create a `nvfuser_direct` PR in Thunder.
- Add `compute_tensor_descriptor` along with `test_compute_tensor_descriptor`.
- Change `FusionDefinition.execute` to support `save_repro_inputs`, `_enable_options`, `_disable_options`.
- Adds `last_repro_script` for Thunder.
The following arguments are not ported to `nvfuser_direct`:
- `override_user_schedule` is irrelevant for `nvfuser_direct`.
- `capture_debug_output` isn't used by thunder.
- `print_repro` argument is redundant. You can call `fd.repro_script_for(inputs)` manually.
- `profile` doesn't work with CUDA 13, so skip it for now.
> Add remaining functions to enable `nvfuser_direct` in Thunder

- csrc/scheduler/utils.cpp
The `use` check can avoid caching lookup tv
> remove redundant gather lookup tv check when caching inputs

- python/python_direct/ops.cpp
- python/python_direct/python_translate.cpp
- tests/python/direct/README.md
- tests/python/direct/test_python_frontend.py
This PR also adds `test_right_shift_logical` and `test_right_shift_logical_sizeof_dtype`, which didn't need any additional changes.
> Add var operation to direct bindings

- CMakeLists.txt
- csrc/options.cpp
- csrc/options.h
- csrc/runtime/compiled_kernel.cpp
- tests/cpp/test_instructions.cpp
- tests/cpp/test_math_opt.cpp
**How to enable**
If run with `NVFUSER_ENABLE=fast_math` will add `--use_fast_math` to compile option.
**Compiler-generated PTX:**
tanh --> `tanh.approx.f32 `
expf ---> `mul.ftz.f32 	%f3, %f2, 0f3FB8AA3B; ex2.approx.ftz.f32 	%f4, %f3;`
**Mainly influenced cases: Perf on GB200**
**Silu:** faster `exp`
**Gelu:** faster `tanh`
**Softmax:** faster `exp` (red markers) + fmaxf (blue markers, will be added in another PR)
> add option to enable compile with `--use_fast_math`

- csrc/ops/alias.cpp
- tests/python/multidevice/test_multidevice.py
`privatizeUpcastOrSqueezeOps` in segmentation clones the `squeeze` operation. The `squeeze` op uses `domain()` (like most APIs) which returns the loop domain, and has device splits at segmentation stage. This produces an error since the `to_squeeze` dimensions are w.r.t. to logical domain.
Unblocks #4873
> Use logical domain in `squeeze` API 

- csrc/ir/nodes.cpp
- tests/cpp/test_sdpa_node.cpp
In preparing for the fix of https://github.com/NVIDIA/Fuser/issues/4888, I am working on https://github.com/NVIDIA/Fuser/pull/5082, which requires the use of `Expr::evaluate` on meta tensors to infer shape and strides of fusion segments selected to be scheduled by the `ExprEval` scheduler. As a consequence of this change, all the `Expr::evaluate` functions should support meta device, and the returned output tensor's shape and stride must match that on device type CUDA.
According to https://docs.pytorch.org/docs/stable/meta.html
> In some cases, not all device types (e.g., CPU and CUDA) have exactly the same output metadata for an operation; we typically prefer representing the CUDA behavior faithfully in this situation.
It is generally safe to assume that we can use device type meta to …
> Add `SdpaFwdOp::evaluate` on meta device

- CMakeLists.txt
- csrc/C++23/utility
- csrc/type.cpp
- csrc/utils.h
This way, any missing cases are captured as early as compile time. 
__builtin_unreachable is necessary to suppress the "control reaches end of non-void function [-Werror=return-type]" error reported by gcc. This is still better than using NVF_THROW in `default` because missing cases are still captured at compile time.
> Remove many switch-defaults for enum classes

- csrc/device_lower/analysis/predicate_elimination.cpp
- csrc/driver_api.cpp
- csrc/driver_api.h
- csrc/scheduler/matmul_utils.cpp
Encountered an error like:
```
unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at /home/scratch.nmaruyama_ent/nvfuser/debug4/csrc/scheduler/matmul_utils.cpp:1128, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues.
Expected _result == cudaSuccess . CUDA error: cudaErrorInvalidResourceHandle failed with error invalid resource handle
Exception raised from getMaxActiveClusters at
```
With the this PR's changes, I no longer see the error.
> Don't mix the runtime and driver APIs

- runtime/block_layout.cu
#5116 PR3: enable codegen for layout op <- this PR
#5115 PR2: add layout op runtime function
#5114 PR1: add layout op
1. Add indexing lowing for `GroupedBlockScalingFactorLayoutOp`:
we resolve indexing for input TV;
we compute logical index for `row_idx` and `col_idx`;
-- added `Index::getLinearRootIndex` and `Index::getConsumerPerDimRootIndex`
in order to compute the row/col indices.
expanded TensorIndex object to store extra logical index;
2. Add codegen for `GroupedBlockScalingFactorLayoutOp`;
The operation adds lowering logic to use the runtime function. The codegen
utilizes the extra indexing bits added during index lowering.
3. Relax domain validation in `OptOutMutator::mutate(TensorDomain*)`
mutating the domain shouldn't try to validate the coverage, because it's not
a guarantee …
> enable codegen for layout op

- tests/python/direct/README.md
- tests/python/direct/test_high_complexity.py
This PR adds the remaining tests from `tests/python/test_python_frontend.py` to `tests/python/direct/test_high_complexity.py`.
PR Stack:
- #5128
- #5129
- #5130  **<<< This PR.**
- #5131
> Add remaining complex tests to direct bindings

- tests/python/direct/README.md
This PR updates `tests/python/direct/README.md` to account for the finished test migration of `tests/python/test_python_frontend.py` from `legacy` to `direct`.
PR Stack:
- #5128
- #5129
- #5130
- #5131  **<<< This PR.**
> Update direct bindings test README

- CMakeLists.txt
- csrc/kernel.cpp
- csrc/kernel.h
- csrc/runtime/compiled_kernel.cpp
- runtime/block_layout.cu
#5118 PR3: enable codegen for layout op
#5115 PR2: add layout op runtime function <- this PR
#5114 PR1: add layout op
Runtime function signature.
template <
typename T,
typename Index_T,
int BLOCK_ROW_OUTER,
int BLOCK_ROW_INNER,
int BLOCK_COL,
int UNROLL_FACTOR>
__device__ void preprocessGroupedMatmulInputSf(
T* output,
const T* input,
const nvfuser_index_t row_idx,
const nvfuser_index_t col_idx,
const Index_T* input_offsets,
const Index_T* output_offsets,
const nvfuser_index_t col_size,
const nvfuser_index_t group_size)
where:
BLOCK_ROW_OUTER, BLOCK_ROW_INNER, BLOCK_COL will be translated from
BlockScalingFactorLayout e.g. Block128x4 is translated to 32, 4, 4.
This function will be used by codegen for `PreprocessGroupedMatmulInputSf`
`output` is expected to be the beginning of output …
> add layout op runtime function

- tools/codediff/codediff.py
- tools/codediff/requirements.txt
This fixes false positives in codediff such as [this example](http://nv/e5M/nvfuser_github_ci/codegen_diff_p34324383_j206130253_1756904251218282579_codediff_c490444f_532ddcc8_custom_command_20250903_051343.html). 
A diff like this should not be counted as an actual code diff and with the PR it won't be:
```diff
--- c490444f
+++ 532ddcc8
@@ -16,35 +16,35 @@
.global .align 1 .u8 _ZN3nvf3std17integral_constantIbLb1EE5valueE;
.global .align 1 .u8 _ZN3nvf3std14__numeric_typeIvE5valueE;
.global .align 1 .u8 _ZN3nvf3std9is_same_vINS_15DefaultBlockDimES2_EE = 1;
.extern .shared .align 16 .b8 _ZN3nvf5arrayE[];
-.visible .entry _ZN3nvf12nvfuser_1085ENS_6TensorIfLi2ELi2EEENS0_IfLi1ELi1EEE(
-	.param .align 8 .b8 _ZN3nvf12nvfuser_1085ENS_6TensorIfLi2ELi2EEENS0_IfLi1ELi1EEE_param_0[24],
-	.param .align …
```
> Ignore different symbol names in codediff

- csrc/ir/interface_nodes.h
- csrc/logical_domain_map.cpp
- csrc/logical_domain_map.h
- csrc/scheduler/greedy.cpp
- csrc/scheduler/tools/inlining.cpp
- csrc/scheduler/tools/inlining.h
- csrc/tensor_view.cpp
- tests/cpp/test_greedy.cpp
Closes #5083 
Inlining is now used to uniformly schedule a given fusion with broadcast IDs.
> Allow broadcast and squeeze in the greedy scheduler

- python/python_direct/ir.cpp
- tests/python/direct/test_tutorial.py
This PR migrates `Tutorial.Memcpy` to python and splits it into two tests. 
The [first half of Tutorial.Memcpy](https://github.com/NVIDIA/Fuser/blob/main/tests/cpp/test_tutorial.cpp#L36-L97) corresponds with `test_tutorial_memcpy`. The [second half of Tutorial.Memcpy](https://github.com/NVIDIA/Fuser/blob/main/tests/cpp/test_tutorial.cpp#L99-L172) corresponds with `test_tutorial_memcpy_scheduled`.
PR stack:
- #5168
- #5169 **<<< This PR**
> Migrate Tutorial.Memcpy to direct bindings

- csrc/device_lower/pass/index.cpp
- csrc/device_lower/validation.cpp
- csrc/ir/internal_nodes.h
- csrc/ir/nodes.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/indexing.cpp
- csrc/scheduler/greedy.cpp
- tests/cpp/test_scatter.cpp
Analogous to the exact size attribute of `GatherOp`.
> Allow ScatterOp with multiple dimensions as long as extents are the same

- csrc/dynamic_transform.cpp
- csrc/fusion_segmenter.cpp
- csrc/ir/internal_base_nodes.h
- csrc/kernel_ir.cpp
- csrc/preseg_passes/remove_empty.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/pointwise.cpp
- csrc/tensor_metadata.cpp
Added TensorDomain::kNoReductions in csrc/ir/internal_base_nodes.h:739 to provide an efficient view-based alternative to TensorDomain::noReductions.
Updated call sites that previously relied solely on noReductions or in tandem with kNoDevices.
For #4571
> Added TensorDomain::kNoReductions

- csrc/device_lower/analysis/tensor_producer_aliases.cpp
- csrc/device_lower/pass/index.cpp
- csrc/ir/internal_base_nodes.h
- csrc/ir/utils.cpp
- csrc/preseg_passes/allocation_order_inference.cpp
- csrc/scheduler/no_op.cpp
- csrc/scheduler/pointwise.cpp
- csrc/scheduler/resize.cpp
- csrc/scheduler/tools/loop_domain_scheduler.cpp
- csrc/val_graph.h
- tests/cpp/utils.cpp
**Summary**
- Added the TensorDomain::kNoBroadcasts view alongside kNoReductions/kNoDevices, and tightened kNoReductions to skip stride axes so the view pipeline matches the legacy helpers.
- Refactored the call sites (scheduler, alias analysis, allocation-order inference, utils, tests) to consume the new views directly—dropping ad-hoc filtering vectors, leaning on std::ranges, and using the local
zip helper where joint iteration is needed.
- Taught ValGraph::toGroups to accept any input range of Val*/Expr*, eliminating extra materialisation when converting filtered domains to graph groups.
> Add TensorDomain::kNoBroadcasts and use it throughout

- tests/python/multidevice/test_overlap.py
Add a python test to exercise the p2p decomposition of AG+GEMM, with nccl backend.
dumped host ir program :
```
%HostIrContainer { (T0_g___bfloat[ideviceIdx.x0{8}, iS1{128}, iS2{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), T1_g___bfloat[iS3{1024}, iS4{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), T2_g___bfloat[iS5{1024}] (DeviceMesh{0 1 2 3 4 5 6 7})) -> (T3_g___bfloat[istreamIdx6{8}, iS7{128}, iS8{1024}, rS9{1024}] (DeviceMesh{0 1 2 3 4 5 6 7})) :
T4_g___bfloat[istreamIdx10{8}, iS11{128}, iS12{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}) = ALLOCATE(buffer=T4_g___bfloat[istreamIdx10{8}, iS11{128}, iS12{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), mem_type=global, size=1048576, zero_init=false, resets_to_zero=false)
T3_g___bfloat[istreamIdx6{8}, iS7{128}, iS8{1024}, rS9{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}) = …
```
> Add AG+GEMM with p2p decomposition python test

- csrc/scheduler/cutlass.cpp
This PR fixes a bug in the `sameAs` check for `CutlassParams`, and also cleans up the printout in `toString`.
> Fix CutlassParams::sameAs to enable kernel reuse

- python/nvfuser_direct/__init__.py
- python/python_direct/bindings.cpp
- python/python_direct/runtime.cpp
- tests/python/direct/test_tutorial.py
Move `get_val_tolerances` and `validate_with_auto_inferred_outputs` from `FusionExecutorCache` member functions to `nvfuser_direct` module functions.
* `validate` uses `FusionExecutorCache` with automatic scheduling.
* `manual_validate` uses `KernelExecutor`.
* `_validate` is a helper function used in `validate` and `manual_validate`.
PR Stack:
* #5187    **<<< This PR.**
* #5188
* #5189
* #5190
> Migrate Tutorial.Reduction to direct bindings 

- csrc/dynamic_transform.cpp
- csrc/expr_evaluator.cpp
- csrc/fusion.cpp
- csrc/fusion_segmenter.cpp
- csrc/host_ir/jit.cpp
- csrc/logical_domain_map.cpp
- csrc/ops/arith.cpp
- csrc/ops/composite.cpp
- csrc/scheduler/mma_utils.cpp
- csrc/scheduler/utils.cpp
- csrc/tensor_metadata.cpp
- csrc/tensor_view.cpp
- csrc/transform_replay.cpp
- csrc/transform_view.cpp
- csrc/type.cpp
- csrc/validator_utils.cpp
- python/python_direct/ir.cpp
- python/python_direct/ops.cpp
- tests/python/direct/test_high_complexity.py
Summary:
- Iteration and rank checks in evaluators, fusion utilities, tensor-view caching, schedulers, validator logic, and Python bindings now walk TensorDomain::kNo* views directly (ranges/enumerate) so we avoid materializing temporary vectors while keeping behavior unchanged.
- Reordered includes across the touched translation units to follow the Google C++ style guide and converted remaining project includes in scheduler/utils.cpp to angle brackets.
> Refactor TensorDomain helpers to use lazy views and tidy includes

- CMakeLists.txt
- csrc/disjoint_set.h
- csrc/id_model/id_model.h
- csrc/val_graph.h
- python/python_direct/bindings.cpp
- python/python_direct/bindings.h
- python/python_direct/enum.cpp
- python/python_direct/id_model.cpp
- python/python_direct/ir.cpp
- tests/python/direct/test_tutorial.py
*  Mapped `DisjointSets::strictAreMapped` to python `strict_are_mapped`
*  Mapped IdModel constructor and `IdModel::maybeBuildGraph`
* Mapped `ValGraph::disjointValSets` and `ValGraph::mapVals`
* Add `IdMappingMode` enum
PR Stack:
* #5187
* #5188
* #5189
* #5190  **<<< This PR.**
> Migrate Tutorial.IdModelReshapeAnalysis to direct bindings

- tests/python/direct_utils/narrow_precision.py
Shouldn't have sliced swizzled & padded data when copying it back to the original buffer. The issue was noticed when I try to validate the layout op in #5198 
This unfortunately didn't affect the threshold for result validation.
> fixing reference implementation.

- CMakeLists.txt
- runtime/cluster.cu
- tests/cpp/cluster_runtime_test/cluster_test_helper.cpp
- tests/cpp/cluster_runtime_test/cluster_test_helper.h
- tests/cpp/cluster_runtime_test/cluster_test_kernels.cu
- tests/cpp/cluster_runtime_test/test_cluster_device_func.cpp
- Adds device-side cluster runtime helpers and a reusable cluster-wide reduction primitive for Hopper (SM90+).
- Provides tests validating remote shared-memory stores and cluster reductions for `float`/`double`.
- Runtime:
- `runtime/cluster.cu`:`storeSharedRemote` and `clusterReduce`.
- Tests:
- Both are tested with float and double data types.
- Cluster utilities expose:
-  `storeSharedRemote<T>` using `st.async.shared::cluster.mbarrier::complete_tx::bytes.{f32,f64}`
- `clusterReduce<...>` algorithm:
- Per-warp reduction → asynchronous remote writes of warp results to all CTAs’ shared memory (DSMEM) with `mbarrier::arriveExpectTX` → `mbarrier::waitParity` → final warp reduction over the aggregated buffer to produce the per-thread result.
> add runtime function for cluster reduction

- csrc/scheduler/pointwise_heuristic.h
- csrc/scheduler/reduction_heuristic.h
This form of bug can lead to inadvertently re-using a suboptimal kernel in dynamic shape contexts.
Note: these were found by Claude Code while I was asking it to summarize all of the heuristic param functionality. I didn't ask it to find these issues.
> Fix missing params in sameAs for reduction/pointwise params

- benchmarks/cpp/p2p_communication.cpp
I merged the previous PR before realizing that I should extend the max tensor size in the benchmark to saturate NVLink bandwidth. After extending, the BiBW tops out at 748, which is 95% of the SOL measured in the NVBandwidth benchmark performance.
```
root@dgx-gaia-15:/opt/Fuser# mpirun -np 2 -H dgx-gaia-15:2 ./python/build/nvfuser_p2p_communication_bench
Starting P2P communication benchmark...
Repetitions per size: 100
Number of devices: 2
Message Size   Elements    Latency (μs)  BiBandwidth (GB/s)
------------------------------------------------------------
4 KB           1024        61.56          0.13
8 KB           2048        90.05          0.18
16 KB          4096        92.01          0.36
32 KB          8192        75.09          0.87
65 KB          16384       67.61 …
```
> Extend max range in Cuda IPC P2P Benchmark

- CMakeLists.txt
- csrc/ir/nodes.cpp
- csrc/ops/arith.cpp
- csrc/preseg_passes/pre_segmenter.cpp
- csrc/preseg_passes/translate_scatter_accumulate.cpp
- csrc/preseg_passes/translate_scatter_accumulate.h
- csrc/scheduler/greedy.cpp
- tests/cpp/test_greedy.cpp
- tests/python/test_moe.py
The greedy scheduler does not yet support reductions, but there's one reduction in test_moe.py. Fortunately, it can be translated to a scatter-accumulate.
Example fusion pattern:
```
index = [m, 1];
scatter_inp = zeros([m, n]); // [m, n]
scatter_out = scatter(scatter_inp, 1, index, src=1);
reduction_out = scatter_out.sum(0); // [n]
```
The greedy scheduler translates it to:
```
index = index.squeeze(-1) // [m]
scatter_inp = zeros([n]); // [n]
scatter_out = scatter(scatter_inp, 0, index, src=1, BinaryOpType::Add)
```
~I was originally thinking about doing this as a preseg pass but decided to do it just for a greedy segment.~
Moved to preseg. I realized translation at scheduling time doesn't work well as the segmenter doesn't see the whole pattern until all ops are fused. We could add yet …
> Translate ScatterOp + ReductionOp to ScatterOp with accumulation

- python/nvfuser/__init__.py
See #5244 where we hit a definition failure. In this case we print the repro correctly but the FusionDefinition has no id yet, so we should invoke the function `nvfuser_incomplete_fusion` instead of `f"nvfuser_fusion_id{self.id()}"` which prints as
`nvfuser_fusion_idNone` in these cases.
> Fix minor bug in printed repros when definition fails

- csrc/multidevice/utils.cpp
- csrc/multidevice/utils.h
- csrc/preseg_passes/finalize_multidevice_domains.cpp
- csrc/scheduler/pointwise.cpp
- tests/cpp/test_multidevice_sharding.cpp
- tests/cpp/test_sharding.cpp
This PR changed reorderDIDToFront to reorder all parallelized dimensions to front. This is less controversial than I expected because currently we only call reorderDIDToFront before intra-GPU scheduling kicks in. 
Needed by #5229
> Reorder all parallelized IterDomains to front

- CMakeLists.txt
- csrc/codegen.cpp
- csrc/device_lower/analysis/fused_reduction.cpp
- csrc/device_lower/lower2device.h
- csrc/device_lower/pass/allocation.cpp
- csrc/device_lower/pass/index.cpp
- csrc/device_lower/pass/index.h
- csrc/device_lower/utils.cpp
- csrc/dispatch.h
- csrc/driver_api.h
- csrc/ir/interface_nodes.h
- csrc/ir/internal_base_nodes.h
- csrc/ir/nodes.cpp
- csrc/kernel.cpp
- csrc/kernel.h
- csrc/kernel_ir.cpp
- csrc/kernel_ir.h
- csrc/runtime/compiled_kernel.cpp
- csrc/runtime/executor.cpp
- csrc/transform_rfactor.cpp
- runtime/cluster.cu
- tests/cpp/cluster_runtime_test/cluster_test_kernels.cu
- tests/cpp/test_cluster.cpp
**Summary**
- End-to-end support for clustered (multi-block) reductions across IR, lowering, codegen, and runtime. 
- Not pluged into scheduler yet, can only be used by manual schedule, see test.
**Key changes**
- IR: Extend `IterDomain` to represent clustered blocks.
- Lowering: Detect and convert `ReductionOp` to `ClusterReductionOp`, allocate and plug `mbarriers` and `cluster syncs`
- Codegen: translate `ClusterReductionOp` to runtime function call.
- Runtime:  launch via `cuLaunchKernelEx`
**Tests**
- Add `tests/cpp/test_cluster.cpp` to test scheduling, lowering, codegen, and execution.
**Follow ups**
(1) revise scheduler to auto select cluster reduction
(2) More tests with auto schedule
(3) Python API test
> cluster reduction IR, lowering, codegen, executor, and manually scheduled fusion

- benchmarks/python/test_batchnorm_fwd.py
Pytest throws an error for duplicate parameters. This has been causing the `batchnorm_fwd` benchmarking failures in CI.
> Remove duplicate parametrization

- tests/cpp/multidevice.cpp
- tests/cpp/multidevice.h
- tests/cpp/test_multidevice_communications.cpp
- tests/cpp/test_multidevice_lower_communication.cpp
- tests/cpp/test_multidevice_matmul.cpp
- tests/cpp/test_multidevice_pipeline.cpp
- tests/cpp/test_multidevice_sharding.cpp
- tests/cpp/test_multidevice_transformer.cpp
- rename MultiDeviceTest::tensor_options to tensor_options_ for consistent private member naming
- _bn && mpirun -np 2 bin/test_multidevice
> Rename MultiDeviceTest tensor options member

- csrc/scheduler/normalization_inner.cpp
saw large performance improvement for `rms norm + add` with small hidden sizes.
> use large bdimx when not all sms are used

- csrc/device_lower/lower2device.cpp
Scatter indexing, which is currently only done when scheduled with the greedy scheduler, relies on `TensorIndexer`, so it needs to be always enabled whenever a fusion has scatter.
> Always use the IdModel indexing when ScatterOp is detected

- tests/python/direct/test_cutlass_gemm.py
Revert #5155 to reenable bf16 grouped gemm on blackwell. This PR runs the CI to Reproduce failure in `jit_python_tests_20_B100_TNVF`
> [SMOKE TEST] Reproduce failure in `jit_python_tests_20_B100_TNVF`

- csrc/alias_analysis.cpp
- csrc/ir/nodes.cpp
- csrc/transform_replay.cpp
> push_back(std::nullopt) and remove unnecessary lint disablers

- csrc/ir/printer.cpp
Improve printing of HostIrContainer by printing the index computations which are not explicitly part of the `topLevelExprs`.
Example from https://github.com/NVIDIA/Fuser/pull/5259
```
%HostIrContainer { (T0_g___bfloat[ideviceIdx.x0{8}, iS1{128}, iS2{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), T1_g___bfloat[iS3{1024}, iS4{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), T2_g___bfloat[iS5{1024}] (DeviceMesh{0 1 2 3 4 5 6 7})) -> (T3_g___bfloat[istreamIdx6{8}, iS7{128}, iS8{1024}, rS9{1024}] (DeviceMesh{0 1 2 3 4 5 6 7})) :
T4_g___bfloat[istreamIdx10{8}, iS11{128}, iS12{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}) = ALLOCATE(buffer=T4_g___bfloat[istreamIdx10{8}, iS11{128}, iS12{1024}] (DeviceMesh{0 1 2 3 4 5 6 7}), mem_type=global, size=1048576, zero_init=false, resets_to_zero=false)
T3_g___bfloat[istreamIdx6{8}, …
```
> [HostIR] Print index definitions in `HostIrContainer::print`

- csrc/scheduler/utils.h
- python/python_direct/ir.cpp
- python/python_direct/schedule.cpp
- tests/python/direct/test_tutorial.py
* Add `swizzle` to `TensorView`; Always use `SwizzleType::XOR`
* Create `bounded_transform_backward` for `BoundedDirectionalTransformPropagator::backward`
<details>
```cuda
__global__ void CUDAGeneratedKernel(Tensor<float, 2, 2> T0, const __grid_constant__ TensorMap var0, const __grid_constant__ TensorMap var1, Tensor<float, 2, 2> T1) {
alignas(16) extern __shared__ char array[];
const unsigned smem_offset = 0;
const TensorMap* ptr2;
ptr2 = &var0;
nvfuser_index_t i3;
i3 = ceilDiv(T0.logical_size[1LL], 32LL);
nvfuser_index_t i4;
i4 = 32LL * (((nvfuser_index_t)blockIdx.x) / i3);
int i5;
i5 = __to_int32(i4);
nvfuser_index_t i6;
i6 = 32LL * (((nvfuser_index_t)blockIdx.x) % i3);
int i7;
i7 = __to_int32(i6);
Array<int, 2, 1> a8;
a8 = Array<int, 2, 1>{i7, i5};
nvfuser_index_t i9;
i9 = …
```
> Migrate `Tutorial.TMABankConflictFreeTranspose` to direct bindings
